name = "LeanScript"
version = "0.1.0"
defaultTargets = ["LeanScript", "NonEmpty", "TyTests", "TermTests"]

[[require]]
name = "aesop"
scope = "leanprover-community"
rev = "v4.34.0"

[[lean_lib]]
name = "LeanScript"
globs = ["LeanScript.+"]

[[lean_lib]]
name = "NonEmpty"
globs = ["NonEmpty.+"]

[[lean_lib]]
name = "TyTests"
globs = ["TyTests.+"]

[[lean_lib]]
name = "TermTests"
globs = ["TermTests.+"]
