module

public import JsTerm.Extern

@[expose] public section

/-!
# The catalogue of externs, at both presets (test data)

Every extern of the catalogue (`LeanScript.LeanInitPureExtern`), with the layouts of its
arguments and result at the preset `faithful` and at the preset `pbo`, the knob of its result,
and whether the backend implements it (an operator, or a function of `runtime/`).  An array's
elements are taken to be `Nat`s.  `Tests/Main.lean` checks that each implemented extern
lowers to an expression that calls only functions the runtime modules export.

Generated from the declarations of `LeanScript/LeanInitPureExterns/*.lean`.
-/

namespace ExternCatalogue

open MoreJs

/-- The externs at the preset `faithful`: name, arguments, result, knob of the result,
    implemented. -/
def faithful : List (String × List JsTerm × JsTerm × Option RtKnob × Bool) := [
  ("lean_uint32_of_nat_mk", [(.bitvec_small 32 (by decide) (by decide))], .uint32, none, true),
  ("lean_uint32_dec_eq", [.uint32, .uint32], .bool, none, true),
  ("lean_uint32_dec_lt", [.uint32, .uint32], .bool, none, true),
  ("lean_nat_div", [.nat, .nat], .nat, some .nat, true),
  ("lean_uint32_of_nat__UInt32_ofNatLT", [.nat], .uint32, none, true),
  ("lean_uint32_of_nat__Char_ofNatAux", [.nat], .string, none, true),
  ("lean_array_get_borrowed", [.uint53, (.genericArray .uint53), .nat], .uint53, none, true),
  ("lean_uint8_to_nat__UInt8_toBitVec", [.uint8], (.bitvec_small 8 (by decide) (by decide)), none, true),
  ("lean_nat_dec_lt", [.nat, .nat], .bool, none, true),
  ("lean_nat_mod__Nat_modCore", [.nat, .nat], .nat, some .nat, true),
  ("lean_nat_mod__Nat_mod", [.nat, .nat], .nat, some .nat, true),
  ("lean_array_push", [(.genericArray .uint53), .uint53], (.genericArray .uint53), none, true),
  ("lean_nat_sub", [.nat, .nat], .nat, some .nat, true),
  ("lean_uint8_dec_lt", [.uint8, .uint8], .bool, none, true),
  ("lean_uint32_dec_le", [.uint32, .uint32], .bool, none, true),
  ("lean_array_get_size", [(.genericArray .uint53)], .nat, some .nat, true),
  ("lean_array_to_list", [(.genericArray .uint53)], (.list .string), none, true),
  ("lean_nat_dec_eq__Nat_decEq", [.nat, .nat], .bool, none, true),
  ("lean_nat_dec_eq__Nat_beq", [.nat, .nat], .bool, none, true),
  ("lean_mk_empty_array_with_capacity__Array_emptyWithCapacity", [.nat], (.genericArray .uint53), none, true),
  ("lean_mk_empty_array_with_capacity__Array_mkEmpty", [.nat], (.genericArray .uint53), none, true),
  ("lean_uint8_of_nat__UInt8_ofNat", [.nat], .uint8, none, true),
  ("lean_uint8_of_nat__UInt8_ofNatLT", [.nat], .uint8, none, true),
  ("lean_uint8_dec_le", [.uint8, .uint8], .bool, none, true),
  ("lean_nat_dec_le__Nat_ble", [.nat, .nat], .bool, none, true),
  ("lean_nat_dec_le__Nat_decLe", [.nat, .nat], .bool, none, true),
  ("lean_array_get", [.uint53, (.genericArray .uint53), .nat], .uint53, none, true),
  ("lean_nat_add", [.nat, .nat], .nat, some .nat, true),
  ("lean_uint16_to_nat__UInt16_toBitVec", [.uint16], (.bitvec_small 16 (by decide) (by decide)), none, true),
  ("lean_uint16_of_nat_mk", [(.bitvec_small 16 (by decide) (by decide))], .uint16, none, true),
  ("lean_uint16_dec_eq", [.uint16, .uint16], .bool, none, true),
  ("lean_string_dec_eq", [.string, .string], .bool, none, true),
  ("lean_nat_pred", [.nat], .nat, some .nat, true),
  ("lean_string_mk__String_ofList", [(.list .string)], .string, none, true),
  ("lean_string_hash", [.string], .nat, some .uint64, false),
  ("lean_uint64_to_nat__UInt64_toBitVec", [.nat], (.bitvec_big 64 (by decide)), some .bitvec, true),
  ("lean_uint64_of_nat_mk", [(.bitvec_big 64 (by decide))], .nat, some .uint64, true),
  ("lean_uint32_to_nat__UInt32_toNat", [.uint32], .nat, some .nat, true),
  ("lean_uint32_to_nat__UInt32_toBitVec", [.uint32], (.bitvec_small 32 (by decide) (by decide)), none, true),
  ("lean_uint64_dec_eq", [.nat, .nat], .bool, none, true),
  ("lean_uint16_of_nat__UInt16_ofNatLT", [.nat], .uint16, none, true),
  ("lean_name_eq", [(.data "Name"), (.data "Name")], .bool, none, false),
  ("lean_uint8_of_nat_mk", [(.bitvec_small 8 (by decide) (by decide))], .uint8, none, true),
  ("lean_uint8_dec_eq", [.uint8, .uint8], .bool, none, true),
  ("lean_nat_pow", [.nat, .nat], .nat, some .nat, true),
  ("lean_nat_mul", [.nat, .nat], .nat, some .nat, true),
  ("lean_string_utf8_byte_size", [.string], .nat, some .nat, true),
  ("lean_array_mk", [(.list .string)], (.genericArray .uint53), none, true),
  ("lean_uint64_mix_hash", [.nat, .nat], .nat, some .uint64, false),
  ("lean_uint64_of_nat__UInt64_ofNatLT", [.nat], .nat, some .uint64, true),
  ("lean_strict_or", [.bool, .bool], .bool, none, true),
  ("lean_thunk_pure", [.uint53], (.thunk .uint53), none, true),
  ("lean_mk_thunk", [(.lazy .string)], (.thunk .uint53), none, true),
  ("lean_thunk_get_own", [(.thunk .uint53)], .uint53, none, true),
  ("lean_strict_and", [.bool, .bool], .bool, none, true),
  ("lean_nat_to_int", [.nat], .int, some .int, true),
  ("lean_int_dec_le", [.int, .int], .bool, none, true),
  ("lean_int_dec_lt", [.int, .int], .bool, none, true),
  ("lean_int_dec_eq", [.int, .int], .bool, none, true),
  ("lean_int_mul", [.int, .int], .int, some .int, true),
  ("lean_int_dec_nonneg", [.int], .bool, none, true),
  ("lean_int_neg_succ_of_nat", [.nat], .int, some .int, true),
  ("lean_int_add", [.int, .int], .int, some .int, true),
  ("lean_int_neg", [.int], .int, some .int, true),
  ("lean_int_sub", [.int, .int], .int, some .int, true),
  ("lean_nat_abs", [.int], .nat, some .nat, true),
  ("lean_nat_div_exact", [.nat, .nat], .nat, some .nat, true),
  ("lean_nat_lxor", [.nat, .nat], .nat, some .nat, true),
  ("lean_nat_shiftl", [.nat, .nat], .nat, some .nat, true),
  ("lean_nat_shiftr", [.nat, .nat], .nat, some .nat, true),
  ("lean_nat_land", [.nat, .nat], .nat, some .nat, true),
  ("lean_nat_lor", [.nat, .nat], .nat, some .nat, true),
  ("lean_dbg_trace_if_shared", [.string, .uint53], .uint53, none, false),
  ("lean_array_set", [(.genericArray .uint53), .nat, .uint53], (.genericArray .uint53), none, true),
  ("lean_array_fset", [(.genericArray .uint53), .nat, .uint53], (.genericArray .uint53), none, true),
  ("lean_array_fswap", [(.genericArray .uint53), .nat, .nat], (.genericArray .uint53), none, true),
  ("lean_mk_array", [.nat, .uint53], (.genericArray .uint53), none, true),
  ("lean_array_swap", [(.genericArray .uint53), .nat, .nat], (.genericArray .uint53), none, true),
  ("lean_array_pop", [(.genericArray .uint53)], (.genericArray .uint53), none, true),
  ("lean_version_get_special_desc", [], (.lazy .string), none, false),
  ("lean_version_get_is_release", [], (.lazy .string), none, false),
  ("lean_version_get_major", [], (.lazy .string), none, false),
  ("lean_version_get_patch", [], (.lazy .string), none, false),
  ("lean_internal_is_stage0", [], (.lazy .string), none, false),
  ("lean_version_get_minor", [], (.lazy .string), none, false),
  ("lean_get_githash", [], (.lazy .string), none, false),
  ("lean_internal_has_llvm_backend", [], (.lazy .string), none, false),
  ("lean_nat_log2", [.nat], .nat, some .nat, true),
  ("lean_int_emod", [.int, .int], .int, some .int, true),
  ("lean_int_div_exact", [.int, .int], .int, some .int, true),
  ("lean_int_mod", [.int, .int], .int, some .int, true),
  ("lean_int_ediv", [.int, .int], .int, some .int, true),
  ("lean_int_div", [.int, .int], .int, some .int, true),
  ("lean_system_platform_emscripten", [], (.lazy .string), none, false),
  ("lean_system_platform_target", [], (.lazy .string), none, false),
  ("lean_uint64_to_nat__UInt64_toNat", [.nat], .nat, some .nat, true),
  ("lean_uint32_to_uint8", [.uint32], .uint8, none, true),
  ("lean_uint64_to_uint32", [.nat], .uint32, none, true),
  ("lean_uint32_to_uint16", [.uint32], .uint16, none, true),
  ("lean_uint16_to_uint32", [.uint16], .uint32, none, true),
  ("lean_uint32_to_uint64", [.uint32], .nat, some .uint64, true),
  ("lean_uint32_of_nat__UInt32_ofNat", [.nat], .uint32, none, true),
  ("lean_uint32_sub", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint16_to_nat__UInt16_toNat", [.uint16], .nat, some .nat, true),
  ("lean_uint16_to_uint8", [.uint16], .uint8, none, true),
  ("lean_uint32_add", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint8_to_uint64", [.uint8], .nat, some .uint64, true),
  ("lean_uint8_to_nat__UInt8_toNat", [.uint8], .nat, some .nat, true),
  ("lean_uint64_of_nat__UInt64_ofNat", [.nat], .nat, some .uint64, true),
  ("lean_uint8_to_uint32", [.uint8], .uint32, none, true),
  ("lean_uint16_of_nat__UInt16_ofNat", [.nat], .uint16, none, true),
  ("lean_uint16_to_uint64", [.uint16], .nat, some .uint64, true),
  ("lean_uint64_to_uint8", [.nat], .uint8, none, true),
  ("lean_uint64_to_uint16", [.nat], .uint16, none, true),
  ("lean_uint8_to_uint16", [.uint8], .uint16, none, true),
  ("lean_uint8_sub", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_neg", [.uint8], .uint8, none, true),
  ("lean_uint8_lor", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_div", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_shift_right", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_shift_left", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_land", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_mul", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_add", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_complement", [.uint8], .uint8, none, true),
  ("lean_uint8_mod", [.uint8, .uint8], .uint8, none, true),
  ("lean_bool_to_uint8", [.bool], .uint8, none, true),
  ("lean_uint8_xor", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint16_neg", [.uint16], .uint16, none, true),
  ("lean_uint16_add", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_lor", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_mul", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_land", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_complement", [.uint16], .uint16, none, true),
  ("lean_uint16_xor", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_shift_left", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_mod", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_dec_lt", [.uint16, .uint16], .bool, none, true),
  ("lean_uint16_div", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_dec_le", [.uint16, .uint16], .bool, none, true),
  ("lean_uint16_sub", [.uint16, .uint16], .uint16, none, true),
  ("lean_bool_to_uint16", [.bool], .uint16, none, true),
  ("lean_uint16_shift_right", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint32_mod", [.uint32, .uint32], .uint32, none, true),
  ("lean_bool_to_uint32", [.bool], .uint32, none, true),
  ("lean_uint32_div", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_shift_right", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_neg", [.uint32], .uint32, none, true),
  ("lean_uint32_lor", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_xor", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_shift_left", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_mul", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_land", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_complement", [.uint32], .uint32, none, true),
  ("lean_uint64_shift_left", [.nat, .nat], .nat, some .uint64, true),
  ("lean_uint64_shift_right", [.nat, .nat], .nat, some .uint64, true),
  ("lean_uint64_complement", [.nat], .nat, some .uint64, true),
  ("lean_uint64_add", [.nat, .nat], .nat, some .uint64, true),
  ("lean_uint64_lor", [.nat, .nat], .nat, some .uint64, true),
  ("lean_uint64_mod", [.nat, .nat], .nat, some .uint64, true),
  ("lean_uint64_div", [.nat, .nat], .nat, some .uint64, true),
  ("lean_uint64_mul", [.nat, .nat], .nat, some .uint64, true),
  ("lean_uint64_land", [.nat, .nat], .nat, some .uint64, true),
  ("lean_bool_to_uint64", [.bool], .nat, some .uint64, true),
  ("lean_uint64_dec_le", [.nat, .nat], .bool, none, true),
  ("lean_uint64_sub", [.nat, .nat], .nat, some .uint64, true),
  ("lean_uint64_neg", [.nat], .nat, some .uint64, true),
  ("lean_uint64_dec_lt", [.nat, .nat], .bool, none, true),
  ("lean_uint64_xor", [.nat, .nat], .nat, some .uint64, true),
  ("lean_int8_add", [.int8, .int8], .int8, none, true),
  ("lean_int8_div", [.int8, .int8], .int8, none, true),
  ("lean_int8_to_int16", [.int8], .int16, none, true),
  ("lean_int8_shift_right", [.int8, .int8], .int8, none, true),
  ("lean_int8_mod", [.int8, .int8], .int8, none, true),
  ("lean_bool_to_int8", [.bool], .int8, none, true),
  ("lean_int8_shift_left", [.int8, .int8], .int8, none, true),
  ("lean_int8_xor", [.int8, .int8], .int8, none, true),
  ("lean_int8_complement", [.int8], .int8, none, true),
  ("lean_int8_dec_eq", [.int8, .int8], .bool, none, true),
  ("lean_int8_neg", [.int8], .int8, none, true),
  ("lean_int8_dec_lt", [.int8, .int8], .bool, none, true),
  ("lean_int8_abs", [.int8], .int8, none, true),
  ("lean_int8_to_int32", [.int8], .int32, none, true),
  ("lean_int8_sub", [.int8, .int8], .int8, none, true),
  ("lean_int8_to_int64", [.int8], .int, some .int64, true),
  ("lean_int8_of_nat", [.nat], .int8, none, true),
  ("lean_int8_dec_le", [.int8, .int8], .bool, none, true),
  ("lean_int8_to_int", [.int8], .int, some .int, true),
  ("lean_int8_mul", [.int8, .int8], .int8, none, true),
  ("lean_int8_land", [.int8, .int8], .int8, none, true),
  ("lean_int8_of_int", [.int], .int8, none, true),
  ("lean_int8_lor", [.int8, .int8], .int8, none, true),
  ("lean_int16_of_nat", [.nat], .int16, none, true),
  ("lean_int16_dec_le", [.int16, .int16], .bool, none, true),
  ("lean_int16_shift_right", [.int16, .int16], .int16, none, true),
  ("lean_int16_div", [.int16, .int16], .int16, none, true),
  ("lean_int16_dec_lt", [.int16, .int16], .bool, none, true),
  ("lean_int16_to_int", [.int16], .int, some .int, true),
  ("lean_int16_mod", [.int16, .int16], .int16, none, true),
  ("lean_int16_dec_eq", [.int16, .int16], .bool, none, true),
  ("lean_bool_to_int16", [.bool], .int16, none, true),
  ("lean_int16_abs", [.int16], .int16, none, true),
  ("lean_int16_to_int32", [.int16], .int32, none, true),
  ("lean_int16_complement", [.int16], .int16, none, true),
  ("lean_int16_land", [.int16, .int16], .int16, none, true),
  ("lean_int16_of_int", [.int], .int16, none, true),
  ("lean_int16_mul", [.int16, .int16], .int16, none, true),
  ("lean_int16_shift_left", [.int16, .int16], .int16, none, true),
  ("lean_int16_xor", [.int16, .int16], .int16, none, true),
  ("lean_int16_lor", [.int16, .int16], .int16, none, true),
  ("lean_int16_add", [.int16, .int16], .int16, none, true),
  ("lean_int16_to_int8", [.int16], .int8, none, true),
  ("lean_int16_neg", [.int16], .int16, none, true),
  ("lean_int16_sub", [.int16, .int16], .int16, none, true),
  ("lean_int16_to_int64", [.int16], .int, some .int64, true),
  ("lean_int32_of_int", [.int], .int32, none, true),
  ("lean_int32_land", [.int32, .int32], .int32, none, true),
  ("lean_int32_mul", [.int32, .int32], .int32, none, true),
  ("lean_int32_dec_le", [.int32, .int32], .bool, none, true),
  ("lean_int32_of_nat", [.nat], .int32, none, true),
  ("lean_int32_to_int64", [.int32], .int, some .int64, true),
  ("lean_int32_sub", [.int32, .int32], .int32, none, true),
  ("lean_int32_neg", [.int32], .int32, none, true),
  ("lean_int32_abs", [.int32], .int32, none, true),
  ("lean_int32_dec_eq", [.int32, .int32], .bool, none, true),
  ("lean_int32_dec_lt", [.int32, .int32], .bool, none, true),
  ("lean_int32_xor", [.int32, .int32], .int32, none, true),
  ("lean_int32_shift_left", [.int32, .int32], .int32, none, true),
  ("lean_int32_shift_right", [.int32, .int32], .int32, none, true),
  ("lean_int32_complement", [.int32], .int32, none, true),
  ("lean_bool_to_int32", [.bool], .int32, none, true),
  ("lean_int32_to_int8", [.int32], .int8, none, true),
  ("lean_int32_add", [.int32, .int32], .int32, none, true),
  ("lean_int32_lor", [.int32, .int32], .int32, none, true),
  ("lean_int32_mod", [.int32, .int32], .int32, none, true),
  ("lean_int32_to_int", [.int32], .int, some .int, true),
  ("lean_int32_to_int16", [.int32], .int16, none, true),
  ("lean_int32_div", [.int32, .int32], .int32, none, true),
  ("lean_int64_sub", [.int, .int], .int, some .int64, true),
  ("lean_int64_xor", [.int, .int], .int, some .int64, true),
  ("lean_int64_to_int8", [.int], .int8, none, true),
  ("lean_int64_mul", [.int, .int], .int, some .int64, true),
  ("lean_int64_of_int", [.int], .int, some .int64, true),
  ("lean_int64_land", [.int, .int], .int, some .int64, true),
  ("lean_int64_lor", [.int, .int], .int, some .int64, true),
  ("lean_int64_mod", [.int, .int], .int, some .int64, true),
  ("lean_int64_shift_left", [.int, .int], .int, some .int64, true),
  ("lean_int64_dec_lt", [.int, .int], .bool, none, true),
  ("lean_int64_complement", [.int], .int, some .int64, true),
  ("lean_int64_to_int32", [.int], .int32, none, true),
  ("lean_int64_abs", [.int], .int, some .int64, true),
  ("lean_bool_to_int64", [.bool], .int, some .int64, true),
  ("lean_int64_dec_eq", [.int, .int], .bool, none, true),
  ("lean_int64_dec_le", [.int, .int], .bool, none, true),
  ("lean_int64_of_nat", [.nat], .int, some .int64, true),
  ("lean_int64_to_int_sint", [.int], .int, some .int, true),
  ("lean_int64_neg", [.int], .int, some .int64, true),
  ("lean_int64_add", [.int, .int], .int, some .int64, true),
  ("lean_int64_div", [.int, .int], .int, some .int64, true),
  ("lean_int64_to_int16", [.int], .int16, none, true),
  ("lean_int64_shift_right", [.int, .int], .int, some .int64, true),
  ("lean_uint16_log2", [.uint16], .uint16, none, true),
  ("lean_uint64_log2", [.nat], .nat, some .uint64, true),
  ("lean_uint8_log2", [.uint8], .uint8, none, true),
  ("lean_uint32_log2", [.uint32], .uint32, none, true),
  ("lean_float_frexp", [.float], (.record [.float, .int]), none, false),
  ("lean_uint8_to_float", [.uint8], .float, none, true),
  ("lean_float_to_bits__Float_toModel", [.float], .float, none, true),
  ("lean_float_to_bits__Float_toBits", [.float], .nat, some .uint64, false),
  ("lean_float_of_bits__Float_ofBits", [.nat], .float, none, false),
  ("lean_float_of_bits__Float_ofModel", [.float], .float, none, true),
  ("lean_float_isnan", [.float], .bool, none, true),
  ("log10", [.float], .float, none, false),
  ("cbrt", [.float], .float, none, false),
  ("log", [.float], .float, none, false),
  ("lean_float_div", [.float, .float], .float, none, true),
  ("lean_float_beq", [.float, .float], .bool, none, true),
  ("tan", [.float], .float, none, false),
  ("tanh", [.float], .float, none, false),
  ("exp2", [.float], .float, none, false),
  ("lean_float_to_uint16", [.float], .uint16, none, false),
  ("lean_uint32_to_float", [.uint32], .float, none, true),
  ("lean_float_decLe__Float_decLe", [.float, .float], .bool, none, true),
  ("lean_float_decLe__Float_le", [.float, .float], .bool, none, true),
  ("lean_float_to_uint64", [.float], .nat, some .uint64, false),
  ("sqrt", [.float], .float, none, false),
  ("acos", [.float], .float, none, false),
  ("atan", [.float], .float, none, false),
  ("acosh", [.float], .float, none, false),
  ("floor", [.float], .float, none, false),
  ("fabs", [.float], .float, none, false),
  ("lean_float_to_uint32", [.float], .uint32, none, false),
  ("lean_float_to_string", [.float], .string, none, false),
  ("lean_uint64_to_float", [.nat], .float, none, true),
  ("lean_float_decLt__Float_decLt", [.float, .float], .bool, none, true),
  ("lean_float_decLt__Float_lt", [.float, .float], .bool, none, true),
  ("lean_float_to_uint8", [.float], .uint8, none, false),
  ("sin", [.float], .float, none, false),
  ("cosh", [.float], .float, none, false),
  ("exp", [.float], .float, none, false),
  ("ceil", [.float], .float, none, false),
  ("lean_float_isfinite", [.float], .bool, none, true),
  ("round", [.float], .float, none, false),
  ("cos", [.float], .float, none, false),
  ("log2", [.float], .float, none, false),
  ("atanh", [.float], .float, none, false),
  ("atan2", [.float, .float], .float, none, false),
  ("sinh", [.float], .float, none, false),
  ("asinh", [.float], .float, none, false),
  ("lean_float_mul", [.float, .float], .float, none, true),
  ("lean_uint16_to_float", [.uint16], .float, none, true),
  ("asin", [.float], .float, none, false),
  ("pow", [.float, .float], .float, none, false),
  ("lean_float_scaleb", [.float, .int], .float, none, false),
  ("lean_float_add", [.float, .float], .float, none, true),
  ("lean_float_sub", [.float, .float], .float, none, true),
  ("lean_float_negate", [.float], .float, none, true),
  ("lean_float_isinf", [.float], .bool, none, true),
  ("lean_int32_to_float", [.int32], .float, none, true),
  ("lean_float_to_int16", [.float], .int16, none, false),
  ("lean_int16_to_float", [.int16], .float, none, true),
  ("lean_float_to_int32", [.float], .int32, none, false),
  ("lean_int8_to_float", [.int8], .float, none, true),
  ("lean_float_to_int8", [.float], .int8, none, false),
  ("lean_int64_to_float", [.int], .float, none, true),
  ("lean_float_to_int64", [.float], .int, some .int64, false),
  ("tanhf", [.float32], .float32, none, false),
  ("exp2f", [.float32], .float32, none, false),
  ("lean_float32_div", [.float32, .float32], .float32, none, true),
  ("logf", [.float32], .float32, none, false),
  ("lean_float32_decLe__Float32_le", [.float32, .float32], .bool, none, true),
  ("lean_float32_decLe__Float32_decLe", [.float32, .float32], .bool, none, true),
  ("lean_float_to_float32", [.float], .float32, none, true),
  ("lean_float32_to_bits__Float32_toModel", [.float32], .float32, none, true),
  ("lean_float32_to_bits__Float32_toBits", [.float32], .uint32, none, false),
  ("lean_float32_of_bits__Float32_ofBits", [.uint32], .float32, none, false),
  ("lean_float32_of_bits__Float32_ofModel", [.float32], .float32, none, true),
  ("atanf", [.float32], .float32, none, false),
  ("acoshf", [.float32], .float32, none, false),
  ("lean_float32_frexp", [.float32], (.record [.float, .int]), none, false),
  ("lean_float32_to_uint64", [.float32], .nat, some .uint64, false),
  ("lean_float32_sub", [.float32, .float32], .float32, none, true),
  ("lean_float32_to_uint16", [.float32], .uint16, none, false),
  ("asinf", [.float32], .float32, none, false),
  ("powf", [.float32, .float32], .float32, none, false),
  ("lean_float32_beq", [.float32, .float32], .bool, none, true),
  ("lean_uint8_to_float32", [.uint8], .float32, none, true),
  ("tanf", [.float32], .float32, none, false),
  ("lean_float32_to_float", [.float32], .float, none, true),
  ("lean_float32_isnan", [.float32], .bool, none, true),
  ("log10f", [.float32], .float32, none, false),
  ("cbrtf", [.float32], .float32, none, false),
  ("atan2f", [.float32, .float32], .float32, none, false),
  ("sinhf", [.float32], .float32, none, false),
  ("cosf", [.float32], .float32, none, false),
  ("lean_uint32_to_float32", [.uint32], .float32, none, true),
  ("lean_float32_isinf", [.float32], .bool, none, true),
  ("lean_float32_negate", [.float32], .float32, none, true),
  ("ceilf", [.float32], .float32, none, false),
  ("lean_float32_isfinite", [.float32], .bool, none, true),
  ("lean_float32_add", [.float32, .float32], .float32, none, true),
  ("lean_float32_scaleb", [.float32, .int], .float32, none, false),
  ("sinf", [.float32], .float32, none, false),
  ("lean_float32_mul", [.float32, .float32], .float32, none, true),
  ("lean_float32_to_string", [.float32], .string, none, false),
  ("asinhf", [.float32], .float32, none, false),
  ("lean_float32_to_uint32", [.float32], .uint32, none, false),
  ("log2f", [.float32], .float32, none, false),
  ("lean_uint64_to_float32", [.nat], .float32, none, true),
  ("atanhf", [.float32], .float32, none, false),
  ("floorf", [.float32], .float32, none, false),
  ("fabsf", [.float32], .float32, none, false),
  ("roundf", [.float32], .float32, none, false),
  ("lean_float32_decLt__Float32_lt", [.float32, .float32], .bool, none, true),
  ("lean_float32_decLt__Float32_decLt", [.float32, .float32], .bool, none, true),
  ("acosf", [.float32], .float32, none, false),
  ("sqrtf", [.float32], .float32, none, false),
  ("lean_uint16_to_float32", [.uint16], .float32, none, true),
  ("coshf", [.float32], .float32, none, false),
  ("expf", [.float32], .float32, none, false),
  ("lean_float32_to_uint8", [.float32], .uint8, none, false),
  ("lean_float32_to_int64", [.float32], .int, some .int64, false),
  ("lean_int32_to_float32", [.int32], .float32, none, true),
  ("lean_float32_to_int8", [.float32], .int8, none, false),
  ("lean_float32_to_int16", [.float32], .int16, none, false),
  ("lean_int8_to_float32", [.int8], .float32, none, true),
  ("lean_float32_to_int32", [.float32], .int32, none, false),
  ("lean_int16_to_float32", [.int16], .float32, none, true),
  ("lean_int64_to_float32", [.int], .float32, none, true),
  ("lean_string_utf8_get__String_Internal_get", [.string, .uint53], .string, none, true),
  ("lean_string_trim", [.string], .string, none, false),
  ("lean_substring_drop", [.substring, .nat], .substring, none, false),
  ("lean_substring_prev", [.substring, .uint53], .uint53, none, false),
  ("lean_substring_extract", [.substring, .uint53, .uint53], .substring, none, false),
  ("lean_string_foldl", [(.fn .string .bool), .string, .string], .string, none, false),
  ("lean_substring_tostring", [.substring], .string, none, false),
  ("lean_string_append__String_Internal_append", [.string, .string], .string, none, true),
  ("lean_string_get_byte_fast__String_Internal_getUTF8Byte", [.string, .nat], .uint8, none, false),
  ("lean_string_isempty", [.string], .bool, none, true),
  ("lean_string_push", [.string, .string], .string, none, true),
  ("lean_string_isprefixof", [.string, .string], .bool, none, false),
  ("lean_string_dropright", [.string, .nat], .string, none, false),
  ("lean_substring_takewhile", [.substring, (.fn .string .bool)], .substring, none, false),
  ("lean_substring_get", [.substring, .uint53], .string, none, false),
  ("lean_string_contains", [.string, .string], .bool, none, false),
  ("lean_string_front", [.string], .string, none, false),
  ("lean_string_posof", [.string, .string], .uint53, none, false),
  ("lean_substring_all", [.substring, (.fn .string .bool)], .bool, none, false),
  ("lean_string_intercalate", [.string, (.list .string)], .string, none, false),
  ("lean_string_drop", [.string, .nat], .string, none, false),
  ("lean_string_length__String_Internal_length", [.string], .nat, some .nat, true),
  ("lean_string_utf8_at_end__String_Internal_atEnd", [.string, .uint53], .bool, none, true),
  ("lean_substring_beq", [.substring, .substring], .bool, none, false),
  ("lean_string_nextwhile", [.string, (.fn .string .bool), .uint53], .uint53, none, false),
  ("lean_string_utf8_next__String_Internal_next", [.string, .uint53], .uint53, none, true),
  ("lean_string_mk__String_mk", [(.list .string)], .string, none, true),
  ("lean_string_any", [.string, (.fn .string .bool)], .bool, none, false),
  ("lean_string_pushn", [.string, .string, .nat], .string, none, true),
  ("lean_string_capitalize", [.string], .string, none, false),
  ("lean_string_utf8_extract__String_Internal_extract", [.string, .uint53, .uint53], .string, none, true),
  ("lean_string_pos_min", [.uint53, .uint53], .uint53, none, false),
  ("lean_substring_front", [.substring], .string, none, false),
  ("lean_string_pos_sub", [.uint53, .uint53], .uint53, none, false),
  ("lean_substring_isempty", [.substring], .bool, none, false),
  ("lean_string_offsetofpos", [.string, .uint53], .nat, some .nat, false),
  ("lean_string_get_byte_fast__String_getUtf8Byte", [.string, .uint53], .uint8, none, false),
  ("lean_string_get_byte_fast__String_getUTF8Byte", [.string, .uint53], .uint8, none, false),
  ("lean_string_append__String_append", [.string, .string], .string, none, true),
  ("lean_string_utf8_next__String_next", [.string, .uint53], .uint53, none, true),
  ("lean_string_utf8_next__String_Pos_Raw_next", [.string, .uint53], .uint53, none, true),
  ("lean_string_utf8_get__String_Pos_Raw_get", [.string, .uint53], .string, none, true),
  ("lean_string_utf8_get__String_get", [.string, .uint53], .string, none, true),
  ("lean_string_utf8_prev__String_Pos_Raw_prev", [.string, .uint53], .uint53, none, false),
  ("lean_string_utf8_prev__String_prev", [.string, .uint53], .uint53, none, false),
  ("lean_string_data__String_data", [.string], (.list .string), none, true),
  ("lean_string_data__String_toList", [.string], (.list .string), none, true),
  ("lean_string_utf8_at_end__String_atEnd", [.string, .uint53], .bool, none, true),
  ("lean_string_utf8_at_end__String_Pos_Raw_atEnd", [.string, .uint53], .bool, none, true),
  ("lean_string_is_valid_pos", [.string, .uint53], .bool, none, false),
  ("lean_string_dec_lt", [.string, .string], .bool, none, true),
  ("lean_string_utf8_extract__String_Pos_Raw_extract", [.string, .uint53, .uint53], .string, none, true),
  ("lean_string_length__String_length", [.string], .nat, some .nat, true),
  ("lean_string_memcmp", [.string, .string, .uint53, .uint53, .uint53], .bool, none, false),
  ("lean_slice_dec_lt", [.stringSlice, .stringSlice], .bool, none, false),
  ("lean_slice_hash", [.stringSlice], .nat, some .uint64, false),
  ("lean_string_utf8_set__String_Pos_Raw_set", [.string, .uint53, .string], .string, none, true),
  ("lean_string_utf8_set__String_set", [.string, .uint53, .string], .string, none, true),
  ("lean_string_compare", [.string, .string], (.enum 3 (-1)), none, true)
]

/-- The externs at the preset `pbo`: name, arguments, result, knob of the result,
    implemented. -/
def pbo : List (String × List JsTerm × JsTerm × Option RtKnob × Bool) := [
  ("lean_uint32_of_nat_mk", [(.bitvec_small 32 (by decide) (by decide))], .uint32, none, true),
  ("lean_uint32_dec_eq", [.uint32, .uint32], .bool, none, true),
  ("lean_uint32_dec_lt", [.uint32, .uint32], .bool, none, true),
  ("lean_nat_div", [.uint53, .uint53], .uint53, some .nat, true),
  ("lean_uint32_of_nat__UInt32_ofNatLT", [.uint53], .uint32, none, true),
  ("lean_uint32_of_nat__Char_ofNatAux", [.uint53], .string, none, true),
  ("lean_array_get_borrowed", [.uint53, (.genericArray .uint53), .uint53], .uint53, none, true),
  ("lean_uint8_to_nat__UInt8_toBitVec", [.uint8], (.bitvec_small 8 (by decide) (by decide)), none, true),
  ("lean_nat_dec_lt", [.uint53, .uint53], .bool, none, true),
  ("lean_nat_mod__Nat_modCore", [.uint53, .uint53], .uint53, some .nat, true),
  ("lean_nat_mod__Nat_mod", [.uint53, .uint53], .uint53, some .nat, true),
  ("lean_array_push", [(.genericArray .uint53), .uint53], (.genericArray .uint53), none, true),
  ("lean_nat_sub", [.uint53, .uint53], .uint53, some .nat, true),
  ("lean_uint8_dec_lt", [.uint8, .uint8], .bool, none, true),
  ("lean_uint32_dec_le", [.uint32, .uint32], .bool, none, true),
  ("lean_array_get_size", [(.genericArray .uint53)], .uint53, some .nat, true),
  ("lean_array_to_list", [(.genericArray .uint53)], (.list .string), none, true),
  ("lean_nat_dec_eq__Nat_decEq", [.uint53, .uint53], .bool, none, true),
  ("lean_nat_dec_eq__Nat_beq", [.uint53, .uint53], .bool, none, true),
  ("lean_mk_empty_array_with_capacity__Array_emptyWithCapacity", [.uint53], (.genericArray .uint53), none, true),
  ("lean_mk_empty_array_with_capacity__Array_mkEmpty", [.uint53], (.genericArray .uint53), none, true),
  ("lean_uint8_of_nat__UInt8_ofNat", [.uint53], .uint8, none, true),
  ("lean_uint8_of_nat__UInt8_ofNatLT", [.uint53], .uint8, none, true),
  ("lean_uint8_dec_le", [.uint8, .uint8], .bool, none, true),
  ("lean_nat_dec_le__Nat_ble", [.uint53, .uint53], .bool, none, true),
  ("lean_nat_dec_le__Nat_decLe", [.uint53, .uint53], .bool, none, true),
  ("lean_array_get", [.uint53, (.genericArray .uint53), .uint53], .uint53, none, true),
  ("lean_nat_add", [.uint53, .uint53], .uint53, some .nat, true),
  ("lean_uint16_to_nat__UInt16_toBitVec", [.uint16], (.bitvec_small 16 (by decide) (by decide)), none, true),
  ("lean_uint16_of_nat_mk", [(.bitvec_small 16 (by decide) (by decide))], .uint16, none, true),
  ("lean_uint16_dec_eq", [.uint16, .uint16], .bool, none, true),
  ("lean_string_dec_eq", [.string, .string], .bool, none, true),
  ("lean_nat_pred", [.uint53], .uint53, some .nat, true),
  ("lean_string_mk__String_ofList", [(.list .string)], .string, none, true),
  ("lean_string_hash", [.string], .uint53, some .uint64, false),
  ("lean_uint64_to_nat__UInt64_toBitVec", [.uint53], .uint53, some .bitvec, true),
  ("lean_uint64_of_nat_mk", [.uint53], .uint53, some .uint64, true),
  ("lean_uint32_to_nat__UInt32_toNat", [.uint32], .uint53, some .nat, true),
  ("lean_uint32_to_nat__UInt32_toBitVec", [.uint32], (.bitvec_small 32 (by decide) (by decide)), none, true),
  ("lean_uint64_dec_eq", [.uint53, .uint53], .bool, none, true),
  ("lean_uint16_of_nat__UInt16_ofNatLT", [.uint53], .uint16, none, true),
  ("lean_name_eq", [(.data "Name"), (.data "Name")], .bool, none, false),
  ("lean_uint8_of_nat_mk", [(.bitvec_small 8 (by decide) (by decide))], .uint8, none, true),
  ("lean_uint8_dec_eq", [.uint8, .uint8], .bool, none, true),
  ("lean_nat_pow", [.uint53, .uint53], .uint53, some .nat, true),
  ("lean_nat_mul", [.uint53, .uint53], .uint53, some .nat, true),
  ("lean_string_utf8_byte_size", [.string], .uint53, some .nat, true),
  ("lean_array_mk", [(.list .string)], (.genericArray .uint53), none, true),
  ("lean_uint64_mix_hash", [.uint53, .uint53], .uint53, some .uint64, false),
  ("lean_uint64_of_nat__UInt64_ofNatLT", [.uint53], .uint53, some .uint64, true),
  ("lean_strict_or", [.bool, .bool], .bool, none, true),
  ("lean_thunk_pure", [.uint53], (.thunk .uint53), none, true),
  ("lean_mk_thunk", [(.lazy .string)], (.thunk .uint53), none, true),
  ("lean_thunk_get_own", [(.thunk .uint53)], .uint53, none, true),
  ("lean_strict_and", [.bool, .bool], .bool, none, true),
  ("lean_nat_to_int", [.uint53], .int53, some .int, true),
  ("lean_int_dec_le", [.int53, .int53], .bool, none, true),
  ("lean_int_dec_lt", [.int53, .int53], .bool, none, true),
  ("lean_int_dec_eq", [.int53, .int53], .bool, none, true),
  ("lean_int_mul", [.int53, .int53], .int53, some .int, true),
  ("lean_int_dec_nonneg", [.int53], .bool, none, true),
  ("lean_int_neg_succ_of_nat", [.uint53], .int53, some .int, true),
  ("lean_int_add", [.int53, .int53], .int53, some .int, true),
  ("lean_int_neg", [.int53], .int53, some .int, true),
  ("lean_int_sub", [.int53, .int53], .int53, some .int, true),
  ("lean_nat_abs", [.int53], .uint53, some .nat, true),
  ("lean_nat_div_exact", [.uint53, .uint53], .uint53, some .nat, true),
  ("lean_nat_lxor", [.uint53, .uint53], .uint53, some .nat, true),
  ("lean_nat_shiftl", [.uint53, .uint53], .uint53, some .nat, true),
  ("lean_nat_shiftr", [.uint53, .uint53], .uint53, some .nat, true),
  ("lean_nat_land", [.uint53, .uint53], .uint53, some .nat, true),
  ("lean_nat_lor", [.uint53, .uint53], .uint53, some .nat, true),
  ("lean_dbg_trace_if_shared", [.string, .uint53], .uint53, none, false),
  ("lean_array_set", [(.genericArray .uint53), .uint53, .uint53], (.genericArray .uint53), none, true),
  ("lean_array_fset", [(.genericArray .uint53), .uint53, .uint53], (.genericArray .uint53), none, true),
  ("lean_array_fswap", [(.genericArray .uint53), .uint53, .uint53], (.genericArray .uint53), none, true),
  ("lean_mk_array", [.uint53, .uint53], (.genericArray .uint53), none, true),
  ("lean_array_swap", [(.genericArray .uint53), .uint53, .uint53], (.genericArray .uint53), none, true),
  ("lean_array_pop", [(.genericArray .uint53)], (.genericArray .uint53), none, true),
  ("lean_version_get_special_desc", [], (.lazy .string), none, false),
  ("lean_version_get_is_release", [], (.lazy .string), none, false),
  ("lean_version_get_major", [], (.lazy .string), none, false),
  ("lean_version_get_patch", [], (.lazy .string), none, false),
  ("lean_internal_is_stage0", [], (.lazy .string), none, false),
  ("lean_version_get_minor", [], (.lazy .string), none, false),
  ("lean_get_githash", [], (.lazy .string), none, false),
  ("lean_internal_has_llvm_backend", [], (.lazy .string), none, false),
  ("lean_nat_log2", [.uint53], .uint53, some .nat, true),
  ("lean_int_emod", [.int53, .int53], .int53, some .int, true),
  ("lean_int_div_exact", [.int53, .int53], .int53, some .int, true),
  ("lean_int_mod", [.int53, .int53], .int53, some .int, true),
  ("lean_int_ediv", [.int53, .int53], .int53, some .int, true),
  ("lean_int_div", [.int53, .int53], .int53, some .int, true),
  ("lean_system_platform_emscripten", [], (.lazy .string), none, false),
  ("lean_system_platform_target", [], (.lazy .string), none, false),
  ("lean_uint64_to_nat__UInt64_toNat", [.uint53], .uint53, some .nat, true),
  ("lean_uint32_to_uint8", [.uint32], .uint8, none, true),
  ("lean_uint64_to_uint32", [.uint53], .uint32, none, true),
  ("lean_uint32_to_uint16", [.uint32], .uint16, none, true),
  ("lean_uint16_to_uint32", [.uint16], .uint32, none, true),
  ("lean_uint32_to_uint64", [.uint32], .uint53, some .uint64, true),
  ("lean_uint32_of_nat__UInt32_ofNat", [.uint53], .uint32, none, true),
  ("lean_uint32_sub", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint16_to_nat__UInt16_toNat", [.uint16], .uint53, some .nat, true),
  ("lean_uint16_to_uint8", [.uint16], .uint8, none, true),
  ("lean_uint32_add", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint8_to_uint64", [.uint8], .uint53, some .uint64, true),
  ("lean_uint8_to_nat__UInt8_toNat", [.uint8], .uint53, some .nat, true),
  ("lean_uint64_of_nat__UInt64_ofNat", [.uint53], .uint53, some .uint64, true),
  ("lean_uint8_to_uint32", [.uint8], .uint32, none, true),
  ("lean_uint16_of_nat__UInt16_ofNat", [.uint53], .uint16, none, true),
  ("lean_uint16_to_uint64", [.uint16], .uint53, some .uint64, true),
  ("lean_uint64_to_uint8", [.uint53], .uint8, none, true),
  ("lean_uint64_to_uint16", [.uint53], .uint16, none, true),
  ("lean_uint8_to_uint16", [.uint8], .uint16, none, true),
  ("lean_uint8_sub", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_neg", [.uint8], .uint8, none, true),
  ("lean_uint8_lor", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_div", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_shift_right", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_shift_left", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_land", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_mul", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_add", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint8_complement", [.uint8], .uint8, none, true),
  ("lean_uint8_mod", [.uint8, .uint8], .uint8, none, true),
  ("lean_bool_to_uint8", [.bool], .uint8, none, true),
  ("lean_uint8_xor", [.uint8, .uint8], .uint8, none, true),
  ("lean_uint16_neg", [.uint16], .uint16, none, true),
  ("lean_uint16_add", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_lor", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_mul", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_land", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_complement", [.uint16], .uint16, none, true),
  ("lean_uint16_xor", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_shift_left", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_mod", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_dec_lt", [.uint16, .uint16], .bool, none, true),
  ("lean_uint16_div", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint16_dec_le", [.uint16, .uint16], .bool, none, true),
  ("lean_uint16_sub", [.uint16, .uint16], .uint16, none, true),
  ("lean_bool_to_uint16", [.bool], .uint16, none, true),
  ("lean_uint16_shift_right", [.uint16, .uint16], .uint16, none, true),
  ("lean_uint32_mod", [.uint32, .uint32], .uint32, none, true),
  ("lean_bool_to_uint32", [.bool], .uint32, none, true),
  ("lean_uint32_div", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_shift_right", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_neg", [.uint32], .uint32, none, true),
  ("lean_uint32_lor", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_xor", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_shift_left", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_mul", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_land", [.uint32, .uint32], .uint32, none, true),
  ("lean_uint32_complement", [.uint32], .uint32, none, true),
  ("lean_uint64_shift_left", [.uint53, .uint53], .uint53, some .uint64, true),
  ("lean_uint64_shift_right", [.uint53, .uint53], .uint53, some .uint64, true),
  ("lean_uint64_complement", [.uint53], .uint53, some .uint64, true),
  ("lean_uint64_add", [.uint53, .uint53], .uint53, some .uint64, true),
  ("lean_uint64_lor", [.uint53, .uint53], .uint53, some .uint64, true),
  ("lean_uint64_mod", [.uint53, .uint53], .uint53, some .uint64, true),
  ("lean_uint64_div", [.uint53, .uint53], .uint53, some .uint64, true),
  ("lean_uint64_mul", [.uint53, .uint53], .uint53, some .uint64, true),
  ("lean_uint64_land", [.uint53, .uint53], .uint53, some .uint64, true),
  ("lean_bool_to_uint64", [.bool], .uint53, some .uint64, true),
  ("lean_uint64_dec_le", [.uint53, .uint53], .bool, none, true),
  ("lean_uint64_sub", [.uint53, .uint53], .uint53, some .uint64, true),
  ("lean_uint64_neg", [.uint53], .uint53, some .uint64, true),
  ("lean_uint64_dec_lt", [.uint53, .uint53], .bool, none, true),
  ("lean_uint64_xor", [.uint53, .uint53], .uint53, some .uint64, true),
  ("lean_int8_add", [.int8, .int8], .int8, none, true),
  ("lean_int8_div", [.int8, .int8], .int8, none, true),
  ("lean_int8_to_int16", [.int8], .int16, none, true),
  ("lean_int8_shift_right", [.int8, .int8], .int8, none, true),
  ("lean_int8_mod", [.int8, .int8], .int8, none, true),
  ("lean_bool_to_int8", [.bool], .int8, none, true),
  ("lean_int8_shift_left", [.int8, .int8], .int8, none, true),
  ("lean_int8_xor", [.int8, .int8], .int8, none, true),
  ("lean_int8_complement", [.int8], .int8, none, true),
  ("lean_int8_dec_eq", [.int8, .int8], .bool, none, true),
  ("lean_int8_neg", [.int8], .int8, none, true),
  ("lean_int8_dec_lt", [.int8, .int8], .bool, none, true),
  ("lean_int8_abs", [.int8], .int8, none, true),
  ("lean_int8_to_int32", [.int8], .int32, none, true),
  ("lean_int8_sub", [.int8, .int8], .int8, none, true),
  ("lean_int8_to_int64", [.int8], .int53, some .int64, true),
  ("lean_int8_of_nat", [.uint53], .int8, none, true),
  ("lean_int8_dec_le", [.int8, .int8], .bool, none, true),
  ("lean_int8_to_int", [.int8], .int53, some .int, true),
  ("lean_int8_mul", [.int8, .int8], .int8, none, true),
  ("lean_int8_land", [.int8, .int8], .int8, none, true),
  ("lean_int8_of_int", [.int53], .int8, none, true),
  ("lean_int8_lor", [.int8, .int8], .int8, none, true),
  ("lean_int16_of_nat", [.uint53], .int16, none, true),
  ("lean_int16_dec_le", [.int16, .int16], .bool, none, true),
  ("lean_int16_shift_right", [.int16, .int16], .int16, none, true),
  ("lean_int16_div", [.int16, .int16], .int16, none, true),
  ("lean_int16_dec_lt", [.int16, .int16], .bool, none, true),
  ("lean_int16_to_int", [.int16], .int53, some .int, true),
  ("lean_int16_mod", [.int16, .int16], .int16, none, true),
  ("lean_int16_dec_eq", [.int16, .int16], .bool, none, true),
  ("lean_bool_to_int16", [.bool], .int16, none, true),
  ("lean_int16_abs", [.int16], .int16, none, true),
  ("lean_int16_to_int32", [.int16], .int32, none, true),
  ("lean_int16_complement", [.int16], .int16, none, true),
  ("lean_int16_land", [.int16, .int16], .int16, none, true),
  ("lean_int16_of_int", [.int53], .int16, none, true),
  ("lean_int16_mul", [.int16, .int16], .int16, none, true),
  ("lean_int16_shift_left", [.int16, .int16], .int16, none, true),
  ("lean_int16_xor", [.int16, .int16], .int16, none, true),
  ("lean_int16_lor", [.int16, .int16], .int16, none, true),
  ("lean_int16_add", [.int16, .int16], .int16, none, true),
  ("lean_int16_to_int8", [.int16], .int8, none, true),
  ("lean_int16_neg", [.int16], .int16, none, true),
  ("lean_int16_sub", [.int16, .int16], .int16, none, true),
  ("lean_int16_to_int64", [.int16], .int53, some .int64, true),
  ("lean_int32_of_int", [.int53], .int32, none, true),
  ("lean_int32_land", [.int32, .int32], .int32, none, true),
  ("lean_int32_mul", [.int32, .int32], .int32, none, true),
  ("lean_int32_dec_le", [.int32, .int32], .bool, none, true),
  ("lean_int32_of_nat", [.uint53], .int32, none, true),
  ("lean_int32_to_int64", [.int32], .int53, some .int64, true),
  ("lean_int32_sub", [.int32, .int32], .int32, none, true),
  ("lean_int32_neg", [.int32], .int32, none, true),
  ("lean_int32_abs", [.int32], .int32, none, true),
  ("lean_int32_dec_eq", [.int32, .int32], .bool, none, true),
  ("lean_int32_dec_lt", [.int32, .int32], .bool, none, true),
  ("lean_int32_xor", [.int32, .int32], .int32, none, true),
  ("lean_int32_shift_left", [.int32, .int32], .int32, none, true),
  ("lean_int32_shift_right", [.int32, .int32], .int32, none, true),
  ("lean_int32_complement", [.int32], .int32, none, true),
  ("lean_bool_to_int32", [.bool], .int32, none, true),
  ("lean_int32_to_int8", [.int32], .int8, none, true),
  ("lean_int32_add", [.int32, .int32], .int32, none, true),
  ("lean_int32_lor", [.int32, .int32], .int32, none, true),
  ("lean_int32_mod", [.int32, .int32], .int32, none, true),
  ("lean_int32_to_int", [.int32], .int53, some .int, true),
  ("lean_int32_to_int16", [.int32], .int16, none, true),
  ("lean_int32_div", [.int32, .int32], .int32, none, true),
  ("lean_int64_sub", [.int53, .int53], .int53, some .int64, true),
  ("lean_int64_xor", [.int53, .int53], .int53, some .int64, true),
  ("lean_int64_to_int8", [.int53], .int8, none, true),
  ("lean_int64_mul", [.int53, .int53], .int53, some .int64, true),
  ("lean_int64_of_int", [.int53], .int53, some .int64, true),
  ("lean_int64_land", [.int53, .int53], .int53, some .int64, true),
  ("lean_int64_lor", [.int53, .int53], .int53, some .int64, true),
  ("lean_int64_mod", [.int53, .int53], .int53, some .int64, true),
  ("lean_int64_shift_left", [.int53, .int53], .int53, some .int64, true),
  ("lean_int64_dec_lt", [.int53, .int53], .bool, none, true),
  ("lean_int64_complement", [.int53], .int53, some .int64, true),
  ("lean_int64_to_int32", [.int53], .int32, none, true),
  ("lean_int64_abs", [.int53], .int53, some .int64, true),
  ("lean_bool_to_int64", [.bool], .int53, some .int64, true),
  ("lean_int64_dec_eq", [.int53, .int53], .bool, none, true),
  ("lean_int64_dec_le", [.int53, .int53], .bool, none, true),
  ("lean_int64_of_nat", [.uint53], .int53, some .int64, true),
  ("lean_int64_to_int_sint", [.int53], .int53, some .int, true),
  ("lean_int64_neg", [.int53], .int53, some .int64, true),
  ("lean_int64_add", [.int53, .int53], .int53, some .int64, true),
  ("lean_int64_div", [.int53, .int53], .int53, some .int64, true),
  ("lean_int64_to_int16", [.int53], .int16, none, true),
  ("lean_int64_shift_right", [.int53, .int53], .int53, some .int64, true),
  ("lean_uint16_log2", [.uint16], .uint16, none, true),
  ("lean_uint64_log2", [.uint53], .uint53, some .uint64, true),
  ("lean_uint8_log2", [.uint8], .uint8, none, true),
  ("lean_uint32_log2", [.uint32], .uint32, none, true),
  ("lean_float_frexp", [.float], (.record [.float, .int53]), none, false),
  ("lean_uint8_to_float", [.uint8], .float, none, true),
  ("lean_float_to_bits__Float_toModel", [.float], .float, none, true),
  ("lean_float_to_bits__Float_toBits", [.float], .uint53, some .uint64, false),
  ("lean_float_of_bits__Float_ofBits", [.uint53], .float, none, false),
  ("lean_float_of_bits__Float_ofModel", [.float], .float, none, true),
  ("lean_float_isnan", [.float], .bool, none, true),
  ("log10", [.float], .float, none, false),
  ("cbrt", [.float], .float, none, false),
  ("log", [.float], .float, none, false),
  ("lean_float_div", [.float, .float], .float, none, true),
  ("lean_float_beq", [.float, .float], .bool, none, true),
  ("tan", [.float], .float, none, false),
  ("tanh", [.float], .float, none, false),
  ("exp2", [.float], .float, none, false),
  ("lean_float_to_uint16", [.float], .uint16, none, false),
  ("lean_uint32_to_float", [.uint32], .float, none, true),
  ("lean_float_decLe__Float_decLe", [.float, .float], .bool, none, true),
  ("lean_float_decLe__Float_le", [.float, .float], .bool, none, true),
  ("lean_float_to_uint64", [.float], .uint53, some .uint64, false),
  ("sqrt", [.float], .float, none, false),
  ("acos", [.float], .float, none, false),
  ("atan", [.float], .float, none, false),
  ("acosh", [.float], .float, none, false),
  ("floor", [.float], .float, none, false),
  ("fabs", [.float], .float, none, false),
  ("lean_float_to_uint32", [.float], .uint32, none, false),
  ("lean_float_to_string", [.float], .string, none, false),
  ("lean_uint64_to_float", [.uint53], .float, none, true),
  ("lean_float_decLt__Float_decLt", [.float, .float], .bool, none, true),
  ("lean_float_decLt__Float_lt", [.float, .float], .bool, none, true),
  ("lean_float_to_uint8", [.float], .uint8, none, false),
  ("sin", [.float], .float, none, false),
  ("cosh", [.float], .float, none, false),
  ("exp", [.float], .float, none, false),
  ("ceil", [.float], .float, none, false),
  ("lean_float_isfinite", [.float], .bool, none, true),
  ("round", [.float], .float, none, false),
  ("cos", [.float], .float, none, false),
  ("log2", [.float], .float, none, false),
  ("atanh", [.float], .float, none, false),
  ("atan2", [.float, .float], .float, none, false),
  ("sinh", [.float], .float, none, false),
  ("asinh", [.float], .float, none, false),
  ("lean_float_mul", [.float, .float], .float, none, true),
  ("lean_uint16_to_float", [.uint16], .float, none, true),
  ("asin", [.float], .float, none, false),
  ("pow", [.float, .float], .float, none, false),
  ("lean_float_scaleb", [.float, .int53], .float, none, false),
  ("lean_float_add", [.float, .float], .float, none, true),
  ("lean_float_sub", [.float, .float], .float, none, true),
  ("lean_float_negate", [.float], .float, none, true),
  ("lean_float_isinf", [.float], .bool, none, true),
  ("lean_int32_to_float", [.int32], .float, none, true),
  ("lean_float_to_int16", [.float], .int16, none, false),
  ("lean_int16_to_float", [.int16], .float, none, true),
  ("lean_float_to_int32", [.float], .int32, none, false),
  ("lean_int8_to_float", [.int8], .float, none, true),
  ("lean_float_to_int8", [.float], .int8, none, false),
  ("lean_int64_to_float", [.int53], .float, none, true),
  ("lean_float_to_int64", [.float], .int53, some .int64, false),
  ("tanhf", [.float32], .float32, none, false),
  ("exp2f", [.float32], .float32, none, false),
  ("lean_float32_div", [.float32, .float32], .float32, none, true),
  ("logf", [.float32], .float32, none, false),
  ("lean_float32_decLe__Float32_le", [.float32, .float32], .bool, none, true),
  ("lean_float32_decLe__Float32_decLe", [.float32, .float32], .bool, none, true),
  ("lean_float_to_float32", [.float], .float32, none, true),
  ("lean_float32_to_bits__Float32_toModel", [.float32], .float32, none, true),
  ("lean_float32_to_bits__Float32_toBits", [.float32], .uint32, none, false),
  ("lean_float32_of_bits__Float32_ofBits", [.uint32], .float32, none, false),
  ("lean_float32_of_bits__Float32_ofModel", [.float32], .float32, none, true),
  ("atanf", [.float32], .float32, none, false),
  ("acoshf", [.float32], .float32, none, false),
  ("lean_float32_frexp", [.float32], (.record [.float, .int53]), none, false),
  ("lean_float32_to_uint64", [.float32], .uint53, some .uint64, false),
  ("lean_float32_sub", [.float32, .float32], .float32, none, true),
  ("lean_float32_to_uint16", [.float32], .uint16, none, false),
  ("asinf", [.float32], .float32, none, false),
  ("powf", [.float32, .float32], .float32, none, false),
  ("lean_float32_beq", [.float32, .float32], .bool, none, true),
  ("lean_uint8_to_float32", [.uint8], .float32, none, true),
  ("tanf", [.float32], .float32, none, false),
  ("lean_float32_to_float", [.float32], .float, none, true),
  ("lean_float32_isnan", [.float32], .bool, none, true),
  ("log10f", [.float32], .float32, none, false),
  ("cbrtf", [.float32], .float32, none, false),
  ("atan2f", [.float32, .float32], .float32, none, false),
  ("sinhf", [.float32], .float32, none, false),
  ("cosf", [.float32], .float32, none, false),
  ("lean_uint32_to_float32", [.uint32], .float32, none, true),
  ("lean_float32_isinf", [.float32], .bool, none, true),
  ("lean_float32_negate", [.float32], .float32, none, true),
  ("ceilf", [.float32], .float32, none, false),
  ("lean_float32_isfinite", [.float32], .bool, none, true),
  ("lean_float32_add", [.float32, .float32], .float32, none, true),
  ("lean_float32_scaleb", [.float32, .int53], .float32, none, false),
  ("sinf", [.float32], .float32, none, false),
  ("lean_float32_mul", [.float32, .float32], .float32, none, true),
  ("lean_float32_to_string", [.float32], .string, none, false),
  ("asinhf", [.float32], .float32, none, false),
  ("lean_float32_to_uint32", [.float32], .uint32, none, false),
  ("log2f", [.float32], .float32, none, false),
  ("lean_uint64_to_float32", [.uint53], .float32, none, true),
  ("atanhf", [.float32], .float32, none, false),
  ("floorf", [.float32], .float32, none, false),
  ("fabsf", [.float32], .float32, none, false),
  ("roundf", [.float32], .float32, none, false),
  ("lean_float32_decLt__Float32_lt", [.float32, .float32], .bool, none, true),
  ("lean_float32_decLt__Float32_decLt", [.float32, .float32], .bool, none, true),
  ("acosf", [.float32], .float32, none, false),
  ("sqrtf", [.float32], .float32, none, false),
  ("lean_uint16_to_float32", [.uint16], .float32, none, true),
  ("coshf", [.float32], .float32, none, false),
  ("expf", [.float32], .float32, none, false),
  ("lean_float32_to_uint8", [.float32], .uint8, none, false),
  ("lean_float32_to_int64", [.float32], .int53, some .int64, false),
  ("lean_int32_to_float32", [.int32], .float32, none, true),
  ("lean_float32_to_int8", [.float32], .int8, none, false),
  ("lean_float32_to_int16", [.float32], .int16, none, false),
  ("lean_int8_to_float32", [.int8], .float32, none, true),
  ("lean_float32_to_int32", [.float32], .int32, none, false),
  ("lean_int16_to_float32", [.int16], .float32, none, true),
  ("lean_int64_to_float32", [.int53], .float32, none, true),
  ("lean_string_utf8_get__String_Internal_get", [.string, .uint53], .string, none, true),
  ("lean_string_trim", [.string], .string, none, false),
  ("lean_substring_drop", [.substring, .uint53], .substring, none, false),
  ("lean_substring_prev", [.substring, .uint53], .uint53, none, false),
  ("lean_substring_extract", [.substring, .uint53, .uint53], .substring, none, false),
  ("lean_string_foldl", [(.fn .string .bool), .string, .string], .string, none, false),
  ("lean_substring_tostring", [.substring], .string, none, false),
  ("lean_string_append__String_Internal_append", [.string, .string], .string, none, true),
  ("lean_string_get_byte_fast__String_Internal_getUTF8Byte", [.string, .uint53], .uint8, none, false),
  ("lean_string_isempty", [.string], .bool, none, true),
  ("lean_string_push", [.string, .string], .string, none, true),
  ("lean_string_isprefixof", [.string, .string], .bool, none, false),
  ("lean_string_dropright", [.string, .uint53], .string, none, false),
  ("lean_substring_takewhile", [.substring, (.fn .string .bool)], .substring, none, false),
  ("lean_substring_get", [.substring, .uint53], .string, none, false),
  ("lean_string_contains", [.string, .string], .bool, none, false),
  ("lean_string_front", [.string], .string, none, false),
  ("lean_string_posof", [.string, .string], .uint53, none, false),
  ("lean_substring_all", [.substring, (.fn .string .bool)], .bool, none, false),
  ("lean_string_intercalate", [.string, (.list .string)], .string, none, false),
  ("lean_string_drop", [.string, .uint53], .string, none, false),
  ("lean_string_length__String_Internal_length", [.string], .uint53, some .nat, true),
  ("lean_string_utf8_at_end__String_Internal_atEnd", [.string, .uint53], .bool, none, true),
  ("lean_substring_beq", [.substring, .substring], .bool, none, false),
  ("lean_string_nextwhile", [.string, (.fn .string .bool), .uint53], .uint53, none, false),
  ("lean_string_utf8_next__String_Internal_next", [.string, .uint53], .uint53, none, true),
  ("lean_string_mk__String_mk", [(.list .string)], .string, none, true),
  ("lean_string_any", [.string, (.fn .string .bool)], .bool, none, false),
  ("lean_string_pushn", [.string, .string, .uint53], .string, none, true),
  ("lean_string_capitalize", [.string], .string, none, false),
  ("lean_string_utf8_extract__String_Internal_extract", [.string, .uint53, .uint53], .string, none, true),
  ("lean_string_pos_min", [.uint53, .uint53], .uint53, none, false),
  ("lean_substring_front", [.substring], .string, none, false),
  ("lean_string_pos_sub", [.uint53, .uint53], .uint53, none, false),
  ("lean_substring_isempty", [.substring], .bool, none, false),
  ("lean_string_offsetofpos", [.string, .uint53], .uint53, some .nat, false),
  ("lean_string_get_byte_fast__String_getUtf8Byte", [.string, .uint53], .uint8, none, false),
  ("lean_string_get_byte_fast__String_getUTF8Byte", [.string, .uint53], .uint8, none, false),
  ("lean_string_append__String_append", [.string, .string], .string, none, true),
  ("lean_string_utf8_next__String_next", [.string, .uint53], .uint53, none, true),
  ("lean_string_utf8_next__String_Pos_Raw_next", [.string, .uint53], .uint53, none, true),
  ("lean_string_utf8_get__String_Pos_Raw_get", [.string, .uint53], .string, none, true),
  ("lean_string_utf8_get__String_get", [.string, .uint53], .string, none, true),
  ("lean_string_utf8_prev__String_Pos_Raw_prev", [.string, .uint53], .uint53, none, false),
  ("lean_string_utf8_prev__String_prev", [.string, .uint53], .uint53, none, false),
  ("lean_string_data__String_data", [.string], (.list .string), none, true),
  ("lean_string_data__String_toList", [.string], (.list .string), none, true),
  ("lean_string_utf8_at_end__String_atEnd", [.string, .uint53], .bool, none, true),
  ("lean_string_utf8_at_end__String_Pos_Raw_atEnd", [.string, .uint53], .bool, none, true),
  ("lean_string_is_valid_pos", [.string, .uint53], .bool, none, false),
  ("lean_string_dec_lt", [.string, .string], .bool, none, true),
  ("lean_string_utf8_extract__String_Pos_Raw_extract", [.string, .uint53, .uint53], .string, none, true),
  ("lean_string_length__String_length", [.string], .uint53, some .nat, true),
  ("lean_string_memcmp", [.string, .string, .uint53, .uint53, .uint53], .bool, none, false),
  ("lean_slice_dec_lt", [.stringSlice, .stringSlice], .bool, none, false),
  ("lean_slice_hash", [.stringSlice], .uint53, some .uint64, false),
  ("lean_string_utf8_set__String_Pos_Raw_set", [.string, .uint53, .string], .string, none, true),
  ("lean_string_utf8_set__String_set", [.string, .uint53, .string], .string, none, true),
  ("lean_string_compare", [.string, .string], (.enum 3 (-1)), none, true)
]

end ExternCatalogue

end
