module

public import Init
public import LeanScript.LeanInitPureExterns

@[expose] public section

set_option autoImplicit false

/-!
# The meaning of the two-argument terminal externs

One Lean function per entry of `LeanInitPureExtern2OnlyPrim`, on the values its arguments
and its result denote.  A position in a string is a byte index, so `.stringPos` denotes a
`Nat` and the functions that take one build a `String.Pos.Raw` from it.
-/

namespace LeanScript

/-- The function a two-argument terminal extern denotes, -/
def LeanInitPureExtern2OnlyPrim.eval : ∀ {a b c : LeanPrimTy},
    LeanInitPureExtern2OnlyPrim a b c → a.denote → b.denote → c.denote
  | _, _, _, .lean_uint32_dec_eq, v, w => (v == w)
  | _, _, _, .lean_uint32_dec_lt, v, w => (decide (v < w))
  | _, _, _, .lean_nat_div, v, w => (v / w)
  | _, _, _, .lean_nat_dec_lt, v, w => (decide (v < w))
  | _, _, _, .lean_nat_mod_core, v, w => (v % w)
  | _, _, _, .lean_nat_mod, v, w => (v % w)
  | _, _, _, .lean_nat_sub, v, w => (v - w)
  | _, _, _, .lean_uint8_dec_lt, v, w => (decide (v < w))
  | _, _, _, .lean_uint32_dec_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_nat_dec_eq, v, w => (decide (v = w))
  | _, _, _, .lean_nat_beq, v, w => (v == w)
  | _, _, _, .lean_uint8_dec_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_nat_ble, v, w => (decide (v ≤ w))
  | _, _, _, .lean_nat_dec_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_nat_add, v, w => (v + w)
  | _, _, _, .lean_uint16_dec_eq, v, w => (v == w)
  | _, _, _, .lean_string_dec_eq, v, w => (v == w)
  | _, _, _, .lean_uint64_dec_eq, v, w => (v == w)
  | _, _, _, .lean_uint8_dec_eq, v, w => (v == w)
  | _, _, _, .lean_nat_pow, v, w => (v ^ w)
  | _, _, _, .lean_usize_dec_eq, v, w => (v == w)
  | _, _, _, .lean_nat_mul, v, w => (v * w)
  | _, _, _, .lean_uint64_mix_hash, v, w => (mixHash v w)
  | _, _, _, .lean_int_dec_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_int_dec_lt, v, w => (decide (v < w))
  | _, _, _, .lean_int_dec_eq, v, w => (decide (v = w))
  | _, _, _, .lean_int_mul, v, w => (v * w)
  | _, _, _, .lean_int_add, v, w => (v + w)
  | _, _, _, .lean_int_sub, v, w => (v - w)
  | _, _, _, .lean_nat_div_exact, v, w => (v / w)
  | _, _, _, .lean_nat_lxor, v, w => (Nat.xor v w)
  | _, _, _, .lean_nat_shiftl, v, w => (Nat.shiftLeft v w)
  | _, _, _, .lean_nat_shiftr, v, w => (Nat.shiftRight v w)
  | _, _, _, .lean_nat_land, v, w => (Nat.land v w)
  | _, _, _, .lean_nat_lor, v, w => (Nat.lor v w)
  | _, _, _, .lean_usize_add, v, w => (v + w)
  | _, _, _, .lean_uint32_sub, v, w => (v - w)
  | _, _, _, .lean_usize_sub, v, w => (v - w)
  | _, _, _, .lean_uint32_add, v, w => (v + w)
  | _, _, _, .lean_usize_dec_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_usize_dec_lt, v, w => (decide (v < w))
  | _, _, _, .lean_string_utf8_get, v, w => (String.Pos.Raw.get v w)
  | _, _, _, .lean_substring_drop, v, w => (Substring.Raw.drop v w)
  | _, _, _, .lean_substring_prev, v, w => (Substring.Raw.prev v w)
  | _, _, _, .lean_string_append, v, w => (v ++ w)
  | _, _, _, .lean_string_push, v, w => (String.push v w)
  | _, _, _, .lean_string_isprefixof, v, w => (String.isPrefixOf v w)
  | _, _, _, .lean_string_dropright, v, w => ((String.dropEnd v w).toString)
  | _, _, _, .lean_substring_get, v, w => (Substring.Raw.get v w)
  | _, _, _, .lean_string_drop, v, w => ((String.drop v w).toString)
  | _, _, _, .lean_string_utf8_at_end, v, w => (String.Pos.Raw.atEnd v w)
  | _, _, _, .lean_substring_beq, v, w => (Substring.Raw.beq v w)
  | _, _, _, .lean_string_utf8_next, v, w => (String.Pos.Raw.next v w)
  | _, _, _, .lean_string_pos_min, v, w => (min v w)
  | _, _, _, .lean_string_pos_sub, v, w => (String.Pos.Raw.Internal.sub v w)
  | _, _, _, .lean_strict_or, v, w => (v || w)
  | _, _, _, .lean_strict_and, v, w => (v && w)
  | _, _, _, .lean_int_emod, v, w => (Int.emod v w)
  | _, _, _, .lean_int_div_exact, v, w => (Int.tdiv v w)
  | _, _, _, .lean_int_mod, v, w => (Int.tmod v w)
  | _, _, _, .lean_int_ediv, v, w => (Int.ediv v w)
  | _, _, _, .lean_int_div, v, w => (Int.tdiv v w)
  | _, _, _, .lean_uint64_shift_left, v, w => (v <<< w)
  | _, _, _, .lean_uint32_mod, v, w => (v % w)
  | _, _, _, .lean_usize_land, v, w => (v &&& w)
  | _, _, _, .lean_usize_mul, v, w => (v * w)
  | _, _, _, .lean_uint64_shift_right, v, w => (v >>> w)
  | _, _, _, .lean_usize_shift_left, v, w => (v <<< w)
  | _, _, _, .lean_uint16_add, v, w => (v + w)
  | _, _, _, .lean_usize_xor, v, w => (v ^^^ w)
  | _, _, _, .lean_uint16_lor, v, w => (v ||| w)
  | _, _, _, .lean_uint16_mul, v, w => (v * w)
  | _, _, _, .lean_uint16_land, v, w => (v &&& w)
  | _, _, _, .lean_uint8_sub, v, w => (v - w)
  | _, _, _, .lean_uint32_div, v, w => (v / w)
  | _, _, _, .lean_uint64_add, v, w => (v + w)
  | _, _, _, .lean_uint64_lor, v, w => (v ||| w)
  | _, _, _, .lean_uint64_mod, v, w => (v % w)
  | _, _, _, .lean_uint8_lor, v, w => (v ||| w)
  | _, _, _, .lean_uint32_shift_right, v, w => (v >>> w)
  | _, _, _, .lean_uint16_xor, v, w => (v ^^^ w)
  | _, _, _, .lean_usize_lor, v, w => (v ||| w)
  | _, _, _, .lean_uint8_div, v, w => (v / w)
  | _, _, _, .lean_uint16_shift_left, v, w => (v <<< w)
  | _, _, _, .lean_uint16_mod, v, w => (v % w)
  | _, _, _, .lean_uint64_div, v, w => (v / w)
  | _, _, _, .lean_uint16_dec_lt, v, w => (decide (v < w))
  | _, _, _, .lean_uint8_shift_right, v, w => (v >>> w)
  | _, _, _, .lean_uint32_lor, v, w => (v ||| w)
  | _, _, _, .lean_uint64_mul, v, w => (v * w)
  | _, _, _, .lean_usize_shift_right, v, w => (v >>> w)
  | _, _, _, .lean_uint64_land, v, w => (v &&& w)
  | _, _, _, .lean_uint8_shift_left, v, w => (v <<< w)
  | _, _, _, .lean_uint16_div, v, w => (v / w)
  | _, _, _, .lean_uint8_land, v, w => (v &&& w)
  | _, _, _, .lean_uint64_dec_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_uint8_mul, v, w => (v * w)
  | _, _, _, .lean_uint64_sub, v, w => (v - w)
  | _, _, _, .lean_uint8_add, v, w => (v + w)
  | _, _, _, .lean_usize_div, v, w => (v / w)
  | _, _, _, .lean_uint32_xor, v, w => (v ^^^ w)
  | _, _, _, .lean_uint16_dec_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_uint32_shift_left, v, w => (v <<< w)
  | _, _, _, .lean_uint16_sub, v, w => (v - w)
  | _, _, _, .lean_uint32_mul, v, w => (v * w)
  | _, _, _, .lean_uint32_land, v, w => (v &&& w)
  | _, _, _, .lean_usize_mod, v, w => (v % w)
  | _, _, _, .lean_uint8_mod, v, w => (v % w)
  | _, _, _, .lean_uint64_dec_lt, v, w => (decide (v < w))
  | _, _, _, .lean_uint8_xor, v, w => (v ^^^ w)
  | _, _, _, .lean_uint16_shift_right, v, w => (v >>> w)
  | _, _, _, .lean_uint64_xor, v, w => (v ^^^ w)
  | _, _, _, .lean_string_append_defs, v, w => (v ++ w)
  | _, _, _, .lean_string_utf8_next_basic, v, w => (String.Pos.Raw.next v w)
  | _, _, _, .lean_string_pos_raw_next, v, w => (String.Pos.Raw.next v w)
  | _, _, _, .lean_string_pos_raw_get, v, w => (String.Pos.Raw.get v w)
  | _, _, _, .lean_string_get_basic, v, w => (String.Pos.Raw.get v w)
  | _, _, _, .lean_string_pos_raw_prev, v, w => (String.Pos.Raw.prev v w)
  | _, _, _, .lean_string_prev, v, w => (String.Pos.Raw.prev v w)
  | _, _, _, .lean_string_next_fast, v, w => (String.Pos.Raw.next v w)
  | _, _, _, .lean_string_pos_raw_next_fast, v, w => (String.Pos.Raw.next v w)
  | _, _, _, .lean_string_pos_next, v, w => (String.Pos.Raw.next v w)
  | _, _, _, .lean_string_at_end_basic, v, w => (String.Pos.Raw.atEnd v w)
  | _, _, _, .lean_string_pos_raw_at_end, v, w => (String.Pos.Raw.atEnd v w)
  | _, _, _, .lean_string_pos_raw_get_bang, v, w => (String.Pos.Raw.get! v w)
  | _, _, _, .lean_string_get_bang, v, w => (String.Pos.Raw.get! v w)
  -- | _, _, _, .lean_string_utf8_get_fast, v, w => (String.decodeChar v w)
  | _, _, _, .lean_string_get_fast, v, w => (String.Pos.Raw.get v w)
  | _, _, _, .lean_string_pos_raw_get_fast, v, w => (String.Pos.Raw.get v w)
  | _, _, _, .lean_string_is_valid_pos, v, w => (String.Pos.Raw.isValid v w)
  | _, _, _, .lean_string_dec_lt, v, w => (decide (v < w))
  | _, _, _, .lean_int8_add, v, w => (v + w)
  | _, _, _, .lean_int16_dec_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_int32_land, v, w => (v &&& w)
  | _, _, _, .lean_int8_div, v, w => (v / w)
  | _, _, _, .lean_int32_mul, v, w => (v * w)
  | _, _, _, .lean_int64_sub, v, w => (v - w)
  | _, _, _, .lean_int16_shift_right, v, w => (v >>> w)
  | _, _, _, .lean_int64_xor, v, w => (v ^^^ w)
  | _, _, _, .lean_int32_dec_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_isize_xor, v, w => (v ^^^ w)
  | _, _, _, .lean_isize_shift_left, v, w => (v <<< w)
  | _, _, _, .lean_int64_mul, v, w => (v * w)
  | _, _, _, .lean_int32_sub, v, w => (v - w)
  | _, _, _, .lean_int64_land, v, w => (v &&& w)
  | _, _, _, .lean_int8_shift_right, v, w => (v >>> w)
  | _, _, _, .lean_int64_lor, v, w => (v ||| w)
  | _, _, _, .lean_int16_div, v, w => (v / w)
  | _, _, _, .lean_isize_mod, v, w => (v % w)
  | _, _, _, .lean_int8_mod, v, w => (v % w)
  | _, _, _, .lean_isize_shift_right, v, w => (v >>> w)
  | _, _, _, .lean_int8_shift_left, v, w => (v <<< w)
  | _, _, _, .lean_int16_dec_lt, v, w => (decide (v < w))
  | _, _, _, .lean_int8_xor, v, w => (v ^^^ w)
  | _, _, _, .lean_int32_dec_eq, v, w => (v == w)
  | _, _, _, .lean_int16_mod, v, w => (v % w)
  | _, _, _, .lean_isize_div, v, w => (v / w)
  | _, _, _, .lean_int16_dec_eq, v, w => (v == w)
  | _, _, _, .lean_isize_add, v, w => (v + w)
  | _, _, _, .lean_int32_dec_lt, v, w => (decide (v < w))
  | _, _, _, .lean_isize_lor, v, w => (v ||| w)
  | _, _, _, .lean_int64_mod, v, w => (v % w)
  | _, _, _, .lean_int64_shift_left, v, w => (v <<< w)
  | _, _, _, .lean_isize_land, v, w => (v &&& w)
  | _, _, _, .lean_isize_mul, v, w => (v * w)
  | _, _, _, .lean_int64_dec_lt, v, w => (decide (v < w))
  | _, _, _, .lean_isize_dec_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_int8_dec_eq, v, w => (v == w)
  | _, _, _, .lean_int32_xor, v, w => (v ^^^ w)
  | _, _, _, .lean_int32_shift_left, v, w => (v <<< w)
  | _, _, _, .lean_isize_sub, v, w => (v - w)
  | _, _, _, .lean_int16_land, v, w => (v &&& w)
  | _, _, _, .lean_int32_shift_right, v, w => (v >>> w)
  | _, _, _, .lean_int16_mul, v, w => (v * w)
  | _, _, _, .lean_int16_shift_left, v, w => (v <<< w)
  | _, _, _, .lean_int16_xor, v, w => (v ^^^ w)
  | _, _, _, .lean_int8_dec_lt, v, w => (decide (v < w))
  | _, _, _, .lean_int64_dec_eq, v, w => (v == w)
  | _, _, _, .lean_int64_dec_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_int32_add, v, w => (v + w)
  | _, _, _, .lean_isize_dec_lt, v, w => (decide (v < w))
  | _, _, _, .lean_int32_lor, v, w => (v ||| w)
  | _, _, _, .lean_int32_mod, v, w => (v % w)
  | _, _, _, .lean_int64_add, v, w => (v + w)
  | _, _, _, .lean_int8_sub, v, w => (v - w)
  | _, _, _, .lean_int16_lor, v, w => (v ||| w)
  | _, _, _, .lean_int64_div, v, w => (v / w)
  | _, _, _, .lean_isize_dec_eq, v, w => (v == w)
  | _, _, _, .lean_int16_add, v, w => (v + w)
  | _, _, _, .lean_int8_dec_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_int8_mul, v, w => (v * w)
  | _, _, _, .lean_int8_land, v, w => (v &&& w)
  | _, _, _, .lean_int32_div, v, w => (v / w)
  | _, _, _, .lean_int16_sub, v, w => (v - w)
  | _, _, _, .lean_int8_lor, v, w => (v ||| w)
  | _, _, _, .lean_int64_shift_right, v, w => (v >>> w)
  | _, _, _, .lean_float_div, v, w => (v / w)
  | _, _, _, .lean_float_beq, v, w => (v == w)
  | _, _, _, .lean_float_decLe, v, w => (decide (v ≤ w))
  | _, _, _, .lean_float_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_float_decLt, v, w => (decide (v < w))
  | _, _, _, .lean_float_lt, v, w => (decide (v < w))
  | _, _, _, .atan2, v, w => (Float.atan2 v w)
  | _, _, _, .lean_float_mul, v, w => (v * w)
  | _, _, _, .pow, v, w => (Float.pow v w)
  | _, _, _, .lean_float_scaleb, v, w => (Float.scaleB v (Int64.toInt w))
  | _, _, _, .lean_float_add, v, w => (v + w)
  | _, _, _, .lean_float_sub, v, w => (v - w)
  | _, _, _, .lean_float32_div, v, w => (v / w)
  | _, _, _, .lean_float32_le, v, w => (decide (v ≤ w))
  | _, _, _, .lean_float32_decLe, v, w => (decide (v ≤ w))
  | _, _, _, .lean_float32_sub, v, w => (v - w)
  | _, _, _, .powf, v, w => (Float32.pow v w)
  | _, _, _, .lean_float32_beq, v, w => (v == w)
  | _, _, _, .atan2f, v, w => (Float32.atan2 v w)
  | _, _, _, .lean_float32_add, v, w => (v + w)
  | _, _, _, .lean_float32_scaleb, v, w => (Float32.scaleB v (Int64.toInt w))
  | _, _, _, .lean_float32_mul, v, w => (v * w)
  | _, _, _, .lean_float32_lt, v, w => (decide (v < w))
  | _, _, _, .lean_float32_decLt, v, w => (decide (v < w))
  | _, _, _, .lean_string_contains, v, w => (String.contains v w)
  | _, _, _, .lean_string_posof, v, w => (String.Internal.posOf v w)
  | _, _, _, .lean_string_offsetofpos, v, w => (String.Pos.Raw.offsetOfPos v w)
  | _, _, _, .lean_string_get_byte_fast, v, w => ((String.toUTF8 v)[w]!)
  -- | _, _, _, .lean_string_get_utf8_byte, v, w => ((String.toUTF8 v)[w]!)
  -- | _, _, _, .lean_string_get_byte_fast_raw, v, w => ((String.toUTF8 v)[w]!)
  | _, _, _, .lean_string_uget_byte_fast, v, w => ((String.toUTF8 v)[w.toNat]!) -- TODO: use ugetUTF8Byte, but its dependent
  | _, _, _, .lean_slice_dec_lt, v, w => (v < w)

end LeanScript

end
