module

prelude
public import Init
public import LeanScript.LeanInitPureExterns
-- public import LeanScript.ExternEval

@[expose] public section

set_option autoImplicit false

/-!
# The meaning of the one-argument terminal externs

One Lean function per entry of `LeanInitPureExtern_T_T`, on the values its argument
and result types denote.  The function is **total**: there is a row for every entry of
the family, so `eval` answers with `b.denote` and not with `Option b.denote`, and the
δ-rule of `LeanScript.Eval` that runs a one-argument extern carries no side condition.
The entries that denoted no function of their argument's value are commented out of
`LeanScript.LeanInitPureExterns`, each with its reason.
-/

namespace LeanScript

/-- The function a one-argument terminal extern denotes. -/
def LeanInitPureExtern_T_T.eval : ∀ {a b : LeanPrimTy},
    LeanInitPureExtern_T_T a b → a.denote → b.denote
  | _, _, .lean_uint32_of_nat_mk, v => (UInt32.ofBitVec v)
  | _, _, .lean_uint32_of_nat_lt, v => (UInt32.ofNat v)
  | _, _, .lean_char_of_nat_aux, v => (Char.ofNat v)
  | _, _, .lean_uint8_to_bitvec, v => (UInt8.toBitVec v)
  | _, _, .lean_uint8_of_nat, v => (UInt8.ofNat v)
  | _, _, .lean_uint8_of_nat_lt, v => (UInt8.ofNat v)
  | _, _, .lean_uint16_to_bitvec, v => (UInt16.toBitVec v)
  | _, _, .lean_uint16_of_nat_mk, v => (UInt16.ofBitVec v)
  | _, _, .lean_nat_pred, v => (Nat.pred v)
  | _, _, .lean_usize_of_nat_lt, v => (UInt64.ofNat v)
  | _, _, .lean_string_hash, v => (String.hash v)
  | _, _, .lean_uint64_to_bitvec, v => (UInt64.toBitVec v)
  | _, _, .lean_uint64_of_nat_mk, v => (UInt64.ofBitVec v)
  | _, _, .lean_uint32_to_nat, v => (UInt32.toNat v)
  | _, _, .lean_uint32_to_bitvec, v => (UInt32.toBitVec v)
  | _, _, .lean_uint16_of_nat_lt, v => (UInt16.ofNat v)
  | _, _, .lean_uint8_of_nat_mk, v => (UInt8.ofBitVec v)
  | _, _, .lean_usize_of_nat_mk, v => (UInt64.ofBitVec v)
  | _, _, .lean_usize_to_bitvec, v => (UInt64.toBitVec v)
  | _, _, .lean_string_utf8_byte_size, v => (String.utf8ByteSize v)
  | _, _, .lean_uint64_of_nat_lt, v => (UInt64.ofNat v)
  | _, _, .lean_nat_to_int, v => (Int.ofNat v)
  | _, _, .lean_int_to_nat, v => (Int.toNat v)
  | _, _, .lean_int_dec_nonneg, v => (@decide _ (Int.decNonneg v))
  | _, _, .lean_int_neg_succ_of_nat, v => (Int.negSucc v)
  | _, _, .lean_int_neg, v => (Int.neg v)
  | _, _, .lean_nat_abs, v => (Int.natAbs v)
  | _, _, .lean_uint64_to_nat, v => (UInt64.toNat v)
  | _, _, .lean_uint32_to_uint8, v => (UInt32.toUInt8 v)
  | _, _, .lean_usize_to_nat, v => (UInt64.toNat v)
  | _, _, .lean_uint64_to_uint32, v => (UInt64.toUInt32 v)
  | _, _, .lean_uint32_to_uint16, v => (UInt32.toUInt16 v)
  | _, _, .lean_uint16_to_uint32, v => (UInt16.toUInt32 v)
  | _, _, .lean_uint32_to_uint64, v => (UInt32.toUInt64 v)
  | _, _, .lean_uint32_of_nat, v => (UInt32.ofNat v)
  | _, _, .lean_uint16_to_nat, v => (UInt16.toNat v)
  | _, _, .lean_uint16_to_uint8, v => (UInt16.toUInt8 v)
  | _, _, .lean_usize_of_nat, v => (UInt64.ofNat v)
  | _, _, .lean_uint8_to_uint64, v => (UInt8.toUInt64 v)
  | _, _, .lean_uint8_to_nat, v => (UInt8.toNat v)
  | _, _, .lean_uint64_of_nat, v => (UInt64.ofNat v)
  | _, _, .lean_uint8_to_uint32, v => (UInt8.toUInt32 v)
  | _, _, .lean_uint16_of_nat, v => (UInt16.ofNat v)
  | _, _, .lean_uint16_to_uint64, v => (UInt16.toUInt64 v)
  | _, _, .lean_uint64_to_uint8, v => (UInt64.toUInt8 v)
  | _, _, .lean_uint64_to_uint16, v => (UInt64.toUInt16 v)
  | _, _, .lean_uint8_to_uint16, v => (UInt8.toUInt16 v)
  | _, _, .lean_string_trim, v => (String.Internal.trim v)
  | _, _, .lean_substring_tostring, v => (Substring.Raw.Internal.toString v)
  | _, _, .lean_string_isempty, v => (String.Internal.isEmpty v)
  | _, _, .lean_string_front, v => (String.Internal.front v)
  | _, _, .lean_string_length, v => (String.Internal.length v)
  | _, _, .lean_string_capitalize, v => (String.Internal.capitalize v)
  | _, _, .lean_substring_front, v => (Substring.Raw.Internal.front v)
  | _, _, .lean_substring_isempty, v => (Substring.Raw.Internal.isEmpty v)
  | _, _, .lean_string_of_usize, v => (USize.repr (UInt64.toUSize v))
  | _, _, .lean_nat_log2, v => (Nat.log2 v)
  | _, _, .lean_uint16_neg, v => (UInt16.neg v)
  | _, _, .lean_uint16_to_usize, v => (UInt16.toUInt64 v)
  | _, _, .lean_uint64_complement, v => (UInt64.complement v)
  | _, _, .lean_bool_to_uint32, v => (Bool.toUInt32 v)
  | _, _, .lean_uint8_neg, v => (UInt8.neg v)
  | _, _, .lean_uint16_complement, v => (UInt16.complement v)
  | _, _, .lean_uint32_neg, v => (UInt32.neg v)
  | _, _, .lean_usize_neg, v => (UInt64.neg v)
  | _, _, .lean_usize_to_uint64, v => v
  | _, _, .lean_bool_to_uint64, v => (Bool.toUInt64 v)
  | _, _, .lean_usize_of_nat32, v => (UInt64.ofNat v)
  | _, _, .lean_uint64_neg, v => (UInt64.neg v)
  | _, _, .lean_uint32_to_usize, v => (UInt32.toUInt64 v)
  | _, _, .lean_uint8_complement, v => (UInt8.complement v)
  | _, _, .lean_usize_to_uint16, v => (UInt64.toUInt16 v)
  | _, _, .lean_usize_to_uint8, v => (UInt64.toUInt8 v)
  | _, _, .lean_bool_to_uint8, v => (Bool.toUInt8 v)
  | _, _, .lean_uint32_complement, v => (UInt32.complement v)
  | _, _, .lean_uint8_to_usize, v => (UInt8.toUInt64 v)
  | _, _, .lean_bool_to_uint16, v => (Bool.toUInt16 v)
  | _, _, .lean_bool_to_usize, v => (Bool.toUInt64 v)
  | _, _, .lean_uint64_to_usize, v => v
  | _, _, .lean_usize_to_uint32, v => (UInt64.toUInt32 v)
  | _, _, .lean_usize_complement, v => (UInt64.complement v)
  | _, _, .lean_string_length_def, v => (String.length v)
  | _, _, .lean_isize_complement, v => (Int64.complement v)
  | _, _, .lean_int16_of_nat, v => (Int16.ofNat v)
  | _, _, .lean_int32_of_int, v => (Int32.ofInt v)
  | _, _, .lean_int64_to_isize, v => v
  | _, _, .lean_isize_to_int8, v => (Int64.toInt8 v)
  | _, _, .lean_int32_of_nat, v => (Int32.ofNat v)
  | _, _, .lean_int64_to_int8, v => (Int64.toInt8 v)
  | _, _, .lean_int32_to_int64, v => (Int32.toInt64 v)
  | _, _, .lean_int8_to_int16, v => (Int8.toInt16 v)
  | _, _, .lean_int64_of_int, v => (Int64.ofInt v)
  | _, _, .lean_int32_to_isize, v => (Int32.toInt64 v)
  | _, _, .lean_int32_neg, v => (Int32.neg v)
  | _, _, .lean_int32_abs, v => (Int32.abs v)
  | _, _, .lean_bool_to_int8, v => (Bool.toInt8 v)
  | _, _, .lean_isize_to_int16, v => (Int64.toInt16 v)
  | _, _, .lean_int16_to_int, v => (Int16.toInt v)
  | _, _, .lean_int8_complement, v => (Int8.complement v)
  | _, _, .lean_bool_to_int16, v => (Bool.toInt16 v)
  | _, _, .lean_isize_of_int, v => (Int64.ofInt v)
  | _, _, .lean_int16_abs, v => (Int16.abs v)
  | _, _, .lean_int16_to_int32, v => (Int16.toInt32 v)
  | _, _, .lean_isize_to_int, v => (Int64.toInt v)
  | _, _, .lean_isize_of_nat, v => (Int64.ofNat v)
  | _, _, .lean_int16_complement, v => (Int16.complement v)
  | _, _, .lean_isize_to_int64, v => v
  | _, _, .lean_int64_complement, v => (Int64.complement v)
  | _, _, .lean_isize_abs, v => (Int64.abs v)
  | _, _, .lean_int16_of_int, v => (Int16.ofInt v)
  | _, _, .lean_int8_neg, v => (Int8.neg v)
  | _, _, .lean_isize_to_int32, v => (Int64.toInt32 v)
  | _, _, .lean_int64_to_int32, v => (Int64.toInt32 v)
  | _, _, .lean_int64_abs, v => (Int64.abs v)
  | _, _, .lean_int32_complement, v => (Int32.complement v)
  | _, _, .lean_bool_to_int64, v => (Bool.toInt64 v)
  | _, _, .lean_bool_to_isize, v => (Bool.toInt64 v)
  | _, _, .lean_bool_to_int32, v => (Bool.toInt32 v)
  | _, _, .lean_int64_of_nat, v => (Int64.ofNat v)
  | _, _, .lean_int32_to_int8, v => (Int32.toInt8 v)
  | _, _, .lean_int64_to_int_sint, v => (Int64.toInt v)
  | _, _, .lean_int64_neg, v => (Int64.neg v)
  | _, _, .lean_int8_abs, v => (Int8.abs v)
  | _, _, .lean_int8_to_int32, v => (Int8.toInt32 v)
  | _, _, .lean_isize_neg, v => (Int64.neg v)
  | _, _, .lean_int32_to_int, v => (Int32.toInt v)
  | _, _, .lean_int32_to_int16, v => (Int32.toInt16 v)
  | _, _, .lean_int8_to_int64, v => (Int8.toInt64 v)
  | _, _, .lean_int8_to_isize, v => (Int8.toInt64 v)
  | _, _, .lean_int8_of_nat, v => (Int8.ofNat v)
  | _, _, .lean_int16_to_int8, v => (Int16.toInt8 v)
  | _, _, .lean_int8_to_int, v => (Int8.toInt v)
  | _, _, .lean_int16_neg, v => (Int16.neg v)
  | _, _, .lean_int64_to_int16, v => (Int64.toInt16 v)
  | _, _, .lean_int8_of_int, v => (Int8.ofInt v)
  | _, _, .lean_int16_to_isize, v => (Int16.toInt64 v)
  | _, _, .lean_int16_to_int64, v => (Int16.toInt64 v)
  | _, _, .lean_slice_hash, v => (String.Slice.hash v)
  | _, _, .lean_uint8_to_float, v => (UInt8.toFloat v)
  | _, _, .lean_float_to_bits, v => (Float.toBits v)
  | _, _, .lean_float_of_bits, v => (Float.ofBits v)
  | _, _, .lean_float_isnan, v => (Float.isNaN v)
  | _, _, .log10, v => (Float.log10 v)
  | _, _, .cbrt, v => (Float.cbrt v)
  | _, _, .log, v => (Float.log v)
  | _, _, .tan, v => (Float.tan v)
  | _, _, .tanh, v => (Float.tanh v)
  | _, _, .exp2, v => (Float.exp2 v)
  | _, _, .lean_float_to_uint16, v => (Float.toUInt16 v)
  | _, _, .lean_uint32_to_float, v => (UInt32.toFloat v)
  | _, _, .lean_float_to_uint64, v => (Float.toUInt64 v)
  | _, _, .sqrt, v => (Float.sqrt v)
  | _, _, .acos, v => (Float.acos v)
  | _, _, .atan, v => (Float.atan v)
  | _, _, .acosh, v => (Float.acosh v)
  | _, _, .floor, v => (Float.floor v)
  | _, _, .fabs, v => (Float.abs v)
  | _, _, .lean_float_to_uint32, v => (Float.toUInt32 v)
  | _, _, .lean_float_to_string, v => (Float.toString v)
  | _, _, .lean_uint64_to_float, v => (UInt64.toFloat v)
  | _, _, .lean_float_to_uint8, v => (Float.toUInt8 v)
  | _, _, .sin, v => (Float.sin v)
  | _, _, .lean_usize_to_float, v => (UInt64.toFloat v)
  | _, _, .cosh, v => (Float.cosh v)
  | _, _, .exp, v => (Float.exp v)
  | _, _, .ceil, v => (Float.ceil v)
  | _, _, .lean_float_to_usize, v => (Float.toUInt64 v)
  | _, _, .lean_float_isfinite, v => (Float.isFinite v)
  | _, _, .round, v => (Float.round v)
  | _, _, .cos, v => (Float.cos v)
  | _, _, .log2, v => (Float.log2 v)
  | _, _, .atanh, v => (Float.atanh v)
  | _, _, .sinh, v => (Float.sinh v)
  | _, _, .asinh, v => (Float.asinh v)
  | _, _, .lean_uint16_to_float, v => (UInt16.toFloat v)
  | _, _, .asin, v => (Float.asin v)
  | _, _, .lean_float_negate, v => (Float.neg v)
  | _, _, .lean_float_isinf, v => (Float.isInf v)
  | _, _, .lean_usize_log2, v => (UInt64.log2 v)
  | _, _, .lean_uint16_log2, v => (UInt16.log2 v)
  | _, _, .lean_uint64_log2, v => (UInt64.log2 v)
  | _, _, .lean_uint8_log2, v => (UInt8.log2 v)
  | _, _, .lean_uint32_log2, v => (UInt32.log2 v)
  | _, _, .lean_int32_to_float, v => (Int32.toFloat v)
  | _, _, .lean_float_to_int16, v => (Float.toInt16 v)
  | _, _, .lean_int16_to_float, v => (Int16.toFloat v)
  | _, _, .lean_float_to_int32, v => (Float.toInt32 v)
  | _, _, .lean_isize_to_float, v => (Int64.toFloat v)
  | _, _, .lean_int8_to_float, v => (Int8.toFloat v)
  | _, _, .lean_float_to_int8, v => (Float.toInt8 v)
  | _, _, .lean_int64_to_float, v => (Int64.toFloat v)
  | _, _, .lean_float_to_int64, v => (Float.toInt64 v)
  | _, _, .lean_float_to_isize, v => (Float.toInt64 v)
  | _, _, .tanhf, v => (Float32.tanh v)
  | _, _, .exp2f, v => (Float32.exp2 v)
  | _, _, .logf, v => (Float32.log v)
  | _, _, .lean_float_to_float32, v => (Float.toFloat32 v)
  | _, _, .lean_float32_to_bits, v => (Float32.toBits v)
  | _, _, .lean_float32_of_bits, v => (Float32.ofBits v)
  | _, _, .atanf, v => (Float32.atan v)
  | _, _, .acoshf, v => (Float32.acosh v)
  | _, _, .lean_float32_to_uint64, v => (Float32.toUInt64 v)
  | _, _, .lean_float32_to_uint16, v => (Float32.toUInt16 v)
  | _, _, .lean_usize_to_float32, v => (UInt64.toFloat32 v)
  | _, _, .asinf, v => (Float32.asin v)
  | _, _, .lean_uint8_to_float32, v => (UInt8.toFloat32 v)
  | _, _, .tanf, v => (Float32.tan v)
  | _, _, .lean_float32_to_float, v => (Float32.toFloat v)
  | _, _, .lean_float32_isnan, v => (Float32.isNaN v)
  | _, _, .log10f, v => (Float32.log10 v)
  | _, _, .cbrtf, v => (Float32.cbrt v)
  | _, _, .sinhf, v => (Float32.sinh v)
  | _, _, .cosf, v => (Float32.cos v)
  | _, _, .lean_uint32_to_float32, v => (UInt32.toFloat32 v)
  | _, _, .lean_float32_isinf, v => (Float32.isInf v)
  | _, _, .lean_float32_negate, v => (Float32.neg v)
  | _, _, .lean_float32_to_usize, v => (Float32.toUInt64 v)
  | _, _, .ceilf, v => (Float32.ceil v)
  | _, _, .lean_float32_isfinite, v => (Float32.isFinite v)
  | _, _, .sinf, v => (Float32.sin v)
  | _, _, .lean_float32_to_string, v => (Float32.toString v)
  | _, _, .asinhf, v => (Float32.asinh v)
  | _, _, .lean_float32_to_uint32, v => (Float32.toUInt32 v)
  | _, _, .log2f, v => (Float32.log2 v)
  | _, _, .lean_uint64_to_float32, v => (UInt64.toFloat32 v)
  | _, _, .atanhf, v => (Float32.atanh v)
  | _, _, .floorf, v => (Float32.floor v)
  | _, _, .fabsf, v => (Float32.abs v)
  | _, _, .roundf, v => (Float32.round v)
  | _, _, .acosf, v => (Float32.acos v)
  | _, _, .sqrtf, v => (Float32.sqrt v)
  | _, _, .lean_uint16_to_float32, v => (UInt16.toFloat32 v)
  | _, _, .coshf, v => (Float32.cosh v)
  | _, _, .expf, v => (Float32.exp v)
  | _, _, .lean_float32_to_uint8, v => (Float32.toUInt8 v)
  | _, _, .lean_float32_to_int64, v => (Float32.toInt64 v)
  | _, _, .lean_float32_to_isize, v => (Float32.toInt64 v)
  | _, _, .lean_int32_to_float32, v => (Int32.toFloat32 v)
  | _, _, .lean_float32_to_int8, v => (Float32.toInt8 v)
  | _, _, .lean_float32_to_int16, v => (Float32.toInt16 v)
  | _, _, .lean_isize_to_float32, v => (Int64.toFloat32 v)
  | _, _, .lean_int8_to_float32, v => (Int8.toFloat32 v)
  | _, _, .lean_float32_to_int32, v => (Float32.toInt32 v)
  | _, _, .lean_int16_to_float32, v => (Int16.toFloat32 v)
  | _, _, .lean_int64_to_float32, v => (Int64.toFloat32 v)

end LeanScript

end
