// JavaScript of Tests/SnapshotsMy/AppArity.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

import { uint53__lean_nat_add, uint53__lean_nat_mul } from "../../runtime.js";

/**
 * `mkAdd`
 * @param {uint53(number)} n
 * @param {uint53(number)} a
 * @param {uint53(number)} a1
 * @returns {uint53(number)}
 */
export const mkAdd = (n, a, a1) =>
  uint53__lean_nat_add(uint53__lean_nat_add(a, a1), n);

/**
 * `test1`
 * @param {uint53(number)} n
 * @param {uint53(number)} x
 * @param {uint53(number)} y
 * @returns {uint53(number)}
 */
export const test1 = (n, x, y) => {
  const k$6 = (x$1, x$2, x$3) => {
    const x$4 = x$1(x$2, x$3);
    const x$5 = x$1(x$3, x$2);
    return uint53__lean_nat_add(x$4, x$5);
  };
  const k$10 = (x$7, x$8, x$9) =>
    uint53__lean_nat_add(uint53__lean_nat_add(x$8, x$9), x$7);
  const x$13 = (y$11, y$12) => k$10(n, y$11, y$12);
  const x$14 = k$6(x$13, x, y);
  return x$14;
};

/**
 * `mkMul`
 * @param {uint53(number)} n
 * @param {uint53(number)} a
 * @param {uint53(number)} a1
 * @returns {uint53(number)}
 */
export const mkMul = (n, a, a1) =>
  uint53__lean_nat_mul(uint53__lean_nat_mul(a, a1), n);

/**
 * `test2`
 * @param {uint53(number)} n
 * @param {uint53(number)} x
 * @param {uint53(number)} y
 * @returns {uint53(number)}
 */
export const test2 = (n, x, y) => {
  const k$6 = (x$1, x$2, x$3) => {
    const x$4 = x$1(x$2, x$3);
    const x$5 = x$1(x$3, x$2);
    return uint53__lean_nat_add(x$4, x$5);
  };
  const k$10 = (x$7, x$8, x$9) =>
    uint53__lean_nat_mul(uint53__lean_nat_mul(x$8, x$9), x$7);
  const x$13 = (y$11, y$12) => k$10(n, y$11, y$12);
  const x$14 = k$6(x$13, x, y);
  return x$14;
};

/**
 * `mkSum3`
 * @param {uint53(number)} n
 * @param {uint53(number)} a
 * @param {uint53(number)} a1
 * @param {uint53(number)} a2
 * @returns {uint53(number)}
 */
export const mkSum3 = (n, a, a1, a2) =>
  uint53__lean_nat_add(
    uint53__lean_nat_add(uint53__lean_nat_add(a, a1), a2),
    n,
  );

/**
 * `test3`
 * @param {uint53(number)} n
 * @param {uint53(number)} x
 * @param {uint53(number)} y
 * @returns {uint53(number)}
 */
export const test3 = (n, x, y) => {
  const k$5 = (x$1, x$2, x$3) => {
    const x$4 = x$1(x$2, x$3, x$2);
    return x$4;
  };
  const k$10 = (x$6, x$7, x$8, x$9) =>
    uint53__lean_nat_add(
      uint53__lean_nat_add(uint53__lean_nat_add(x$7, x$8), x$9),
      x$6,
    );
  const x$14 = (y$11, y$12, y$13) => k$10(n, y$11, y$12, y$13);
  const x$15 = k$5(x$14, x, y);
  return x$15;
};

/**
 * `test4`
 * @param {(uint53(number), uint53(number)) => uint53(number)} f
 * @param {uint53(number)} x
 * @param {uint53(number)} y
 * @returns {uint53(number)}
 */
export const test4 = (f, x, y) => {
  const x$1 = f(x, y);
  const x$2 = f(y, x);
  return uint53__lean_nat_add(x$1, x$2);
};
