// Differential checks of ArrayInPlace.js against Lean, generated by leanscript --check
import * as M from "./ArrayInPlace.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  return String(v);
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("test1(0n)", () => M.test1(0n), "#[]", false);
check("test1(1n)", () => M.test1(1n), "#[0]", false);
check("test1(2n)", () => M.test1(2n), "#[0, 1]", false);
check("test1(5n)", () => M.test1(5n), "#[0, 1, 4, 9, 16]", false);
check("test1(13n)", () => M.test1(13n), "#[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144]", false);
check("test3([])", () => M.test3([]), "#[]", false);
check("test3([0n])", () => M.test3([0n]), "#[0]", false);
check("test3([0n, 1n, 2n])", () => M.test3([0n, 1n, 2n]), "#[0, 2, 4]", false);
check("test3([13n, 5n, 2n, 1n])", () => M.test3([13n, 5n, 2n, 1n]), "#[26, 10, 4, 2]", false);
check("test5(0n)", () => M.test5(0n), "#[]", false);
check("test5(1n)", () => M.test5(1n), "#[]", false);
check("test5(2n)", () => M.test5(2n), "#[1]", false);
check("test5(5n)", () => M.test5(5n), "#[4, 3, 2, 1]", false);
check("test5(13n)", () => M.test5(13n), "#[12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]", false);
check("test6(0n)", () => M.test6(0n), "#[]", false);
check("test6(1n)", () => M.test6(1n), "#[0]", false);
check("test6(2n)", () => M.test6(2n), "#[1, 0]", false);
check("test6(5n)", () => M.test6(5n), "#[4, 3, 2, 1, 0]", false);
check("test6(13n)", () => M.test6(13n), "#[12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]", false);

console.log(`ArrayInPlace.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
