// Differential checks of ArrayFSet-faithful.js against Lean, generated by leanscript --check
import * as M from "./ArrayFSet-faithful.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("test1(0n)", () => M.test1(0n), "#[7, 2, 1, 3]", false);
check("test1(1n)", () => M.test1(1n), "#[7, 2, 1, 3]", false);
check("test1(2n)", () => M.test1(2n), "#[7, 2, 1, 3]", false);
check("test1(5n)", () => M.test1(5n), "#[7, 2, 1, 3]", false);
check("test1(13n)", () => M.test1(13n), "#[7, 2, 1, 3]", false);
check("test2(0n)", () => M.test2(0n), "{#[0, 1, 2, 3], #[0, 1, 0, 3]}", false);
check("test2(1n)", () => M.test2(1n), "{#[1, 1, 2, 3], #[1, 1, 1, 3]}", false);
check("test2(2n)", () => M.test2(2n), "{#[2, 1, 2, 3], #[2, 1, 2, 3]}", false);
check("test2(5n)", () => M.test2(5n), "{#[5, 1, 2, 3], #[5, 1, 5, 3]}", false);
check("test2(13n)", () => M.test2(13n), "{#[13, 1, 2, 3], #[13, 1, 13, 3]}", false);
check("test4([])", () => M.test4([]), "#[]", false);
check("test4([]) twice", () => ((a0) => (M.test4(a0), M.test4(a0)))([]), "#[]", false);
check("test4([0n])", () => M.test4([0n]), "#[5]", false);
check("test4([0n]) twice", () => ((a0) => (M.test4(a0), M.test4(a0)))([0n]), "#[5]", false);
check("test4([0n, 1n, 2n])", () => M.test4([0n, 1n, 2n]), "#[5, 1, 2]", false);
check("test4([0n, 1n, 2n]) twice", () => ((a0) => (M.test4(a0), M.test4(a0)))([0n, 1n, 2n]), "#[5, 1, 2]", false);
check("test4([13n, 5n, 2n, 1n])", () => M.test4([13n, 5n, 2n, 1n]), "#[5, 5, 2, 1]", false);
check("test4([13n, 5n, 2n, 1n]) twice", () => ((a0) => (M.test4(a0), M.test4(a0)))([13n, 5n, 2n, 1n]), "#[5, 5, 2, 1]", false);

console.log(`ArrayFSet-faithful.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
