// Differential checks of ArrayIndexBounds-pbo.js against Lean, generated by leanscript --check
import * as M from "./ArrayIndexBounds-pbo.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
// a recursive union: as `showUnion`, the fields marked in `rec[tag]` (the type itself) printed
// the same way, one level less deep (`…` at depth 0, as `showExpr` cuts it in Lean)
function showTree(v, rec, d) {
  if (d === 0) return "…";
  if (typeof v === "number") return v + "()";
  const r = rec[v.tag] || [];
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++)
    fs.push(r[i - 1] ? showTree(v["_" + i], rec, d - 1) : show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("array", () => M.array, "#[1, 2, 3]", false);
check("getOpt(0)", () => (showUnion)(M.getOpt(0)), "1(1)", false);
check("getOpt(1)", () => (showUnion)(M.getOpt(1)), "1(2)", false);
check("getOpt(2)", () => (showUnion)(M.getOpt(2)), "1(3)", false);
check("getOpt(5)", () => (showUnion)(M.getOpt(5)), "0()", false);
check("getOpt(13)", () => (showUnion)(M.getOpt(13)), "0()", false);
check("getD(0)", () => M.getD(0), "10", false);
check("getD(1)", () => M.getD(1), "20", false);
check("getD(2)", () => M.getD(2), "30", false);
check("getD(5)", () => M.getD(5), "0", false);
check("getD(13)", () => M.getD(13), "0", false);
check("getLe(0)", () => M.getLe(0), "10", false);
check("getLe(1)", () => M.getLe(1), "20", false);
check("getLe(2)", () => M.getLe(2), "30", false);
check("getLe(5)", () => M.getLe(5), "0", false);
check("getLe(13)", () => M.getLe(13), "0", false);
check("getGe(0)", () => M.getGe(0), "10", false);
check("getGe(1)", () => M.getGe(1), "20", false);
check("getGe(2)", () => M.getGe(2), "30", false);
check("getGe(5)", () => M.getGe(5), "0", false);
check("getGe(13)", () => M.getGe(13), "0", false);
check("getUnproved(0)", () => M.getUnproved(0), "10", false);
check("getUnproved(1)", () => M.getUnproved(1), "20", false);
check("getUnproved(2)", () => M.getUnproved(2), "30", false);
check("getUnproved(5)", () => M.getUnproved(5), "0", false);
check("getUnproved(13)", () => M.getUnproved(13), "0", false);
check("getSized([], 0)", () => M.getSized([], 0), "2", false);
check("getSized([], 0) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([], 0), "2", false);
check("getSized([], 1)", () => M.getSized([], 1), "2", false);
check("getSized([], 1) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([], 1), "2", false);
check("getSized([-7], 0)", () => M.getSized([-7], 0), "2", false);
check("getSized([-7], 0) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7], 0), "2", false);
check("getSized([], 2)", () => M.getSized([], 2), "2", false);
check("getSized([], 2) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([], 2), "2", false);
check("getSized([-7], 1)", () => M.getSized([-7], 1), "2", false);
check("getSized([-7], 1) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7], 1), "2", false);
check("getSized([-7, -1, 0], 0)", () => M.getSized([-7, -1, 0], 0), "2", false);
check("getSized([-7, -1, 0], 0) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7, -1, 0], 0), "2", false);
check("getSized([], 5)", () => M.getSized([], 5), "2", false);
check("getSized([], 5) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([], 5), "2", false);
check("getSized([-7], 2)", () => M.getSized([-7], 2), "2", false);
check("getSized([-7], 2) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7], 2), "2", false);
check("getSized([-7, -1, 0], 1)", () => M.getSized([-7, -1, 0], 1), "2", false);
check("getSized([-7, -1, 0], 1) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7, -1, 0], 1), "2", false);
check("getSized([12, 3, 2, 1], 0)", () => M.getSized([12, 3, 2, 1], 0), "2", false);
check("getSized([12, 3, 2, 1], 0) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([12, 3, 2, 1], 0), "2", false);
check("getSized([], 13)", () => M.getSized([], 13), "2", false);
check("getSized([], 13) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([], 13), "2", false);
check("getSized([-7], 5)", () => M.getSized([-7], 5), "2", false);
check("getSized([-7], 5) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7], 5), "2", false);
check("getSized([-7, -1, 0], 2)", () => M.getSized([-7, -1, 0], 2), "2", false);
check("getSized([-7, -1, 0], 2) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7, -1, 0], 2), "2", false);
check("getSized([12, 3, 2, 1], 1)", () => M.getSized([12, 3, 2, 1], 1), "2", false);
check("getSized([12, 3, 2, 1], 1) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([12, 3, 2, 1], 1), "2", false);
check("getSized([-7], 13)", () => M.getSized([-7], 13), "2", false);
check("getSized([-7], 13) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7], 13), "2", false);
check("getSized([-7, -1, 0], 5)", () => M.getSized([-7, -1, 0], 5), "2", false);
check("getSized([-7, -1, 0], 5) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7, -1, 0], 5), "2", false);
check("getSized([12, 3, 2, 1], 2)", () => M.getSized([12, 3, 2, 1], 2), "2", false);
check("getSized([12, 3, 2, 1], 2) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([12, 3, 2, 1], 2), "2", false);
check("getSized([-7, -1, 0], 13)", () => M.getSized([-7, -1, 0], 13), "2", false);
check("getSized([-7, -1, 0], 13) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7, -1, 0], 13), "2", false);
check("getSized([12, 3, 2, 1], 5)", () => M.getSized([12, 3, 2, 1], 5), "2", false);
check("getSized([12, 3, 2, 1], 5) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([12, 3, 2, 1], 5), "2", false);
check("getSized([12, 3, 2, 1], 13)", () => M.getSized([12, 3, 2, 1], 13), "2", false);
check("getSized([12, 3, 2, 1], 13) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([12, 3, 2, 1], 13), "2", false);
check("getSizedUnproved([], 0)", () => M.getSizedUnproved([], 0), "2", false);
check("getSizedUnproved([], 0) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([], 0), "2", false);
check("getSizedUnproved([], 1)", () => M.getSizedUnproved([], 1), "2", false);
check("getSizedUnproved([], 1) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([], 1), "2", false);
check("getSizedUnproved([-7], 0)", () => M.getSizedUnproved([-7], 0), "2", false);
check("getSizedUnproved([-7], 0) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7], 0), "2", false);
check("getSizedUnproved([], 2)", () => M.getSizedUnproved([], 2), "2", false);
check("getSizedUnproved([], 2) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([], 2), "2", false);
check("getSizedUnproved([-7], 1)", () => M.getSizedUnproved([-7], 1), "2", false);
check("getSizedUnproved([-7], 1) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7], 1), "2", false);
check("getSizedUnproved([-7, -1, 0], 0)", () => M.getSizedUnproved([-7, -1, 0], 0), "2", false);
check("getSizedUnproved([-7, -1, 0], 0) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7, -1, 0], 0), "2", false);
check("getSizedUnproved([], 5)", () => M.getSizedUnproved([], 5), "2", false);
check("getSizedUnproved([], 5) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([], 5), "2", false);
check("getSizedUnproved([-7], 2)", () => M.getSizedUnproved([-7], 2), "2", false);
check("getSizedUnproved([-7], 2) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7], 2), "2", false);
check("getSizedUnproved([-7, -1, 0], 1)", () => M.getSizedUnproved([-7, -1, 0], 1), "2", false);
check("getSizedUnproved([-7, -1, 0], 1) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7, -1, 0], 1), "2", false);
check("getSizedUnproved([12, 3, 2, 1], 0)", () => M.getSizedUnproved([12, 3, 2, 1], 0), "2", false);
check("getSizedUnproved([12, 3, 2, 1], 0) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([12, 3, 2, 1], 0), "2", false);
check("getSizedUnproved([], 13)", () => M.getSizedUnproved([], 13), "2", false);
check("getSizedUnproved([], 13) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([], 13), "2", false);
check("getSizedUnproved([-7], 5)", () => M.getSizedUnproved([-7], 5), "2", false);
check("getSizedUnproved([-7], 5) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7], 5), "2", false);
check("getSizedUnproved([-7, -1, 0], 2)", () => M.getSizedUnproved([-7, -1, 0], 2), "2", false);
check("getSizedUnproved([-7, -1, 0], 2) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7, -1, 0], 2), "2", false);
check("getSizedUnproved([12, 3, 2, 1], 1)", () => M.getSizedUnproved([12, 3, 2, 1], 1), "2", false);
check("getSizedUnproved([12, 3, 2, 1], 1) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([12, 3, 2, 1], 1), "2", false);
check("getSizedUnproved([-7], 13)", () => M.getSizedUnproved([-7], 13), "2", false);
check("getSizedUnproved([-7], 13) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7], 13), "2", false);
check("getSizedUnproved([-7, -1, 0], 5)", () => M.getSizedUnproved([-7, -1, 0], 5), "2", false);
check("getSizedUnproved([-7, -1, 0], 5) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7, -1, 0], 5), "2", false);
check("getSizedUnproved([12, 3, 2, 1], 2)", () => M.getSizedUnproved([12, 3, 2, 1], 2), "2", false);
check("getSizedUnproved([12, 3, 2, 1], 2) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([12, 3, 2, 1], 2), "2", false);
check("getSizedUnproved([-7, -1, 0], 13)", () => M.getSizedUnproved([-7, -1, 0], 13), "2", false);
check("getSizedUnproved([-7, -1, 0], 13) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7, -1, 0], 13), "2", false);
check("getSizedUnproved([12, 3, 2, 1], 5)", () => M.getSizedUnproved([12, 3, 2, 1], 5), "2", false);
check("getSizedUnproved([12, 3, 2, 1], 5) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([12, 3, 2, 1], 5), "2", false);
check("getSizedUnproved([12, 3, 2, 1], 13)", () => M.getSizedUnproved([12, 3, 2, 1], 13), "2", false);
check("getSizedUnproved([12, 3, 2, 1], 13) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([12, 3, 2, 1], 13), "2", false);

console.log(`ArrayIndexBounds-pbo.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
