// Differential checks of ArrayIndexBounds-faithful.js against Lean, generated by leanscript --check
import * as M from "./ArrayIndexBounds-faithful.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
// a recursive union: as `showUnion`, the fields marked in `rec[tag]` (the type itself) printed
// the same way, one level less deep (`…` at depth 0, as `showExpr` cuts it in Lean)
function showTree(v, rec, d) {
  if (d === 0) return "…";
  if (typeof v === "number") return v + "()";
  const r = rec[v.tag] || [];
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++)
    fs.push(r[i - 1] ? showTree(v["_" + i], rec, d - 1) : show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("array", () => M.array, "#[1, 2, 3]", false);
check("getOpt(0n)", () => (showUnion)(M.getOpt(0n)), "1(1)", false);
check("getOpt(1n)", () => (showUnion)(M.getOpt(1n)), "1(2)", false);
check("getOpt(2n)", () => (showUnion)(M.getOpt(2n)), "1(3)", false);
check("getOpt(5n)", () => (showUnion)(M.getOpt(5n)), "0()", false);
check("getOpt(13n)", () => (showUnion)(M.getOpt(13n)), "0()", false);
check("getD(0n)", () => M.getD(0n), "10", false);
check("getD(1n)", () => M.getD(1n), "20", false);
check("getD(2n)", () => M.getD(2n), "30", false);
check("getD(5n)", () => M.getD(5n), "0", false);
check("getD(13n)", () => M.getD(13n), "0", false);
check("getLe(0n)", () => M.getLe(0n), "10", false);
check("getLe(1n)", () => M.getLe(1n), "20", false);
check("getLe(2n)", () => M.getLe(2n), "30", false);
check("getLe(5n)", () => M.getLe(5n), "0", false);
check("getLe(13n)", () => M.getLe(13n), "0", false);
check("getGe(0n)", () => M.getGe(0n), "10", false);
check("getGe(1n)", () => M.getGe(1n), "20", false);
check("getGe(2n)", () => M.getGe(2n), "30", false);
check("getGe(5n)", () => M.getGe(5n), "0", false);
check("getGe(13n)", () => M.getGe(13n), "0", false);
check("getUnproved(0n)", () => M.getUnproved(0n), "10", false);
check("getUnproved(1n)", () => M.getUnproved(1n), "20", false);
check("getUnproved(2n)", () => M.getUnproved(2n), "30", false);
check("getUnproved(5n)", () => M.getUnproved(5n), "0", false);
check("getUnproved(13n)", () => M.getUnproved(13n), "0", false);
check("getSized([], 0n)", () => M.getSized([], 0n), "2", false);
check("getSized([], 0n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([], 0n), "2", false);
check("getSized([], 1n)", () => M.getSized([], 1n), "2", false);
check("getSized([], 1n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([], 1n), "2", false);
check("getSized([-7n], 0n)", () => M.getSized([-7n], 0n), "2", false);
check("getSized([-7n], 0n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7n], 0n), "2", false);
check("getSized([], 2n)", () => M.getSized([], 2n), "2", false);
check("getSized([], 2n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([], 2n), "2", false);
check("getSized([-7n], 1n)", () => M.getSized([-7n], 1n), "2", false);
check("getSized([-7n], 1n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7n], 1n), "2", false);
check("getSized([-7n, -1n, 0n], 0n)", () => M.getSized([-7n, -1n, 0n], 0n), "2", false);
check("getSized([-7n, -1n, 0n], 0n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7n, -1n, 0n], 0n), "2", false);
check("getSized([], 5n)", () => M.getSized([], 5n), "2", false);
check("getSized([], 5n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([], 5n), "2", false);
check("getSized([-7n], 2n)", () => M.getSized([-7n], 2n), "2", false);
check("getSized([-7n], 2n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7n], 2n), "2", false);
check("getSized([-7n, -1n, 0n], 1n)", () => M.getSized([-7n, -1n, 0n], 1n), "2", false);
check("getSized([-7n, -1n, 0n], 1n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7n, -1n, 0n], 1n), "2", false);
check("getSized([12n, 3n, 2n, 1n], 0n)", () => M.getSized([12n, 3n, 2n, 1n], 0n), "2", false);
check("getSized([12n, 3n, 2n, 1n], 0n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([12n, 3n, 2n, 1n], 0n), "2", false);
check("getSized([], 13n)", () => M.getSized([], 13n), "2", false);
check("getSized([], 13n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([], 13n), "2", false);
check("getSized([-7n], 5n)", () => M.getSized([-7n], 5n), "2", false);
check("getSized([-7n], 5n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7n], 5n), "2", false);
check("getSized([-7n, -1n, 0n], 2n)", () => M.getSized([-7n, -1n, 0n], 2n), "2", false);
check("getSized([-7n, -1n, 0n], 2n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7n, -1n, 0n], 2n), "2", false);
check("getSized([12n, 3n, 2n, 1n], 1n)", () => M.getSized([12n, 3n, 2n, 1n], 1n), "2", false);
check("getSized([12n, 3n, 2n, 1n], 1n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([12n, 3n, 2n, 1n], 1n), "2", false);
check("getSized([-7n], 13n)", () => M.getSized([-7n], 13n), "2", false);
check("getSized([-7n], 13n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7n], 13n), "2", false);
check("getSized([-7n, -1n, 0n], 5n)", () => M.getSized([-7n, -1n, 0n], 5n), "2", false);
check("getSized([-7n, -1n, 0n], 5n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7n, -1n, 0n], 5n), "2", false);
check("getSized([12n, 3n, 2n, 1n], 2n)", () => M.getSized([12n, 3n, 2n, 1n], 2n), "2", false);
check("getSized([12n, 3n, 2n, 1n], 2n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([12n, 3n, 2n, 1n], 2n), "2", false);
check("getSized([-7n, -1n, 0n], 13n)", () => M.getSized([-7n, -1n, 0n], 13n), "2", false);
check("getSized([-7n, -1n, 0n], 13n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([-7n, -1n, 0n], 13n), "2", false);
check("getSized([12n, 3n, 2n, 1n], 5n)", () => M.getSized([12n, 3n, 2n, 1n], 5n), "2", false);
check("getSized([12n, 3n, 2n, 1n], 5n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([12n, 3n, 2n, 1n], 5n), "2", false);
check("getSized([12n, 3n, 2n, 1n], 13n)", () => M.getSized([12n, 3n, 2n, 1n], 13n), "2", false);
check("getSized([12n, 3n, 2n, 1n], 13n) twice", () => ((a0, a1) => (M.getSized(a0, a1), M.getSized(a0, a1)))([12n, 3n, 2n, 1n], 13n), "2", false);
check("getSizedUnproved([], 0n)", () => M.getSizedUnproved([], 0n), "2", false);
check("getSizedUnproved([], 0n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([], 0n), "2", false);
check("getSizedUnproved([], 1n)", () => M.getSizedUnproved([], 1n), "2", false);
check("getSizedUnproved([], 1n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([], 1n), "2", false);
check("getSizedUnproved([-7n], 0n)", () => M.getSizedUnproved([-7n], 0n), "2", false);
check("getSizedUnproved([-7n], 0n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7n], 0n), "2", false);
check("getSizedUnproved([], 2n)", () => M.getSizedUnproved([], 2n), "2", false);
check("getSizedUnproved([], 2n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([], 2n), "2", false);
check("getSizedUnproved([-7n], 1n)", () => M.getSizedUnproved([-7n], 1n), "2", false);
check("getSizedUnproved([-7n], 1n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7n], 1n), "2", false);
check("getSizedUnproved([-7n, -1n, 0n], 0n)", () => M.getSizedUnproved([-7n, -1n, 0n], 0n), "2", false);
check("getSizedUnproved([-7n, -1n, 0n], 0n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7n, -1n, 0n], 0n), "2", false);
check("getSizedUnproved([], 5n)", () => M.getSizedUnproved([], 5n), "2", false);
check("getSizedUnproved([], 5n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([], 5n), "2", false);
check("getSizedUnproved([-7n], 2n)", () => M.getSizedUnproved([-7n], 2n), "2", false);
check("getSizedUnproved([-7n], 2n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7n], 2n), "2", false);
check("getSizedUnproved([-7n, -1n, 0n], 1n)", () => M.getSizedUnproved([-7n, -1n, 0n], 1n), "2", false);
check("getSizedUnproved([-7n, -1n, 0n], 1n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7n, -1n, 0n], 1n), "2", false);
check("getSizedUnproved([12n, 3n, 2n, 1n], 0n)", () => M.getSizedUnproved([12n, 3n, 2n, 1n], 0n), "2", false);
check("getSizedUnproved([12n, 3n, 2n, 1n], 0n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([12n, 3n, 2n, 1n], 0n), "2", false);
check("getSizedUnproved([], 13n)", () => M.getSizedUnproved([], 13n), "2", false);
check("getSizedUnproved([], 13n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([], 13n), "2", false);
check("getSizedUnproved([-7n], 5n)", () => M.getSizedUnproved([-7n], 5n), "2", false);
check("getSizedUnproved([-7n], 5n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7n], 5n), "2", false);
check("getSizedUnproved([-7n, -1n, 0n], 2n)", () => M.getSizedUnproved([-7n, -1n, 0n], 2n), "2", false);
check("getSizedUnproved([-7n, -1n, 0n], 2n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7n, -1n, 0n], 2n), "2", false);
check("getSizedUnproved([12n, 3n, 2n, 1n], 1n)", () => M.getSizedUnproved([12n, 3n, 2n, 1n], 1n), "2", false);
check("getSizedUnproved([12n, 3n, 2n, 1n], 1n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([12n, 3n, 2n, 1n], 1n), "2", false);
check("getSizedUnproved([-7n], 13n)", () => M.getSizedUnproved([-7n], 13n), "2", false);
check("getSizedUnproved([-7n], 13n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7n], 13n), "2", false);
check("getSizedUnproved([-7n, -1n, 0n], 5n)", () => M.getSizedUnproved([-7n, -1n, 0n], 5n), "2", false);
check("getSizedUnproved([-7n, -1n, 0n], 5n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7n, -1n, 0n], 5n), "2", false);
check("getSizedUnproved([12n, 3n, 2n, 1n], 2n)", () => M.getSizedUnproved([12n, 3n, 2n, 1n], 2n), "2", false);
check("getSizedUnproved([12n, 3n, 2n, 1n], 2n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([12n, 3n, 2n, 1n], 2n), "2", false);
check("getSizedUnproved([-7n, -1n, 0n], 13n)", () => M.getSizedUnproved([-7n, -1n, 0n], 13n), "2", false);
check("getSizedUnproved([-7n, -1n, 0n], 13n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([-7n, -1n, 0n], 13n), "2", false);
check("getSizedUnproved([12n, 3n, 2n, 1n], 5n)", () => M.getSizedUnproved([12n, 3n, 2n, 1n], 5n), "2", false);
check("getSizedUnproved([12n, 3n, 2n, 1n], 5n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([12n, 3n, 2n, 1n], 5n), "2", false);
check("getSizedUnproved([12n, 3n, 2n, 1n], 13n)", () => M.getSizedUnproved([12n, 3n, 2n, 1n], 13n), "2", false);
check("getSizedUnproved([12n, 3n, 2n, 1n], 13n) twice", () => ((a0, a1) => (M.getSizedUnproved(a0, a1), M.getSizedUnproved(a0, a1)))([12n, 3n, 2n, 1n], 13n), "2", false);

console.log(`ArrayIndexBounds-faithful.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
