// JavaScript of Tests/SnapshotsMy/ArrayAppend.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic
// not translated:
//   test1: LeanScript: the call List.forIn'.loop xss (fun a x => (fun xs __s => have acc := __s; have acc := acc ++ xs; pure (ForInStep.yield acc)) a) xss acc ⋯ is not a call of an extern: `List.forIn'.loop` is not the Lean function of an entry of the catalogue of externs (`LeanInitPureExtern`), and its definition cannot be unfolded
//   test3: Application type mismatch: The argument LeanScript.UVar.head ⋯ has type LeanScript.UVar ({ ty := ?m.359, use := ?m.360, lv := ?m.361 } :: ?m.362) ?m.359 ?m.361 but is expected to have type LeanScript.UVar [{ ty := LeanScript.Ty.prim ?m.283, use := LeanScript.Usage1ω.many.toUsage01ω, lv := 1 }, { ty := (LeanScript.Ty.prim LeanScript.LeanPrimTy.nat).array, use := LeanScript.Usage01ω.many, lv := 0 + 1 }] (LeanScript.Ty.prim LeanScript.LeanPrimTy.nat).array ?m.351 in the application LeanScript.Neu.var (LeanScript.UVar.head ⋯)

import { uint53__lean_nat_mul } from "../../runtime.js";

/**
 * `test2`
 * @param {Array<uint53(number)>} a
 * @param {Array<uint53(number)>} b
 * @returns {Array<uint53(number)>}
 */
export const test2 = (a, b) => [...a, ...b];

/**
 * `test4`
 * @param {Array<uint53(number)>} b
 * @returns {Array<uint53(number)>}
 */
export const test4 = (b) => [1, 2, ...b];

/**
 * `test5`
 * @param {uint53(number)} n
 * @returns {Array<uint53(number)>}
 */
export const test5 = (n) => {
  let acc$1 = { tag: 1, _1: [] };
  for (let i$2 = 0; i$2 < n; i$2++) {
    if (acc$1.tag === 0) {
      const { _1: f$3 } = acc$1;
      acc$1 = { tag: 0, _1: f$3 };
    } else {
      const { _1: f$4 } = acc$1;
      const x$5 = [...f$4, i$2, uint53__lean_nat_mul(i$2, i$2)];
      acc$1 = { tag: 1, _1: x$5 };
    }
  }
  if (acc$1.tag === 0) {
    const { _1: f$6 } = acc$1;
    return f$6;
  } else {
    const { _1: f$7 } = acc$1;
    return f$7;
  }
};
