// JavaScript of Tests/SnapshotsMy/ArrayInPlace.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   test2: LeanScript: the call List.forIn'.loop xs (fun a x => (fun x __s => have a := __s; have a := a.set! (x % 8) (a[x % 8]! + 1); pure (ForInStep.yield a)) a) xs a ⋯ is not a call of an extern: `List.forIn'.loop` is not the Lean function of an entry of the catalogue of externs (`LeanInitPureExtern`), and its definition cannot be unfolded

import {
  array__lean_array_push_mutable,
  uint53__lean_nat_mul,
  uint53__lean_array_set_mutable,
  uint53__lean_mk_array,
  uint53__lean_nat_div,
  uint53__lean_array_swap_mutable,
  uint53__lean_nat_sub,
  array__lean_array_pop_mutable,
} from "../../runtime.js";

/**
 * `test1`
 * @param {uint53(number)} n
 * @returns {Array<uint53(number)>}
 */
export const test1 = (n) => {
  const x$1 = [];
  let acc$2 = x$1;
  for (let i$3 = 0; i$3 < n; i$3++) {
    acc$2 = array__lean_array_push_mutable(
      acc$2,
      uint53__lean_nat_mul(i$3, i$3),
    );
  }
  return acc$2;
};

/**
 * `test3`
 * @param {Array<uint53(number)>} a0
 * @returns {Array<uint53(number)>}
 */
export const test3 = (a0) => {
  let acc$1 = [...a0];
  const n$2 = a0.length;
  for (let i$3 = 0; i$3 < n$2; i$3++) {
    acc$1 = uint53__lean_array_set_mutable(
      acc$1,
      i$3,
      uint53__lean_nat_mul(acc$1[i$3] ?? 0, 2),
    );
  }
  return acc$1;
};

/**
 * `test3`
 * owns `a0`: its caller gives it up, and it may update it in place (1 update(s) in place, 0 copies of arrays)
 * @param {Array<uint53(number)>} a0
 * @returns {Array<uint53(number)>}
 */
export const test3$$mut_0 = (a0) => {
  let acc$1 = a0;
  const n$2 = a0.length;
  for (let i$3 = 0; i$3 < n$2; i$3++) {
    acc$1 = uint53__lean_array_set_mutable(
      acc$1,
      i$3,
      uint53__lean_nat_mul(acc$1[i$3] ?? 0, 2),
    );
  }
  return acc$1;
};

/**
 * `test4`
 * @param {uint53(number)} n
 * @returns {{ _1: Array<uint53(number)>, _2: Array<uint53(number)> }}
 */
export const test4 = (n) => {
  const x$1 = uint53__lean_mk_array(3, n);
  return { _1: x$1, _2: uint53__lean_array_set_mutable([...x$1], 0, 7) };
};

/**
 * `test5`
 * @param {uint53(number)} n
 * @returns {Array<uint53(number)>}
 */
export const test5 = (n) => {
  const x$1 = [];
  let acc$2 = x$1;
  for (let i$3 = 0; i$3 < n; i$3++) {
    acc$2 = array__lean_array_push_mutable(acc$2, i$3);
  }
  let acc$4 = acc$2;
  const n$5 = uint53__lean_nat_div(n, 2);
  for (let i$6 = 0; i$6 < n$5; i$6++) {
    acc$4 = uint53__lean_array_swap_mutable(
      acc$4,
      i$6,
      uint53__lean_nat_sub(uint53__lean_nat_sub(n, i$6), 1),
    );
  }
  return array__lean_array_pop_mutable(acc$4);
};

/**
 * `test6`
 * @param {uint53(number)} n
 * @returns {Array<uint53(number)>}
 */
export const test6 = (n) => {
  let p$1 = [];
  let j$2 = n;
  while (true) {
    if (j$2 === 0) {
      return p$1;
    }
    j$2--;
    p$1 = array__lean_array_push_mutable(p$1, j$2);
  }
};
