// Differential checks of AssignSteps-pbo.js against Lean, generated by leanscript --check
import * as M from "./AssignSteps-pbo.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  return String(v);
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("test1(0, 0, 0)", () => M.test1(0, 0, 0), "0", false);
check("test1(0, 1, 1)", () => M.test1(0, 1, 1), "1", false);
check("test1(1, 1, 0)", () => M.test1(1, 1, 0), "1", false);
check("test1(0, 2, 2)", () => M.test1(0, 2, 2), "2", false);
check("test1(1, 2, 1)", () => M.test1(1, 2, 1), "1", false);
check("test1(2, 2, 0)", () => M.test1(2, 2, 0), "2", false);
check("test1(0, 5, 5)", () => M.test1(0, 5, 5), "5", false);
check("test1(1, 5, 2)", () => M.test1(1, 5, 2), "2", false);
check("test1(2, 0, 13)", () => M.test1(2, 0, 13), "13", false);
check("test1(2, 5, 1)", () => M.test1(2, 5, 1), "1", false);
check("test1(5, 0, 5)", () => M.test1(5, 0, 5), "5", false);
check("test1(5, 5, 0)", () => M.test1(5, 5, 0), "5", false);
check("test1(13, 0, 2)", () => M.test1(13, 0, 2), "2", false);
check("test1(0, 13, 13)", () => M.test1(0, 13, 13), "13", false);
check("test1(1, 13, 5)", () => M.test1(1, 13, 5), "5", false);
check("test1(2, 13, 2)", () => M.test1(2, 13, 2), "1", false);
check("test1(5, 1, 13)", () => M.test1(5, 1, 13), "1", false);
check("test1(5, 13, 1)", () => M.test1(5, 13, 1), "1", false);
check("test1(13, 1, 5)", () => M.test1(13, 1, 5), "1", false);
check("test1(13, 13, 0)", () => M.test1(13, 13, 0), "13", false);
check("test1(13, 2, 13)", () => M.test1(13, 2, 13), "1", false);
check("test2(0, 0, 0, 0)", () => M.test2(0, 0, 0, 0), "0", false);
check("test2(0, 1, 0, 2)", () => M.test2(0, 1, 0, 2), "102", false);
check("test2(1, 0, 2, 0)", () => M.test2(1, 0, 2, 0), "201", false);
check("test2(0, 5, 1, 1)", () => M.test2(0, 5, 1, 1), "511", false);
check("test2(5, 1, 1, 0)", () => M.test2(5, 1, 1, 0), "133", false);
check("test2(0, 2, 0, 13)", () => M.test2(0, 2, 0, 13), "213", false);
check("test2(1, 1, 2, 2)", () => M.test2(1, 1, 2, 2), "222", false);
check("test2(2, 0, 13, 0)", () => M.test2(2, 0, 13, 0), "24", false);
check("test2(5, 0, 0, 5)", () => M.test2(5, 0, 0, 5), "622", false);
check("test2(2, 13, 0, 1)", () => M.test2(2, 13, 0, 1), "241", false);
check("test2(0, 13, 1, 5)", () => M.test2(0, 13, 1, 5), "1315", false);
check("test2(1, 5, 5, 1)", () => M.test2(1, 5, 5, 1), "516", false);
check("test2(5, 2, 1, 2)", () => M.test2(5, 2, 1, 2), "343", false);
check("test2(13, 1, 5, 0)", () => M.test2(13, 1, 5, 0), "946", false);
check("test2(1, 2, 2, 13)", () => M.test2(1, 2, 2, 13), "333", false);
check("test2(2, 1, 13, 2)", () => M.test2(2, 1, 13, 2), "234", false);
check("test2(13, 0, 2, 5)", () => M.test2(13, 0, 2, 5), "695", false);
check("test2(5, 13, 2, 1)", () => M.test2(5, 13, 2, 1), "354", false);
check("test2(1, 13, 5, 5)", () => M.test2(1, 13, 5, 5), "564", false);
check("test2(5, 5, 1, 13)", () => M.test2(5, 5, 1, 13), "1473", false);
check("test2(13, 2, 5, 2)", () => M.test2(13, 2, 5, 2), "967", false);
check("test2(2, 2, 13, 13)", () => M.test2(2, 2, 13, 13), "1344", false);
check("test2(13, 13, 13, 1)", () => M.test2(13, 13, 13, 1), "1768", false);
check("test2(13, 5, 5, 13)", () => M.test2(13, 5, 5, 13), "1080", false);
check("test4(0, 0, 0)", () => M.test4(0, 0, 0), "0", false);
check("test4(0, 1, 1)", () => M.test4(0, 1, 1), "2", false);
check("test4(1, 1, 0)", () => M.test4(1, 1, 0), "4", false);
check("test4(0, 2, 2)", () => M.test4(0, 2, 2), "4", false);
check("test4(1, 2, 1)", () => M.test4(1, 2, 1), "6", false);
check("test4(2, 2, 0)", () => M.test4(2, 2, 0), "8", false);
check("test4(0, 5, 5)", () => M.test4(0, 5, 5), "10", false);
check("test4(1, 5, 2)", () => M.test4(1, 5, 2), "10", false);
check("test4(2, 0, 13)", () => M.test4(2, 0, 13), "19", false);
check("test4(2, 5, 1)", () => M.test4(2, 5, 1), "12", false);
check("test4(5, 0, 5)", () => M.test4(5, 0, 5), "20", false);
check("test4(5, 5, 0)", () => M.test4(5, 5, 0), "20", false);
check("test4(13, 0, 2)", () => M.test4(13, 0, 2), "41", false);
check("test4(0, 13, 13)", () => M.test4(0, 13, 13), "26", false);
check("test4(1, 13, 5)", () => M.test4(1, 13, 5), "21", false);
check("test4(2, 13, 2)", () => M.test4(2, 13, 2), "21", false);
check("test4(5, 1, 13)", () => M.test4(5, 1, 13), "29", false);
check("test4(5, 13, 1)", () => M.test4(5, 13, 1), "29", false);
check("test4(13, 1, 5)", () => M.test4(13, 1, 5), "45", false);
check("test4(13, 13, 0)", () => M.test4(13, 13, 0), "52", false);
check("test4(13, 2, 13)", () => M.test4(13, 2, 13), "54", false);

console.log(`AssignSteps-pbo.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
