// JavaScript of Tests/SnapshotsMy/AssignSteps.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic
// not translated:
//   test3: LeanScript: the call b.gcd (a + 7) is not a call of an extern: `Nat.gcd` is not the Lean function of an entry of the catalogue of externs (`LeanInitPureExtern`), and its definition cannot be unfolded

import {
  uint53__lean_nat_mod__Nat_mod,
  uint53__lean_nat_add,
  uint53__lean_nat_mul,
} from "../../runtime.js";

/**
 * `test1`
 * @param {uint53(number)} fuel
 * @param {uint53(number)} a
 * @param {uint53(number)} b
 * @returns {uint53(number)}
 */
export const test1 = (fuel, a, b) => {
  let r$1 = undefined;
  let done$2 = false;
  let x$3 = a;
  let x$4 = b;
  for (let j$5 = 0; j$5 < fuel; j$5++) {
    if (!done$2) {
      const x$6 = x$3;
      if (x$4 === 0) {
        r$1 = x$6;
        done$2 = true;
      } else {
        x$3 = x$4;
        x$4 = uint53__lean_nat_mod__Nat_mod(x$6, x$4);
      }
    }
  }
  return done$2 ? r$1 : x$3;
};

/**
 * `test2`
 * @param {uint53(number)} fuel
 * @param {uint53(number)} a
 * @param {uint53(number)} b
 * @param {uint53(number)} c
 * @returns {uint53(number)}
 */
export const test2 = (fuel, a, b, c) => {
  let x$1 = a;
  let x$2 = b;
  let x$3 = c;
  for (let j$4 = 0; j$4 < fuel; j$4++) {
    const x$5 = x$1;
    x$1 = x$2;
    x$2 = x$3;
    x$3 = uint53__lean_nat_add(x$5, 1);
  }
  return uint53__lean_nat_add(
    uint53__lean_nat_add(
      uint53__lean_nat_mul(x$1, 100),
      uint53__lean_nat_mul(x$2, 10),
    ),
    x$3,
  );
};

/**
 * `test4`
 * @param {uint53(number)} fuel
 * @param {uint53(number)} a
 * @param {uint53(number)} b
 * @returns {uint53(number)}
 */
export const test4 = (fuel, a, b) => {
  let x$1 = a;
  let x$2 = b;
  for (let j$3 = 0; j$3 < fuel; j$3++) {
    x$1 = uint53__lean_nat_add(x$1, 1);
    x$2 = uint53__lean_nat_add(x$2, 2);
  }
  return uint53__lean_nat_add(x$1, x$2);
};
