// JavaScript of Tests/SnapshotsMy/CaseGuardedSweep.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

import {
  int53__lean_int_add,
  uint53__lean_nat_add,
  int53__lean_int_emod,
  int53__lean_int_mul,
} from "../../runtime.js";

/**
 * `test1`
 * @param {int53(number)} n
 * @returns {string}
 */
export const test1 = (n) => {
  if (n < 1) {
    return "n: " + n;
  }
  return n > 1 && n < 100 ? "1 < x < 100: " + n : "catch";
};

/**
 * `test4`
 * @param {{ _1: int53(number), _2: int53(number), _3: int53(number) }} a
 * @param {{ _1: int53(number), _2: int53(number), _3: int53(number) }} a1
 * @returns {int53(number)}
 */
export const test4 = (a, a1) => {
  const { _1: f$1, _3: f$2 } = a;
  if (f$1 === 1) {
    const { _1: f$3 } = a1;
    if (f$3 === 1) {
      return 1;
    }
    if (f$3 === 2) {
      return 2;
    }
    if (f$3 === 3) {
      return 3;
    }
    if (f$3 === 4) {
      return 4;
    }
    return f$3 === 5
      ? 5
      : int53__lean_int_add(int53__lean_int_add(f$2, a1._3), 11);
  }
  if (f$1 === 2) {
    const { _1: f$4, _2: f$5 } = a1;
    if (f$4 === 2) {
      return 2;
    }
    if (f$4 === 3) {
      return 3;
    }
    if (f$4 === 1) {
      return 6;
    }
    if (f$4 === 4) {
      if (f$2 === f$5) {
        return 7;
      }
      return f$2 < f$5 ? 8 : 9;
    }
    return int53__lean_int_add(int53__lean_int_add(f$2, a1._3), 11);
  }
  const { _1: f$6, _2: f$7, _3: f$8 } = a1;
  if (f$6 === 2) {
    return 2;
  }
  if (f$6 === 3) {
    return 3;
  }
  if (f$6 === 4) {
    if (f$2 === f$7) {
      return 7;
    }
    return f$2 < f$7 ? 8 : 9;
  }
  if (f$6 === 1 && f$8 === 10) {
    return a._2 === 2 ? 10 : int53__lean_int_add(f$2, 21);
  }
  return int53__lean_int_add(int53__lean_int_add(f$2, f$8), 11);
};

/**
 * `sweep1`
 * @param {int53(number)} lo
 * @returns {string}
 */
export const sweep1 = (lo) => {
  let acc$1 = "";
  for (let i$2 = 0; i$2 < 110; i$2++) {
    const x$3 = int53__lean_int_add(lo, i$2);
    acc$1 =
      acc$1 +
      (x$3 < 1
        ? "n: " + x$3
        : x$3 > 1 && x$3 < 100
          ? "1 < x < 100: " + x$3
          : "catch") +
      ";";
  }
  return acc$1;
};

/**
 * `sweep4`
 * @param {int53(number)} lo
 * @returns {int53(number)}
 */
export const sweep4 = (lo) => {
  let acc$1 = 0;
  for (let i$2 = 0; i$2 < 4; i$2++) {
    let acc$3 = acc$1;
    for (let i$4 = 0; i$4 < 3; i$4++) {
      let acc$5 = acc$3;
      for (let i$6 = 0; i$6 < 7; i$6++) {
        let acc$7 = acc$5;
        for (let i$8 = 0; i$8 < 2; i$8++) {
          let acc$9 = acc$7;
          for (let i$10 = 0; i$10 < 3; i$10++) {
            let acc$11 = acc$9;
            for (let i$12 = 0; i$12 < 3; i$12++) {
              const x$13 = test4(
                {
                  _1: int53__lean_int_add(lo, i$2),
                  _2: int53__lean_int_add(lo, i$4),
                  _3: int53__lean_int_add(lo, i$10),
                },
                {
                  _1: int53__lean_int_add(lo, i$6),
                  _2: int53__lean_int_add(lo, i$12),
                  _3: int53__lean_int_add(lo, uint53__lean_nat_add(i$8, 9)),
                },
              );
              acc$11 = int53__lean_int_add(
                int53__lean_int_emod(
                  int53__lean_int_mul(acc$11, 31),
                  1000000007,
                ),
                x$13,
              );
            }
            acc$9 = acc$11;
          }
          acc$7 = acc$9;
        }
        acc$5 = acc$7;
      }
      acc$3 = acc$5;
    }
    acc$1 = acc$3;
  }
  return acc$1;
};
