// Differential checks of FloatUnit-pbo.js against Lean, generated by leanscript --check
import * as M from "./FloatUnit-pbo.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("mulOne(0)", () => M.mulOne(0), "0", true);
check("mulOne(0.5)", () => M.mulOne(0.5), "4602678819172646912", true);
check("mulOne(1)", () => M.mulOne(1), "4607182418800017408", true);
check("mulOne(2)", () => M.mulOne(2), "4611686018427387904", true);
check("mulOne(3)", () => M.mulOne(3), "4613937818241073152", true);
check("mulOne(2.25)", () => M.mulOne(2.25), "4612248968380809216", true);
check("mulOne(30)", () => M.mulOne(30), "4629137466983448576", true);
check("mulOne(-1.5)", () => M.mulOne(-1.5), "13832806255468478464", true);
check("oneMul(0)", () => M.oneMul(0), "0", true);
check("oneMul(0.5)", () => M.oneMul(0.5), "4602678819172646912", true);
check("oneMul(1)", () => M.oneMul(1), "4607182418800017408", true);
check("oneMul(2)", () => M.oneMul(2), "4611686018427387904", true);
check("oneMul(3)", () => M.oneMul(3), "4613937818241073152", true);
check("oneMul(2.25)", () => M.oneMul(2.25), "4612248968380809216", true);
check("oneMul(30)", () => M.oneMul(30), "4629137466983448576", true);
check("oneMul(-1.5)", () => M.oneMul(-1.5), "13832806255468478464", true);
check("divOne(0)", () => M.divOne(0), "0", true);
check("divOne(0.5)", () => M.divOne(0.5), "4602678819172646912", true);
check("divOne(1)", () => M.divOne(1), "4607182418800017408", true);
check("divOne(2)", () => M.divOne(2), "4611686018427387904", true);
check("divOne(3)", () => M.divOne(3), "4613937818241073152", true);
check("divOne(2.25)", () => M.divOne(2.25), "4612248968380809216", true);
check("divOne(30)", () => M.divOne(30), "4629137466983448576", true);
check("divOne(-1.5)", () => M.divOne(-1.5), "13832806255468478464", true);
check("subZero(0)", () => M.subZero(0), "0", true);
check("subZero(0.5)", () => M.subZero(0.5), "4602678819172646912", true);
check("subZero(1)", () => M.subZero(1), "4607182418800017408", true);
check("subZero(2)", () => M.subZero(2), "4611686018427387904", true);
check("subZero(3)", () => M.subZero(3), "4613937818241073152", true);
check("subZero(2.25)", () => M.subZero(2.25), "4612248968380809216", true);
check("subZero(30)", () => M.subZero(30), "4629137466983448576", true);
check("subZero(-1.5)", () => M.subZero(-1.5), "13832806255468478464", true);
check("addZero(0)", () => M.addZero(0), "0", true);
check("addZero(0.5)", () => M.addZero(0.5), "4602678819172646912", true);
check("addZero(1)", () => M.addZero(1), "4607182418800017408", true);
check("addZero(2)", () => M.addZero(2), "4611686018427387904", true);
check("addZero(3)", () => M.addZero(3), "4613937818241073152", true);
check("addZero(2.25)", () => M.addZero(2.25), "4612248968380809216", true);
check("addZero(30)", () => M.addZero(30), "4629137466983448576", true);
check("addZero(-1.5)", () => M.addZero(-1.5), "13832806255468478464", true);
check("zeroAdd(0)", () => M.zeroAdd(0), "0", true);
check("zeroAdd(0.5)", () => M.zeroAdd(0.5), "4602678819172646912", true);
check("zeroAdd(1)", () => M.zeroAdd(1), "4607182418800017408", true);
check("zeroAdd(2)", () => M.zeroAdd(2), "4611686018427387904", true);
check("zeroAdd(3)", () => M.zeroAdd(3), "4613937818241073152", true);
check("zeroAdd(2.25)", () => M.zeroAdd(2.25), "4612248968380809216", true);
check("zeroAdd(30)", () => M.zeroAdd(30), "4629137466983448576", true);
check("zeroAdd(-1.5)", () => M.zeroAdd(-1.5), "13832806255468478464", true);
check("mulTwo(0)", () => M.mulTwo(0), "0", true);
check("mulTwo(0.5)", () => M.mulTwo(0.5), "4607182418800017408", true);
check("mulTwo(1)", () => M.mulTwo(1), "4611686018427387904", true);
check("mulTwo(2)", () => M.mulTwo(2), "4616189618054758400", true);
check("mulTwo(3)", () => M.mulTwo(3), "4618441417868443648", true);
check("mulTwo(2.25)", () => M.mulTwo(2.25), "4616752568008179712", true);
check("mulTwo(30)", () => M.mulTwo(30), "4633641066610819072", true);
check("mulTwo(-1.5)", () => M.mulTwo(-1.5), "13837309855095848960", true);
check("subZeroLeft(0)", () => M.subZeroLeft(0), "0", true);
check("subZeroLeft(0.5)", () => M.subZeroLeft(0.5), "13826050856027422720", true);
check("subZeroLeft(1)", () => M.subZeroLeft(1), "13830554455654793216", true);
check("subZeroLeft(2)", () => M.subZeroLeft(2), "13835058055282163712", true);
check("subZeroLeft(3)", () => M.subZeroLeft(3), "13837309855095848960", true);
check("subZeroLeft(2.25)", () => M.subZeroLeft(2.25), "13835621005235585024", true);
check("subZeroLeft(30)", () => M.subZeroLeft(30), "13852509503838224384", true);
check("subZeroLeft(-1.5)", () => M.subZeroLeft(-1.5), "4609434218613702656", true);
check("addNegZero(0)", () => M.addNegZero(0), "0", true);
check("addNegZero(0.5)", () => M.addNegZero(0.5), "4602678819172646912", true);
check("addNegZero(1)", () => M.addNegZero(1), "4607182418800017408", true);
check("addNegZero(2)", () => M.addNegZero(2), "4611686018427387904", true);
check("addNegZero(3)", () => M.addNegZero(3), "4613937818241073152", true);
check("addNegZero(2.25)", () => M.addNegZero(2.25), "4612248968380809216", true);
check("addNegZero(30)", () => M.addNegZero(30), "4629137466983448576", true);
check("addNegZero(-1.5)", () => M.addNegZero(-1.5), "13832806255468478464", true);
check("lits(0)", () => M.lits(0), "4921056587992461136", true);
check("lits(0.5)", () => M.lits(0.5), "4921056587992461136", true);
check("lits(1)", () => M.lits(1), "4921056587992461136", true);
check("lits(2)", () => M.lits(2), "4921056587992461136", true);
check("lits(3)", () => M.lits(3), "4921056587992461136", true);
check("lits(2.25)", () => M.lits(2.25), "4921056587992461136", true);
check("lits(30)", () => M.lits(30), "4921056587992461136", true);
check("lits(-1.5)", () => M.lits(-1.5), "4921056587992461136", true);
check("closed(0)", () => M.closed(0), "4617315517961601024", true);
check("closed(0.5)", () => M.closed(0.5), "4617878467915022336", true);
check("closed(1)", () => M.closed(1), "4618441417868443648", true);
check("closed(2)", () => M.closed(2), "4619567317775286272", true);
check("closed(3)", () => M.closed(3), "4620693217682128896", true);
check("closed(2.25)", () => M.closed(2.25), "4619848792751996928", true);
check("closed(30)", () => M.closed(30), "4630122629401935872", true);
check("closed(-1.5)", () => M.closed(-1.5), "4615063718147915776", true);

console.log(`FloatUnit-pbo.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
