// JavaScript of Tests/SnapshotsMy/Html.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   instReprHtml.repr: a `partial` definition

import { array__lean_array_push_mutable } from "../../runtime.js";

/**
 * `test`
 * @param {string} user
 * @returns {D0}
 */
export const test = (user) => {
  const x$1 = array__lean_array_push_mutable([], {
    tag: 1,
    _1: "Posts for " + user,
  });
  return {
    tag: 0,
    _1: "section",
    _2: array__lean_array_push_mutable(
      array__lean_array_push_mutable([], { tag: 0, _1: "h1", _2: x$1 }),
      {
        tag: 0,
        _1: "article",
        _2: [
          { tag: 0, _1: "h2", _2: [{ tag: 1, _1: "The first post" }] },
          {
            tag: 0,
            _1: "p",
            _2: [
              { tag: 1, _1: "This is the first post." },
              { tag: 1, _1: "Not much else to say." },
            ],
          },
        ],
      },
    ),
  };
};
