// JavaScript of Tests/SnapshotsMy/InlineClosures.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

import {
  uint53__lean_nat_add,
  uint53__lean_nat_mul,
  array__lean_array_push_mutable,
} from "../../runtime.js";

/**
 * `addAfter`
 * @param {uint53(number)} fuel
 * @param {uint53(number)} a
 * @param {uint53(number)} b
 * @returns {uint53(number)}
 */
export const addAfter = (fuel, a, b) => {
  let p$1 = a;
  let p$2 = b;
  let j$3 = fuel;
  while (true) {
    if (j$3 === 0) {
      return uint53__lean_nat_add(p$1, p$2);
    }
    j$3--;
    const x$4 = uint53__lean_nat_add(p$1, 2);
    p$1 = x$4;
    p$2 = uint53__lean_nat_add(p$2, 3);
  }
};

/**
 * `sumShifted`
 * @param {uint53(number)} k
 * @returns {uint53(number)}
 */
export const sumShifted = (k) => {
  const k$2 = (x$1) => uint53__lean_nat_mul(x$1, k);
  const x$3 = k$2(1);
  const x$4 = k$2(2);
  const x$5 = k$2(3);
  return uint53__lean_nat_add(uint53__lean_nat_add(x$3, x$4), x$5);
};

/**
 * `downFrom`
 * @param {uint53(number)} n
 * @returns {Array<uint53(number)>}
 */
export const downFrom = (n) => {
  let p$1 = [];
  let j$2 = n;
  while (true) {
    if (j$2 === 0) {
      return p$1;
    }
    j$2--;
    p$1 = array__lean_array_push_mutable(p$1, j$2);
  }
};

/**
 * `ordered`
 * @param {uint53(number)} a
 * @param {uint53(number)} b
 * @returns {{ _1: uint53(number), _2: uint53(number) }}
 */
export const ordered = (a, b) => {
  const k$4 = (x$1) => {
    const { _1: f$2, _2: f$3 } = x$1;
    return f$2 <= f$3 ? x$1 : { _1: f$3, _2: f$2 };
  };
  return k$4({ _1: a, _2: b });
};

/**
 * `keep`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const keep = (x) => (x === 7 ? 7 : x);

/**
 * `around`
 * @param {List<string>} xs
 * @returns {List<string>}
 */
export const around = (xs) => ["<", ...xs, ",", ...xs, ">"];
