// JavaScript of Tests/SnapshotsMy/InlineDemo.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic

import {
  $lean_nat_mul,
  $lean_nat_add,
} from "../../runtime/lean_runtime_nat_num.mjs";

const $k1 = (x$2) => $lean_nat_mul(x$2, 2);
const $k2 = (x$5) => $lean_nat_mul(x$5, 2);
const $k3 = (x$2) => $lean_nat_mul(x$2, 3);
const $k4 = (x$5) => $lean_nat_mul(x$5, 3);

/**
 * `foo`
 * @param {uint53(number)} a
 * @param {uint53(number)} b
 * @returns {uint53(number)}
 */
export const foo = (a, b) => $lean_nat_add($lean_nat_mul(a, b), a);

/**
 * `bar`
 * @returns {uint53(number)}
 */
export const bar = () => 3;

/**
 * `useScale`
 * @param {uint53(number)} n
 * @returns {uint53(number)}
 */
export const useScale = (n) => {
  const k$1 = $k1;
  const x$3 = k$1(n);
  const k$4 = $k2;
  const x$6 = k$4($lean_nat_add(n, 1));
  return $lean_nat_add(x$3, x$6);
};

/**
 * `triple`
 * @param {uint53(number)} a
 * @returns {uint53(number)}
 */
export const triple = (a) => $lean_nat_mul(a, 3);

/**
 * `useTriple`
 * @param {uint53(number)} n
 * @returns {uint53(number)}
 */
export const useTriple = (n) => {
  const k$1 = $k3;
  const x$3 = k$1(n);
  const k$4 = $k4;
  const x$6 = k$4($lean_nat_add(n, 1));
  return $lean_nat_add(x$3, x$6);
};
