// JavaScript of Tests/SnapshotsMy/KnownCtorCondConst.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `twoAppends`
 * @param {(string, string) => string} f
 * @param {int53(number)} x
 * @returns {string}
 */
export const twoAppends = (f, x) => {
  const x$1 = 42 < x;
  return f(
    x$1 ? "Hello, World" : "Default, World",
    x$1 ? "Hello, Universe" : "Default, Universe",
  );
};

/**
 * `intOps`
 * @param {(int53(number), int53(number)) => int53(number)} f
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const intOps = (f, x) => {
  const x$1 = 42 < x;
  return f(x$1 ? 11 : 21, x$1 ? 30 : 60);
};

/**
 * `threeUses`
 * @param {int53(number)} x
 * @returns {Array<string>}
 */
export const threeUses = (x) =>
  0 < x ? ["pos!", "<pos", "yes"] : ["neg!", "<neg", "no"];

/**
 * `usesInArms`
 * @param {(string) => string} f
 * @param {int53(number)} x
 * @param {int53(number)} y
 * @returns {string}
 */
export const usesInArms = (f, x, y) => {
  const x$1 = 0 < x;
  if (0 < y) {
    return f(x$1 ? "a1" : "b1");
  }
  return f(x$1 ? "a2" : "b2");
};

/**
 * `alsoDirect`
 * @param {(string, string) => string} f
 * @param {int53(number)} x
 * @returns {string}
 */
export const alsoDirect = (f, x) => {
  const x$1 = 0 < x ? "a" : "b";
  return f(x$1, x$1 + "!");
};

/**
 * `natOps`
 * @param {(uint53(number), uint53(number)) => uint53(number)} f
 * @param {uint53(number)} x
 * @returns {uint53(number)}
 */
export const natOps = (f, x) => {
  const x$1 = 5 < x;
  return f(x$1 ? 9 : 11, x$1 ? 6 : 8);
};
