// JavaScript of Tests/SnapshotsMy/KnownCtorEnumParse.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

import { int53__lean_int_add } from "../../runtime.js";

/**
 * `instInhabitedColor.default`
 * @type {enum4@0}
 */
export const instInhabitedColor$default = 0;

/**
 * `parseColor`
 * @param {string} a
 * @returns {({ tag: 0 } | { tag: 1, _1: enum4@0 })}
 */
export const parseColor = (a) => {
  if (a === "red") {
    return { tag: 1, _1: 0 };
  }
  if (a === "green") {
    return { tag: 1, _1: 1 };
  }
  if (a === "blue") {
    return { tag: 1, _1: 2 };
  }
  return a === "black" ? { tag: 1, _1: 3 } : { tag: 0 };
};

/**
 * `wildcard`
 * @param {string} a
 * @returns {int53(number)}
 */
export const wildcard = (a) => (a === "red" ? 1 : 0);

/**
 * `sharedArm`
 * @param {string} a
 * @returns {int53(number)}
 */
export const sharedArm = (a) => {
  if (a === "red" || a === "green") {
    return 1;
  }
  return a === "blue" ? 2 : 0;
};

/**
 * `armsCall`
 * @param {(int53(number)) => int53(number)} f
 * @param {string} a
 * @returns {int53(number)}
 */
export const armsCall = (f, a) => {
  if (a === "red") {
    return f(1);
  }
  if (a === "green") {
    return f(2);
  }
  if (a === "blue") {
    return f(3);
  }
  if (a === "black") {
    return f(4);
  }
  return 0;
};

/**
 * `thenMore`
 * @param {(int53(number)) => int53(number)} f
 * @param {string} a
 * @returns {int53(number)}
 */
export const thenMore = (f, a) =>
  f(
    int53__lean_int_add(
      a === "red"
        ? 1
        : a === "green"
          ? 2
          : a === "blue"
            ? 3
            : a === "black"
              ? 4
              : 0,
      10,
    ),
  );

/**
 * `Color.code`
 * @param {enum4@0} a
 * @returns {int53(number)}
 */
export const Color$code = (a) => {
  if (a === 0) {
    return 1;
  }
  if (a === 1) {
    return 2;
  }
  return a === 2 ? 3 : 4;
};

/**
 * `mapGetD`
 * @param {string} a
 * @returns {int53(number)}
 */
export const mapGetD = (a) => {
  if (a === "red") {
    return 1;
  }
  if (a === "green") {
    return 2;
  }
  if (a === "blue") {
    return 3;
  }
  return a === "black" ? 4 : 0;
};

/**
 * `getDEnum`
 * @param {string} a
 * @returns {enum4@0}
 */
export const getDEnum = (a) => {
  if (a === "red") {
    return 0;
  }
  if (a === "green") {
    return 1;
  }
  return a === "blue" ? 2 : 3;
};

/**
 * `isColor`
 * @param {string} a
 * @returns {boolean}
 */
export const isColor = (a) => {
  if (a === "red" || a === "green" || a === "blue") {
    return true;
  }
  return a === "black";
};

/**
 * `two`
 * @param {string} a
 * @param {string} b
 * @returns {int53(number)}
 */
export const two = (a, b) => {
  if (a === "red") {
    if (b === "red") {
      return 1;
    }
    return b === "green" || b === "blue" || b === "black" ? 2 : 0;
  }
  if (a === "green" || a === "blue") {
    return b === "red" || b === "green" || b === "blue" || b === "black"
      ? 2
      : 0;
  }
  return a === "black" &&
    (b === "red" || b === "green" || b === "blue" || b === "black")
    ? 2
    : 0;
};

/**
 * `describe`
 * @param {string} a
 * @returns {string}
 */
export const describe = (a) => {
  if (a === "red") {
    return "warm";
  }
  if (a === "green" || a === "blue") {
    return "cool";
  }
  return a === "black" ? "dark" : a + "?";
};

/**
 * `sumCodes`
 * @param {(uint53(number)) => string} f
 * @param {uint53(number)} n
 * @returns {int53(number)}
 */
export const sumCodes = (f, n) => {
  let acc$1 = 0;
  for (let i$2 = 0; i$2 < n; i$2++) {
    const x$3 = f(i$2);
    if (x$3 === "red") {
      acc$1 = int53__lean_int_add(acc$1, 1);
    } else if (x$3 === "green") {
      acc$1 = int53__lean_int_add(acc$1, 2);
    } else if (x$3 === "blue") {
      acc$1 = int53__lean_int_add(acc$1, 3);
    } else if (x$3 === "black") {
      acc$1 = int53__lean_int_add(acc$1, 4);
    }
  }
  return acc$1;
};

/**
 * `firstBad`
 * @param {(uint53(number)) => string} f
 * @param {uint53(number)} n
 * @returns {uint53(number)}
 */
export const firstBad = (f, n) => {
  let acc$1 = { tag: 1, _1: n };
  j$1: for (let i$2 = 0; i$2 < n; i$2++) {
    const x$3 = f(i$2);
    if (!(
      x$3 === "red" ||
      x$3 === "green" ||
      x$3 === "blue" ||
      x$3 === "black"
    )) {
      acc$1 = { tag: 0, _1: i$2 };
      break j$1;
    }
  }
  return acc$1._1;
};

/**
 * `natSwitch`
 * @param {uint53(number)} n
 * @returns {string}
 */
export const natSwitch = (n) => {
  if (n === 0) {
    return "zero";
  }
  if (n === 1) {
    return "one";
  }
  return n === 2 ? "two" : "many";
};
