// Differential checks of KnownCtorOption-faithful.js against Lean, generated by leanscript --check
import * as M from "./KnownCtorOption-faithful.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
// a recursive union: as `showUnion`, the fields marked in `rec[tag]` (the type itself) printed
// the same way, one level less deep (`…` at depth 0, as `showExpr` cuts it in Lean)
function showTree(v, rec, d) {
  if (d === 0) return "…";
  if (typeof v === "number") return v + "()";
  const r = rec[v.tag] || [];
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++)
    fs.push(r[i - 1] ? showTree(v["_" + i], rec, d - 1) : show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("mapConstArg(\"\")", () => M.mapConstArg(""), "b", false);
check("mapConstArg(\"a\")", () => M.mapConstArg("a"), "b", false);
check("mapConstArg(\"hello world\")", () => M.mapConstArg("hello world"), "b", false);
check("mapConstArg(\"héllo, wörld\")", () => M.mapConstArg("héllo, wörld"), "b", false);
check("mapConstArg(\"abcabc\")", () => M.mapConstArg("abcabc"), "b", false);
check("mapConstArg(\"b\")", () => M.mapConstArg("b"), "b", false);
check("mapFnArg((x) => \"[\" + String(x) + \"]\")", () => M.mapFnArg((x) => "[" + String(x) + "]"), "[c]", false);
check("mapFnArg((x) => \"(\" + String(x) + \")\")", () => M.mapFnArg((x) => "(" + String(x) + ")"), "(c)", false);
check("mapBoth((x) => \"[\" + String(x) + \"]\", \"\")", () => M.mapBoth((x) => "[" + String(x) + "]", ""), "[]", false);
check("mapBoth((x) => \"[\" + String(x) + \"]\", \"a\")", () => M.mapBoth((x) => "[" + String(x) + "]", "a"), "[a]", false);
check("mapBoth((x) => \"(\" + String(x) + \")\", \"\")", () => M.mapBoth((x) => "(" + String(x) + ")", ""), "()", false);
check("mapBoth((x) => \"[\" + String(x) + \"]\", \"hello world\")", () => M.mapBoth((x) => "[" + String(x) + "]", "hello world"), "[hello world]", false);
check("mapBoth((x) => \"(\" + String(x) + \")\", \"a\")", () => M.mapBoth((x) => "(" + String(x) + ")", "a"), "(a)", false);
check("mapBoth((x) => \"[\" + String(x) + \"]\", \"héllo, wörld\")", () => M.mapBoth((x) => "[" + String(x) + "]", "héllo, wörld"), "[héllo, wörld]", false);
check("mapBoth((x) => \"(\" + String(x) + \")\", \"hello world\")", () => M.mapBoth((x) => "(" + String(x) + ")", "hello world"), "(hello world)", false);
check("mapBoth((x) => \"[\" + String(x) + \"]\", \"abcabc\")", () => M.mapBoth((x) => "[" + String(x) + "]", "abcabc"), "[abcabc]", false);
check("mapBoth((x) => \"(\" + String(x) + \")\", \"héllo, wörld\")", () => M.mapBoth((x) => "(" + String(x) + ")", "héllo, wörld"), "(héllo, wörld)", false);
check("mapBoth((x) => \"(\" + String(x) + \")\", \"abcabc\")", () => M.mapBoth((x) => "(" + String(x) + ")", "abcabc"), "(abcabc)", false);
check("mapNone((x) => \"[\" + String(x) + \"]\")", () => M.mapNone((x) => "[" + String(x) + "]"), "a", false);
check("mapNone((x) => \"(\" + String(x) + \")\")", () => M.mapNone((x) => "(" + String(x) + ")"), "a", false);
check("mapIf(false, (x) => \"[\" + String(x) + \"]\", \"\")", () => M.mapIf(false, (x) => "[" + String(x) + "]", ""), "a", false);
check("mapIf(false, (x) => \"[\" + String(x) + \"]\", \"a\")", () => M.mapIf(false, (x) => "[" + String(x) + "]", "a"), "a", false);
check("mapIf(false, (x) => \"(\" + String(x) + \")\", \"\")", () => M.mapIf(false, (x) => "(" + String(x) + ")", ""), "a", false);
check("mapIf(true, (x) => \"[\" + String(x) + \"]\", \"\")", () => M.mapIf(true, (x) => "[" + String(x) + "]", ""), "[]", false);
check("mapIf(false, (x) => \"[\" + String(x) + \"]\", \"hello world\")", () => M.mapIf(false, (x) => "[" + String(x) + "]", "hello world"), "a", false);
check("mapIf(false, (x) => \"(\" + String(x) + \")\", \"a\")", () => M.mapIf(false, (x) => "(" + String(x) + ")", "a"), "a", false);
check("mapIf(true, (x) => \"[\" + String(x) + \"]\", \"a\")", () => M.mapIf(true, (x) => "[" + String(x) + "]", "a"), "[a]", false);
check("mapIf(true, (x) => \"(\" + String(x) + \")\", \"\")", () => M.mapIf(true, (x) => "(" + String(x) + ")", ""), "()", false);
check("mapIf(false, (x) => \"[\" + String(x) + \"]\", \"héllo, wörld\")", () => M.mapIf(false, (x) => "[" + String(x) + "]", "héllo, wörld"), "a", false);
check("mapIf(false, (x) => \"(\" + String(x) + \")\", \"hello world\")", () => M.mapIf(false, (x) => "(" + String(x) + ")", "hello world"), "a", false);
check("mapIf(true, (x) => \"[\" + String(x) + \"]\", \"hello world\")", () => M.mapIf(true, (x) => "[" + String(x) + "]", "hello world"), "[hello world]", false);
check("mapIf(true, (x) => \"(\" + String(x) + \")\", \"a\")", () => M.mapIf(true, (x) => "(" + String(x) + ")", "a"), "(a)", false);
check("mapIf(false, (x) => \"[\" + String(x) + \"]\", \"abcabc\")", () => M.mapIf(false, (x) => "[" + String(x) + "]", "abcabc"), "a", false);
check("mapIf(false, (x) => \"(\" + String(x) + \")\", \"héllo, wörld\")", () => M.mapIf(false, (x) => "(" + String(x) + ")", "héllo, wörld"), "a", false);
check("mapIf(true, (x) => \"[\" + String(x) + \"]\", \"héllo, wörld\")", () => M.mapIf(true, (x) => "[" + String(x) + "]", "héllo, wörld"), "[héllo, wörld]", false);
check("mapIf(true, (x) => \"(\" + String(x) + \")\", \"hello world\")", () => M.mapIf(true, (x) => "(" + String(x) + ")", "hello world"), "(hello world)", false);
check("mapIf(false, (x) => \"(\" + String(x) + \")\", \"abcabc\")", () => M.mapIf(false, (x) => "(" + String(x) + ")", "abcabc"), "a", false);
check("mapIf(true, (x) => \"[\" + String(x) + \"]\", \"abcabc\")", () => M.mapIf(true, (x) => "[" + String(x) + "]", "abcabc"), "[abcabc]", false);
check("mapIf(true, (x) => \"(\" + String(x) + \")\", \"héllo, wörld\")", () => M.mapIf(true, (x) => "(" + String(x) + ")", "héllo, wörld"), "(héllo, wörld)", false);
check("mapIf(true, (x) => \"(\" + String(x) + \")\", \"abcabc\")", () => M.mapIf(true, (x) => "(" + String(x) + ")", "abcabc"), "(abcabc)", false);
check("mapTwice((x) => \"[\" + String(x) + \"]\", (x) => \"[\" + String(x) + \"]\", \"\")", () => M.mapTwice((x) => "[" + String(x) + "]", (x) => "[" + String(x) + "]", ""), "[[]]", false);
check("mapTwice((x) => \"[\" + String(x) + \"]\", (x) => \"[\" + String(x) + \"]\", \"a\")", () => M.mapTwice((x) => "[" + String(x) + "]", (x) => "[" + String(x) + "]", "a"), "[[a]]", false);
check("mapTwice((x) => \"[\" + String(x) + \"]\", (x) => \"(\" + String(x) + \")\", \"\")", () => M.mapTwice((x) => "[" + String(x) + "]", (x) => "(" + String(x) + ")", ""), "([])", false);
check("mapTwice((x) => \"(\" + String(x) + \")\", (x) => \"[\" + String(x) + \"]\", \"\")", () => M.mapTwice((x) => "(" + String(x) + ")", (x) => "[" + String(x) + "]", ""), "[()]", false);
check("mapTwice((x) => \"[\" + String(x) + \"]\", (x) => \"[\" + String(x) + \"]\", \"hello world\")", () => M.mapTwice((x) => "[" + String(x) + "]", (x) => "[" + String(x) + "]", "hello world"), "[[hello world]]", false);
check("mapTwice((x) => \"[\" + String(x) + \"]\", (x) => \"(\" + String(x) + \")\", \"a\")", () => M.mapTwice((x) => "[" + String(x) + "]", (x) => "(" + String(x) + ")", "a"), "([a])", false);
check("mapTwice((x) => \"(\" + String(x) + \")\", (x) => \"[\" + String(x) + \"]\", \"a\")", () => M.mapTwice((x) => "(" + String(x) + ")", (x) => "[" + String(x) + "]", "a"), "[(a)]", false);
check("mapTwice((x) => \"(\" + String(x) + \")\", (x) => \"(\" + String(x) + \")\", \"\")", () => M.mapTwice((x) => "(" + String(x) + ")", (x) => "(" + String(x) + ")", ""), "(())", false);
check("mapTwice((x) => \"[\" + String(x) + \"]\", (x) => \"[\" + String(x) + \"]\", \"héllo, wörld\")", () => M.mapTwice((x) => "[" + String(x) + "]", (x) => "[" + String(x) + "]", "héllo, wörld"), "[[héllo, wörld]]", false);
check("mapTwice((x) => \"[\" + String(x) + \"]\", (x) => \"(\" + String(x) + \")\", \"hello world\")", () => M.mapTwice((x) => "[" + String(x) + "]", (x) => "(" + String(x) + ")", "hello world"), "([hello world])", false);
check("mapTwice((x) => \"(\" + String(x) + \")\", (x) => \"[\" + String(x) + \"]\", \"hello world\")", () => M.mapTwice((x) => "(" + String(x) + ")", (x) => "[" + String(x) + "]", "hello world"), "[(hello world)]", false);
check("mapTwice((x) => \"(\" + String(x) + \")\", (x) => \"(\" + String(x) + \")\", \"a\")", () => M.mapTwice((x) => "(" + String(x) + ")", (x) => "(" + String(x) + ")", "a"), "((a))", false);
check("mapTwice((x) => \"[\" + String(x) + \"]\", (x) => \"[\" + String(x) + \"]\", \"abcabc\")", () => M.mapTwice((x) => "[" + String(x) + "]", (x) => "[" + String(x) + "]", "abcabc"), "[[abcabc]]", false);
check("mapTwice((x) => \"[\" + String(x) + \"]\", (x) => \"(\" + String(x) + \")\", \"héllo, wörld\")", () => M.mapTwice((x) => "[" + String(x) + "]", (x) => "(" + String(x) + ")", "héllo, wörld"), "([héllo, wörld])", false);
check("mapTwice((x) => \"(\" + String(x) + \")\", (x) => \"[\" + String(x) + \"]\", \"héllo, wörld\")", () => M.mapTwice((x) => "(" + String(x) + ")", (x) => "[" + String(x) + "]", "héllo, wörld"), "[(héllo, wörld)]", false);
check("mapTwice((x) => \"(\" + String(x) + \")\", (x) => \"(\" + String(x) + \")\", \"hello world\")", () => M.mapTwice((x) => "(" + String(x) + ")", (x) => "(" + String(x) + ")", "hello world"), "((hello world))", false);
check("mapTwice((x) => \"[\" + String(x) + \"]\", (x) => \"(\" + String(x) + \")\", \"abcabc\")", () => M.mapTwice((x) => "[" + String(x) + "]", (x) => "(" + String(x) + ")", "abcabc"), "([abcabc])", false);
check("mapTwice((x) => \"(\" + String(x) + \")\", (x) => \"[\" + String(x) + \"]\", \"abcabc\")", () => M.mapTwice((x) => "(" + String(x) + ")", (x) => "[" + String(x) + "]", "abcabc"), "[(abcabc)]", false);
check("mapTwice((x) => \"(\" + String(x) + \")\", (x) => \"(\" + String(x) + \")\", \"héllo, wörld\")", () => M.mapTwice((x) => "(" + String(x) + ")", (x) => "(" + String(x) + ")", "héllo, wörld"), "((héllo, wörld))", false);
check("mapTwice((x) => \"(\" + String(x) + \")\", (x) => \"(\" + String(x) + \")\", \"abcabc\")", () => M.mapTwice((x) => "(" + String(x) + ")", (x) => "(" + String(x) + ")", "abcabc"), "((abcabc))", false);
check("exceptKnown((x) => x + 1n, 0n)", () => M.exceptKnown((x) => x + 1n, 0n), "1", false);
check("exceptKnown((x) => x + 1n, 1n)", () => M.exceptKnown((x) => x + 1n, 1n), "2", false);
check("exceptKnown((x) => x * 3n, 0n)", () => M.exceptKnown((x) => x * 3n, 0n), "0", false);
check("exceptKnown((x) => x + 1n, 2n)", () => M.exceptKnown((x) => x + 1n, 2n), "3", false);
check("exceptKnown((x) => x * 3n, 1n)", () => M.exceptKnown((x) => x * 3n, 1n), "3", false);
check("exceptKnown((x) => x + 1n, 5n)", () => M.exceptKnown((x) => x + 1n, 5n), "6", false);
check("exceptKnown((x) => x * 3n, 2n)", () => M.exceptKnown((x) => x * 3n, 2n), "6", false);
check("exceptKnown((x) => x + 1n, 13n)", () => M.exceptKnown((x) => x + 1n, 13n), "14", false);
check("exceptKnown((x) => x * 3n, 5n)", () => M.exceptKnown((x) => x * 3n, 5n), "15", false);
check("exceptKnown((x) => x * 3n, 13n)", () => M.exceptKnown((x) => x * 3n, 13n), "39", false);
check("wrapSome(0n)", () => (showUnion)(M.wrapSome(0n)), "1(1)", false);
check("wrapSome(1n)", () => (showUnion)(M.wrapSome(1n)), "1(2)", false);
check("wrapSome(2n)", () => (showUnion)(M.wrapSome(2n)), "1(3)", false);
check("wrapSome(5n)", () => (showUnion)(M.wrapSome(5n)), "1(6)", false);
check("wrapSome(13n)", () => (showUnion)(M.wrapSome(13n)), "1(14)", false);
check("viaHelper(0n)", () => M.viaHelper(0n), "1", false);
check("viaHelper(1n)", () => M.viaHelper(1n), "2", false);
check("viaHelper(2n)", () => M.viaHelper(2n), "3", false);
check("viaHelper(5n)", () => M.viaHelper(5n), "6", false);
check("viaHelper(13n)", () => M.viaHelper(13n), "14", false);
check("viaPrivate(0n)", () => M.viaPrivate(0n), "7", false);
check("viaPrivate(1n)", () => M.viaPrivate(1n), "7", false);
check("viaPrivate(2n)", () => M.viaPrivate(2n), "7", false);
check("viaPrivate(5n)", () => M.viaPrivate(5n), "7", false);
check("viaPrivate(13n)", () => M.viaPrivate(13n), "26", false);
check("loopOpt(0n)", () => M.loopOpt(0n), "0", false);
check("loopOpt(1n)", () => M.loopOpt(1n), "0", false);
check("loopOpt(2n)", () => M.loopOpt(2n), "1", false);
check("loopOpt(5n)", () => M.loopOpt(5n), "10", false);
check("loopOpt(13n)", () => M.loopOpt(13n), "78", false);
check("loopPair(0n)", () => M.loopPair(0n), "{0, 0}", false);
check("loopPair(1n)", () => M.loopPair(1n), "{0, 1}", false);
check("loopPair(2n)", () => M.loopPair(2n), "{1, 2}", false);
check("loopPair(5n)", () => M.loopPair(5n), "{10, 5}", false);
check("loopPair(13n)", () => M.loopPair(13n), "{78, 13}", false);
check("loopBreak(0n, 0n)", () => M.loopBreak(0n, 0n), "0", false);
check("loopBreak(0n, 2n)", () => M.loopBreak(0n, 2n), "0", false);
check("loopBreak(1n, 1n)", () => M.loopBreak(1n, 1n), "0", false);
check("loopBreak(2n, 0n)", () => M.loopBreak(2n, 0n), "1", false);
check("loopBreak(0n, 13n)", () => M.loopBreak(0n, 13n), "0", false);
check("loopBreak(1n, 5n)", () => M.loopBreak(1n, 5n), "0", false);
check("loopBreak(2n, 2n)", () => M.loopBreak(2n, 2n), "0", false);
check("loopBreak(5n, 1n)", () => M.loopBreak(5n, 1n), "2", false);
check("loopBreak(13n, 0n)", () => M.loopBreak(13n, 0n), "1", false);
check("loopBreak(2n, 13n)", () => M.loopBreak(2n, 13n), "0", false);
check("loopBreak(5n, 5n)", () => M.loopBreak(5n, 5n), "0", false);
check("loopBreak(13n, 2n)", () => M.loopBreak(13n, 2n), "3", false);
check("loopBreak(13n, 13n)", () => M.loopBreak(13n, 13n), "0", false);
check("loopNested(0n)", () => M.loopNested(0n), "0", false);
check("loopNested(1n)", () => M.loopNested(1n), "0", false);
check("loopNested(2n)", () => M.loopNested(2n), "0", false);
check("loopNested(5n)", () => M.loopNested(5n), "10", false);
check("loopNested(13n)", () => M.loopNested(13n), "286", false);

console.log(`KnownCtorOption-faithful.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
