// Differential checks of KnownCtorCondConst-pbo.js against Lean, generated by leanscript --check
import * as M from "./KnownCtorCondConst-pbo.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
// a recursive union: as `showUnion`, the fields marked in `rec[tag]` (the type itself) printed
// the same way, one level less deep (`…` at depth 0, as `showExpr` cuts it in Lean)
function showTree(v, rec, d) {
  if (d === 0) return "…";
  if (typeof v === "number") return v + "()";
  const r = rec[v.tag] || [];
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++)
    fs.push(r[i - 1] ? showTree(v["_" + i], rec, d - 1) : show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("intOps((x, y) => x * 10 + y, -7)", () => M.intOps((x, y) => x * 10 + y, -7), "270", false);
check("intOps((x, y) => x * 10 + y, -1)", () => M.intOps((x, y) => x * 10 + y, -1), "270", false);
check("intOps((x, y) => y * 3 - x, -7)", () => M.intOps((x, y) => y * 3 - x, -7), "159", false);
check("intOps((x, y) => x * 10 + y, 0)", () => M.intOps((x, y) => x * 10 + y, 0), "270", false);
check("intOps((x, y) => y * 3 - x, -1)", () => M.intOps((x, y) => y * 3 - x, -1), "159", false);
check("intOps((x, y) => x * 10 + y, 1)", () => M.intOps((x, y) => x * 10 + y, 1), "270", false);
check("intOps((x, y) => y * 3 - x, 0)", () => M.intOps((x, y) => y * 3 - x, 0), "159", false);
check("intOps((x, y) => x * 10 + y, 2)", () => M.intOps((x, y) => x * 10 + y, 2), "270", false);
check("intOps((x, y) => y * 3 - x, 1)", () => M.intOps((x, y) => y * 3 - x, 1), "159", false);
check("intOps((x, y) => x * 10 + y, 3)", () => M.intOps((x, y) => x * 10 + y, 3), "270", false);
check("intOps((x, y) => y * 3 - x, 2)", () => M.intOps((x, y) => y * 3 - x, 2), "159", false);
check("intOps((x, y) => x * 10 + y, 12)", () => M.intOps((x, y) => x * 10 + y, 12), "270", false);
check("intOps((x, y) => y * 3 - x, 3)", () => M.intOps((x, y) => y * 3 - x, 3), "159", false);
check("intOps((x, y) => y * 3 - x, 12)", () => M.intOps((x, y) => y * 3 - x, 12), "159", false);
check("threeUses(-7)", () => M.threeUses(-7), "#[neg!, <neg, no]", false);
check("threeUses(-1)", () => M.threeUses(-1), "#[neg!, <neg, no]", false);
check("threeUses(0)", () => M.threeUses(0), "#[neg!, <neg, no]", false);
check("threeUses(1)", () => M.threeUses(1), "#[pos!, <pos, yes]", false);
check("threeUses(2)", () => M.threeUses(2), "#[pos!, <pos, yes]", false);
check("threeUses(3)", () => M.threeUses(3), "#[pos!, <pos, yes]", false);
check("threeUses(12)", () => M.threeUses(12), "#[pos!, <pos, yes]", false);
check("usesInArms((x) => \"[\" + String(x) + \"]\", -7, -7)", () => M.usesInArms((x) => "[" + String(x) + "]", -7, -7), "[b2]", false);
check("usesInArms((x) => \"(\" + String(x) + \")\", -7, -1)", () => M.usesInArms((x) => "(" + String(x) + ")", -7, -1), "(b2)", false);
check("usesInArms((x) => \"[\" + String(x) + \"]\", 0, -1)", () => M.usesInArms((x) => "[" + String(x) + "]", 0, -1), "[b2]", false);
check("usesInArms((x) => \"[\" + String(x) + \"]\", -1, 1)", () => M.usesInArms((x) => "[" + String(x) + "]", -1, 1), "[b1]", false);
check("usesInArms((x) => \"(\" + String(x) + \")\", 1, -7)", () => M.usesInArms((x) => "(" + String(x) + ")", 1, -7), "(a2)", false);
check("usesInArms((x) => \"[\" + String(x) + \"]\", -7, 3)", () => M.usesInArms((x) => "[" + String(x) + "]", -7, 3), "[b1]", false);
check("usesInArms((x) => \"[\" + String(x) + \"]\", 3, -7)", () => M.usesInArms((x) => "[" + String(x) + "]", 3, -7), "[a2]", false);
check("usesInArms((x) => \"(\" + String(x) + \")\", 0, 0)", () => M.usesInArms((x) => "(" + String(x) + ")", 0, 0), "(b2)", false);
check("usesInArms((x) => \"[\" + String(x) + \"]\", 2, 0)", () => M.usesInArms((x) => "[" + String(x) + "]", 2, 0), "[a2]", false);
check("usesInArms((x) => \"(\" + String(x) + \")\", -1, 2)", () => M.usesInArms((x) => "(" + String(x) + ")", -1, 2), "(b1)", false);
check("usesInArms((x) => \"[\" + String(x) + \"]\", 1, 2)", () => M.usesInArms((x) => "[" + String(x) + "]", 1, 2), "[a1]", false);
check("usesInArms((x) => \"(\" + String(x) + \")\", -7, 12)", () => M.usesInArms((x) => "(" + String(x) + ")", -7, 12), "(b1)", false);
check("usesInArms((x) => \"(\" + String(x) + \")\", 3, -1)", () => M.usesInArms((x) => "(" + String(x) + ")", 3, -1), "(a2)", false);
check("usesInArms((x) => \"[\" + String(x) + \"]\", 0, 12)", () => M.usesInArms((x) => "[" + String(x) + "]", 0, 12), "[b1]", false);
check("usesInArms((x) => \"(\" + String(x) + \")\", 2, 1)", () => M.usesInArms((x) => "(" + String(x) + ")", 2, 1), "(a1)", false);
check("usesInArms((x) => \"[\" + String(x) + \"]\", 12, 1)", () => M.usesInArms((x) => "[" + String(x) + "]", 12, 1), "[a1]", false);
check("usesInArms((x) => \"(\" + String(x) + \")\", 1, 3)", () => M.usesInArms((x) => "(" + String(x) + ")", 1, 3), "(a1)", false);
check("usesInArms((x) => \"[\" + String(x) + \"]\", 3, 3)", () => M.usesInArms((x) => "[" + String(x) + "]", 3, 3), "[a1]", false);
check("usesInArms((x) => \"(\" + String(x) + \")\", 12, 2)", () => M.usesInArms((x) => "(" + String(x) + ")", 12, 2), "(a1)", false);
check("usesInArms((x) => \"(\" + String(x) + \")\", 3, 12)", () => M.usesInArms((x) => "(" + String(x) + ")", 3, 12), "(a1)", false);
check("natOps((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y), 0)", () => M.natOps((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y), 0), "118", false);
check("natOps((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y), 1)", () => M.natOps((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y), 1), "118", false);
check("natOps((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x), 0)", () => M.natOps((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x), 0), "13", false);
check("natOps((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y), 2)", () => M.natOps((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y), 2), "118", false);
check("natOps((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x), 1)", () => M.natOps((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x), 1), "13", false);
check("natOps((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y), 5)", () => M.natOps((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y), 5), "118", false);
check("natOps((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x), 2)", () => M.natOps((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x), 2), "13", false);
check("natOps((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y), 13)", () => M.natOps((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y), 13), "96", false);
check("natOps((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x), 5)", () => M.natOps((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x), 5), "13", false);
check("natOps((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x), 13)", () => M.natOps((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x), 13), "9", false);

console.log(`KnownCtorCondConst-pbo.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
