// JavaScript of Tests/SnapshotsMy/ListRepr.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `ListRepr.x`
 * @type {List<uint53(number)>}
 */
export const ListRepr$x = [1, 2, 3];

/**
 * `ListRepr.empty`
 * @type {List<string>}
 */
export const ListRepr$empty = [];

/**
 * `ListRepr.front`
 * @param {string} a
 * @param {List<string>} xs
 * @returns {List<string>}
 */
export const ListRepr$front = (a, xs) => [a, "b", ...xs];

/**
 * `ListRepr.middle`
 * @param {List<uint53(number)>} xs
 * @returns {List<uint53(number)>}
 */
export const ListRepr$middle = (xs) => [0, ...xs, 7, 8];

/**
 * `ListRepr.append`
 * @param {List<uint53(number)>} xs
 * @param {List<uint53(number)>} ys
 * @returns {List<uint53(number)>}
 */
export const ListRepr$append = (xs, ys) => [...xs, ...ys];

/**
 * `ListRepr.ofArr`
 * @param {Array<uint53(number)>} a
 * @returns {List<uint53(number)>}
 */
export const ListRepr$ofArr = (a) => a;

/**
 * `ListRepr.toArr`
 * @param {List<uint53(number)>} xs
 * @returns {Array<uint53(number)>}
 */
export const ListRepr$toArr = (xs) => xs;

/**
 * `ListRepr.roundTrip`
 * @param {List<int53(number)>} xs
 * @returns {List<int53(number)>}
 */
export const ListRepr$roundTrip = (xs) => xs;

/**
 * `ListRepr.nested`
 * @param {List<uint53(number)>} xs
 * @returns {List<List<uint53(number)>>}
 */
export const ListRepr$nested = (xs) => [xs, [1], xs];
