// Differential checks of ListRepr-faithful.js against Lean, generated by leanscript --check
import * as M from "./ListRepr-faithful.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("ListRepr$x", () => M.ListRepr$x, "#[1, 2, 3]", false);
check("ListRepr$empty", () => M.ListRepr$empty, "#[]", false);
check("ListRepr$front(\"\", { tag: 0 })", () => M.ListRepr$front("", { tag: 0 }), "#[, b]", false);
check("ListRepr$front(\"\", { tag: 1, _1: \"\", _2: { tag: 0 } })", () => M.ListRepr$front("", { tag: 1, _1: "", _2: { tag: 0 } }), "#[, b, ]", false);
check("ListRepr$front(\"a\", { tag: 0 })", () => M.ListRepr$front("a", { tag: 0 }), "#[a, b]", false);
check("ListRepr$front(\"\", { tag: 1, _1: \"\", _2: { tag: 1, _1: \"a\", _2: { tag: 1, _1: \"hello world\", _2: { tag: 0 } } } })", () => M.ListRepr$front("", { tag: 1, _1: "", _2: { tag: 1, _1: "a", _2: { tag: 1, _1: "hello world", _2: { tag: 0 } } } }), "#[, b, , a, hello world]", false);
check("ListRepr$front(\"a\", { tag: 1, _1: \"\", _2: { tag: 0 } })", () => M.ListRepr$front("a", { tag: 1, _1: "", _2: { tag: 0 } }), "#[a, b, ]", false);
check("ListRepr$front(\"hello world\", { tag: 0 })", () => M.ListRepr$front("hello world", { tag: 0 }), "#[hello world, b]", false);
check("ListRepr$front(\"\", { tag: 1, _1: \"abcabc\", _2: { tag: 1, _1: \"héllo, wörld\", _2: { tag: 1, _1: \"hello world\", _2: { tag: 1, _1: \"a\", _2: { tag: 0 } } } } })", () => M.ListRepr$front("", { tag: 1, _1: "abcabc", _2: { tag: 1, _1: "héllo, wörld", _2: { tag: 1, _1: "hello world", _2: { tag: 1, _1: "a", _2: { tag: 0 } } } } }), "#[, b, abcabc, héllo, wörld, hello world, a]", false);
check("ListRepr$front(\"a\", { tag: 1, _1: \"\", _2: { tag: 1, _1: \"a\", _2: { tag: 1, _1: \"hello world\", _2: { tag: 0 } } } })", () => M.ListRepr$front("a", { tag: 1, _1: "", _2: { tag: 1, _1: "a", _2: { tag: 1, _1: "hello world", _2: { tag: 0 } } } }), "#[a, b, , a, hello world]", false);
check("ListRepr$front(\"hello world\", { tag: 1, _1: \"\", _2: { tag: 0 } })", () => M.ListRepr$front("hello world", { tag: 1, _1: "", _2: { tag: 0 } }), "#[hello world, b, ]", false);
check("ListRepr$front(\"héllo, wörld\", { tag: 0 })", () => M.ListRepr$front("héllo, wörld", { tag: 0 }), "#[héllo, wörld, b]", false);
check("ListRepr$front(\"a\", { tag: 1, _1: \"abcabc\", _2: { tag: 1, _1: \"héllo, wörld\", _2: { tag: 1, _1: \"hello world\", _2: { tag: 1, _1: \"a\", _2: { tag: 0 } } } } })", () => M.ListRepr$front("a", { tag: 1, _1: "abcabc", _2: { tag: 1, _1: "héllo, wörld", _2: { tag: 1, _1: "hello world", _2: { tag: 1, _1: "a", _2: { tag: 0 } } } } }), "#[a, b, abcabc, héllo, wörld, hello world, a]", false);
check("ListRepr$front(\"hello world\", { tag: 1, _1: \"\", _2: { tag: 1, _1: \"a\", _2: { tag: 1, _1: \"hello world\", _2: { tag: 0 } } } })", () => M.ListRepr$front("hello world", { tag: 1, _1: "", _2: { tag: 1, _1: "a", _2: { tag: 1, _1: "hello world", _2: { tag: 0 } } } }), "#[hello world, b, , a, hello world]", false);
check("ListRepr$front(\"héllo, wörld\", { tag: 1, _1: \"\", _2: { tag: 0 } })", () => M.ListRepr$front("héllo, wörld", { tag: 1, _1: "", _2: { tag: 0 } }), "#[héllo, wörld, b, ]", false);
check("ListRepr$front(\"abcabc\", { tag: 0 })", () => M.ListRepr$front("abcabc", { tag: 0 }), "#[abcabc, b]", false);
check("ListRepr$front(\"hello world\", { tag: 1, _1: \"abcabc\", _2: { tag: 1, _1: \"héllo, wörld\", _2: { tag: 1, _1: \"hello world\", _2: { tag: 1, _1: \"a\", _2: { tag: 0 } } } } })", () => M.ListRepr$front("hello world", { tag: 1, _1: "abcabc", _2: { tag: 1, _1: "héllo, wörld", _2: { tag: 1, _1: "hello world", _2: { tag: 1, _1: "a", _2: { tag: 0 } } } } }), "#[hello world, b, abcabc, héllo, wörld, hello world, a]", false);
check("ListRepr$front(\"héllo, wörld\", { tag: 1, _1: \"\", _2: { tag: 1, _1: \"a\", _2: { tag: 1, _1: \"hello world\", _2: { tag: 0 } } } })", () => M.ListRepr$front("héllo, wörld", { tag: 1, _1: "", _2: { tag: 1, _1: "a", _2: { tag: 1, _1: "hello world", _2: { tag: 0 } } } }), "#[héllo, wörld, b, , a, hello world]", false);
check("ListRepr$front(\"abcabc\", { tag: 1, _1: \"\", _2: { tag: 0 } })", () => M.ListRepr$front("abcabc", { tag: 1, _1: "", _2: { tag: 0 } }), "#[abcabc, b, ]", false);
check("ListRepr$front(\"b\", { tag: 0 })", () => M.ListRepr$front("b", { tag: 0 }), "#[b, b]", false);
check("ListRepr$front(\"héllo, wörld\", { tag: 1, _1: \"abcabc\", _2: { tag: 1, _1: \"héllo, wörld\", _2: { tag: 1, _1: \"hello world\", _2: { tag: 1, _1: \"a\", _2: { tag: 0 } } } } })", () => M.ListRepr$front("héllo, wörld", { tag: 1, _1: "abcabc", _2: { tag: 1, _1: "héllo, wörld", _2: { tag: 1, _1: "hello world", _2: { tag: 1, _1: "a", _2: { tag: 0 } } } } }), "#[héllo, wörld, b, abcabc, héllo, wörld, hello world, a]", false);
check("ListRepr$front(\"abcabc\", { tag: 1, _1: \"\", _2: { tag: 1, _1: \"a\", _2: { tag: 1, _1: \"hello world\", _2: { tag: 0 } } } })", () => M.ListRepr$front("abcabc", { tag: 1, _1: "", _2: { tag: 1, _1: "a", _2: { tag: 1, _1: "hello world", _2: { tag: 0 } } } }), "#[abcabc, b, , a, hello world]", false);
check("ListRepr$front(\"b\", { tag: 1, _1: \"\", _2: { tag: 0 } })", () => M.ListRepr$front("b", { tag: 1, _1: "", _2: { tag: 0 } }), "#[b, b, ]", false);
check("ListRepr$front(\"abcabc\", { tag: 1, _1: \"abcabc\", _2: { tag: 1, _1: \"héllo, wörld\", _2: { tag: 1, _1: \"hello world\", _2: { tag: 1, _1: \"a\", _2: { tag: 0 } } } } })", () => M.ListRepr$front("abcabc", { tag: 1, _1: "abcabc", _2: { tag: 1, _1: "héllo, wörld", _2: { tag: 1, _1: "hello world", _2: { tag: 1, _1: "a", _2: { tag: 0 } } } } }), "#[abcabc, b, abcabc, héllo, wörld, hello world, a]", false);
check("ListRepr$front(\"b\", { tag: 1, _1: \"\", _2: { tag: 1, _1: \"a\", _2: { tag: 1, _1: \"hello world\", _2: { tag: 0 } } } })", () => M.ListRepr$front("b", { tag: 1, _1: "", _2: { tag: 1, _1: "a", _2: { tag: 1, _1: "hello world", _2: { tag: 0 } } } }), "#[b, b, , a, hello world]", false);
check("ListRepr$front(\"b\", { tag: 1, _1: \"abcabc\", _2: { tag: 1, _1: \"héllo, wörld\", _2: { tag: 1, _1: \"hello world\", _2: { tag: 1, _1: \"a\", _2: { tag: 0 } } } } })", () => M.ListRepr$front("b", { tag: 1, _1: "abcabc", _2: { tag: 1, _1: "héllo, wörld", _2: { tag: 1, _1: "hello world", _2: { tag: 1, _1: "a", _2: { tag: 0 } } } } }), "#[b, b, abcabc, héllo, wörld, hello world, a]", false);
check("ListRepr$middle({ tag: 0 })", () => M.ListRepr$middle({ tag: 0 }), "#[0, 7, 8]", false);
check("ListRepr$middle({ tag: 1, _1: 0n, _2: { tag: 0 } })", () => M.ListRepr$middle({ tag: 1, _1: 0n, _2: { tag: 0 } }), "#[0, 0, 7, 8]", false);
check("ListRepr$middle({ tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } })", () => M.ListRepr$middle({ tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }), "#[0, 0, 1, 2, 7, 8]", false);
check("ListRepr$middle({ tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } })", () => M.ListRepr$middle({ tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }), "#[0, 13, 5, 2, 1, 7, 8]", false);
check("ListRepr$append({ tag: 0 }, { tag: 0 })", () => M.ListRepr$append({ tag: 0 }, { tag: 0 }), "#[]", false);
check("ListRepr$append({ tag: 0 }, { tag: 1, _1: 0n, _2: { tag: 0 } })", () => M.ListRepr$append({ tag: 0 }, { tag: 1, _1: 0n, _2: { tag: 0 } }), "#[0]", false);
check("ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 0 } }, { tag: 0 })", () => M.ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 0 } }, { tag: 0 }), "#[0]", false);
check("ListRepr$append({ tag: 0 }, { tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } })", () => M.ListRepr$append({ tag: 0 }, { tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }), "#[0, 1, 2]", false);
check("ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 0 } }, { tag: 1, _1: 0n, _2: { tag: 0 } })", () => M.ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 0 } }, { tag: 1, _1: 0n, _2: { tag: 0 } }), "#[0, 0]", false);
check("ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }, { tag: 0 })", () => M.ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }, { tag: 0 }), "#[0, 1, 2]", false);
check("ListRepr$append({ tag: 0 }, { tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } })", () => M.ListRepr$append({ tag: 0 }, { tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }), "#[13, 5, 2, 1]", false);
check("ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 0 } }, { tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } })", () => M.ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 0 } }, { tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }), "#[0, 0, 1, 2]", false);
check("ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }, { tag: 1, _1: 0n, _2: { tag: 0 } })", () => M.ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }, { tag: 1, _1: 0n, _2: { tag: 0 } }), "#[0, 1, 2, 0]", false);
check("ListRepr$append({ tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }, { tag: 0 })", () => M.ListRepr$append({ tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }, { tag: 0 }), "#[13, 5, 2, 1]", false);
check("ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 0 } }, { tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } })", () => M.ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 0 } }, { tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }), "#[0, 13, 5, 2, 1]", false);
check("ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }, { tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } })", () => M.ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }, { tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }), "#[0, 1, 2, 0, 1, 2]", false);
check("ListRepr$append({ tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }, { tag: 1, _1: 0n, _2: { tag: 0 } })", () => M.ListRepr$append({ tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }, { tag: 1, _1: 0n, _2: { tag: 0 } }), "#[13, 5, 2, 1, 0]", false);
check("ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }, { tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } })", () => M.ListRepr$append({ tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }, { tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }), "#[0, 1, 2, 13, 5, 2, 1]", false);
check("ListRepr$append({ tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }, { tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } })", () => M.ListRepr$append({ tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }, { tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }), "#[13, 5, 2, 1, 0, 1, 2]", false);
check("ListRepr$append({ tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }, { tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } })", () => M.ListRepr$append({ tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }, { tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }), "#[13, 5, 2, 1, 13, 5, 2, 1]", false);
check("ListRepr$ofArr([])", () => M.ListRepr$ofArr([]), "#[]", false);
check("ListRepr$ofArr([]) twice", () => ((a0) => (M.ListRepr$ofArr(a0), M.ListRepr$ofArr(a0)))([]), "#[]", false);
check("ListRepr$ofArr([0n])", () => M.ListRepr$ofArr([0n]), "#[0]", false);
check("ListRepr$ofArr([0n]) twice", () => ((a0) => (M.ListRepr$ofArr(a0), M.ListRepr$ofArr(a0)))([0n]), "#[0]", false);
check("ListRepr$ofArr([0n, 1n, 2n])", () => M.ListRepr$ofArr([0n, 1n, 2n]), "#[0, 1, 2]", false);
check("ListRepr$ofArr([0n, 1n, 2n]) twice", () => ((a0) => (M.ListRepr$ofArr(a0), M.ListRepr$ofArr(a0)))([0n, 1n, 2n]), "#[0, 1, 2]", false);
check("ListRepr$ofArr([13n, 5n, 2n, 1n])", () => M.ListRepr$ofArr([13n, 5n, 2n, 1n]), "#[13, 5, 2, 1]", false);
check("ListRepr$ofArr([13n, 5n, 2n, 1n]) twice", () => ((a0) => (M.ListRepr$ofArr(a0), M.ListRepr$ofArr(a0)))([13n, 5n, 2n, 1n]), "#[13, 5, 2, 1]", false);
check("ListRepr$toArr({ tag: 0 })", () => M.ListRepr$toArr({ tag: 0 }), "#[]", false);
check("ListRepr$toArr({ tag: 1, _1: 0n, _2: { tag: 0 } })", () => M.ListRepr$toArr({ tag: 1, _1: 0n, _2: { tag: 0 } }), "#[0]", false);
check("ListRepr$toArr({ tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } })", () => M.ListRepr$toArr({ tag: 1, _1: 0n, _2: { tag: 1, _1: 1n, _2: { tag: 1, _1: 2n, _2: { tag: 0 } } } }), "#[0, 1, 2]", false);
check("ListRepr$toArr({ tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } })", () => M.ListRepr$toArr({ tag: 1, _1: 13n, _2: { tag: 1, _1: 5n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }), "#[13, 5, 2, 1]", false);
check("ListRepr$roundTrip({ tag: 0 })", () => M.ListRepr$roundTrip({ tag: 0 }), "#[]", false);
check("ListRepr$roundTrip({ tag: 1, _1: -7n, _2: { tag: 0 } })", () => M.ListRepr$roundTrip({ tag: 1, _1: -7n, _2: { tag: 0 } }), "#[-7]", false);
check("ListRepr$roundTrip({ tag: 1, _1: -7n, _2: { tag: 1, _1: -1n, _2: { tag: 1, _1: 0n, _2: { tag: 0 } } } })", () => M.ListRepr$roundTrip({ tag: 1, _1: -7n, _2: { tag: 1, _1: -1n, _2: { tag: 1, _1: 0n, _2: { tag: 0 } } } }), "#[-7, -1, 0]", false);
check("ListRepr$roundTrip({ tag: 1, _1: 12n, _2: { tag: 1, _1: 3n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } })", () => M.ListRepr$roundTrip({ tag: 1, _1: 12n, _2: { tag: 1, _1: 3n, _2: { tag: 1, _1: 2n, _2: { tag: 1, _1: 1n, _2: { tag: 0 } } } } }), "#[12, 3, 2, 1]", false);

console.log(`ListRepr-faithful.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
