// JavaScript of Tests/SnapshotsMy/LocalFnInPlace.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

import {
  array__lean_array_push_mutable,
  array__lean_array_push_immutable,
  uint53__lean_nat_add,
  uint53__lean_mk_array,
  array__lean_array_append_mutable,
  uint53__lean_array_set_mutable,
} from "../../runtime.js";

/**
 * `test1`
 * @param {Array<uint53(number)>} a
 * @param {uint53(number)} n
 * @returns {Array<uint53(number)>}
 */
export const test1 = (a, n) => {
  const k$3 = (x$1, x$2) =>
    array__lean_array_push_mutable(
      array__lean_array_push_immutable(x$1, x$2),
      uint53__lean_nat_add(x$2, 1),
    );
  const k_mut$6 = (x$4, x$5) =>
    array__lean_array_push_mutable(
      array__lean_array_push_mutable(x$4, x$5),
      uint53__lean_nat_add(x$5, 1),
    );
  return array__lean_array_append_mutable(
    array__lean_array_append_mutable(
      k_mut$6(uint53__lean_mk_array(n, 0), n),
      k$3(a, n),
    ),
    a,
  );
};

/**
 * `test2`
 * @param {uint53(number)} n
 * @param {uint53(number)} m
 * @returns {Array<uint53(number)>}
 */
export const test2 = (n, m) => {
  const k_mut$3 = (x$1, x$2) =>
    uint53__lean_array_set_mutable(
      array__lean_array_push_mutable(x$1, x$2),
      0,
      x$2,
    );
  return array__lean_array_append_mutable(
    k_mut$3(uint53__lean_mk_array(n, 0), m),
    k_mut$3(uint53__lean_mk_array(m, 1), n),
  );
};

/**
 * `test3`
 * @param {uint53(number)} n
 * @param {uint53(number)} m
 * @returns {Array<uint53(number)>}
 */
export const test3 = (n, m) => {
  const x$1 = uint53__lean_mk_array(n, n);
  const x$2 = uint53__lean_mk_array(m, m);
  return array__lean_array_append_mutable(
    array__lean_array_push_mutable(x$1, m),
    x$2,
  );
};

/**
 * `test4`
 * @param {Array<uint53(number)>} a
 * @param {uint53(number)} n
 * @returns {Array<uint53(number)>}
 */
export const test4 = (a, n) => {
  const k$3 = (x$1, x$2) => ({
    _1: array__lean_array_push_immutable(x$1, x$2.length),
    _2: x$2.length,
  });
  const k_mut$6 = (x$4, x$5) => ({
    _1: array__lean_array_push_mutable(x$4, x$5.length),
    _2: x$5.length,
  });
  const x$7 = k_mut$6(uint53__lean_mk_array(n, 0), a);
  const x$8 = k$3(a, a);
  return array__lean_array_append_mutable(
    array__lean_array_push_mutable(
      array__lean_array_append_mutable(x$7._1, x$8._1),
      uint53__lean_nat_add(x$7._2, x$8._2),
    ),
    a,
  );
};

/**
 * `test5`
 * @param {uint53(number)} n
 * @returns {Array<uint53(number)>}
 */
export const test5 = (n) => {
  let p$1 = uint53__lean_mk_array(n, 7);
  let j$2 = n;
  while (true) {
    if (j$2 === 0) {
      return p$1;
    }
    j$2--;
    p$1 = array__lean_array_push_mutable(p$1, j$2);
  }
};

/**
 * `test6`
 * @param {Array<uint53(number)>} a
 * @param {uint53(number)} n
 * @returns {Array<uint53(number)>}
 */
export const test6 = (a, n) => {
  let p$1 = [...a];
  let j$2 = n;
  while (true) {
    if (j$2 === 0) {
      return p$1;
    }
    j$2--;
    p$1 = array__lean_array_push_mutable(p$1, j$2);
  }
};

/**
 * `test6`
 * owns `a`: its caller gives it up, and it may update it in place (1 update(s) in place, 0 copies of arrays)
 * @param {Array<uint53(number)>} a
 * @param {uint53(number)} n
 * @returns {Array<uint53(number)>}
 */
export const test6$$mut_0 = (a, n) => {
  let p$1 = a;
  let j$2 = n;
  while (true) {
    if (j$2 === 0) {
      return p$1;
    }
    j$2--;
    p$1 = array__lean_array_push_mutable(p$1, j$2);
  }
};

/**
 * `test7`
 * @param {uint53(number)} n
 * @returns {Array<uint53(number)>}
 */
export const test7 = (n) => {
  const k_mut$4 = (x$1) => {
    let p$2 = x$1;
    let j$3 = n;
    while (true) {
      if (j$3 === 0) {
        return p$2;
      }
      j$3--;
      p$2 = array__lean_array_push_mutable(p$2, j$3);
    }
  };
  const x$5 = k_mut$4([]);
  const x$6 = k_mut$4([1]);
  return [...x$5, ...x$6];
};
