// JavaScript of Tests/SnapshotsMy/LoopEntry.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic
// not translated:
//   printAll: an `IO`/`ST` action: the language has no side effects
//   main: an `IO`/`ST` action: the language has no side effects

import { $lean_nat_add } from "../../runtime/lean_runtime_nat_num.mjs";

const $k1 = (x$2) => x$2;

/**
 * `messages`
 * @returns {List<string>}
 */
export const messages = () => ["one", "two", "three"];

/**
 * `countUp`
 * @param {string} unused
 * @param {uint53(number)} step
 * @param {uint53(number)} n
 * @param {uint53(number)} acc
 * @returns {uint53(number)}
 */
export const countUp = (unused, step, n, acc) => {
  const k$1 = $k1;
  let acc$3 = k$1;
  for (let i$4 = 0; i$4 < n; i$4++) {
    const a$5 = acc$3;
    const k$6 = (x$7) => a$5($lean_nat_add(x$7, step));
    acc$3 = k$6;
  }
  return acc$3(acc);
};
