// JavaScript of Tests/SnapshotsMy/LoopClosure.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic
// not translated:
//   test2: LeanScript: the recursive type List Nat is not declared in any signature; declare it with `leanscript_signature`

// ---- runtime helpers ----

function $chk53(x) {
  if (!Number.isSafeInteger(x)) {
    throw new RangeError(
      "LeanScript: integer overflow: the result does not fit in a number (use the bigint representation)",
    );
  }
  return x;
}

function lean_nat_add$nnn(a, b) {
  return $chk53(a + b);
}

// ---- exported functions ----

/**
 * `test1`
 * @param {uint53(number)} k
 * @param {uint53(number)} n
 * @returns {uint53(number)}
 */
export const test1 = (k, n) => {
  let acc$1 = { tag: 1, _1: 0 };
  for (let i$2 = 0; i$2 < n; i$2++) {
    const a$3 = acc$1;
    if (a$3.tag === 0) {
      const { _1: f$4 } = a$3;
      acc$1 = { tag: 0, _1: f$4 };
    } else {
      const { _1: f$5 } = a$3;
      const k$6 = (x$7) => {
        const x$8 = x$7(1);
        const x$9 = x$7(2);
        const x$10 = x$7(3);
        return lean_nat_add$nnn(lean_nat_add$nnn(x$8, x$9), x$10);
      };
      const k$11 = (x$12) => lean_nat_add$nnn(x$12, k);
      const x$13 = k$6(k$11);
      const x$14 = lean_nat_add$nnn(f$5, x$13);
      acc$1 = { tag: 1, _1: x$14 };
    }
  }
  if (acc$1.tag === 0) {
    const { _1: f$15 } = acc$1;
    return f$15;
  } else {
    const { _1: f$16 } = acc$1;
    return f$16;
  }
};
