// JavaScript of Tests/SnapshotsMy/LoopEntry.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   printAll: an `IO`/`ST` action: the language has no side effects
//   main: an `IO`/`ST` action: the language has no side effects

import { uint53__lean_nat_add } from "../../runtime.js";

/**
 * `messages`
 * @returns {List<string>}
 */
export const messages = () => ["one", "two", "three"];

/**
 * `countUp`
 * @param {string} unused
 * @param {uint53(number)} step
 * @param {uint53(number)} n
 * @param {uint53(number)} acc
 * @returns {uint53(number)}
 */
export const countUp = (unused, step, n, acc) => {
  const k$2 = (x$1) => x$1;
  let acc$3 = k$2;
  for (let i$4 = 0; i$4 < n; i$4++) {
    const a$5 = acc$3;
    const k$9 = (x$6) => {
      const x$7 = uint53__lean_nat_add(x$6, step);
      const x$8 = a$5(x$7);
      return x$8;
    };
    acc$3 = k$9;
  }
  const x$10 = acc$3;
  const x$11 = x$10(acc);
  return x$11;
};
