// JavaScript of Tests/SnapshotsMy/MapFilter.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

import {
  uint53__lean_nat_mul,
  array__lean_array_map,
  uint53__lean_array_filter,
  uint53__lean_nat_add,
} from "../../runtime.js";

/**
 * `test1`
 * @param {Array<uint53(number)>} a
 * @returns {Array<uint53(number)>}
 */
export const test1 = (a) => {
  const k$2 = (x$1) => uint53__lean_nat_mul(x$1, 2);
  const x$3 = array__lean_array_map(k$2, a);
  const k$5 = (x$4) => 4 < x$4;
  return uint53__lean_array_filter(k$5, x$3, 0, x$3.length);
};

/**
 * `test2`
 * @param {Array<uint53(number)>} a
 * @param {(uint53(number)) => uint53(number)} f
 * @param {(uint53(number)) => boolean} g
 * @returns {Array<uint53(number)>}
 */
export const test2 = (a, f, g) => {
  const x$1 = array__lean_array_map(f, a);
  return uint53__lean_array_filter(g, x$1, 0, x$1.length);
};

/**
 * `test3`
 * @param {Array<uint53(number)>} a
 * @returns {{ _1: Array<uint53(number)>, _2: Array<uint53(number)> }}
 */
export const test3 = (a) => {
  const k$2 = (x$1) => uint53__lean_nat_mul(x$1, 2);
  const x$3 = array__lean_array_map(k$2, a);
  const k$5 = (x$4) => 4 < x$4;
  return { _1: x$3, _2: uint53__lean_array_filter(k$5, x$3, 0, x$3.length) };
};

/**
 * `test4`
 * @param {Array<uint53(number)>} a
 * @returns {Array<uint53(number)>}
 */
export const test4 = (a) => {
  const k$2 = (x$1) => uint53__lean_nat_add(x$1, 1);
  return array__lean_array_map(k$2, a);
};

/**
 * `test5`
 * @param {Array<uint53(number)>} a
 * @returns {Array<uint53(number)>}
 */
export const test5 = (a) => {
  const k$2 = (x$1) => 4 < x$1;
  return uint53__lean_array_filter(k$2, a, 0, a.length);
};
