// JavaScript of Tests/SnapshotsMy/MutualTail.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   test3: a member of a `mutual` block defined by well-founded recursion: only non-recursive and structurally recursive definitions are translated (to `Term`)
//   test4: a member of a `mutual` block defined by well-founded recursion: only non-recursive and structurally recursive definitions are translated (to `Term`)
//   test5: a member of a `mutual` block defined by well-founded recursion: only non-recursive and structurally recursive definitions are translated (to `Term`)

/**
 * `test1`
 * @param {uint53(number)} a
 * @returns {boolean}
 */
export const test1 = (a) => {
  let j$1 = a;
  while (true) {
    if (j$1 === 0) {
      return true;
    }
    j$1--;
    if (j$1 === 0) {
      return false;
    }
    j$1--;
  }
};

/**
 * `test2`
 * @param {uint53(number)} a
 * @returns {boolean}
 */
export const test2 = (a) => {
  if (a === 0) {
    return false;
  }
  return test1(a - 1);
};
