// Differential checks of OptionUnbox-pbo.js against Lean, generated by leanscript --check
import * as M from "./OptionUnbox-pbo.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
// a recursive union: as `showUnion`, the fields marked in `rec[tag]` (the type itself) printed
// the same way, one level less deep (`…` at depth 0, as `showExpr` cuts it in Lean)
function showTree(v, rec, d) {
  if (d === 0) return "…";
  if (typeof v === "number") return v + "()";
  const r = rec[v.tag] || [];
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++)
    fs.push(r[i - 1] ? showTree(v["_" + i], rec, d - 1) : show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("test3({  }, \"\")", () => M.test3({  }, ""), "0", false);
check("test3({  }, \"a\")", () => M.test3({  }, "a"), "0", false);
check("test3({ [\"foo\"]: 1 }, \"\")", () => M.test3({ ["foo"]: 1 }, ""), "0", false);
check("test3({  }, \"hello world\")", () => M.test3({  }, "hello world"), "0", false);
check("test3({ [\"foo\"]: 1 }, \"a\")", () => M.test3({ ["foo"]: 1 }, "a"), "0", false);
check("test3({ [\"foo.bar\"]: 5, [\"a\"]: 2, [\"wat\"]: 13 }, \"\")", () => M.test3({ ["foo.bar"]: 5, ["a"]: 2, ["wat"]: 13 }, ""), "0", false);
check("test3({  }, \"héllo, wörld\")", () => M.test3({  }, "héllo, wörld"), "0", false);
check("test3({ [\"foo\"]: 1 }, \"hello world\")", () => M.test3({ ["foo"]: 1 }, "hello world"), "0", false);
check("test3({ [\"foo.bar\"]: 5, [\"a\"]: 2, [\"wat\"]: 13 }, \"a\")", () => M.test3({ ["foo.bar"]: 5, ["a"]: 2, ["wat"]: 13 }, "a"), "2", false);
check("test3({ [\"\"]: 1, [\"hello world\"]: 5, [\"foo\"]: 0, [\"abcabc\"]: 13, [\"toString\"]: 2 }, \"\")", () => M.test3({ [""]: 1, ["hello world"]: 5, ["foo"]: 0, ["abcabc"]: 13, ["toString"]: 2 }, ""), "1", false);
check("test3({  }, \"abcabc\")", () => M.test3({  }, "abcabc"), "0", false);
check("test3({ [\"foo\"]: 1 }, \"héllo, wörld\")", () => M.test3({ ["foo"]: 1 }, "héllo, wörld"), "0", false);
check("test3({ [\"foo.bar\"]: 5, [\"a\"]: 2, [\"wat\"]: 13 }, \"hello world\")", () => M.test3({ ["foo.bar"]: 5, ["a"]: 2, ["wat"]: 13 }, "hello world"), "0", false);
check("test3({ [\"\"]: 1, [\"hello world\"]: 5, [\"foo\"]: 0, [\"abcabc\"]: 13, [\"toString\"]: 2 }, \"a\")", () => M.test3({ [""]: 1, ["hello world"]: 5, ["foo"]: 0, ["abcabc"]: 13, ["toString"]: 2 }, "a"), "0", false);
check("test3({  }, \"toString\")", () => M.test3({  }, "toString"), "0", false);
check("test3({ [\"foo\"]: 1 }, \"abcabc\")", () => M.test3({ ["foo"]: 1 }, "abcabc"), "0", false);
check("test3({ [\"foo.bar\"]: 5, [\"a\"]: 2, [\"wat\"]: 13 }, \"héllo, wörld\")", () => M.test3({ ["foo.bar"]: 5, ["a"]: 2, ["wat"]: 13 }, "héllo, wörld"), "0", false);
check("test3({ [\"\"]: 1, [\"hello world\"]: 5, [\"foo\"]: 0, [\"abcabc\"]: 13, [\"toString\"]: 2 }, \"hello world\")", () => M.test3({ [""]: 1, ["hello world"]: 5, ["foo"]: 0, ["abcabc"]: 13, ["toString"]: 2 }, "hello world"), "5", false);
check("test3({  }, \"__proto__\")", () => M.test3({  }, "__proto__"), "0", false);
check("test3({ [\"foo\"]: 1 }, \"toString\")", () => M.test3({ ["foo"]: 1 }, "toString"), "0", false);
check("test3({ [\"foo.bar\"]: 5, [\"a\"]: 2, [\"wat\"]: 13 }, \"abcabc\")", () => M.test3({ ["foo.bar"]: 5, ["a"]: 2, ["wat"]: 13 }, "abcabc"), "0", false);
check("test3({ [\"\"]: 1, [\"hello world\"]: 5, [\"foo\"]: 0, [\"abcabc\"]: 13, [\"toString\"]: 2 }, \"héllo, wörld\")", () => M.test3({ [""]: 1, ["hello world"]: 5, ["foo"]: 0, ["abcabc"]: 13, ["toString"]: 2 }, "héllo, wörld"), "0", false);
check("test3({ [\"foo\"]: 1 }, \"__proto__\")", () => M.test3({ ["foo"]: 1 }, "__proto__"), "0", false);
check("test3({ [\"foo.bar\"]: 5, [\"a\"]: 2, [\"wat\"]: 13 }, \"toString\")", () => M.test3({ ["foo.bar"]: 5, ["a"]: 2, ["wat"]: 13 }, "toString"), "0", false);
check("test3({ [\"\"]: 1, [\"hello world\"]: 5, [\"foo\"]: 0, [\"abcabc\"]: 13, [\"toString\"]: 2 }, \"abcabc\")", () => M.test3({ [""]: 1, ["hello world"]: 5, ["foo"]: 0, ["abcabc"]: 13, ["toString"]: 2 }, "abcabc"), "13", false);
check("test3({ [\"foo.bar\"]: 5, [\"a\"]: 2, [\"wat\"]: 13 }, \"__proto__\")", () => M.test3({ ["foo.bar"]: 5, ["a"]: 2, ["wat"]: 13 }, "__proto__"), "0", false);
check("test3({ [\"\"]: 1, [\"hello world\"]: 5, [\"foo\"]: 0, [\"abcabc\"]: 13, [\"toString\"]: 2 }, \"toString\")", () => M.test3({ [""]: 1, ["hello world"]: 5, ["foo"]: 0, ["abcabc"]: 13, ["toString"]: 2 }, "toString"), "2", false);
check("test3({ [\"\"]: 1, [\"hello world\"]: 5, [\"foo\"]: 0, [\"abcabc\"]: 13, [\"toString\"]: 2 }, \"__proto__\")", () => M.test3({ [""]: 1, ["hello world"]: 5, ["foo"]: 0, ["abcabc"]: 13, ["toString"]: 2 }, "__proto__"), "0", false);
check("test4(false)", () => M.test4(false), "none", false);
check("test4(true)", () => M.test4(true), "0", false);
check("test6(0, 0)", () => M.test6(0, 0), "0", false);
check("test6(0, 2)", () => M.test6(0, 2), "2", false);
check("test6(1, 1)", () => M.test6(1, 1), "1", false);
check("test6(2, 0)", () => M.test6(2, 0), "2", false);
check("test6(0, 13)", () => M.test6(0, 13), "2", false);
check("test6(1, 5)", () => M.test6(1, 5), "2", false);
check("test6(2, 2)", () => M.test6(2, 2), "2", false);
check("test6(5, 1)", () => M.test6(5, 1), "1", false);
check("test6(13, 0)", () => M.test6(13, 0), "13", false);
check("test6(2, 13)", () => M.test6(2, 13), "2", false);
check("test6(5, 5)", () => M.test6(5, 5), "2", false);
check("test6(13, 2)", () => M.test6(13, 2), "2", false);
check("test6(13, 13)", () => M.test6(13, 13), "2", false);

console.log(`OptionUnbox-pbo.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
