// Differential checks of OrderingCmp-faithful.js against Lean, generated by leanscript --check
import * as M from "./OrderingCmp-faithful.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
// a recursive union: as `showUnion`, the fields marked in `rec[tag]` (the type itself) printed
// the same way, one level less deep (`…` at depth 0, as `showExpr` cuts it in Lean)
function showTree(v, rec, d) {
  if (d === 0) return "…";
  if (typeof v === "number") return v + "()";
  const r = rec[v.tag] || [];
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++)
    fs.push(r[i - 1] ? showTree(v["_" + i], rec, d - 1) : show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("instBEqShade$beq(0, 0)", () => M.instBEqShade$beq(0, 0), "true", false);
check("instBEqShade$beq(0, 1)", () => M.instBEqShade$beq(0, 1), "false", false);
check("instBEqShade$beq(1, 0)", () => M.instBEqShade$beq(1, 0), "false", false);
check("instBEqShade$beq(0, 2)", () => M.instBEqShade$beq(0, 2), "false", false);
check("instBEqShade$beq(1, 1)", () => M.instBEqShade$beq(1, 1), "true", false);
check("instBEqShade$beq(2, 0)", () => M.instBEqShade$beq(2, 0), "false", false);
check("instBEqShade$beq(1, 2)", () => M.instBEqShade$beq(1, 2), "false", false);
check("instBEqShade$beq(2, 1)", () => M.instBEqShade$beq(2, 1), "false", false);
check("instBEqShade$beq(2, 2)", () => M.instBEqShade$beq(2, 2), "true", false);
check("natLt(0n, 0n)", () => M.natLt(0n, 0n), "false", false);
check("natLt(0n, 2n)", () => M.natLt(0n, 2n), "true", false);
check("natLt(1n, 1n)", () => M.natLt(1n, 1n), "false", false);
check("natLt(2n, 0n)", () => M.natLt(2n, 0n), "false", false);
check("natLt(0n, 13n)", () => M.natLt(0n, 13n), "true", false);
check("natLt(1n, 5n)", () => M.natLt(1n, 5n), "true", false);
check("natLt(2n, 2n)", () => M.natLt(2n, 2n), "false", false);
check("natLt(5n, 1n)", () => M.natLt(5n, 1n), "false", false);
check("natLt(13n, 0n)", () => M.natLt(13n, 0n), "false", false);
check("natLt(2n, 13n)", () => M.natLt(2n, 13n), "true", false);
check("natLt(5n, 5n)", () => M.natLt(5n, 5n), "false", false);
check("natLt(13n, 2n)", () => M.natLt(13n, 2n), "false", false);
check("natLt(13n, 13n)", () => M.natLt(13n, 13n), "false", false);
check("natGt(0n, 0n)", () => M.natGt(0n, 0n), "false", false);
check("natGt(0n, 2n)", () => M.natGt(0n, 2n), "false", false);
check("natGt(1n, 1n)", () => M.natGt(1n, 1n), "false", false);
check("natGt(2n, 0n)", () => M.natGt(2n, 0n), "true", false);
check("natGt(0n, 13n)", () => M.natGt(0n, 13n), "false", false);
check("natGt(1n, 5n)", () => M.natGt(1n, 5n), "false", false);
check("natGt(2n, 2n)", () => M.natGt(2n, 2n), "false", false);
check("natGt(5n, 1n)", () => M.natGt(5n, 1n), "true", false);
check("natGt(13n, 0n)", () => M.natGt(13n, 0n), "true", false);
check("natGt(2n, 13n)", () => M.natGt(2n, 13n), "false", false);
check("natGt(5n, 5n)", () => M.natGt(5n, 5n), "false", false);
check("natGt(13n, 2n)", () => M.natGt(13n, 2n), "true", false);
check("natGt(13n, 13n)", () => M.natGt(13n, 13n), "false", false);
check("natNe(0n, 0n)", () => M.natNe(0n, 0n), "false", false);
check("natNe(0n, 2n)", () => M.natNe(0n, 2n), "true", false);
check("natNe(1n, 1n)", () => M.natNe(1n, 1n), "false", false);
check("natNe(2n, 0n)", () => M.natNe(2n, 0n), "true", false);
check("natNe(0n, 13n)", () => M.natNe(0n, 13n), "true", false);
check("natNe(1n, 5n)", () => M.natNe(1n, 5n), "true", false);
check("natNe(2n, 2n)", () => M.natNe(2n, 2n), "false", false);
check("natNe(5n, 1n)", () => M.natNe(5n, 1n), "true", false);
check("natNe(13n, 0n)", () => M.natNe(13n, 0n), "true", false);
check("natNe(2n, 13n)", () => M.natNe(2n, 13n), "true", false);
check("natNe(5n, 5n)", () => M.natNe(5n, 5n), "false", false);
check("natNe(13n, 2n)", () => M.natNe(13n, 2n), "true", false);
check("natNe(13n, 13n)", () => M.natNe(13n, 13n), "false", false);
check("natIsLE(0n, 0n)", () => M.natIsLE(0n, 0n), "true", false);
check("natIsLE(0n, 2n)", () => M.natIsLE(0n, 2n), "true", false);
check("natIsLE(1n, 1n)", () => M.natIsLE(1n, 1n), "true", false);
check("natIsLE(2n, 0n)", () => M.natIsLE(2n, 0n), "false", false);
check("natIsLE(0n, 13n)", () => M.natIsLE(0n, 13n), "true", false);
check("natIsLE(1n, 5n)", () => M.natIsLE(1n, 5n), "true", false);
check("natIsLE(2n, 2n)", () => M.natIsLE(2n, 2n), "true", false);
check("natIsLE(5n, 1n)", () => M.natIsLE(5n, 1n), "false", false);
check("natIsLE(13n, 0n)", () => M.natIsLE(13n, 0n), "false", false);
check("natIsLE(2n, 13n)", () => M.natIsLE(2n, 13n), "true", false);
check("natIsLE(5n, 5n)", () => M.natIsLE(5n, 5n), "true", false);
check("natIsLE(13n, 2n)", () => M.natIsLE(13n, 2n), "false", false);
check("natIsLE(13n, 13n)", () => M.natIsLE(13n, 13n), "true", false);
check("intLt(-7n, -7n)", () => M.intLt(-7n, -7n), "false", false);
check("intLt(-7n, 1n)", () => M.intLt(-7n, 1n), "true", false);
check("intLt(-1n, 0n)", () => M.intLt(-1n, 0n), "true", false);
check("intLt(0n, -1n)", () => M.intLt(0n, -1n), "false", false);
check("intLt(1n, -7n)", () => M.intLt(1n, -7n), "false", false);
check("intLt(-7n, 12n)", () => M.intLt(-7n, 12n), "true", false);
check("intLt(-1n, 3n)", () => M.intLt(-1n, 3n), "true", false);
check("intLt(0n, 2n)", () => M.intLt(0n, 2n), "true", false);
check("intLt(1n, 1n)", () => M.intLt(1n, 1n), "false", false);
check("intLt(2n, 0n)", () => M.intLt(2n, 0n), "false", false);
check("intLt(3n, -1n)", () => M.intLt(3n, -1n), "false", false);
check("intLt(12n, -7n)", () => M.intLt(12n, -7n), "false", false);
check("intLt(1n, 12n)", () => M.intLt(1n, 12n), "true", false);
check("intLt(2n, 3n)", () => M.intLt(2n, 3n), "true", false);
check("intLt(3n, 2n)", () => M.intLt(3n, 2n), "false", false);
check("intLt(12n, 1n)", () => M.intLt(12n, 1n), "false", false);
check("intLt(12n, 12n)", () => M.intLt(12n, 12n), "false", false);
check("intNe(-7n, -7n)", () => M.intNe(-7n, -7n), "false", false);
check("intNe(-7n, 1n)", () => M.intNe(-7n, 1n), "true", false);
check("intNe(-1n, 0n)", () => M.intNe(-1n, 0n), "true", false);
check("intNe(0n, -1n)", () => M.intNe(0n, -1n), "true", false);
check("intNe(1n, -7n)", () => M.intNe(1n, -7n), "true", false);
check("intNe(-7n, 12n)", () => M.intNe(-7n, 12n), "true", false);
check("intNe(-1n, 3n)", () => M.intNe(-1n, 3n), "true", false);
check("intNe(0n, 2n)", () => M.intNe(0n, 2n), "true", false);
check("intNe(1n, 1n)", () => M.intNe(1n, 1n), "false", false);
check("intNe(2n, 0n)", () => M.intNe(2n, 0n), "true", false);
check("intNe(3n, -1n)", () => M.intNe(3n, -1n), "true", false);
check("intNe(12n, -7n)", () => M.intNe(12n, -7n), "true", false);
check("intNe(1n, 12n)", () => M.intNe(1n, 12n), "true", false);
check("intNe(2n, 3n)", () => M.intNe(2n, 3n), "true", false);
check("intNe(3n, 2n)", () => M.intNe(3n, 2n), "true", false);
check("intNe(12n, 1n)", () => M.intNe(12n, 1n), "true", false);
check("intNe(12n, 12n)", () => M.intNe(12n, 12n), "false", false);
check("natCompare(0n, 0n)", () => M.natCompare(0n, 0n), "0", false);
check("natCompare(0n, 2n)", () => M.natCompare(0n, 2n), "-1", false);
check("natCompare(1n, 1n)", () => M.natCompare(1n, 1n), "0", false);
check("natCompare(2n, 0n)", () => M.natCompare(2n, 0n), "1", false);
check("natCompare(0n, 13n)", () => M.natCompare(0n, 13n), "-1", false);
check("natCompare(1n, 5n)", () => M.natCompare(1n, 5n), "-1", false);
check("natCompare(2n, 2n)", () => M.natCompare(2n, 2n), "0", false);
check("natCompare(5n, 1n)", () => M.natCompare(5n, 1n), "1", false);
check("natCompare(13n, 0n)", () => M.natCompare(13n, 0n), "1", false);
check("natCompare(2n, 13n)", () => M.natCompare(2n, 13n), "-1", false);
check("natCompare(5n, 5n)", () => M.natCompare(5n, 5n), "0", false);
check("natCompare(13n, 2n)", () => M.natCompare(13n, 2n), "1", false);
check("natCompare(13n, 13n)", () => M.natCompare(13n, 13n), "0", false);
check("shadeNe(0, 0)", () => M.shadeNe(0, 0), "false", false);
check("shadeNe(0, 1)", () => M.shadeNe(0, 1), "true", false);
check("shadeNe(1, 0)", () => M.shadeNe(1, 0), "true", false);
check("shadeNe(0, 2)", () => M.shadeNe(0, 2), "true", false);
check("shadeNe(1, 1)", () => M.shadeNe(1, 1), "false", false);
check("shadeNe(2, 0)", () => M.shadeNe(2, 0), "true", false);
check("shadeNe(1, 2)", () => M.shadeNe(1, 2), "true", false);
check("shadeNe(2, 1)", () => M.shadeNe(2, 1), "true", false);
check("shadeNe(2, 2)", () => M.shadeNe(2, 2), "false", false);
check("shadeEq(0, 0)", () => M.shadeEq(0, 0), "true", false);
check("shadeEq(0, 1)", () => M.shadeEq(0, 1), "false", false);
check("shadeEq(1, 0)", () => M.shadeEq(1, 0), "false", false);
check("shadeEq(0, 2)", () => M.shadeEq(0, 2), "false", false);
check("shadeEq(1, 1)", () => M.shadeEq(1, 1), "true", false);
check("shadeEq(2, 0)", () => M.shadeEq(2, 0), "false", false);
check("shadeEq(1, 2)", () => M.shadeEq(1, 2), "false", false);
check("shadeEq(2, 1)", () => M.shadeEq(2, 1), "false", false);
check("shadeEq(2, 2)", () => M.shadeEq(2, 2), "true", false);

console.log(`OrderingCmp-faithful.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
