// JavaScript of Tests/SnapshotsMy/PlatformInts.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

import {
  uint53__lean_uint64_add,
  uint53__lean_uint64_mul,
  uint53__lean_nat_add,
  uint53__lean_uint64_of_nat__UInt64_ofNat,
  uint53__lean_uint64_lor,
  uint53__lean_uint64_land,
  uint53__lean_uint64_xor,
  uint53__lean_uint64_complement,
  uint53__lean_uint64_mod,
  uint53__lean_uint64_to_uint32,
  uint53__lean_uint64_to_uint8,
  int53__lean_int64_add,
  int53__lean_int64_mul,
  int53__lean_int_sub,
  int53__lean_int64_of_int,
  int53__lean_int64_mod,
  int53__lean_int64_lor,
  int53__lean_int64_land,
  int53__lean_int64_xor,
  int53__lean_int64_complement,
  int53__lean_int64_sub,
  uint53__int53__lean_int64_of_nat,
} from "../../runtime.js";

/**
 * `usizeLit`
 * @param {uint53(number)} a
 * @returns {uint53(number)}
 */
export const usizeLit = (a) =>
  uint53__lean_uint64_add(uint53__lean_uint64_mul(a, 3), 7);

/**
 * `usizeToNat`
 * @param {uint53(number)} a
 * @returns {uint53(number)}
 */
export const usizeToNat = (a) => uint53__lean_nat_add(a, 1);

/**
 * `usizeOfNat`
 * @param {uint53(number)} n
 * @returns {uint53(number)}
 */
export const usizeOfNat = (n) =>
  uint53__lean_uint64_mul(uint53__lean_uint64_of_nat__UInt64_ofNat(n), 2);

/**
 * `natToUSize`
 * @param {uint53(number)} n
 * @returns {uint53(number)}
 */
export const natToUSize = (n) => uint53__lean_uint64_of_nat__UInt64_ofNat(n);

/**
 * `usizeBits`
 * @param {uint53(number)} a
 * @param {uint53(number)} b
 * @returns {uint53(number)}
 */
export const usizeBits = (a, b) =>
  uint53__lean_uint64_lor(
    uint53__lean_uint64_land(a, b),
    uint53__lean_uint64_xor(a, b),
  );

/**
 * `usizeNot`
 * @param {uint53(number)} a
 * @returns {uint53(number)}
 */
export const usizeNot = (a) => uint53__lean_uint64_complement(a);

/**
 * `usizeMod`
 * @param {uint53(number)} a
 * @param {uint53(number)} b
 * @returns {uint53(number)}
 */
export const usizeMod = (a, b) => uint53__lean_uint64_mod(a, b);

/**
 * `usizeToUInt64`
 * @param {uint53(number)} a
 * @returns {uint53(number)}
 */
export const usizeToUInt64 = (a) => uint53__lean_uint64_add(a, 1);

/**
 * `uint64ToUSize`
 * @param {uint53(number)} x
 * @returns {uint53(number)}
 */
export const uint64ToUSize = (x) => uint53__lean_uint64_add(x, 1);

/**
 * `uint32ToUSize`
 * @param {uint32} x
 * @returns {uint53(number)}
 */
export const uint32ToUSize = (x) => x;

/**
 * `usizeToUInt32`
 * @param {uint53(number)} a
 * @returns {uint32}
 */
export const usizeToUInt32 = (a) => uint53__lean_uint64_to_uint32(a);

/**
 * `usizeToUInt8`
 * @param {uint53(number)} a
 * @returns {uint8}
 */
export const usizeToUInt8 = (a) => uint53__lean_uint64_to_uint8(a);

/**
 * `usizeMax`
 * @param {uint53(number)} a
 * @param {uint53(number)} b
 * @returns {uint53(number)}
 */
export const usizeMax = (a, b) => (a < b ? b : a);

/**
 * `usizeClamp`
 * @param {uint53(number)} a
 * @returns {uint53(number)}
 */
export const usizeClamp = (a) => (a <= 10 ? a : 10);

/**
 * `isizeLit`
 * @param {int53(number)} a
 * @returns {int53(number)}
 */
export const isizeLit = (a) =>
  int53__lean_int64_add(int53__lean_int64_mul(a, -3), 7);

/**
 * `isizeToInt`
 * @param {int53(number)} a
 * @returns {int53(number)}
 */
export const isizeToInt = (a) => int53__lean_int_sub(a, 1);

/**
 * `isizeOfInt`
 * @param {int53(number)} i
 * @returns {int53(number)}
 */
export const isizeOfInt = (i) => int53__lean_int64_of_int(i);

/**
 * `isizeMod`
 * @param {int53(number)} a
 * @param {int53(number)} b
 * @returns {int53(number)}
 */
export const isizeMod = (a, b) => int53__lean_int64_mod(a, b);

/**
 * `isizeBits`
 * @param {int53(number)} a
 * @param {int53(number)} b
 * @returns {int53(number)}
 */
export const isizeBits = (a, b) =>
  int53__lean_int64_lor(
    int53__lean_int64_land(a, b),
    int53__lean_int64_xor(a, int53__lean_int64_complement(b)),
  );

/**
 * `isizeToInt64`
 * @param {int53(number)} a
 * @returns {int53(number)}
 */
export const isizeToInt64 = (a) => int53__lean_int64_sub(a, 1);

/**
 * `int64ToISize`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const int64ToISize = (x) => int53__lean_int64_add(x, 1);

/**
 * `isizeSign`
 * @param {int53(number)} a
 * @returns {int53(number)}
 */
export const isizeSign = (a) => {
  if (a < 0) {
    return -1;
  }
  return a === 0 ? 0 : 1;
};

/**
 * `isizeAbsDiff`
 * @param {int53(number)} a
 * @param {int53(number)} b
 * @returns {int53(number)}
 */
export const isizeAbsDiff = (a, b) =>
  a <= b ? int53__lean_int64_sub(b, a) : int53__lean_int64_sub(a, b);

/**
 * `usizeSumTo`
 * @param {uint53(number)} n
 * @param {uint53(number)} acc
 * @returns {uint53(number)}
 */
export const usizeSumTo = (n, acc) => {
  let p$1 = acc;
  let j$2 = n;
  while (true) {
    if (j$2 === 0) {
      return p$1;
    }
    j$2--;
    p$1 = uint53__lean_uint64_add(
      p$1,
      uint53__lean_uint64_of_nat__UInt64_ofNat(j$2),
    );
  }
};

/**
 * `isizeSubTo`
 * @param {uint53(number)} n
 * @param {int53(number)} acc
 * @returns {int53(number)}
 */
export const isizeSubTo = (n, acc) => {
  let p$1 = acc;
  let j$2 = n;
  while (true) {
    if (j$2 === 0) {
      return p$1;
    }
    j$2--;
    p$1 = int53__lean_int64_sub(p$1, uint53__int53__lean_int64_of_nat(j$2));
  }
};
