// Differential checks of PrimOpNumberBottom-faithful.js against Lean, generated by leanscript --check
import * as M from "./PrimOpNumberBottom-faithful.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
// a recursive union: as `showUnion`, the fields marked in `rec[tag]` (the type itself) printed
// the same way, one level less deep (`…` at depth 0, as `showExpr` cuts it in Lean)
function showTree(v, rec, d) {
  if (d === 0) return "…";
  if (typeof v === "number") return v + "()";
  const r = rec[v.tag] || [];
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++)
    fs.push(r[i - 1] ? showTree(v["_" + i], rec, d - 1) : show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("fn(0n)", () => M.fn(0n), "0", true);
check("fn(1n)", () => M.fn(1n), "0", true);
check("fn(2n)", () => M.fn(2n), "0", true);
check("fn(5n)", () => M.fn(5n), "0", true);
check("fn(13n)", () => M.fn(13n), "0", true);
check("bottom", () => M.bottom, "18442240474082181120", true);
check("test1", () => M.test1, "4637440978796412928", true);
check("test2", () => M.test2, "4635892866424504320", true);
check("test3", () => M.test3, "4652504288096944128", true);
check("test4", () => M.test4, "4621256167635550208", true);
check("test5", () => M.test5, "4637440978796412928", true);
check("test6", () => M.test6, "4635892866424504320", true);
check("test7", () => M.test7, "4652504288096944128", true);
check("test8", () => M.test8, "4621256167635550208", true);
check("selNegInf(0)", () => M.selNegInf(0), "0", true);
check("selNegInf(0.5)", () => M.selNegInf(0.5), "4602678819172646912", true);
check("selNegInf(1)", () => M.selNegInf(1), "4607182418800017408", true);
check("selNegInf(2)", () => M.selNegInf(2), "4611686018427387904", true);
check("selNegInf(3)", () => M.selNegInf(3), "4613937818241073152", true);
check("selNegInf(2.25)", () => M.selNegInf(2.25), "4612248968380809216", true);
check("selNegInf(30)", () => M.selNegInf(30), "4629137466983448576", true);
check("selNegInf(-1.5)", () => M.selNegInf(-1.5), "13832806255468478464", true);
check("selPosInf(0)", () => M.selPosInf(0), "0", true);
check("selPosInf(0.5)", () => M.selPosInf(0.5), "4602678819172646912", true);
check("selPosInf(1)", () => M.selPosInf(1), "4607182418800017408", true);
check("selPosInf(2)", () => M.selPosInf(2), "4611686018427387904", true);
check("selPosInf(3)", () => M.selPosInf(3), "4613937818241073152", true);
check("selPosInf(2.25)", () => M.selPosInf(2.25), "4612248968380809216", true);
check("selPosInf(30)", () => M.selPosInf(30), "4629137466983448576", true);
check("selPosInf(-1.5)", () => M.selPosInf(-1.5), "13832806255468478464", true);
check("selFive(0)", () => M.selFive(0), "0", true);
check("selFive(0.5)", () => M.selFive(0.5), "4602678819172646912", true);
check("selFive(1)", () => M.selFive(1), "4607182418800017408", true);
check("selFive(2)", () => M.selFive(2), "4611686018427387904", true);
check("selFive(3)", () => M.selFive(3), "4613937818241073152", true);
check("selFive(2.25)", () => M.selFive(2.25), "4612248968380809216", true);
check("selFive(30)", () => M.selFive(30), "4629137466983448576", true);
check("selFive(-1.5)", () => M.selFive(-1.5), "13832806255468478464", true);
check("selFiveFlip(0)", () => M.selFiveFlip(0), "4617315517961601024", true);
check("selFiveFlip(0.5)", () => M.selFiveFlip(0.5), "4617315517961601024", true);
check("selFiveFlip(1)", () => M.selFiveFlip(1), "4617315517961601024", true);
check("selFiveFlip(2)", () => M.selFiveFlip(2), "4617315517961601024", true);
check("selFiveFlip(3)", () => M.selFiveFlip(3), "4617315517961601024", true);
check("selFiveFlip(2.25)", () => M.selFiveFlip(2.25), "4617315517961601024", true);
check("selFiveFlip(30)", () => M.selFiveFlip(30), "4617315517961601024", true);
check("selFiveFlip(-1.5)", () => M.selFiveFlip(-1.5), "4617315517961601024", true);
check("selNegHalf(0)", () => M.selNegHalf(0), "0", true);
check("selNegHalf(0.5)", () => M.selNegHalf(0.5), "4602678819172646912", true);
check("selNegHalf(1)", () => M.selNegHalf(1), "4607182418800017408", true);
check("selNegHalf(2)", () => M.selNegHalf(2), "4611686018427387904", true);
check("selNegHalf(3)", () => M.selNegHalf(3), "4613937818241073152", true);
check("selNegHalf(2.25)", () => M.selNegHalf(2.25), "4612248968380809216", true);
check("selNegHalf(30)", () => M.selNegHalf(30), "4629137466983448576", true);
check("selNegHalf(-1.5)", () => M.selNegHalf(-1.5), "13832806255468478464", true);
check("keepZero(0)", () => M.keepZero(0), "0", true);
check("keepZero(0.5)", () => M.keepZero(0.5), "4602678819172646912", true);
check("keepZero(1)", () => M.keepZero(1), "4607182418800017408", true);
check("keepZero(2)", () => M.keepZero(2), "4611686018427387904", true);
check("keepZero(3)", () => M.keepZero(3), "4613937818241073152", true);
check("keepZero(2.25)", () => M.keepZero(2.25), "4612248968380809216", true);
check("keepZero(30)", () => M.keepZero(30), "4629137466983448576", true);
check("keepZero(-1.5)", () => M.keepZero(-1.5), "13832806255468478464", true);
check("keepOther(0)", () => M.keepOther(0), "0", true);
check("keepOther(0.5)", () => M.keepOther(0.5), "4602678819172646912", true);
check("keepOther(1)", () => M.keepOther(1), "4607182418800017408", true);
check("keepOther(2)", () => M.keepOther(2), "4611686018427387904", true);
check("keepOther(3)", () => M.keepOther(3), "4613937818241073152", true);
check("keepOther(2.25)", () => M.keepOther(2.25), "4612248968380809216", true);
check("keepOther(30)", () => M.keepOther(30), "4629137466983448576", true);
check("keepOther(-1.5)", () => M.keepOther(-1.5), "13832806255468478464", true);
check("keepVars(0, 0)", () => M.keepVars(0, 0), "0", true);
check("keepVars(0.5, 0.5)", () => M.keepVars(0.5, 0.5), "4602678819172646912", true);
check("keepVars(0, 2)", () => M.keepVars(0, 2), "0", true);
check("keepVars(2, 0)", () => M.keepVars(2, 0), "4611686018427387904", true);
check("keepVars(1, 1)", () => M.keepVars(1, 1), "4607182418800017408", true);
check("keepVars(0.5, 3)", () => M.keepVars(0.5, 3), "4602678819172646912", true);
check("keepVars(3, 0.5)", () => M.keepVars(3, 0.5), "4613937818241073152", true);
check("keepVars(0, 30)", () => M.keepVars(0, 30), "0", true);
check("keepVars(2, 2)", () => M.keepVars(2, 2), "4611686018427387904", true);
check("keepVars(30, 0)", () => M.keepVars(30, 0), "4629137466983448576", true);
check("keepVars(1, 2.25)", () => M.keepVars(1, 2.25), "4607182418800017408", true);
check("keepVars(2.25, 1)", () => M.keepVars(2.25, 1), "4612248968380809216", true);
check("keepVars(0.5, -1.5)", () => M.keepVars(0.5, -1.5), "4602678819172646912", true);
check("keepVars(3, 3)", () => M.keepVars(3, 3), "4613937818241073152", true);
check("keepVars(-1.5, 0.5)", () => M.keepVars(-1.5, 0.5), "13832806255468478464", true);
check("keepVars(2, 30)", () => M.keepVars(2, 30), "4611686018427387904", true);
check("keepVars(30, 2)", () => M.keepVars(30, 2), "4629137466983448576", true);
check("keepVars(2.25, 2.25)", () => M.keepVars(2.25, 2.25), "4612248968380809216", true);
check("keepVars(3, -1.5)", () => M.keepVars(3, -1.5), "4613937818241073152", true);
check("keepVars(-1.5, 3)", () => M.keepVars(-1.5, 3), "13832806255468478464", true);
check("keepVars(30, 30)", () => M.keepVars(30, 30), "4629137466983448576", true);
check("keepVars(-1.5, -1.5)", () => M.keepVars(-1.5, -1.5), "13832806255468478464", true);

console.log(`PrimOpNumberBottom-faithful.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
