// Differential checks of PrimOpIntEqSelect-faithful.js against Lean, generated by leanscript --check
import * as M from "./PrimOpIntEqSelect-faithful.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
// a recursive union: as `showUnion`, the fields marked in `rec[tag]` (the type itself) printed
// the same way, one level less deep (`…` at depth 0, as `showExpr` cuts it in Lean)
function showTree(v, rec, d) {
  if (d === 0) return "…";
  if (typeof v === "number") return v + "()";
  const r = rec[v.tag] || [];
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++)
    fs.push(r[i - 1] ? showTree(v["_" + i], rec, d - 1) : show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("selInt(-7n)", () => M.selInt(-7n), "-7", false);
check("selInt(-1n)", () => M.selInt(-1n), "-1", false);
check("selInt(0n)", () => M.selInt(0n), "0", false);
check("selInt(1n)", () => M.selInt(1n), "1", false);
check("selInt(2n)", () => M.selInt(2n), "2", false);
check("selInt(3n)", () => M.selInt(3n), "3", false);
check("selInt(12n)", () => M.selInt(12n), "12", false);
check("selIntEq(-7n)", () => M.selIntEq(-7n), "-7", false);
check("selIntEq(-1n)", () => M.selIntEq(-1n), "-1", false);
check("selIntEq(0n)", () => M.selIntEq(0n), "0", false);
check("selIntEq(1n)", () => M.selIntEq(1n), "1", false);
check("selIntEq(2n)", () => M.selIntEq(2n), "2", false);
check("selIntEq(3n)", () => M.selIntEq(3n), "3", false);
check("selIntEq(12n)", () => M.selIntEq(12n), "12", false);
check("selIntFlip(-7n)", () => M.selIntFlip(-7n), "5", false);
check("selIntFlip(-1n)", () => M.selIntFlip(-1n), "5", false);
check("selIntFlip(0n)", () => M.selIntFlip(0n), "5", false);
check("selIntFlip(1n)", () => M.selIntFlip(1n), "5", false);
check("selIntFlip(2n)", () => M.selIntFlip(2n), "5", false);
check("selIntFlip(3n)", () => M.selIntFlip(3n), "5", false);
check("selIntFlip(12n)", () => M.selIntFlip(12n), "5", false);
check("selIntVars(-7n, -7n)", () => M.selIntVars(-7n, -7n), "-7", false);
check("selIntVars(-7n, 1n)", () => M.selIntVars(-7n, 1n), "-7", false);
check("selIntVars(-1n, 0n)", () => M.selIntVars(-1n, 0n), "-1", false);
check("selIntVars(0n, -1n)", () => M.selIntVars(0n, -1n), "0", false);
check("selIntVars(1n, -7n)", () => M.selIntVars(1n, -7n), "1", false);
check("selIntVars(-7n, 12n)", () => M.selIntVars(-7n, 12n), "-7", false);
check("selIntVars(-1n, 3n)", () => M.selIntVars(-1n, 3n), "-1", false);
check("selIntVars(0n, 2n)", () => M.selIntVars(0n, 2n), "0", false);
check("selIntVars(1n, 1n)", () => M.selIntVars(1n, 1n), "1", false);
check("selIntVars(2n, 0n)", () => M.selIntVars(2n, 0n), "2", false);
check("selIntVars(3n, -1n)", () => M.selIntVars(3n, -1n), "3", false);
check("selIntVars(12n, -7n)", () => M.selIntVars(12n, -7n), "12", false);
check("selIntVars(1n, 12n)", () => M.selIntVars(1n, 12n), "1", false);
check("selIntVars(2n, 3n)", () => M.selIntVars(2n, 3n), "2", false);
check("selIntVars(3n, 2n)", () => M.selIntVars(3n, 2n), "3", false);
check("selIntVars(12n, 1n)", () => M.selIntVars(12n, 1n), "12", false);
check("selIntVars(12n, 12n)", () => M.selIntVars(12n, 12n), "12", false);
check("selNat(0n)", () => M.selNat(0n), "0", false);
check("selNat(1n)", () => M.selNat(1n), "1", false);
check("selNat(2n)", () => M.selNat(2n), "2", false);
check("selNat(5n)", () => M.selNat(5n), "5", false);
check("selNat(13n)", () => M.selNat(13n), "13", false);
check("selString(\"\")", () => M.selString(""), "", false);
check("selString(\"a\")", () => M.selString("a"), "a", false);
check("selString(\"hello world\")", () => M.selString("hello world"), "hello world", false);
check("selString(\"héllo, wörld\")", () => M.selString("héllo, wörld"), "héllo, wörld", false);
check("selString(\"abcabc\")", () => M.selString("abcabc"), "abcabc", false);
check("selUInt8(0)", () => M.selUInt8(0), "0", false);
check("selUInt8(1)", () => M.selUInt8(1), "1", false);
check("selUInt8(2)", () => M.selUInt8(2), "2", false);
check("selUInt8(5)", () => M.selUInt8(5), "5", false);
check("selUInt8(13)", () => M.selUInt8(13), "13", false);
check("selUInt8(255)", () => M.selUInt8(255), "255", false);
check("selInt32(-7)", () => M.selInt32(-7), "-7", false);
check("selInt32(-1)", () => M.selInt32(-1), "-1", false);
check("selInt32(0)", () => M.selInt32(0), "0", false);
check("selInt32(3)", () => M.selInt32(3), "3", false);
check("selInt32(12)", () => M.selInt32(12), "12", false);
check("selInt32(-2147483648)", () => M.selInt32(-2147483648), "-2147483648", false);
check("selInt32(2147483647)", () => M.selInt32(2147483647), "2147483647", false);
check("selCall((x) => x + 1n, -7n)", () => M.selCall((x) => x + 1n, -7n), "-6", false);
check("selCall((x) => x + 1n, -1n)", () => M.selCall((x) => x + 1n, -1n), "0", false);
check("selCall((x) => 2n - x, -7n)", () => M.selCall((x) => 2n - x, -7n), "9", false);
check("selCall((x) => x + 1n, 0n)", () => M.selCall((x) => x + 1n, 0n), "1", false);
check("selCall((x) => 2n - x, -1n)", () => M.selCall((x) => 2n - x, -1n), "3", false);
check("selCall((x) => x + 1n, 1n)", () => M.selCall((x) => x + 1n, 1n), "2", false);
check("selCall((x) => 2n - x, 0n)", () => M.selCall((x) => 2n - x, 0n), "2", false);
check("selCall((x) => x + 1n, 2n)", () => M.selCall((x) => x + 1n, 2n), "3", false);
check("selCall((x) => 2n - x, 1n)", () => M.selCall((x) => 2n - x, 1n), "1", false);
check("selCall((x) => x + 1n, 3n)", () => M.selCall((x) => x + 1n, 3n), "4", false);
check("selCall((x) => 2n - x, 2n)", () => M.selCall((x) => 2n - x, 2n), "0", false);
check("selCall((x) => x + 1n, 12n)", () => M.selCall((x) => x + 1n, 12n), "13", false);
check("selCall((x) => 2n - x, 3n)", () => M.selCall((x) => 2n - x, 3n), "-1", false);
check("selCall((x) => 2n - x, 12n)", () => M.selCall((x) => 2n - x, 12n), "-10", false);
check("keepOther(-7n)", () => M.keepOther(-7n), "-7", false);
check("keepOther(-1n)", () => M.keepOther(-1n), "-1", false);
check("keepOther(0n)", () => M.keepOther(0n), "0", false);
check("keepOther(1n)", () => M.keepOther(1n), "1", false);
check("keepOther(2n)", () => M.keepOther(2n), "2", false);
check("keepOther(3n)", () => M.keepOther(3n), "3", false);
check("keepOther(12n)", () => M.keepOther(12n), "12", false);
check("keepFloat(0)", () => M.keepFloat(0), "0", true);
check("keepFloat(0.5)", () => M.keepFloat(0.5), "4602678819172646912", true);
check("keepFloat(1)", () => M.keepFloat(1), "4607182418800017408", true);
check("keepFloat(2)", () => M.keepFloat(2), "4611686018427387904", true);
check("keepFloat(3)", () => M.keepFloat(3), "4613937818241073152", true);
check("keepFloat(2.25)", () => M.keepFloat(2.25), "4612248968380809216", true);
check("keepFloat(30)", () => M.keepFloat(30), "4629137466983448576", true);
check("keepFloat(-1.5)", () => M.keepFloat(-1.5), "13832806255468478464", true);
check("origin", () => M.origin, "{3, 4}", false);
check("originSum(-7n)", () => M.originSum(-7n), "-17", false);
check("originSum(-1n)", () => M.originSum(-1n), "1", false);
check("originSum(0n)", () => M.originSum(0n), "4", false);
check("originSum(1n)", () => M.originSum(1n), "7", false);
check("originSum(2n)", () => M.originSum(2n), "10", false);
check("originSum(3n)", () => M.originSum(3n), "13", false);
check("originSum(12n)", () => M.originSum(12n), "40", false);
check("arr", () => M.arr, "#[1, 2, 3]", false);

console.log(`PrimOpIntEqSelect-faithful.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
