// JavaScript of Tests/SnapshotsMy/RecData.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// imports not found (left out): LeanScript.Term.Elab
// not translated:
//   RecData.Prog.Δ: LeanScript: a field of the constructor `LeanScript.DSig.cons` has the type LeanScript.Mems ks (k + 1) which depends on the value of an earlier field (or of the argument of a dependent arrow) in a way that cannot be erased: only arrows, type arguments, and inductive types with one constructor of one field besides proofs (`Fin n`, `Vector α n`, `{x // p x}`) are erased to a non-dependent type
//   RecData.Prog.block3: LeanScript: a field of the constructor `LeanScript.Mems.cons` has the type LeanScript.Decl [0, 0, 0] (1 + 1) g which depends on the value of an earlier field (or of the argument of a dependent arrow) in a way that cannot be erased: only arrows, type arguments, and inductive types with one constructor of one field besides proofs (`Fin n`, `Vector α n`, `{x // p x}`) are erased to a non-dependent type
//   RecData.Prog.myList: LeanScript: the recursive type LeanScript.Ref is not declared in the signature `RecData.Prog`; add it to `leanscript_signature RecData.Prog`
//   RecData.Prog.rose: LeanScript: the recursive type LeanScript.Ref is not declared in the signature `RecData.Prog`; add it to `leanscript_signature RecData.Prog`
//   RecData.Prog.block2: LeanScript: a field of the constructor `LeanScript.Mems.cons` has the type LeanScript.Decl [0, 0] (0 + 1) g which depends on the value of an earlier field (or of the argument of a dependent arrow) in a way that cannot be erased: only arrows, type arguments, and inductive types with one constructor of one field besides proofs (`Fin n`, `Vector α n`, `{x // p x}`) are erased to a non-dependent type
//   RecData.Prog.roseF: LeanScript: the recursive type LeanScript.Ref is not declared in the signature `RecData.Prog`; add it to `leanscript_signature RecData.Prog`
//   RecData.Prog.block0: LeanScript: a field of the constructor `LeanScript.Mems.cons` has the type LeanScript.Decl [] (0 + 1) g which depends on the value of an earlier field (or of the argument of a dependent arrow) in a way that cannot be erased: only arrows, type arguments, and inductive types with one constructor of one field besides proofs (`Fin n`, `Vector α n`, `{x // p x}`) are erased to a non-dependent type
//   RecData.Prog.tree: LeanScript: the recursive type LeanScript.Ref is not declared in the signature `RecData.Prog`; add it to `leanscript_signature RecData.Prog`
//   RecData.Prog.block1: LeanScript: a field of the constructor `LeanScript.Mems.cons` has the type LeanScript.Decl [0] (0 + 1) g which depends on the value of an earlier field (or of the argument of a dependent arrow) in a way that cannot be erased: only arrows, type arguments, and inductive types with one constructor of one field besides proofs (`Fin n`, `Vector α n`, `{x // p x}`) are erased to a non-dependent type

import {
  uint53__lean_nat_add,
  array__lean_array_push_mutable,
} from "../../runtime.js";

/**
 * `RecData.Prog.ks`
 * @returns {List<uint53(number)>}
 */
export const RecData$Prog$ks = () => [1, 0, 0, 0];

/**
 * `RecData.two`
 * @returns {D0}
 */
export const RecData$two = () => ({
  tag: 1,
  _1: 1,
  _2: { tag: 1, _1: 2, _2: { tag: 0 } },
});

/**
 * `RecData.push`
 * @param {uint53(number)} x
 * @param {D0} l
 * @returns {D0}
 */
export const RecData$push = (x, l) => ({ tag: 1, _1: x, _2: l });

/**
 * `RecData.head`
 * @param {D0} l
 * @returns {uint53(number)}
 */
export const RecData$head = (l) => (l.tag === 0 ? 0 : l._1);

/**
 * `RecData.sum`
 * @param {D0} a
 * @returns {uint53(number)}
 */
export const RecData$sum = (a) => {
  const go0$1 = (v$2) => {
    let x$3;
    if (v$2.tag === 0) {
      x$3 = { tag: 0 };
    } else {
      const { _2: f$4 } = v$2;
      x$3 = { tag: 1, _1: v$2._1, _2: { _1: f$4, _2: go0$1(f$4) } };
    }
    if (x$3.tag === 0) {
      return 0;
    }
    return uint53__lean_nat_add(x$3._1, x$3._2._2);
  };
  const x$5 = go0$1(a);
  return x$5;
};

/**
 * `RecData.ofArray`
 * @param {Array<uint53(number)>} xs
 * @returns {D0}
 */
export const RecData$ofArray = (xs) => {
  let acc$1 = { tag: 0 };
  for (const e$2 of xs) {
    const a$3 = acc$1;
    acc$1 = { tag: 1, _1: e$2, _2: a$3 };
  }
  return acc$1;
};

/**
 * `RecData.toArray`
 * @param {D0} a
 * @returns {Array<uint53(number)>}
 */
export const RecData$toArray = (a) => {
  const go0$1 = (v$2) => {
    let x$3;
    if (v$2.tag === 0) {
      x$3 = { tag: 0 };
    } else {
      const { _2: f$4 } = v$2;
      x$3 = { tag: 1, _1: v$2._1, _2: { _1: f$4, _2: go0$1(f$4) } };
    }
    if (x$3.tag === 0) {
      return [];
    }
    return array__lean_array_push_mutable(x$3._2._2, x$3._1);
  };
  const x$5 = go0$1(a);
  return x$5;
};

/**
 * `RecData.size`
 * @param {D1} a
 * @returns {uint53(number)}
 */
export const RecData$size = (a) => {
  const go0$1 = (v$2) => {
    let x$3;
    if (v$2.tag === 0) {
      x$3 = { tag: 0 };
    } else {
      const { _1: f$4, _3: f$5 } = v$2;
      x$3 = {
        tag: 1,
        _1: { _1: f$4, _2: go0$1(f$4) },
        _2: v$2._2,
        _3: { _1: f$5, _2: go0$1(f$5) },
      };
    }
    if (x$3.tag === 0) {
      return 0;
    }
    return uint53__lean_nat_add(uint53__lean_nat_add(x$3._1._2, 1), x$3._3._2);
  };
  const x$6 = go0$1(a);
  return x$6;
};

/**
 * `RecData.insert`
 * @param {uint53(number)} x
 * @param {D1} a
 * @returns {D1}
 */
export const RecData$insert = (x, a) => {
  const go0$1 = (v$2) => {
    let x$3;
    if (v$2.tag === 0) {
      x$3 = { tag: 0 };
    } else {
      const { _1: f$4, _3: f$5 } = v$2;
      x$3 = {
        tag: 1,
        _1: { _1: f$4, _2: go0$1(f$4) },
        _2: v$2._2,
        _3: { _1: f$5, _2: go0$1(f$5) },
      };
    }
    if (x$3.tag === 0) {
      return { tag: 1, _1: { tag: 0 }, _2: x, _3: { tag: 0 } };
    }
    const { _2: f$6 } = x$3;
    return x < f$6
      ? { tag: 1, _1: x$3._1._2, _2: f$6, _3: x$3._3._1 }
      : { tag: 1, _1: x$3._1._1, _2: f$6, _3: x$3._3._2 };
  };
  const x$7 = go0$1(a);
  return x$7;
};

/**
 * `RecData.inorder`
 * @param {D1} a
 * @returns {Array<uint53(number)>}
 */
export const RecData$inorder = (a) => {
  const go0$1 = (v$2) => {
    let x$3;
    if (v$2.tag === 0) {
      x$3 = { tag: 0 };
    } else {
      const { _1: f$4, _3: f$5 } = v$2;
      x$3 = {
        tag: 1,
        _1: { _1: f$4, _2: go0$1(f$4) },
        _2: v$2._2,
        _3: { _1: f$5, _2: go0$1(f$5) },
      };
    }
    if (x$3.tag === 0) {
      return [];
    }
    let acc$6 = array__lean_array_push_mutable(x$3._1._2, x$3._2);
    for (const e$7 of x$3._3._2) {
      const a$8 = acc$6;
      acc$6 = array__lean_array_push_mutable(a$8, e$7);
    }
    return acc$6;
  };
  const x$9 = go0$1(a);
  return x$9;
};

/**
 * `RecData.ofArrayT`
 * @param {Array<uint53(number)>} xs
 * @returns {D1}
 */
export const RecData$ofArrayT = (xs) => {
  let acc$1 = { tag: 0 };
  for (const e$2 of xs) {
    const a$3 = acc$1;
    const k$13 = (x$4, x$5) => {
      const go0$6 = (v$7) => {
        let x$8;
        if (v$7.tag === 0) {
          x$8 = { tag: 0 };
        } else {
          const { _1: f$9, _3: f$10 } = v$7;
          x$8 = {
            tag: 1,
            _1: { _1: f$9, _2: go0$6(f$9) },
            _2: v$7._2,
            _3: { _1: f$10, _2: go0$6(f$10) },
          };
        }
        if (x$8.tag === 0) {
          return { tag: 1, _1: { tag: 0 }, _2: x$4, _3: { tag: 0 } };
        }
        const { _2: f$11 } = x$8;
        return x$4 < f$11
          ? { tag: 1, _1: x$8._1._2, _2: f$11, _3: x$8._3._1 }
          : { tag: 1, _1: x$8._1._1, _2: f$11, _3: x$8._3._2 };
      };
      const x$12 = go0$6(x$5);
      return x$12;
    };
    const x$14 = k$13(e$2, a$3);
    acc$1 = x$14;
  }
  return acc$1;
};

/**
 * `RecData.sumTwo`
 * @returns {uint53(number)}
 */
export const RecData$sumTwo = () => 3;

/**
 * `RecData.sumArray`
 * @param {Array<uint53(number)>} xs
 * @returns {uint53(number)}
 */
export const RecData$sumArray = (xs) => {
  const k$7 = (x$1) => {
    const go0$2 = (v$3) => {
      let x$4;
      if (v$3.tag === 0) {
        x$4 = { tag: 0 };
      } else {
        const { _2: f$5 } = v$3;
        x$4 = { tag: 1, _1: v$3._1, _2: { _1: f$5, _2: go0$2(f$5) } };
      }
      if (x$4.tag === 0) {
        return 0;
      }
      return uint53__lean_nat_add(x$4._1, x$4._2._2);
    };
    const x$6 = go0$2(x$1);
    return x$6;
  };
  const k$12 = (x$8) => {
    let acc$9 = { tag: 0 };
    for (const e$10 of x$8) {
      const a$11 = acc$9;
      acc$9 = { tag: 1, _1: e$10, _2: a$11 };
    }
    return acc$9;
  };
  const x$13 = k$12(xs);
  const x$14 = k$7(x$13);
  return x$14;
};

/**
 * `RecData.reverse`
 * @param {Array<uint53(number)>} xs
 * @returns {Array<uint53(number)>}
 */
export const RecData$reverse = (xs) => {
  const k$7 = (x$1) => {
    const go0$2 = (v$3) => {
      let x$4;
      if (v$3.tag === 0) {
        x$4 = { tag: 0 };
      } else {
        const { _2: f$5 } = v$3;
        x$4 = { tag: 1, _1: v$3._1, _2: { _1: f$5, _2: go0$2(f$5) } };
      }
      if (x$4.tag === 0) {
        return [];
      }
      return array__lean_array_push_mutable(x$4._2._2, x$4._1);
    };
    const x$6 = go0$2(x$1);
    return x$6;
  };
  const k$12 = (x$8) => {
    let acc$9 = { tag: 0 };
    for (const e$10 of x$8) {
      const a$11 = acc$9;
      acc$9 = { tag: 1, _1: e$10, _2: a$11 };
    }
    return acc$9;
  };
  const x$13 = k$12(xs);
  const x$14 = k$7(x$13);
  return x$14;
};

/**
 * `RecData.sort`
 * @param {Array<uint53(number)>} xs
 * @returns {Array<uint53(number)>}
 */
export const RecData$sort = (xs) => {
  const k$11 = (x$1) => {
    const go0$2 = (v$3) => {
      let x$4;
      if (v$3.tag === 0) {
        x$4 = { tag: 0 };
      } else {
        const { _1: f$5, _3: f$6 } = v$3;
        x$4 = {
          tag: 1,
          _1: { _1: f$5, _2: go0$2(f$5) },
          _2: v$3._2,
          _3: { _1: f$6, _2: go0$2(f$6) },
        };
      }
      if (x$4.tag === 0) {
        return [];
      }
      let acc$7 = array__lean_array_push_mutable(x$4._1._2, x$4._2);
      for (const e$8 of x$4._3._2) {
        const a$9 = acc$7;
        acc$7 = array__lean_array_push_mutable(a$9, e$8);
      }
      return acc$7;
    };
    const x$10 = go0$2(x$1);
    return x$10;
  };
  const k$27 = (x$12) => {
    let acc$13 = { tag: 0 };
    for (const e$14 of x$12) {
      const a$15 = acc$13;
      const k$25 = (x$16, x$17) => {
        const go0$18 = (v$19) => {
          let x$20;
          if (v$19.tag === 0) {
            x$20 = { tag: 0 };
          } else {
            const { _1: f$21, _3: f$22 } = v$19;
            x$20 = {
              tag: 1,
              _1: { _1: f$21, _2: go0$18(f$21) },
              _2: v$19._2,
              _3: { _1: f$22, _2: go0$18(f$22) },
            };
          }
          if (x$20.tag === 0) {
            return { tag: 1, _1: { tag: 0 }, _2: x$16, _3: { tag: 0 } };
          }
          const { _2: f$23 } = x$20;
          return x$16 < f$23
            ? { tag: 1, _1: x$20._1._2, _2: f$23, _3: x$20._3._1 }
            : { tag: 1, _1: x$20._1._1, _2: f$23, _3: x$20._3._2 };
        };
        const x$24 = go0$18(x$17);
        return x$24;
      };
      const x$26 = k$25(e$14, a$15);
      acc$13 = x$26;
    }
    return acc$13;
  };
  const x$28 = k$27(xs);
  const x$29 = k$11(x$28);
  return x$29;
};

/**
 * `RecData.sizeArray`
 * @param {Array<uint53(number)>} xs
 * @returns {uint53(number)}
 */
export const RecData$sizeArray = (xs) => {
  const k$8 = (x$1) => {
    const go0$2 = (v$3) => {
      let x$4;
      if (v$3.tag === 0) {
        x$4 = { tag: 0 };
      } else {
        const { _1: f$5, _3: f$6 } = v$3;
        x$4 = {
          tag: 1,
          _1: { _1: f$5, _2: go0$2(f$5) },
          _2: v$3._2,
          _3: { _1: f$6, _2: go0$2(f$6) },
        };
      }
      if (x$4.tag === 0) {
        return 0;
      }
      return uint53__lean_nat_add(
        uint53__lean_nat_add(x$4._1._2, 1),
        x$4._3._2,
      );
    };
    const x$7 = go0$2(x$1);
    return x$7;
  };
  const k$24 = (x$9) => {
    let acc$10 = { tag: 0 };
    for (const e$11 of x$9) {
      const a$12 = acc$10;
      const k$22 = (x$13, x$14) => {
        const go0$15 = (v$16) => {
          let x$17;
          if (v$16.tag === 0) {
            x$17 = { tag: 0 };
          } else {
            const { _1: f$18, _3: f$19 } = v$16;
            x$17 = {
              tag: 1,
              _1: { _1: f$18, _2: go0$15(f$18) },
              _2: v$16._2,
              _3: { _1: f$19, _2: go0$15(f$19) },
            };
          }
          if (x$17.tag === 0) {
            return { tag: 1, _1: { tag: 0 }, _2: x$13, _3: { tag: 0 } };
          }
          const { _2: f$20 } = x$17;
          return x$13 < f$20
            ? { tag: 1, _1: x$17._1._2, _2: f$20, _3: x$17._3._1 }
            : { tag: 1, _1: x$17._1._1, _2: f$20, _3: x$17._3._2 };
        };
        const x$21 = go0$15(x$14);
        return x$21;
      };
      const x$23 = k$22(e$11, a$12);
      acc$10 = x$23;
    }
    return acc$10;
  };
  const x$25 = k$24(xs);
  const x$26 = k$8(x$25);
  return x$26;
};

/**
 * `RecData.roseOf`
 * @param {uint53(number)} x
 * @returns {D2}
 */
export const RecData$roseOf = (x) => (2 < x ? [[], [[]]] : [[[], []]]);

/**
 * `RecData.roseKids`
 * @param {D2} a
 * @returns {uint53(number)}
 */
export const RecData$roseKids = (a) => {
  const x$1 = a;
  return x$1.length;
};

/**
 * `RecData.roseKidsTest`
 * @param {uint53(number)} x
 * @returns {uint53(number)}
 */
export const RecData$roseKidsTest = (x) => {
  const k$3 = (x$1) => {
    const x$2 = x$1;
    return x$2.length;
  };
  const k$5 = (x$4) => (2 < x$4 ? [[], [[]]] : [[[], []]]);
  const x$6 = k$5(x);
  const x$7 = k$3(x$6);
  return x$7;
};

/**
 * `RecData.RoseF.size`
 * @param {D4} a
 * @returns {uint53(number)}
 */
export const RecData$RoseF$size = (a) => {
  const go0$1 = (v$3) => {
    let x$4;
    if (v$3.tag === 0) {
      x$4 = { tag: 0 };
    } else {
      const { _1: f$5 } = v$3;
      x$4 = { tag: 1, _1: { _1: f$5, _2: go1$2(f$5) } };
    }
    if (x$4.tag === 0) {
      return { tag: 0 };
    }
    return { tag: 1, _1: x$4._1._2 };
  };
  const go1$2 = (v$6) => {
    const { _2: f$7 } = v$6;
    const x$10 = {
      _1: v$6._1,
      _2: (y$8) => {
        const r$9 = f$7(y$8);
        return { _1: r$9, _2: go0$1(r$9) };
      },
    };
    const { _2: f$11 } = x$10;
    let acc$12 = 1;
    for (let i$13 = 0; i$13 < x$10._1; i$13++) {
      const a$14 = acc$12;
      const x$15 = f$11(i$13);
      let x$16;
      if (x$15._2.tag === 0) {
        x$16 = 0;
      } else {
        x$16 = x$15._2._1;
      }
      acc$12 = uint53__lean_nat_add(a$14, x$16);
    }
    return acc$12;
  };
  const x$17 = go1$2(a);
  return x$17;
};

/**
 * `RecData.roseFOf`
 * @param {uint53(number)} n
 * @returns {D4}
 */
export const RecData$roseFOf = (n) => {
  const k$6 = (x$1) => {
    if (x$1 < n) {
      const k$5 = (x$2) => {
        if (x$2 < 2) {
          const k$4 = (x$3) => ({ tag: 0 });
          return { tag: 1, _1: { _1: 0, _2: k$4 } };
        }
        return { tag: 0 };
      };
      return { tag: 1, _1: { _1: 2, _2: k$5 } };
    }
    return { tag: 0 };
  };
  return { _1: n, _2: k$6 };
};

/**
 * `RecData.roseFTest`
 * @param {uint53(number)} n
 * @returns {uint53(number)}
 */
export const RecData$roseFTest = (n) => {
  const k$19 = (x$1) => {
    const go0$2 = (v$4) => {
      let x$5;
      if (v$4.tag === 0) {
        x$5 = { tag: 0 };
      } else {
        const { _1: f$6 } = v$4;
        x$5 = { tag: 1, _1: { _1: f$6, _2: go1$3(f$6) } };
      }
      if (x$5.tag === 0) {
        return { tag: 0 };
      }
      return { tag: 1, _1: x$5._1._2 };
    };
    const go1$3 = (v$7) => {
      const { _2: f$8 } = v$7;
      const x$11 = {
        _1: v$7._1,
        _2: (y$9) => {
          const r$10 = f$8(y$9);
          return { _1: r$10, _2: go0$2(r$10) };
        },
      };
      const { _2: f$12 } = x$11;
      let acc$13 = 1;
      for (let i$14 = 0; i$14 < x$11._1; i$14++) {
        const a$15 = acc$13;
        const x$16 = f$12(i$14);
        let x$17;
        if (x$16._2.tag === 0) {
          x$17 = 0;
        } else {
          x$17 = x$16._2._1;
        }
        acc$13 = uint53__lean_nat_add(a$15, x$17);
      }
      return acc$13;
    };
    const x$18 = go1$3(x$1);
    return x$18;
  };
  const k$27 = (x$20) => {
    const k$26 = (x$21) => {
      if (x$21 < x$20) {
        const k$25 = (x$22) => {
          if (x$22 < 2) {
            const k$24 = (x$23) => ({ tag: 0 });
            return { tag: 1, _1: { _1: 0, _2: k$24 } };
          }
          return { tag: 0 };
        };
        return { tag: 1, _1: { _1: 2, _2: k$25 } };
      }
      return { tag: 0 };
    };
    return { _1: x$20, _2: k$26 };
  };
  const x$28 = k$27(n);
  const x$29 = k$19(x$28);
  return x$29;
};
