// Differential checks of ScalarRepl-faithful.js against Lean, generated by leanscript --check
import * as M from "./ScalarRepl-faithful.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
// a recursive union: as `showUnion`, the fields marked in `rec[tag]` (the type itself) printed
// the same way, one level less deep (`…` at depth 0, as `showExpr` cuts it in Lean)
function showTree(v, rec, d) {
  if (d === 0) return "…";
  if (typeof v === "number") return v + "()";
  const r = rec[v.tag] || [];
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++)
    fs.push(r[i - 1] ? showTree(v["_" + i], rec, d - 1) : show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("test1(0n)", () => M.test1(0n), "0", false);
check("test1(1n)", () => M.test1(1n), "0", false);
check("test1(2n)", () => M.test1(2n), "1", false);
check("test1(5n)", () => M.test1(5n), "10", false);
check("test1(13n)", () => M.test1(13n), "78", false);
check("test2(0n)", () => M.test2(0n), "0", false);
check("test2(1n)", () => M.test2(1n), "0", false);
check("test2(2n)", () => M.test2(2n), "0", false);
check("test2(5n)", () => M.test2(5n), "10", false);
check("test2(13n)", () => M.test2(13n), "286", false);
check("test3(0n, 0n)", () => M.test3(0n, 0n), "1", false);
check("test3(0n, 2n)", () => M.test3(0n, 2n), "3", false);
check("test3(1n, 1n)", () => M.test3(1n, 1n), "1", false);
check("test3(2n, 0n)", () => M.test3(2n, 0n), "5", false);
check("test3(0n, 13n)", () => M.test3(0n, 13n), "25", false);
check("test3(1n, 5n)", () => M.test3(1n, 5n), "7", false);
check("test3(2n, 2n)", () => M.test3(2n, 2n), "1", false);
check("test3(5n, 1n)", () => M.test3(5n, 1n), "9", false);
check("test3(13n, 0n)", () => M.test3(13n, 0n), "27", false);
check("test3(2n, 13n)", () => M.test3(2n, 13n), "21", false);
check("test3(5n, 5n)", () => M.test3(5n, 5n), "1", false);
check("test3(13n, 2n)", () => M.test3(13n, 2n), "23", false);
check("test3(13n, 13n)", () => M.test3(13n, 13n), "1", false);
check("test4(0n, 0n)", () => M.test4(0n, 0n), "{0, 0}", false);
check("test4(0n, 2n)", () => M.test4(0n, 2n), "{0, 2}", false);
check("test4(1n, 1n)", () => M.test4(1n, 1n), "{1, 1}", false);
check("test4(2n, 0n)", () => M.test4(2n, 0n), "{0, 2}", false);
check("test4(0n, 13n)", () => M.test4(0n, 13n), "{0, 13}", false);
check("test4(1n, 5n)", () => M.test4(1n, 5n), "{1, 5}", false);
check("test4(2n, 2n)", () => M.test4(2n, 2n), "{2, 2}", false);
check("test4(5n, 1n)", () => M.test4(5n, 1n), "{1, 5}", false);
check("test4(13n, 0n)", () => M.test4(13n, 0n), "{0, 13}", false);
check("test4(2n, 13n)", () => M.test4(2n, 13n), "{2, 13}", false);
check("test4(5n, 5n)", () => M.test4(5n, 5n), "{5, 5}", false);
check("test4(13n, 2n)", () => M.test4(13n, 2n), "{2, 13}", false);
check("test4(13n, 13n)", () => M.test4(13n, 13n), "{13, 13}", false);
check("test5(0n, 0n)", () => M.test5(0n, 0n), "0", false);
check("test5(0n, 2n)", () => M.test5(0n, 2n), "2", false);
check("test5(1n, 1n)", () => M.test5(1n, 1n), "2", false);
check("test5(2n, 0n)", () => M.test5(2n, 0n), "2", false);
check("test5(0n, 13n)", () => M.test5(0n, 13n), "13", false);
check("test5(1n, 5n)", () => M.test5(1n, 5n), "6", false);
check("test5(2n, 2n)", () => M.test5(2n, 2n), "4", false);
check("test5(5n, 1n)", () => M.test5(5n, 1n), "6", false);
check("test5(13n, 0n)", () => M.test5(13n, 0n), "13", false);
check("test5(2n, 13n)", () => M.test5(2n, 13n), "15", false);
check("test5(5n, 5n)", () => M.test5(5n, 5n), "10", false);
check("test5(13n, 2n)", () => M.test5(13n, 2n), "15", false);
check("test5(13n, 13n)", () => M.test5(13n, 13n), "26", false);
check("test6(0n)", () => M.test6(0n), "0", false);
check("test6(1n)", () => M.test6(1n), "1", false);
check("test6(2n)", () => M.test6(2n), "4", false);
check("test6(5n)", () => M.test6(5n), "13", false);
check("test6(13n)", () => M.test6(13n), "73", false);

console.log(`ScalarRepl-faithful.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
