// JavaScript of Tests/SnapshotsMy/ScalarRepl.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic
// not translated:
//   test6: invalid scope

// ---- runtime helpers ----

function $chk53(x) {
  if (!Number.isSafeInteger(x)) {
    throw new RangeError(
      "LeanScript: integer overflow: the result does not fit in a number (use the bigint representation)",
    );
  }
  return x;
}

function lean_nat_add$nnn(a, b) {
  return $chk53(a + b);
}

function lean_nat_sub$nnn(a, b) {
  return a > b ? a - b : 0;
}

// ---- exported functions ----

/**
 * `test1`
 * @param {uint53(number)} n
 * @returns {uint53(number)}
 */
export const test1 = (n) => {
  let acc$1 = { tag: 1, _1: 0 };
  for (let i$2 = 0; i$2 < n; i$2++) {
    if (acc$1.tag === 0) {
      const { _1: f$4 } = acc$1;
      acc$1 = { tag: 0, _1: f$4 };
    } else {
      const { _1: f$5 } = acc$1;
      const x$6 = lean_nat_add$nnn(f$5, i$2);
      acc$1 = { tag: 1, _1: x$6 };
    }
  }
  if (acc$1.tag === 0) {
    const { _1: f$7 } = acc$1;
    return f$7;
  } else {
    const { _1: f$8 } = acc$1;
    return f$8;
  }
};

/**
 * `test2`
 * @param {uint53(number)} n
 * @returns {uint53(number)}
 */
export const test2 = (n) => {
  let acc$1 = { tag: 1, _1: 0 };
  for (let i$2 = 0; i$2 < n; i$2++) {
    j$1: {
      if (acc$1.tag === 0) {
        const { _1: f$4 } = acc$1;
        acc$1 = { tag: 0, _1: f$4 };
        break j$1;
      } else {
        const { _1: f$5 } = acc$1;
        let acc$6 = { tag: 1, _1: f$5 };
        for (let i$7 = 0; i$7 < i$2; i$7++) {
          if (acc$6.tag === 0) {
            const { _1: f$9 } = acc$6;
            acc$6 = { tag: 0, _1: f$9 };
          } else {
            const { _1: f$10 } = acc$6;
            const x$11 = lean_nat_add$nnn(f$10, i$7);
            acc$6 = { tag: 1, _1: x$11 };
          }
        }
        let x$12;
        j$2: {
          if (acc$6.tag === 0) {
            const { _1: f$13 } = acc$6;
            x$12 = f$13;
            break j$2;
          } else {
            const { _1: f$14 } = acc$6;
            x$12 = f$14;
            break j$2;
          }
        }
        acc$1 = { tag: 1, _1: x$12 };
        break j$1;
      }
    }
  }
  if (acc$1.tag === 0) {
    const { _1: f$15 } = acc$1;
    return f$15;
  } else {
    const { _1: f$16 } = acc$1;
    return f$16;
  }
};

/**
 * `test3`
 * @param {uint53(number)} a
 * @param {uint53(number)} b
 * @returns {uint53(number)}
 */
export const test3 = (a, b) => {
  const k$1 = (x$2) => {
    const { _1: f$3, _2: f$4 } = x$2;
    const { _1: f$5, _2: f$6 } = x$2;
    if (f$3 < f$6) {
      const { _1: f$7, _2: f$8 } = x$2;
      const { _1: f$9, _2: f$10 } = x$2;
      return lean_nat_sub$nnn(f$8, f$9);
    } else {
      const { _1: f$11, _2: f$12 } = x$2;
      const { _1: f$13, _2: f$14 } = x$2;
      return lean_nat_sub$nnn(f$11, f$14);
    }
  };
  const x$15 = k$1({ _1: a, _2: b });
  const k$16 = (x$17) => {
    const { _1: f$18, _2: f$19 } = x$17;
    const { _1: f$20, _2: f$21 } = x$17;
    if (f$18 < f$21) {
      const { _1: f$22, _2: f$23 } = x$17;
      const { _1: f$24, _2: f$25 } = x$17;
      return lean_nat_sub$nnn(f$23, f$24);
    } else {
      const { _1: f$26, _2: f$27 } = x$17;
      const { _1: f$28, _2: f$29 } = x$17;
      return lean_nat_sub$nnn(f$26, f$29);
    }
  };
  const x$30 = k$16({ _1: b, _2: lean_nat_add$nnn(a, 1) });
  return lean_nat_add$nnn(x$15, x$30);
};

/**
 * `test4`
 * @param {uint53(number)} a
 * @param {uint53(number)} b
 * @returns {{ _1: uint53(number), _2: uint53(number) }}
 */
export const test4 = (a, b) => {
  const k$1 = (x$2) => {
    const { _1: f$3, _2: f$4 } = x$2;
    const { _1: f$5, _2: f$6 } = x$2;
    if (f$3 < f$6) {
      return x$2;
    } else {
      const { _1: f$7, _2: f$8 } = x$2;
      const { _1: f$9, _2: f$10 } = x$2;
      return { _1: f$8, _2: f$9 };
    }
  };
  return k$1({ _1: a, _2: b });
};

/**
 * `test5`
 * @param {uint53(number)} a
 * @param {uint53(number)} b
 * @returns {uint53(number)}
 */
export const test5 = (a, b) => {
  const k$1 = (x$2) => {
    if (x$2.tag === 0) {
      return 0;
    } else {
      const { _1: f$3 } = x$2;
      const { _1: f$4, _2: f$5 } = f$3;
      return lean_nat_add$nnn(f$4, f$5);
    }
  };
  const x$6 = k$1({ tag: 1, _1: { _1: a, _2: b } });
  return lean_nat_add$nnn(x$6, 0);
};
