// Differential checks of ShareFuns-pbo.js against Lean, generated by leanscript --check
import * as M from "./ShareFuns-pbo.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  return String(v);
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("absDiff(0, 0)", () => M.absDiff(0, 0), "0", false);
check("absDiff(0, 2)", () => M.absDiff(0, 2), "2", false);
check("absDiff(1, 1)", () => M.absDiff(1, 1), "0", false);
check("absDiff(2, 0)", () => M.absDiff(2, 0), "2", false);
check("absDiff(0, 13)", () => M.absDiff(0, 13), "13", false);
check("absDiff(1, 5)", () => M.absDiff(1, 5), "4", false);
check("absDiff(2, 2)", () => M.absDiff(2, 2), "0", false);
check("absDiff(5, 1)", () => M.absDiff(5, 1), "4", false);
check("absDiff(13, 0)", () => M.absDiff(13, 0), "13", false);
check("absDiff(2, 13)", () => M.absDiff(2, 13), "11", false);
check("absDiff(5, 5)", () => M.absDiff(5, 5), "0", false);
check("absDiff(13, 2)", () => M.absDiff(13, 2), "11", false);
check("absDiff(13, 13)", () => M.absDiff(13, 13), "0", false);
check("plus(0, 0)", () => M.plus(0, 0), "0", false);
check("plus(0, 2)", () => M.plus(0, 2), "2", false);
check("plus(1, 1)", () => M.plus(1, 1), "2", false);
check("plus(2, 0)", () => M.plus(2, 0), "2", false);
check("plus(0, 13)", () => M.plus(0, 13), "13", false);
check("plus(1, 5)", () => M.plus(1, 5), "6", false);
check("plus(2, 2)", () => M.plus(2, 2), "4", false);
check("plus(5, 1)", () => M.plus(5, 1), "6", false);
check("plus(13, 0)", () => M.plus(13, 0), "13", false);
check("plus(2, 13)", () => M.plus(2, 13), "15", false);
check("plus(5, 5)", () => M.plus(5, 5), "10", false);
check("plus(13, 2)", () => M.plus(13, 2), "15", false);
check("plus(13, 13)", () => M.plus(13, 13), "26", false);
check("maxMod(0)", () => M.maxMod(0), "0", false);
check("maxMod(1)", () => M.maxMod(1), "0", false);
check("maxMod(2)", () => M.maxMod(2), "3", false);
check("maxMod(5)", () => M.maxMod(5), "9", false);
check("maxMod(13)", () => M.maxMod(13), "9", false);

console.log(`ShareFuns-pbo.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
