// Differential checks of SharedBranches-pbo.js against Lean, generated by leanscript --check
import * as M from "./SharedBranches-pbo.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("test1({ tag: 0 }, 0, \"\")", () => M.test1({ tag: 0 }, 0, ""), " (error code: 0)", false);
check("test1({ tag: 0 }, 1, \"a\")", () => M.test1({ tag: 0 }, 1, "a"), "a (error code: 1)", false);
check("test1({ tag: 1, _1: \"\" }, 1, \"\")", () => M.test1({ tag: 1, _1: "" }, 1, ""), " (error code: 1)\n  file: ", false);
check("test1({ tag: 0 }, 0, \"héllo, wörld\")", () => M.test1({ tag: 0 }, 0, "héllo, wörld"), "héllo, wörld (error code: 0)", false);
check("test1({ tag: 0 }, 5, \"\")", () => M.test1({ tag: 0 }, 5, ""), " (error code: 5)", false);
check("test1({ tag: 1, _1: \"\" }, 0, \"hello world\")", () => M.test1({ tag: 1, _1: "" }, 0, "hello world"), "hello world (error code: 0)\n  file: ", false);
check("test1({ tag: 1, _1: \"a\" }, 0, \"a\")", () => M.test1({ tag: 1, _1: "a" }, 0, "a"), "a (error code: 0)\n  file: a", false);
check("test1({ tag: 0 }, 2, \"hello world\")", () => M.test1({ tag: 0 }, 2, "hello world"), "hello world (error code: 2)", false);
check("test1({ tag: 1, _1: \"\" }, 2, \"a\")", () => M.test1({ tag: 1, _1: "" }, 2, "a"), "a (error code: 2)\n  file: ", false);
check("test1({ tag: 1, _1: \"a\" }, 2, \"\")", () => M.test1({ tag: 1, _1: "a" }, 2, ""), " (error code: 2)\n  file: a", false);
check("test1({ tag: 0 }, 1, \"abcabc\")", () => M.test1({ tag: 0 }, 1, "abcabc"), "abcabc (error code: 1)", false);
check("test1({ tag: 0 }, 13, \"a\")", () => M.test1({ tag: 0 }, 13, "a"), "a (error code: 13)", false);
check("test1({ tag: 1, _1: \"\" }, 1, \"héllo, wörld\")", () => M.test1({ tag: 1, _1: "" }, 1, "héllo, wörld"), "héllo, wörld (error code: 1)\n  file: ", false);
check("test1({ tag: 1, _1: \"\" }, 13, \"\")", () => M.test1({ tag: 1, _1: "" }, 13, ""), " (error code: 13)\n  file: ", false);
check("test1({ tag: 1, _1: \"a\" }, 1, \"hello world\")", () => M.test1({ tag: 1, _1: "a" }, 1, "hello world"), "hello world (error code: 1)\n  file: a", false);
check("test1({ tag: 0 }, 0, \")\")", () => M.test1({ tag: 0 }, 0, ")"), ") (error code: 0)", false);
check("test1({ tag: 0 }, 5, \"héllo, wörld\")", () => M.test1({ tag: 0 }, 5, "héllo, wörld"), "héllo, wörld (error code: 5)", false);
check("test1({ tag: 1, _1: \"\" }, 0, \" (error code: \")", () => M.test1({ tag: 1, _1: "" }, 0, " (error code: "), " (error code:  (error code: 0)\n  file: ", false);
check("test1({ tag: 1, _1: \"\" }, 5, \"hello world\")", () => M.test1({ tag: 1, _1: "" }, 5, "hello world"), "hello world (error code: 5)\n  file: ", false);
check("test1({ tag: 1, _1: \"a\" }, 0, \"abcabc\")", () => M.test1({ tag: 1, _1: "a" }, 0, "abcabc"), "abcabc (error code: 0)\n  file: a", false);
check("test1({ tag: 1, _1: \"a\" }, 5, \"a\")", () => M.test1({ tag: 1, _1: "a" }, 5, "a"), "a (error code: 5)\n  file: a", false);
check("test1({ tag: 0 }, 2, \" (error code: \")", () => M.test1({ tag: 0 }, 2, " (error code: "), " (error code:  (error code: 2)", false);
check("test1({ tag: 1, _1: \"\" }, 2, \"abcabc\")", () => M.test1({ tag: 1, _1: "" }, 2, "abcabc"), "abcabc (error code: 2)\n  file: ", false);
check("test1({ tag: 1, _1: \"a\" }, 2, \"héllo, wörld\")", () => M.test1({ tag: 1, _1: "a" }, 2, "héllo, wörld"), "héllo, wörld (error code: 2)\n  file: a", false);
check("test1({ tag: 0 }, 1, \")\\n  file: \")", () => M.test1({ tag: 0 }, 1, ")\n  file: "), ")\n  file:  (error code: 1)", false);
check("test1({ tag: 0 }, 13, \"abcabc\")", () => M.test1({ tag: 0 }, 13, "abcabc"), "abcabc (error code: 13)", false);
check("test1({ tag: 1, _1: \"\" }, 1, \")\")", () => M.test1({ tag: 1, _1: "" }, 1, ")"), ") (error code: 1)\n  file: ", false);
check("test1({ tag: 1, _1: \"\" }, 13, \"héllo, wörld\")", () => M.test1({ tag: 1, _1: "" }, 13, "héllo, wörld"), "héllo, wörld (error code: 13)\n  file: ", false);
check("test1({ tag: 1, _1: \"a\" }, 1, \" (error code: \")", () => M.test1({ tag: 1, _1: "a" }, 1, " (error code: "), " (error code:  (error code: 1)\n  file: a", false);
check("test1({ tag: 1, _1: \"a\" }, 13, \"hello world\")", () => M.test1({ tag: 1, _1: "a" }, 13, "hello world"), "hello world (error code: 13)\n  file: a", false);
check("test1({ tag: 0 }, 5, \")\")", () => M.test1({ tag: 0 }, 5, ")"), ") (error code: 5)", false);
check("test1({ tag: 1, _1: \"\" }, 5, \" (error code: \")", () => M.test1({ tag: 1, _1: "" }, 5, " (error code: "), " (error code:  (error code: 5)\n  file: ", false);
check("test1({ tag: 1, _1: \"a\" }, 0, \")\\n  file: \")", () => M.test1({ tag: 1, _1: "a" }, 0, ")\n  file: "), ")\n  file:  (error code: 0)\n  file: a", false);
check("test1({ tag: 1, _1: \"a\" }, 5, \"abcabc\")", () => M.test1({ tag: 1, _1: "a" }, 5, "abcabc"), "abcabc (error code: 5)\n  file: a", false);
check("test1({ tag: 1, _1: \"\" }, 2, \")\\n  file: \")", () => M.test1({ tag: 1, _1: "" }, 2, ")\n  file: "), ")\n  file:  (error code: 2)\n  file: ", false);
check("test1({ tag: 1, _1: \"a\" }, 2, \")\")", () => M.test1({ tag: 1, _1: "a" }, 2, ")"), ") (error code: 2)\n  file: a", false);
check("test1({ tag: 0 }, 13, \")\\n  file: \")", () => M.test1({ tag: 0 }, 13, ")\n  file: "), ")\n  file:  (error code: 13)", false);
check("test1({ tag: 1, _1: \"\" }, 13, \")\")", () => M.test1({ tag: 1, _1: "" }, 13, ")"), ") (error code: 13)\n  file: ", false);
check("test1({ tag: 1, _1: \"a\" }, 13, \" (error code: \")", () => M.test1({ tag: 1, _1: "a" }, 13, " (error code: "), " (error code:  (error code: 13)\n  file: a", false);
check("test1({ tag: 1, _1: \"a\" }, 5, \")\\n  file: \")", () => M.test1({ tag: 1, _1: "a" }, 5, ")\n  file: "), ")\n  file:  (error code: 5)\n  file: a", false);
check("test3(\"\")", () => M.test3(""), "A", false);
check("test3(\"a\")", () => M.test3("a"), "a", false);
check("test3(\"hello world\")", () => M.test3("hello world"), "h", false);
check("test3(\"héllo, wörld\")", () => M.test3("héllo, wörld"), "h", false);
check("test3(\"abcabc\")", () => M.test3("abcabc"), "a", false);
check("test4(\"\", \"a\")", () => M.test4("", "a"), "", false);
check("test4(\"\", \"z\")", () => M.test4("", "z"), "", false);
check("test4(\"a\", \"a\")", () => M.test4("a", "a"), "a", false);
check("test4(\"\", \" \")", () => M.test4("", " "), "", false);
check("test4(\"a\", \"z\")", () => M.test4("a", "z"), "z", false);
check("test4(\"hello world\", \"a\")", () => M.test4("hello world", "a"), "aello world", false);
check("test4(\"\", \"é\")", () => M.test4("", "é"), "", false);
check("test4(\"a\", \" \")", () => M.test4("a", " "), " ", false);
check("test4(\"hello world\", \"z\")", () => M.test4("hello world", "z"), "zello world", false);
check("test4(\"héllo, wörld\", \"a\")", () => M.test4("héllo, wörld", "a"), "aéllo, wörld", false);
check("test4(\"a\", \"é\")", () => M.test4("a", "é"), "é", false);
check("test4(\"hello world\", \" \")", () => M.test4("hello world", " "), " ello world", false);
check("test4(\"héllo, wörld\", \"z\")", () => M.test4("héllo, wörld", "z"), "zéllo, wörld", false);
check("test4(\"abcabc\", \"a\")", () => M.test4("abcabc", "a"), "abcabc", false);
check("test4(\"hello world\", \"é\")", () => M.test4("hello world", "é"), "éello world", false);
check("test4(\"héllo, wörld\", \" \")", () => M.test4("héllo, wörld", " "), " éllo, wörld", false);
check("test4(\"abcabc\", \"z\")", () => M.test4("abcabc", "z"), "zbcabc", false);
check("test4(\"héllo, wörld\", \"é\")", () => M.test4("héllo, wörld", "é"), "ééllo, wörld", false);
check("test4(\"abcabc\", \" \")", () => M.test4("abcabc", " "), " bcabc", false);
check("test4(\"abcabc\", \"é\")", () => M.test4("abcabc", "é"), "ébcabc", false);
check("test5(\"\")", () => M.test5(""), "true", false);
check("test5(\"a\")", () => M.test5("a"), "false", false);
check("test5(\"hello world\")", () => M.test5("hello world"), "false", false);
check("test5(\"héllo, wörld\")", () => M.test5("héllo, wörld"), "false", false);
check("test5(\"abcabc\")", () => M.test5("abcabc"), "false", false);

console.log(`SharedBranches-pbo.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
