// JavaScript of Tests/SnapshotsMy/StringAppend.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

import { uint53__lean_string_length__String_Internal_length } from "../../runtime.js";

/**
 * `rightNested`
 * @param {string} x
 * @param {string} y
 * @returns {string}
 */
export const rightNested = (x, y) => x + "a" + y + "bc";

/**
 * `emptyLeft`
 * @param {string} x
 * @returns {string}
 */
export const emptyLeft = (x) => x;

/**
 * `emptyRight`
 * @param {string} x
 * @returns {string}
 */
export const emptyRight = (x) => x;

/**
 * `emptyMiddle`
 * @param {string} x
 * @param {string} y
 * @returns {string}
 */
export const emptyMiddle = (x, y) => x + y;

/**
 * `twoVars`
 * @param {string} x
 * @param {string} y
 * @returns {string}
 */
export const twoVars = (x, y) => {
  const x$1 = x + "-";
  return x$1 + y + "-" + x$1 + y;
};

/**
 * `closedPart`
 * @param {string} x
 * @returns {string}
 */
export const closedPart = (x) => "ab" + x + "cde";

/**
 * `insideCall`
 * @param {string} x
 * @returns {uint53(number)}
 */
export const insideCall = (x) =>
  uint53__lean_string_length__String_Internal_length("a" + x + "b");

/**
 * `ofCall`
 * @param {string} x
 * @param {string} y
 * @returns {string}
 */
export const ofCall = (x, y) => "[" + x + "ab|" + y + "]";

/**
 * `unicode`
 * @param {string} x
 * @returns {string}
 */
export const unicode = (x) => "é" + x + "ü€";
