// JavaScript of Tests/SnapshotsMy/StringWalk.lean, generated by leanscript
// configuration: nat=bigint int=bigint uint64=bigint int64=bigint bitvec=bigint array-fixed-int=typed array-float=typed array-uint64=typed array-int64=typed array-bitvec=round-up array-bool=generic array-char=generic

// ---- runtime helpers ----

const $utf8Enc = new TextEncoder();
function $utf8(s) {
  return $utf8Enc.encode(s);
}

function lean_string_utf8_at_end__String_Pos_Raw_atEnd$_n_(a, b) {
  return b >= $utf8(a).length;
}

function $utf8At(s, p) {
  let off = 0;
  for (const ch of s) {
    const cp = ch.codePointAt(0);
    const n = cp < 0x80 ? 1 : cp < 0x800 ? 2 : cp < 0x10000 ? 3 : 4;
    if (off === p) return [ch, n];
    if (off > p) return undefined;
    off += n;
  }
  return undefined;
}

function lean_string_utf8_next__String_Pos_Raw_next$_nn(a, b) {
  return (($r) => $r === undefined ? b + 1 : b + $r[1])($utf8At(a, b));
}

function lean_string_utf8_get__String_Pos_Raw_get$_n_(a, b) {
  return ($utf8At(a, b) ?? ["A"])[0];
}

function lean_string_length__String_length$_b(a) {
  return BigInt([...a].length);
}

function lean_string_utf8_byte_size$_b(a) {
  return BigInt($utf8(a).length);
}

// ---- exported functions ----

/**
 * `test1`
 * @param {string} s
 * @param {string} c
 * @returns {nat(bigint)}
 */
export function test1(s, c) {
  return test1_go(s, c, 0, 0n);
}

/**
 * `test1.go`
 * @param {string} s
 * @param {string} c
 * @param {uint53(number)} p
 * @param {nat(bigint)} n
 * @returns {nat(bigint)}
 */
export function test1_go(s, c, p, n) {
  if (lean_string_utf8_at_end__String_Pos_Raw_atEnd$_n_(s, p)) {
    return n;
  } else {
    return test1_go(
      s,
      c,
      lean_string_utf8_next__String_Pos_Raw_next$_nn(s, p),
      lean_string_utf8_get__String_Pos_Raw_get$_n_(s, p) === c ? n + 1n : n,
    );
  }
}

/**
 * `test2`
 * @param {string} s
 * @param {string} c
 * @returns {uint53(number)}
 */
export function test2(s, c) {
  return test2_go(s, c, 0);
}

/**
 * `test2.go`
 * @param {string} s
 * @param {string} c
 * @param {uint53(number)} p
 * @returns {uint53(number)}
 */
export function test2_go(s, c, p) {
  if (lean_string_utf8_at_end__String_Pos_Raw_atEnd$_n_(s, p)) {
    return p;
  } else if (lean_string_utf8_get__String_Pos_Raw_get$_n_(s, p) === c) {
    return p;
  } else {
    return test2_go(s, c, lean_string_utf8_next__String_Pos_Raw_next$_nn(s, p));
  }
}

/**
 * `test4`
 * @param {string} s
 * @returns {nat(bigint)}
 */
export function test4(s) {
  return test4_go(s, 0n, 0n);
}

/**
 * `test4.go`
 * @param {string} s
 * @param {nat(bigint)} i
 * @param {nat(bigint)} acc
 * @returns {nat(bigint)}
 */
export function test4_go(s, i, acc) {
  if (i < lean_string_length__String_length$_b(s)) {
    return test4_go(s, i + 1n, acc + i);
  } else {
    return acc;
  }
}

/**
 * `test3`
 * @param {string} s
 * @param {nat(bigint)} n
 * @returns {nat(bigint)}
 */
export function test3(s, n) {
  let acc$1 = [1, [s, 0n]];
  for (let i$2 = 0n; i$2 < n; i$2++) {
    if (acc$1[0] === 0) {
      const [, f$4] = acc$1;
      acc$1 = [0, f$4];
    } else {
      const [, f$5] = acc$1;
      const [f$6, f$7] = f$5;
      const [f$8, f$9] = f$5;
      const x$10 = f$9 + lean_string_utf8_byte_size$_b(f$6);
      const x$11 = f$6 + "x";
      acc$1 = [1, [x$11, x$10]];
    }
  }
  const j$12 = (x$13) => {
    const [f$14, f$15] = x$13;
    return f$15;
  };
  if (acc$1[0] === 0) {
    const [, f$16] = acc$1;
    return j$12(f$16);
  } else {
    const [, f$17] = acc$1;
    return j$12(f$17);
  }
}
