// JavaScript of Tests/SnapshotsMy/StringWalk.lean, generated by leanscript
// configuration: nat=bigint int=bigint uint64=bigint int64=bigint bitvec=bigint array-fixed-int=typed array-float=typed array-uint64=typed array-int64=typed array-bitvec=round-up array-bool=generic array-char=generic
// not translated:
//   test1.go: LeanScript: `Char` is a leaf of the language: its values are literals, not constructor applications
//   test2.go: LeanScript: `Char` is a leaf of the language: its values are literals, not constructor applications
//   test1: it calls `test1.go`, which is not translated to JavaScript
//   test2: it calls `test2.go`, which is not translated to JavaScript

// ---- runtime helpers ----

function lean_string_length__String_length$_b(a) {
  return BigInt([...a].length);
}

const $utf8Enc = new TextEncoder();
function $utf8(s) {
  return $utf8Enc.encode(s);
}

function lean_string_utf8_byte_size$_b(a) {
  return BigInt($utf8(a).length);
}

// ---- exported functions ----

/**
 * `test4`
 * @param {string} s
 * @returns {nat(bigint)}
 */
export function test4(s) {
  return test4_go(s, 0n, 0n);
}

/**
 * `test4.go`
 * @param {string} s
 * @param {nat(bigint)} i
 * @param {nat(bigint)} acc
 * @returns {nat(bigint)}
 */
export function test4_go(s, i, acc) {
  if (i < lean_string_length__String_length$_b(s)) {
    return test4_go(s, i + 1n, acc + i);
  } else {
    return acc;
  }
}

/**
 * `test3`
 * @param {string} s
 * @param {nat(bigint)} n
 * @returns {nat(bigint)}
 */
export function test3(s, n) {
  let acc$1 = [1, [s, 0n]];
  for (let i$2 = 0n; i$2 < n; i$2++) {
    if (acc$1[0] === 0) {
      const [, f$4] = acc$1;
      acc$1 = [0, f$4];
    } else {
      const [, f$5] = acc$1;
      const [f$6, f$7] = f$5;
      const [f$8, f$9] = f$5;
      const x$10 = f$9 + lean_string_utf8_byte_size$_b(f$6);
      const x$11 = f$6 + "x";
      acc$1 = [1, [x$11, x$10]];
    }
  }
  const j$12 = (x$13) => {
    const [f$14, f$15] = x$13;
    return f$15;
  };
  if (acc$1[0] === 0) {
    const [, f$16] = acc$1;
    return j$12(f$16);
  } else {
    const [, f$17] = acc$1;
    return j$12(f$17);
  }
}
