// JavaScript of Tests/SnapshotsMy/TcoAck.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic
// imports not found (left out): LeanScript.Term.Elab, LeanScript.Term.Compile
// not translated:
//   ack: defined by well-founded recursion: only non-recursive and structurally recursive definitions are translated (to `Term`)
//   ack999: the closed value `ack 999 1` could not be computed at compile time (it normalises to `ack 999 1`)
//   ackWhile: LeanScript: the `while` loop forIn { } ([m], curN) fun x __s => have stack := __s.fst; have curN := __s.snd; if (!stack.isEmpty) = true then match stack with | [] => pure (ForInStep.done (stack, curN)) | top :: rest => have stack := rest; if (top == 0) = true then have curN := curN + 1; pure (ForInStep.yield (stack, curN)) else if (curN == 0) = true then have stack := (top - 1) :: stack; have curN := 1; pure (ForInStep.yield (stack, curN)) else have stack := (top - 1) :: top :: stack; have curN := curN - 1; pure (ForInStep.yield (stack, curN)) else pure (ForInStep.done (stack, curN)) is not structurally terminating: the language has no unbounded loop, so a `while` loop is only accepted when its condition bounds a `Nat` variable `x` of the loop (`x > 0`, `x ≠ 0`, `x < b`, `x ≤ b`, with `b` unchanged by the loop) and every iteration that goes on moves `x` towards the bound by a literal step (`x := x - k`, `x := x / k`, `x := x + k`)
//   AckWithoutStackButUsingCantorPairing.isqrt: LeanScript: the `while` loop forIn { } (x, y) fun x __s => have x := __s.fst; have y := __s.snd; if y < x then have x := y; have y := (x + n / x) / 2; pure (ForInStep.yield (x, y)) else pure (ForInStep.done (x, y)) is not structurally terminating: the language has no unbounded loop, so a `while` loop is only accepted when its condition bounds a `Nat` variable `x` of the loop (`x > 0`, `x ≠ 0`, `x < b`, `x ≤ b`, with `b` unchanged by the loop) and every iteration that goes on moves `x` towards the bound by a literal step (`x := x - k`, `x := x / k`, `x := x + k`)
//   AckWithoutStackButUsingCantorPairing.unpairLeft: LeanScript: the `while` loop forIn { } (x, y) fun x __s => have x := __s.fst; have y := __s.snd; if y < x then have x := y; have y := (x + n / x) / 2; pure (ForInStep.yield (x, y)) else pure (ForInStep.done (x, y)) is not structurally terminating: the language has no unbounded loop, so a `while` loop is only accepted when its condition bounds a `Nat` variable `x` of the loop (`x > 0`, `x ≠ 0`, `x < b`, `x ≤ b`, with `b` unchanged by the loop) and every iteration that goes on moves `x` towards the bound by a literal step (`x := x - k`, `x := x / k`, `x := x + k`)
//   AckWithoutStackButUsingCantorPairing.unpairRight: LeanScript: the `while` loop forIn { } (x, y) fun x __s => have x := __s.fst; have y := __s.snd; if y < x then have x := y; have y := (x + n / x) / 2; pure (ForInStep.yield (x, y)) else pure (ForInStep.done (x, y)) is not structurally terminating: the language has no unbounded loop, so a `while` loop is only accepted when its condition bounds a `Nat` variable `x` of the loop (`x > 0`, `x ≠ 0`, `x < b`, `x ≤ b`, with `b` unchanged by the loop) and every iteration that goes on moves `x` towards the bound by a literal step (`x := x - k`, `x := x / k`, `x := x + k`)
//   AckWithoutStackButUsingCantorPairing.ackNoDataStructure: LeanScript: the `while` loop forIn { } (s, curN) fun x __s => have s := __s.fst; have curN := __s.snd; if (s != 0) = true then have code := s - 1; have top := AckWithoutStackButUsingCantorPairing.unpairLeft code; have s := AckWithoutStackButUsingCantorPairing.unpairRight code; if (top == 0) = true then have curN := curN + 1; pure (ForInStep.yield (s, curN)) else if (curN == 0) = true then have s := AckWithoutStackButUsingCantorPairing.pair (top - 1) s + 1; have curN := 1; pure (ForInStep.yield (s, curN)) else have s := AckWithoutStackButUsingCantorPairing.pair (top - 1) s + 1; have s := AckWithoutStackButUsingCantorPairing.pair top s + 1; have curN := curN - 1; pure (ForInStep.yield (s, curN)) else pure (ForInStep.done (s, curN)) is not structurally terminating: the language has no unbounded loop, so a `while` loop is only accepted when its condition bounds a `Nat` variable `x` of the loop (`x > 0`, `x ≠ 0`, `x < b`, `x ≤ b`, with `b` unchanged by the loop) and every iteration that goes on moves `x` towards the bound by a literal step (`x := x - k`, `x := x / k`, `x := x + k`)

import {
  uint53__lean_nat_add,
  uint53__lean_nat_div,
  uint53__lean_nat_mul,
} from "../../runtime.js";

const $k1 = (x$1) => uint53__lean_nat_add(x$1, 1);
const $k2 = (x$1, x$2) => {
  const x$3 = 1;
  const x$4 = x$1(x$3);
  let acc$5 = x$4;
  for (let i$6 = 0; i$6 < x$2; i$6++) {
    const x$7 = x$1(acc$5);
    acc$5 = x$7;
  }
  return acc$5;
};

/**
 * `ack2`
 * @param {uint53(number)} a
 * @param {uint53(number)} a1
 * @returns {uint53(number)}
 */
export const ack2 = (a, a1) => {
  let f$1;
  const k$2 = $k1;
  let acc$3 = k$2;
  for (let i$4 = 0; i$4 < a; i$4++) {
    const a$5 = acc$3;
    const k$6 = $k2;
    acc$3 = (y$7) => k$6(a$5, y$7);
  }
  f$1 = acc$3;
  return f$1(a1);
};

/**
 * `AckWithoutStackButUsingCantorPairing.pair`
 * @param {uint53(number)} x
 * @param {uint53(number)} y
 * @returns {uint53(number)}
 */
export const AckWithoutStackButUsingCantorPairing$pair = (x, y) =>
  uint53__lean_nat_add(
    uint53__lean_nat_div(
      uint53__lean_nat_mul(
        uint53__lean_nat_add(x, y),
        uint53__lean_nat_add(uint53__lean_nat_add(x, y), 1),
      ),
      2,
    ),
    y,
  );
