// JavaScript of Tests/SnapshotsMy/TcoDiagonal.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic
// imports not found (left out): LeanScript.Term.Elab, LeanScript.Term.Compile
// not translated:
//   diagonal: defined by well-founded recursion: only non-recursive and structurally recursive definitions are translated (to `Term`)
//   diagonal_tr: defined by well-founded recursion: only non-recursive and structurally recursive definitions are translated (to `Term`)
//   diagonalWhile: LeanScript: the `while` loop forIn { } (m, n, acc) fun x __s => have m := __s.fst; have __s := __s.snd; have n := __s.fst; have acc := __s.snd; if (m != 0 || n != 0) = true then have acc := acc + 1; if m > 0 then have m := m - 1; have n := n + 1; pure (ForInStep.yield (m, n, acc)) else have m := n - 1; have n := 0; pure (ForInStep.yield (m, n, acc)) else pure (ForInStep.done (m, n, acc)) is not structurally terminating: the language has no unbounded loop, so a `while` loop is only accepted when its condition bounds a `Nat` variable `x` of the loop (`x > 0`, `x ≠ 0`, `x < b`, `x ≤ b`, with `b` unchanged by the loop) and every iteration that goes on moves `x` towards the bound by a literal step (`x := x - k`, `x := x / k`, `x := x + k`)


