// JavaScript of Tests/SnapshotsMy/TcoHyper.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic
// imports not found (left out): LeanScript.Term.Elab, LeanScript.Term.Compile
// not translated:
//   hyper: defined by well-founded recursion: only non-recursive and structurally recursive definitions are translated (to `Term`)

import { uint53__lean_nat_add } from "../../runtime.js";

const $k1 = (x$1) => uint53__lean_nat_add(x$1, 1);
const $k2 = (x$1, x$2, x$3) => {
  let x$4 = x$3;
  for (let j$5 = 0; j$5 < x$2; j$5++) {
    x$4 = x$1(x$4);
  }
  return x$4;
};
const $k3 = (x$1, x$2) => {
  let acc$3 = 1;
  if (0 < x$1) {
    const i$4 = x$1 - 1;
    acc$3 = x$2;
    if (0 < i$4) {
      const i$5 = i$4 - 1;
      acc$3 = 0;
      if (0 < i$5) {
        acc$3 = 1;
      }
    }
  }
  return acc$3;
};

/**
 * `hyperBase`
 * @param {uint53(number)} a
 * @param {uint53(number)} a1
 * @returns {uint53(number)}
 */
export const hyperBase = (a, a1) => {
  let acc$1 = 1;
  if (0 < a) {
    const i$2 = a - 1;
    acc$1 = a1;
    if (0 < i$2) {
      const i$3 = i$2 - 1;
      acc$1 = 0;
      if (0 < i$3) {
        acc$1 = 1;
      }
    }
  }
  return acc$1;
};

/**
 * `hyperLoop`
 * @param {(uint53(number)) => uint53(number)} f
 * @param {uint53(number)} a
 * @param {uint53(number)} a1
 * @returns {uint53(number)}
 */
export const hyperLoop = (f, a, a1) => {
  let x$1 = a1;
  for (let j$2 = 0; j$2 < a; j$2++) {
    x$1 = f(x$1);
  }
  return x$1;
};

/**
 * `hyperTCO`
 * @param {uint53(number)} a
 * @param {uint53(number)} a1
 * @param {uint53(number)} a2
 * @returns {uint53(number)}
 */
export const hyperTCO = (a, a1, a2) => {
  let acc$1 = $k1;
  for (let i$2 = 0; i$2 < a; i$2++) {
    const a$3 = acc$1;
    acc$1 = (x$4) => $k2(a$3, x$4, $k3(uint53__lean_nat_add(i$2, 1), a1));
  }
  return acc$1(a2);
};

/**
 * `hyperWhile`
 * @param {uint53(number)} a
 * @param {uint53(number)} a1
 * @param {uint53(number)} a2
 * @returns {uint53(number)}
 */
export const hyperWhile = (a, a1, a2) => {
  let acc$1 = $k1;
  for (let i$2 = 0; i$2 < a; i$2++) {
    const a$3 = acc$1;
    acc$1 = (x$4) => {
      let acc$5 = $k3(uint53__lean_nat_add(i$2, 1), a1);
      for (let i$6 = 0; i$6 < x$4; i$6++) {
        acc$5 = a$3(acc$5);
      }
      return acc$5;
    };
  }
  return acc$1(a2);
};
