#!/usr/bin/env python3
"""Generate what is derived from the catalogue of externs.

Reads the catalogue (`LeanScript/LeanInitPureExterns.lean` and its parts in
`LeanScript/LeanInitPureExterns/`), in two levels: one inductive
per family (`PreludeExtern`, `StringBasicExtern`, ...), whose constructors are the entries
and hold their arguments as values (and the proofs they take), and `LeanInitPureExtern`,
with one constructor per family.  Writes `LeanScript/ToTerm/ExternTable.lean`: for each
Lean function the catalogue models, the entry (its shorthand), and what each of its
arguments is.  Some Lean functions are translated to the entry of another one
(`Array.uget` is `Array.getInternal` once `USize` is `Nat`); they are listed in `REDIRECTS`
below, next to the entry they are translated to.

(The shorthands `LeanInitPureExtern.lean_nat_add a b := .preludeExtern (.lean_nat_add a b)`
are not generated by this script: `LeanScript/LeanInitPureExternShorthands.lean` computes
them from the constructors with `derive_catalogue_shorthands`.)

Run from the root of the project:  python3 scripts/gen_externs.py
"""

import re
import sys

# The catalogue: the families, in the parts of `LeanScript/LeanInitPureExterns/`, and
# `LeanInitPureExtern` itself, in `LeanScript/LeanInitPureExterns.lean`.
CATALOGUE = [
    "LeanScript/LeanInitPureExterns/Core.lean",
    "LeanScript/LeanInitPureExterns/FixedWidth.lean",
    "LeanScript/LeanInitPureExterns/String.lean",
    "LeanScript/LeanInitPureExterns/Float.lean",
    "LeanScript/LeanInitPureExterns.lean",
]
TABLE = "LeanScript/ToTerm/ExternTable.lean"
OUTER = "LeanInitPureExtern"

# Lean functions whose entry is commented out because it is another entry: the Lean
# function, the entry it is translated to, and its argument kinds.
REDIRECTS = [
    ("Array.uget", "lean_array_fget", "tvup"),
    ("Array.uset", "lean_array_fset", "tvuvp"),
    ("String.Internal.ugetUTF8Byte",
     "lean_string_get_byte_fast__String_Internal_getUTF8Byte", "vup"),
    ("String.Pos.Raw.next'", "lean_string_utf8_next_fast__String_next'", "vvp"),
]


def split_top(s, sep=" → "):
    parts, depth, cur, i = [], 0, "", 0
    while i < len(s):
        ch = s[i]
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        if depth == 0 and s.startswith(sep, i):
            parts.append(cur.strip())
            cur = ""
            i += len(sep)
            continue
        cur += ch
        i += 1
    parts.append(cur.strip())
    return parts


def is_prop(t):
    return any(tok in t for tok in [" < ", " ≤ ", " ∣ ", " ≠ ", "¬", "isValidChar", " = "])


def parse_line(line, family):
    m = re.match(r"\s*\| (\S+) : (.*)$", line)
    name, body = m.group(1), m.group(2)
    sig, _, comment = body.partition(" -- ")
    comment = comment.strip()
    lean_fn = comment.split()[0] if comment else None
    parts = split_top(sig.strip())
    res = parts[-1]
    assert res.startswith(family + " "), line
    return name, parts[:-1], res[len(family) + 1:], lean_fn


def parse_catalogue():
    """The entries of the families, in order (the families in the order of the
    constructors of `LeanInitPureExtern`, the entries of a family in the order they are
    written): (family, name, args, result index, Lean function); and the constructor of
    `LeanInitPureExtern` of each family."""
    entries, ctor_of = [], {}
    current = None
    lines = []
    for path in CATALOGUE:
        lines += open(path).read().split("\n")
    for line in lines:
        m = re.match(r"inductive (\S+) : ", line)
        if m:
            current = m.group(1)
            continue
        if not re.match(r"\s*\| ", line) or current is None:
            continue
        if current == OUTER:
            m = re.match(r"\s*\| (\S+) \{τ : MyTy\} : (\S+) ", line)
            assert m, line
            ctor_of[m.group(2)] = m.group(1)
            continue
        name, args, res, lean_fn = parse_line(line, current)
        entries.append((current, name, args, res, lean_fn))
    for fam, name, *_ in entries:
        assert fam in ctor_of, f"`{OUTER}` has no constructor for the family `{fam}`"
    rank = {fam: i for i, fam in enumerate(ctor_of)}
    entries.sort(key=lambda e: rank[e[0]])
    names = [name for _, name, *_ in entries]
    dups = {n for n in names if names.count(n) > 1}
    assert not dups, f"entries in two families: {sorted(dups)}"
    return entries, ctor_of


def kinds_of(args):
    """One letter per argument: `t` a type, `s` a value the type depends on (implicit, and
    fixed where the term is written), `i` the `Inhabited` default, `p` a proof, `v` a
    value."""
    kinds = ""
    for a in args:
        a = a.strip()
        m = re.fullmatch(r"[({]\s*(\w+)\s*:\s*(.*?)(\s*:= by .*)?[)}]", a)
        bname, t = (m.group(1), m.group(2).strip()) if m else (None, a)
        if a.startswith("{"):
            kinds += "s"
        elif t == "MyTy":
            kinds += "t"
        elif bname == "inhabited_default":
            kinds += "i"
        elif is_prop(t):
            kinds += "p"
        else:
            kinds += "v"
    return kinds


def lean_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    entries, ctor_of = parse_catalogue()
    table = []
    for fam, name, args, res, lean_fn in entries:
        table.append((lean_fn, name, kinds_of(args)))
    table += REDIRECTS

    with open(TABLE, "w") as f:
        f.write("""module

-- This file is generated by `scripts/gen_externs.py` from the catalogue
-- `LeanScript/LeanInitPureExterns.lean` (and its parts in `LeanScript/LeanInitPureExterns/`);
-- edit the catalogue and rerun the script.

@[expose] public section

set_option autoImplicit false

namespace LeanScript.ToTerm

/-!
# The externs `#leanscript_to_term` knows

The Lean functions of `Init` that are implemented by a pure extern, each with the entry of
the catalogue `LeanScript.LeanInitPureExtern` that models it.  A call of one of them is
translated to that entry: `LeanScript.Term.extern` of it when every argument is a closed
Lean value, and otherwise `LeanScript.Term.externCall` (or `Term.externCallChecked`, for
an entry that takes a proof) applied to the terms of its arguments.  A call of any other
function marked `@[extern]` is refused, except `Nat.gcd`, which is translated as an
ordinary function.
-/

/-- A Lean function implemented by an extern, and the entry of the catalogue that models
    it. -/
structure ExternEntry where
  /-- The Lean function. -/
  leanFn : String
  /-- The entry of the catalogue `LeanScript.LeanInitPureExtern`: the name of its
      shorthand `LeanInitPureExtern.<ctor>` (`LeanScript.LeanInitPureExternShorthands`),
      which is also the name of its constructor in its family. -/
  ctor : String
  /-- One letter per argument of the Lean function: `t` a type (a type of the language,
      fixed where the term is written), `s` a value a type depends on (the string `s` of
      `s.Pos`; fixed where the term is written, so it must be a closed Lean value), `i`
      the `Inhabited` instance whose default the entry takes as a value, `v` a value,
      `u` a `USize`, which is a `Nat` here, and `p` a proof. -/
  kinds : String

/-- The externs a term can call. -/
def externTable : Array ExternEntry := #[
""")
        f.write(",\n".join(f"  ⟨{lean_str(fn)}, {lean_str(c)}, {lean_str(k)}⟩"
                           for fn, c, k in table))
        f.write("\n]\n\nend LeanScript.ToTerm\n\nend\n")

    print(f"{len(entries)} entries in {len(ctor_of)} families, {len(table)} externs",
          file=sys.stderr)


if __name__ == "__main__":
    main()
