// JavaScript of Tests/SnapshotsPBOPure/AssocIntOps.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic

// ---- runtime helpers ----

function $chk53(x) {
  if (!Number.isSafeInteger(x)) throw new RangeError("LeanScript: integer overflow: the result does not fit in a number (use the bigint representation)");
  return x;
}

function lean_int_add$nnn(a, b) {
  return $chk53(a + b);
}

function lean_int_mul$nnn(a, b) {
  return $chk53(a * b);
}

// ---- exported functions ----

/**
 * `test1`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const test1 = (x) =>
  lean_int_add$nnn(
    lean_int_add$nnn(
      1,
      lean_int_add$nnn(
        lean_int_add$nnn(
          lean_int_add$nnn(lean_int_add$nnn(lean_int_add$nnn(2, x), x), x),
          x,
        ),
        3,
      ),
    ),
    4,
  );

/**
 * `test2`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const test2 = (x) =>
  lean_int_add$nnn(
    lean_int_add$nnn(
      1,
      lean_int_add$nnn(
        2,
        lean_int_add$nnn(
          x,
          lean_int_add$nnn(x, lean_int_add$nnn(x, lean_int_add$nnn(x, 3))),
        ),
      ),
    ),
    4,
  );

/**
 * `test3`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const test3 = (x) =>
  lean_int_add$nnn(
    lean_int_add$nnn(
      lean_int_add$nnn(
        lean_int_add$nnn(
          1,
          lean_int_add$nnn(
            2,
            lean_int_add$nnn(
              x,
              lean_int_add$nnn(x, lean_int_add$nnn(x, lean_int_add$nnn(x, 3))),
            ),
          ),
        ),
        4,
      ),
      lean_int_add$nnn(
        lean_int_add$nnn(
          lean_int_add$nnn(lean_int_add$nnn(lean_int_add$nnn(5, x), x), x),
          x,
        ),
        6,
      ),
    ),
    7,
  );

/**
 * `test4`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const test4 = (x) =>
  lean_int_mul$nnn(
    lean_int_mul$nnn(
      1,
      lean_int_mul$nnn(
        lean_int_mul$nnn(
          lean_int_mul$nnn(lean_int_mul$nnn(lean_int_mul$nnn(2, x), x), x),
          x,
        ),
        3,
      ),
    ),
    4,
  );

/**
 * `test5`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const test5 = (x) =>
  lean_int_mul$nnn(
    lean_int_mul$nnn(
      1,
      lean_int_mul$nnn(
        2,
        lean_int_mul$nnn(
          x,
          lean_int_mul$nnn(x, lean_int_mul$nnn(x, lean_int_mul$nnn(x, 3))),
        ),
      ),
    ),
    4,
  );

/**
 * `test6`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const test6 = (x) =>
  lean_int_mul$nnn(
    lean_int_mul$nnn(
      lean_int_mul$nnn(
        lean_int_mul$nnn(
          1,
          lean_int_mul$nnn(
            2,
            lean_int_mul$nnn(
              x,
              lean_int_mul$nnn(x, lean_int_mul$nnn(x, lean_int_mul$nnn(x, 3))),
            ),
          ),
        ),
        4,
      ),
      lean_int_mul$nnn(
        lean_int_mul$nnn(
          lean_int_mul$nnn(lean_int_mul$nnn(lean_int_mul$nnn(5, x), x), x),
          x,
        ),
        6,
      ),
    ),
    7,
  );
