// JavaScript of Tests/SnapshotsPBOPure/AssocIntOps.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic

import { int53__lean_int_add, int53__lean_int_mul } from "../../runtime.js";

/**
 * `test1`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const test1 = (x) =>
  int53__lean_int_add(
    int53__lean_int_add(
      1,
      int53__lean_int_add(
        int53__lean_int_add(
          int53__lean_int_add(
            int53__lean_int_add(int53__lean_int_add(2, x), x),
            x,
          ),
          x,
        ),
        3,
      ),
    ),
    4,
  );

/**
 * `test2`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const test2 = (x) =>
  int53__lean_int_add(
    int53__lean_int_add(
      1,
      int53__lean_int_add(
        2,
        int53__lean_int_add(
          x,
          int53__lean_int_add(
            x,
            int53__lean_int_add(x, int53__lean_int_add(x, 3)),
          ),
        ),
      ),
    ),
    4,
  );

/**
 * `test3`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const test3 = (x) =>
  int53__lean_int_add(
    int53__lean_int_add(
      int53__lean_int_add(
        int53__lean_int_add(
          1,
          int53__lean_int_add(
            2,
            int53__lean_int_add(
              x,
              int53__lean_int_add(
                x,
                int53__lean_int_add(x, int53__lean_int_add(x, 3)),
              ),
            ),
          ),
        ),
        4,
      ),
      int53__lean_int_add(
        int53__lean_int_add(
          int53__lean_int_add(
            int53__lean_int_add(int53__lean_int_add(5, x), x),
            x,
          ),
          x,
        ),
        6,
      ),
    ),
    7,
  );

/**
 * `test4`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const test4 = (x) =>
  int53__lean_int_mul(
    int53__lean_int_mul(
      int53__lean_int_mul(
        int53__lean_int_mul(
          int53__lean_int_mul(int53__lean_int_mul(2, x), x),
          x,
        ),
        x,
      ),
      3,
    ),
    4,
  );

/**
 * `test5`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const test5 = (x) =>
  int53__lean_int_mul(
    int53__lean_int_mul(
      2,
      int53__lean_int_mul(
        x,
        int53__lean_int_mul(
          x,
          int53__lean_int_mul(x, int53__lean_int_mul(x, 3)),
        ),
      ),
    ),
    4,
  );

/**
 * `test6`
 * @param {int53(number)} x
 * @returns {int53(number)}
 */
export const test6 = (x) =>
  int53__lean_int_mul(
    int53__lean_int_mul(
      int53__lean_int_mul(
        int53__lean_int_mul(
          2,
          int53__lean_int_mul(
            x,
            int53__lean_int_mul(
              x,
              int53__lean_int_mul(x, int53__lean_int_mul(x, 3)),
            ),
          ),
        ),
        4,
      ),
      int53__lean_int_mul(
        int53__lean_int_mul(
          int53__lean_int_mul(
            int53__lean_int_mul(int53__lean_int_mul(5, x), x),
            x,
          ),
          x,
        ),
        6,
      ),
    ),
    7,
  );
