// JavaScript of Tests/SnapshotsPBOPure/AssocIntOps.lean, generated by leanscript
// configuration: nat=bigint int=bigint uint64=bigint int64=bigint bitvec=bigint array-fixed-int=typed array-float=typed array-uint64=typed array-int64=typed array-bitvec=round-up array-bool=generic array-char=generic


/**
 * `test1`
 * @param {int(bigint)} x
 * @returns {int(bigint)}
 */
export function test1(x) {
  return 1n + (2n + x + x + x + x + 3n) + 4n;
}

/**
 * `test2`
 * @param {int(bigint)} x
 * @returns {int(bigint)}
 */
export function test2(x) {
  return 1n + (2n + (x + (x + (x + (x + 3n))))) + 4n;
}

/**
 * `test3`
 * @param {int(bigint)} x
 * @returns {int(bigint)}
 */
export function test3(x) {
  return (
    1n + (2n + (x + (x + (x + (x + 3n))))) + 4n + (5n + x + x + x + x + 6n) + 7n
  );
}

/**
 * `test4`
 * @param {int(bigint)} x
 * @returns {int(bigint)}
 */
export function test4(x) {
  return 1n * (2n * x * x * x * x * 3n) * 4n;
}

/**
 * `test5`
 * @param {int(bigint)} x
 * @returns {int(bigint)}
 */
export function test5(x) {
  return 1n * (2n * (x * (x * (x * (x * 3n))))) * 4n;
}

/**
 * `test6`
 * @param {int(bigint)} x
 * @returns {int(bigint)}
 */
export function test6(x) {
  return (
    1n * (2n * (x * (x * (x * (x * 3n))))) * 4n * (5n * x * x * x * x * 6n) * 7n
  );
}
