// JavaScript of Tests/SnapshotsPBOPure/CaptureDerefRegression01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

import { int53__lean_int_add } from "../../runtime.js";

/**
 * `test1`
 * @param {{ _1: int53(number), _2: int53(number) }} v
 * @param {int53(number)} b
 * @returns {int53(number)}
 */
export const test1 = (v, b) => int53__lean_int_add(v._1, b);

/**
 * `test2`
 * @param {{ _1: int53(number), _2: int53(number) }} v
 * @param {int53(number)} a
 * @returns {int53(number)}
 */
export const test2 = (v, a) => int53__lean_int_add(v._1, a);

/**
 * `test3`
 * @param {{ _1: int53(number), _2: int53(number) }} v
 * @param {int53(number)} p1
 * @returns {int53(number)}
 */
export const test3 = (v, p1) => int53__lean_int_add(v._1, p1);

/**
 * `test4`
 * @param {{ _1: int53(number), _2: int53(number) }} v
 * @returns {{ _1: (int53(number)) => int53(number), _2: (int53(number)) => int53(number) }}
 */
export const test4 = (v) => ({
  _1: (x$1) => int53__lean_int_add(v._1, x$1),
  _2: (x$2) => int53__lean_int_add(v._2, x$2),
});

/**
 * `test5`
 * @param {{ _1: int53(number), _2: int53(number) }} v
 * @returns {{ _1: (int53(number)) => int53(number), _2: (int53(number)) => int53(number) }}
 */
export const test5 = (v) => ({
  _1: (x$1) => int53__lean_int_add(v._1, x$1),
  _2: (x$2) => int53__lean_int_add(v._2, x$2),
});

/**
 * `testEven`
 * @param {uint53(number)} n
 * @param {{ _1: int53(number), _2: int53(number) }} b
 * @returns {{ _1: int53(number), _2: int53(number) }}
 */
export const testEven = (n, b) => {
  let p$1 = b._1;
  let p$2 = b._2;
  let j$3 = n;
  while (true) {
    if (j$3 === 0) {
      return { _1: p$1, _2: p$2 };
    }
    j$3--;
    const x$4 = int53__lean_int_add(p$2, 1);
    const x$5 = int53__lean_int_add(p$1, 2);
    if (j$3 === 0) {
      return { _1: x$4, _2: x$5 };
    }
    j$3--;
    p$1 = int53__lean_int_add(x$5, 3);
    p$2 = int53__lean_int_add(x$4, 4);
  }
};

/**
 * `testOdd`
 * @param {uint53(number)} n
 * @param {{ _1: int53(number), _2: int53(number) }} b
 * @returns {{ _1: int53(number), _2: int53(number) }}
 */
export const testOdd = (n, b) => {
  if (n === 0) {
    return b;
  }
  return testEven(n - 1, {
    _1: int53__lean_int_add(b._2, 3),
    _2: int53__lean_int_add(b._1, 4),
  });
};
