// JavaScript of Tests/SnapshotsPBOPure/CaptureDerefRegression01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic
// not translated:
//   testEven: a member of a `mutual` block: only non-recursive and structurally recursive definitions are translated (to `Term`)
//   testOdd: a member of a `mutual` block: only non-recursive and structurally recursive definitions are translated (to `Term`)
//   test4: invalid scope
//   test5: invalid scope

import { int53__lean_int_add } from "../../runtime.js";

/**
 * `test1`
 * @param {{ _1: int53(number), _2: int53(number) }} v
 * @param {int53(number)} b
 * @returns {int53(number)}
 */
export const test1 = (v, b) => {
  const { _1: f$1, _2: f$2 } = v;
  return int53__lean_int_add(f$1, b);
};

/**
 * `test2`
 * @param {{ _1: int53(number), _2: int53(number) }} v
 * @param {int53(number)} a
 * @returns {int53(number)}
 */
export const test2 = (v, a) => {
  const { _1: f$1, _2: f$2 } = v;
  return int53__lean_int_add(f$1, a);
};

/**
 * `test3`
 * @param {{ _1: int53(number), _2: int53(number) }} v
 * @param {int53(number)} p1
 * @returns {int53(number)}
 */
export const test3 = (v, p1) => {
  const { _1: f$1, _2: f$2 } = v;
  return int53__lean_int_add(f$1, p1);
};
