// JavaScript of Tests/SnapshotsPBOPure/CaseGuarded.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

import { int53__lean_int_add } from "../../runtime.js";

/**
 * `test1`
 * @param {int53(number)} n
 * @returns {string}
 */
export const test1 = (n) => {
  if (n < 1) {
    return "n: " + n;
  }
  return n > 1 && n < 100 ? "1 < x < 100: " + n : "catch";
};

/**
 * `test2`
 * @param {int53(number)} a
 * @returns {int53(number)}
 */
export const test2 = (a) => {
  if (a < 1 || a > 1) {
    return a;
  }
  return a === 1 ? 1 : 0;
};

/**
 * `test3`
 * @param {{ _1: int53(number), _2: int53(number), _3: int53(number) }} a
 * @returns {int53(number)}
 */
export const test3 = (a) => {
  const { _1: f$1, _2: f$2, _3: f$3 } = a;
  if (f$1 === f$2 || f$3 === f$2) {
    return f$1;
  }
  return f$1 === f$3 ? f$3 : f$2;
};

/**
 * `instReprRec1.repr`
 * @param {{ _1: int53(number), _2: int53(number), _3: int53(number) }} x
 * @param {uint53(number)} prec
 * @returns {D0}
 */
export const instReprRec1$repr = (x, prec) => ({
  tag: 6,
  _1: {
    tag: 4,
    _1: 2,
    _2: {
      tag: 5,
      _1: {
        tag: 5,
        _1: { tag: 3, _1: "{ " },
        _2: {
          tag: 5,
          _1: {
            tag: 5,
            _1: {
              tag: 5,
              _1: {
                tag: 5,
                _1: {
                  tag: 5,
                  _1: {
                    tag: 5,
                    _1: {
                      tag: 5,
                      _1: {
                        tag: 5,
                        _1: {
                          tag: 5,
                          _1: {
                            tag: 5,
                            _1: {
                              tag: 5,
                              _1: {
                                tag: 5,
                                _1: {
                                  tag: 5,
                                  _1: { tag: 0 },
                                  _2: { tag: 3, _1: "a" },
                                },
                                _2: { tag: 3, _1: " := " },
                              },
                              _2: {
                                tag: 6,
                                _1: {
                                  tag: 4,
                                  _1: 5,
                                  _2: { tag: 3, _1: String(x._1) },
                                },
                                _2: false,
                              },
                            },
                            _2: { tag: 3, _1: "," },
                          },
                          _2: { tag: 1 },
                        },
                        _2: { tag: 3, _1: "b" },
                      },
                      _2: { tag: 3, _1: " := " },
                    },
                    _2: {
                      tag: 6,
                      _1: { tag: 4, _1: 5, _2: { tag: 3, _1: String(x._2) } },
                      _2: false,
                    },
                  },
                  _2: { tag: 3, _1: "," },
                },
                _2: { tag: 1 },
              },
              _2: { tag: 3, _1: "c" },
            },
            _2: { tag: 3, _1: " := " },
          },
          _2: {
            tag: 6,
            _1: { tag: 4, _1: 5, _2: { tag: 3, _1: String(x._3) } },
            _2: false,
          },
        },
      },
      _2: { tag: 3, _1: " }" },
    },
  },
  _2: false,
});

/**
 * `instReprRec2.repr`
 * @param {{ _1: int53(number), _2: int53(number), _3: int53(number) }} x
 * @param {uint53(number)} prec
 * @returns {D0}
 */
export const instReprRec2$repr = (x, prec) => ({
  tag: 6,
  _1: {
    tag: 4,
    _1: 2,
    _2: {
      tag: 5,
      _1: {
        tag: 5,
        _1: { tag: 3, _1: "{ " },
        _2: {
          tag: 5,
          _1: {
            tag: 5,
            _1: {
              tag: 5,
              _1: {
                tag: 5,
                _1: {
                  tag: 5,
                  _1: {
                    tag: 5,
                    _1: {
                      tag: 5,
                      _1: {
                        tag: 5,
                        _1: {
                          tag: 5,
                          _1: {
                            tag: 5,
                            _1: {
                              tag: 5,
                              _1: {
                                tag: 5,
                                _1: {
                                  tag: 5,
                                  _1: { tag: 0 },
                                  _2: { tag: 3, _1: "d" },
                                },
                                _2: { tag: 3, _1: " := " },
                              },
                              _2: {
                                tag: 6,
                                _1: {
                                  tag: 4,
                                  _1: 5,
                                  _2: { tag: 3, _1: String(x._1) },
                                },
                                _2: false,
                              },
                            },
                            _2: { tag: 3, _1: "," },
                          },
                          _2: { tag: 1 },
                        },
                        _2: { tag: 3, _1: "e" },
                      },
                      _2: { tag: 3, _1: " := " },
                    },
                    _2: {
                      tag: 6,
                      _1: { tag: 4, _1: 5, _2: { tag: 3, _1: String(x._2) } },
                      _2: false,
                    },
                  },
                  _2: { tag: 3, _1: "," },
                },
                _2: { tag: 1 },
              },
              _2: { tag: 3, _1: "f" },
            },
            _2: { tag: 3, _1: " := " },
          },
          _2: {
            tag: 6,
            _1: { tag: 4, _1: 5, _2: { tag: 3, _1: String(x._3) } },
            _2: false,
          },
        },
      },
      _2: { tag: 3, _1: " }" },
    },
  },
  _2: false,
});

/**
 * `test4`
 * @param {{ _1: int53(number), _2: int53(number), _3: int53(number) }} a
 * @param {{ _1: int53(number), _2: int53(number), _3: int53(number) }} a1
 * @returns {int53(number)}
 */
export const test4 = (a, a1) => {
  const { _1: f$1, _3: f$2 } = a;
  if (f$1 === 1) {
    const { _1: f$3 } = a1;
    if (f$3 === 1) {
      return 1;
    }
    if (f$3 === 2) {
      return 2;
    }
    if (f$3 === 3) {
      return 3;
    }
    if (f$3 === 4) {
      return 4;
    }
    return f$3 === 5
      ? 5
      : int53__lean_int_add(int53__lean_int_add(f$2, a1._3), 11);
  }
  if (f$1 === 2) {
    const { _1: f$4, _2: f$5 } = a1;
    if (f$4 === 2) {
      return 2;
    }
    if (f$4 === 3) {
      return 3;
    }
    if (f$4 === 1) {
      return 6;
    }
    if (f$4 === 4) {
      if (f$2 === f$5) {
        return 7;
      }
      return f$2 < f$5 ? 8 : 9;
    }
    return int53__lean_int_add(int53__lean_int_add(f$2, a1._3), 11);
  }
  const { _1: f$6, _2: f$7, _3: f$8 } = a1;
  if (f$6 === 2) {
    return 2;
  }
  if (f$6 === 3) {
    return 3;
  }
  if (f$6 === 4) {
    if (f$2 === f$7) {
      return 7;
    }
    return f$2 < f$7 ? 8 : 9;
  }
  if (f$6 === 1 && f$8 === 10) {
    return a._2 === 2 ? 10 : int53__lean_int_add(f$2, 21);
  }
  return int53__lean_int_add(int53__lean_int_add(f$2, f$8), 11);
};

/**
 * `test5`
 * @param {({ tag: 0 } | { tag: 1, _1: ({ tag: 0, _1: int53(number) } | { tag: 1, _1: int53(number) }) })} x_
 * @returns {int53(number)}
 */
export const test5 = (x_) => {
  if (x_.tag === 0) {
    return 5;
  }
  if (x_._1.tag === 0) {
    return x_._1._1 === 2 ? 4 : 5;
  }
  return x_._1._1;
};
