// JavaScript of Tests/SnapshotsPBOPure/CaseLeafTco.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

import {
  array__lean_array_back_opt,
  array__lean_array_push_mutable,
} from "../../runtime.js";

/**
 * `test1Fuel`
 * @param {uint53(number)} a
 * @param {boolean} a1
 * @param {Array<int53(number)>} a2
 * @returns {Array<int53(number)>}
 */
export const test1Fuel = (a, a1, a2) => {
  let p$1 = [...a2];
  let j$2 = a;
  while (true) {
    if (j$2 === 0) {
      return p$1;
    }
    j$2--;
    if (0 < p$1.length) {
      const x$3 = p$1[0];
      if (x$3 === 1) {
        const s$4 = array__lean_array_back_opt(p$1);
        if (s$4.tag === 0) {
          return array__lean_array_push_mutable(p$1, 1);
        }
        const { _1: f$5 } = s$4;
        if (f$5 === 2) {
          return p$1;
        }
        if (a1) {
          return [];
        }
        p$1 = [
          f$5,
          1,
          3,
          f$5,
          5,
          6,
          7,
          8,
          9,
          10,
          1,
          12,
          13,
          14,
          15,
          16,
          17,
          ...p$1,
        ];
      } else {
        const s$6 = array__lean_array_back_opt(p$1);
        if (s$6.tag === 0) {
          return array__lean_array_push_mutable(p$1, x$3);
        }
        const { _1: f$7 } = s$6;
        if (a1) {
          return [];
        }
        p$1 = [
          f$7,
          x$3,
          3,
          f$7,
          5,
          6,
          7,
          8,
          9,
          10,
          x$3,
          12,
          13,
          14,
          15,
          16,
          17,
          ...p$1,
        ];
      }
    } else {
      const s$8 = array__lean_array_back_opt(p$1);
      if (s$8.tag === 0) {
        return p$1;
      }
      return array__lean_array_push_mutable(p$1, s$8._1);
    }
  }
};

/**
 * `test1Fuel`
 * owns `a2`: its caller gives it up, and it may update it in place (5 update(s) in place, 0 copies of arrays)
 * @param {uint53(number)} a
 * @param {boolean} a1
 * @param {Array<int53(number)>} a2
 * @returns {Array<int53(number)>}
 */
export const test1Fuel$$mut_2 = (a, a1, a2) => {
  let p$1 = a2;
  let j$2 = a;
  while (true) {
    if (j$2 === 0) {
      return p$1;
    }
    j$2--;
    if (0 < p$1.length) {
      const x$3 = p$1[0];
      if (x$3 === 1) {
        const s$4 = array__lean_array_back_opt(p$1);
        if (s$4.tag === 0) {
          return array__lean_array_push_mutable(p$1, 1);
        }
        const { _1: f$5 } = s$4;
        if (f$5 === 2) {
          return p$1;
        }
        if (a1) {
          return [];
        }
        p$1 = [
          f$5,
          1,
          3,
          f$5,
          5,
          6,
          7,
          8,
          9,
          10,
          1,
          12,
          13,
          14,
          15,
          16,
          17,
          ...p$1,
        ];
      } else {
        const s$6 = array__lean_array_back_opt(p$1);
        if (s$6.tag === 0) {
          return array__lean_array_push_mutable(p$1, x$3);
        }
        const { _1: f$7 } = s$6;
        if (a1) {
          return [];
        }
        p$1 = [
          f$7,
          x$3,
          3,
          f$7,
          5,
          6,
          7,
          8,
          9,
          10,
          x$3,
          12,
          13,
          14,
          15,
          16,
          17,
          ...p$1,
        ];
      }
    } else {
      const s$8 = array__lean_array_back_opt(p$1);
      if (s$8.tag === 0) {
        return p$1;
      }
      return array__lean_array_push_mutable(p$1, s$8._1);
    }
  }
};

/**
 * `test1FuelCalled`
 * @param {boolean} b
 * @param {Array<int53(number)>} arr
 * @returns {Array<int53(number)>}
 */
export const test1FuelCalled = (b, arr) => test1Fuel(1000000, b, arr);

/**
 * `test1FuelCalled`
 * owns `arr`: its caller gives it up, and it may update it in place (5 update(s) in place, 0 copies of arrays)
 * @param {boolean} b
 * @param {Array<int53(number)>} arr
 * @returns {Array<int53(number)>}
 */
export const test1FuelCalled$$mut_1 = (b, arr) =>
  test1Fuel$$mut_2(1000000, b, arr);
