// Differential checks of CaseJacobs-pbo.js against Lean, generated by leanscript --check
import * as M from "./CaseJacobs-pbo.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("renderExpr({ tag: 3 })", () => M.renderExpr({ tag: 3 }), "Zero", false);
check("renderExpr({ tag: 3 }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 3 }), "Zero", false);
check("renderExpr({ tag: 0, _1: { tag: 3 }, _2: { tag: 3 } })", () => M.renderExpr({ tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }), "Add(Zero Zero)", false);
check("renderExpr({ tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }), "Add(Zero Zero)", false);
check("renderExpr({ tag: 1, _1: { tag: 3 }, _2: { tag: 3 } })", () => M.renderExpr({ tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }), "Mul(Zero Zero)", false);
check("renderExpr({ tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }), "Mul(Zero Zero)", false);
check("renderExpr({ tag: 2, _1: { tag: 3 } })", () => M.renderExpr({ tag: 2, _1: { tag: 3 } }), "Succ(Zero)", false);
check("renderExpr({ tag: 2, _1: { tag: 3 } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 2, _1: { tag: 3 } }), "Succ(Zero)", false);
check("renderExpr({ tag: 0, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 0, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Zero Add(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Zero Add(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 0, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Zero Mul(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Zero Mul(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.renderExpr({ tag: 0, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } }), "Add(Zero Succ(Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } }), "Add(Zero Succ(Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } })", () => M.renderExpr({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "Add(Add(Zero Zero) Zero)", false);
check("renderExpr({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "Add(Add(Zero Zero) Zero)", false);
check("renderExpr({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Add(Zero Zero) Add(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Add(Zero Zero) Add(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Add(Zero Zero) Mul(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Add(Zero Zero) Mul(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.renderExpr({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "Add(Add(Zero Zero) Succ(Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "Add(Add(Zero Zero) Succ(Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } })", () => M.renderExpr({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "Add(Mul(Zero Zero) Zero)", false);
check("renderExpr({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "Add(Mul(Zero Zero) Zero)", false);
check("renderExpr({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Mul(Zero Zero) Add(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Mul(Zero Zero) Add(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Mul(Zero Zero) Mul(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Mul(Zero Zero) Mul(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.renderExpr({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "Add(Mul(Zero Zero) Succ(Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "Add(Mul(Zero Zero) Succ(Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } })", () => M.renderExpr({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } }), "Add(Succ(Zero) Zero)", false);
check("renderExpr({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } }), "Add(Succ(Zero) Zero)", false);
check("renderExpr({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Succ(Zero) Add(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Succ(Zero) Add(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Succ(Zero) Mul(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Add(Succ(Zero) Mul(Zero Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.renderExpr({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "Add(Succ(Zero) Succ(Zero))", false);
check("renderExpr({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "Add(Succ(Zero) Succ(Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 1, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Zero Add(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Zero Add(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 1, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Zero Mul(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Zero Mul(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.renderExpr({ tag: 1, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } }), "Mul(Zero Succ(Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } }), "Mul(Zero Succ(Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } })", () => M.renderExpr({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "Mul(Add(Zero Zero) Zero)", false);
check("renderExpr({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "Mul(Add(Zero Zero) Zero)", false);
check("renderExpr({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Add(Zero Zero) Add(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Add(Zero Zero) Add(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Add(Zero Zero) Mul(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Add(Zero Zero) Mul(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.renderExpr({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "Mul(Add(Zero Zero) Succ(Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "Mul(Add(Zero Zero) Succ(Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } })", () => M.renderExpr({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "Mul(Mul(Zero Zero) Zero)", false);
check("renderExpr({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "Mul(Mul(Zero Zero) Zero)", false);
check("renderExpr({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Mul(Zero Zero) Add(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Mul(Zero Zero) Add(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Mul(Zero Zero) Mul(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Mul(Zero Zero) Mul(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.renderExpr({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "Mul(Mul(Zero Zero) Succ(Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "Mul(Mul(Zero Zero) Succ(Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } })", () => M.renderExpr({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } }), "Mul(Succ(Zero) Zero)", false);
check("renderExpr({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } }), "Mul(Succ(Zero) Zero)", false);
check("renderExpr({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Succ(Zero) Add(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Succ(Zero) Add(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Succ(Zero) Mul(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Mul(Succ(Zero) Mul(Zero Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.renderExpr({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "Mul(Succ(Zero) Succ(Zero))", false);
check("renderExpr({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "Mul(Succ(Zero) Succ(Zero))", false);
check("renderExpr({ tag: 2, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 2, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Succ(Add(Zero Zero))", false);
check("renderExpr({ tag: 2, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 2, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "Succ(Add(Zero Zero))", false);
check("renderExpr({ tag: 2, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.renderExpr({ tag: 2, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Succ(Mul(Zero Zero))", false);
check("renderExpr({ tag: 2, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 2, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "Succ(Mul(Zero Zero))", false);
check("renderExpr({ tag: 2, _1: { tag: 2, _1: { tag: 3 } } })", () => M.renderExpr({ tag: 2, _1: { tag: 2, _1: { tag: 3 } } }), "Succ(Succ(Zero))", false);
check("renderExpr({ tag: 2, _1: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.renderExpr(a0), M.renderExpr(a0)))({ tag: 2, _1: { tag: 2, _1: { tag: 3 } } }), "Succ(Succ(Zero))", false);
check("test1({ tag: 3 })", () => M.test1({ tag: 3 }), "e7: Zero", false);
check("test1({ tag: 3 }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 3 }), "e7: Zero", false);
check("test1({ tag: 0, _1: { tag: 3 }, _2: { tag: 3 } })", () => M.test1({ tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }), "e1", false);
check("test1({ tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }), "e1", false);
check("test1({ tag: 1, _1: { tag: 3 }, _2: { tag: 3 } })", () => M.test1({ tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }), "e2: Zero", false);
check("test1({ tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }), "e2: Zero", false);
check("test1({ tag: 2, _1: { tag: 3 } })", () => M.test1({ tag: 2, _1: { tag: 3 } }), "e7: Succ(Zero)", false);
check("test1({ tag: 2, _1: { tag: 3 } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 2, _1: { tag: 3 } }), "e7: Succ(Zero)", false);
check("test1({ tag: 0, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 0, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Add(Zero Add(Zero Zero))", false);
check("test1({ tag: 0, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Add(Zero Add(Zero Zero))", false);
check("test1({ tag: 0, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 0, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Add(Zero Mul(Zero Zero))", false);
check("test1({ tag: 0, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Add(Zero Mul(Zero Zero))", false);
check("test1({ tag: 0, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.test1({ tag: 0, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } }), "e7: Add(Zero Succ(Zero))", false);
check("test1({ tag: 0, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } }), "e7: Add(Zero Succ(Zero))", false);
check("test1({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } })", () => M.test1({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "e6: Add(Zero Zero)", false);
check("test1({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "e6: Add(Zero Zero)", false);
check("test1({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Add(Add(Zero Zero) Add(Zero Zero))", false);
check("test1({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Add(Add(Zero Zero) Add(Zero Zero))", false);
check("test1({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Add(Add(Zero Zero) Mul(Zero Zero))", false);
check("test1({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Add(Add(Zero Zero) Mul(Zero Zero))", false);
check("test1({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.test1({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "e7: Add(Add(Zero Zero) Succ(Zero))", false);
check("test1({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "e7: Add(Add(Zero Zero) Succ(Zero))", false);
check("test1({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } })", () => M.test1({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "e6: Mul(Zero Zero)", false);
check("test1({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "e6: Mul(Zero Zero)", false);
check("test1({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Add(Mul(Zero Zero) Add(Zero Zero))", false);
check("test1({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Add(Mul(Zero Zero) Add(Zero Zero))", false);
check("test1({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Add(Mul(Zero Zero) Mul(Zero Zero))", false);
check("test1({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Add(Mul(Zero Zero) Mul(Zero Zero))", false);
check("test1({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.test1({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "e7: Add(Mul(Zero Zero) Succ(Zero))", false);
check("test1({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "e7: Add(Mul(Zero Zero) Succ(Zero))", false);
check("test1({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } })", () => M.test1({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } }), "e3: Zero Zero", false);
check("test1({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } }), "e3: Zero Zero", false);
check("test1({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e3: Zero Add(Zero Zero)", false);
check("test1({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e3: Zero Add(Zero Zero)", false);
check("test1({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e3: Zero Mul(Zero Zero)", false);
check("test1({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e3: Zero Mul(Zero Zero)", false);
check("test1({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.test1({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "e3: Zero Succ(Zero)", false);
check("test1({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 0, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "e3: Zero Succ(Zero)", false);
check("test1({ tag: 1, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 1, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e2: Add(Zero Zero)", false);
check("test1({ tag: 1, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 3 }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e2: Add(Zero Zero)", false);
check("test1({ tag: 1, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 1, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e2: Mul(Zero Zero)", false);
check("test1({ tag: 1, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 3 }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e2: Mul(Zero Zero)", false);
check("test1({ tag: 1, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.test1({ tag: 1, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } }), "e2: Succ(Zero)", false);
check("test1({ tag: 1, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 3 }, _2: { tag: 2, _1: { tag: 3 } } }), "e2: Succ(Zero)", false);
check("test1({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } })", () => M.test1({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "e4: Add(Zero Zero)", false);
check("test1({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "e4: Add(Zero Zero)", false);
check("test1({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e5: Zero Zero Add(Zero Zero)", false);
check("test1({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e5: Zero Zero Add(Zero Zero)", false);
check("test1({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e5: Zero Zero Mul(Zero Zero)", false);
check("test1({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e5: Zero Zero Mul(Zero Zero)", false);
check("test1({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.test1({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "e5: Zero Zero Succ(Zero)", false);
check("test1({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "e5: Zero Zero Succ(Zero)", false);
check("test1({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } })", () => M.test1({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "e4: Mul(Zero Zero)", false);
check("test1({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 3 } }), "e4: Mul(Zero Zero)", false);
check("test1({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Mul(Mul(Zero Zero) Add(Zero Zero))", false);
check("test1({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Mul(Mul(Zero Zero) Add(Zero Zero))", false);
check("test1({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Mul(Mul(Zero Zero) Mul(Zero Zero))", false);
check("test1({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Mul(Mul(Zero Zero) Mul(Zero Zero))", false);
check("test1({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.test1({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "e7: Mul(Mul(Zero Zero) Succ(Zero))", false);
check("test1({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "e7: Mul(Mul(Zero Zero) Succ(Zero))", false);
check("test1({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } })", () => M.test1({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } }), "e4: Succ(Zero)", false);
check("test1({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 3 } }), "e4: Succ(Zero)", false);
check("test1({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Mul(Succ(Zero) Add(Zero Zero))", false);
check("test1({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Mul(Succ(Zero) Add(Zero Zero))", false);
check("test1({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Mul(Succ(Zero) Mul(Zero Zero))", false);
check("test1({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Mul(Succ(Zero) Mul(Zero Zero))", false);
check("test1({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } })", () => M.test1({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "e7: Mul(Succ(Zero) Succ(Zero))", false);
check("test1({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 1, _1: { tag: 2, _1: { tag: 3 } }, _2: { tag: 2, _1: { tag: 3 } } }), "e7: Mul(Succ(Zero) Succ(Zero))", false);
check("test1({ tag: 2, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 2, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Succ(Add(Zero Zero))", false);
check("test1({ tag: 2, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 2, _1: { tag: 0, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Succ(Add(Zero Zero))", false);
check("test1({ tag: 2, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } })", () => M.test1({ tag: 2, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Succ(Mul(Zero Zero))", false);
check("test1({ tag: 2, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 2, _1: { tag: 1, _1: { tag: 3 }, _2: { tag: 3 } } }), "e7: Succ(Mul(Zero Zero))", false);
check("test1({ tag: 2, _1: { tag: 2, _1: { tag: 3 } } })", () => M.test1({ tag: 2, _1: { tag: 2, _1: { tag: 3 } } }), "e7: Succ(Succ(Zero))", false);
check("test1({ tag: 2, _1: { tag: 2, _1: { tag: 3 } } }) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))({ tag: 2, _1: { tag: 2, _1: { tag: 3 } } }), "e7: Succ(Succ(Zero))", false);

console.log(`CaseJacobs-pbo.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
