// JavaScript of Tests/SnapshotsPBOPure/CaseRecord.lean, generated by leanscript
// configuration: nat=bigint int=bigint uint64=bigint int64=bigint bitvec=bigint array-fixed-int=typed array-float=typed array-uint64=typed array-int64=typed array-bitvec=round-up array-bool=generic array-char=generic


/**
 * `test1`
 * @param {[int(bigint), int(bigint), int(bigint)]} x
 * @returns {string}
 */
export function test1(x) {
  const [f$1, f$2, f$3] = x;
  if (f$1 === 1n) {
    return "0";
  } else if (f$1 === 2n) {
    if (f$2 === 1n) {
      return "1";
    } else if (f$2 === 2n) {
      if (f$3 === 1n) {
        return "2";
      } else {
        return "3";
      }
    } else if (f$3 === 1n) {
      return "2";
    } else {
      return "catch";
    }
  } else if (f$2 === 1n) {
    return "1";
  } else if (f$3 === 1n) {
    return "2";
  } else {
    return "catch";
  }
}

/**
 * `Test2.test2`
 * @param {[[int(bigint), int(bigint)], [int(bigint), int(bigint)]]} x
 * @returns {int(bigint)}
 */
export function Test2_test2(x) {
  const [f$1, f$2] = x;
  const [f$3, f$4] = f$1;
  if (f$3 === 1n) {
    if (f$4 === 2n) {
      const [f$5, f$6] = f$2;
      if (f$5 === 1n) {
        if (f$6 === 2n) {
          return 1n;
        } else {
          return 3n;
        }
      } else {
        return 3n;
      }
    } else {
      return 4n;
    }
  } else if (f$4 === 2n) {
    const [f$7, f$8] = f$2;
    if (f$7 === 1n) {
      if (f$8 === 2n) {
        return 2n;
      } else {
        return 4n;
      }
    } else {
      return 4n;
    }
  } else {
    return 4n;
  }
}

/**
 * `test3`
 * @param {[int(bigint), int(bigint)]} x
 * @returns {int(bigint)}
 */
export function test3(x) {
  const [f$1, f$2] = x;
  if (0n < f$1) {
    return f$1;
  } else {
    const [f$3, f$4] = x;
    if (1n < f$4) {
      return f$4;
    } else {
      return 3n;
    }
  }
}

/**
 * `test4`
 * @param {[int(bigint), int(bigint)]} x
 * @returns {int(bigint)}
 */
export function test4(x) {
  const [f$1, f$2] = x;
  if (0n < f$1) {
    return f$1;
  } else {
    const [f$3, f$4] = x;
    if (1n < f$4) {
      return f$4;
    } else {
      return 3n;
    }
  }
}

/**
 * `test5`
 * @param {[int(bigint), int(bigint)]} x
 * @returns {int(bigint)}
 */
export function test5(x) {
  const [f$1, f$2] = x;
  if (0n < f$1) {
    return f$1;
  } else {
    const [f$3, f$4] = x;
    if (0n < f$4) {
      return f$4;
    } else {
      return 0n;
    }
  }
}

/**
 * `test6`
 * @param {[int(bigint), int(bigint)]} x
 * @returns {int(bigint)}
 */
export function test6(x) {
  const [f$1, f$2] = x;
  if (0n < f$1) {
    return f$1;
  } else if (0n < f$2) {
    return f$2;
  } else {
    return 0n;
  }
}
