// Differential checks of CasePartial-faithful.js against Lean, generated by leanscript --check
import * as M from "./CasePartial-faithful.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("test1(-7n)", () => M.test1(-7n), "threw: PANIC at test1 CasePartial:5:9: mypanic -7", false);
check("test1(-1n)", () => M.test1(-1n), "threw: PANIC at test1 CasePartial:5:9: mypanic -1", false);
check("test1(0n)", () => M.test1(0n), "threw: PANIC at test1 CasePartial:5:9: mypanic 0", false);
check("test1(1n)", () => M.test1(1n), "1", false);
check("test1(2n)", () => M.test1(2n), "2", false);
check("test1(3n)", () => M.test1(3n), "3", false);
check("test1(12n)", () => M.test1(12n), "threw: PANIC at test1 CasePartial:5:9: mypanic 12", false);

console.log(`CasePartial-faithful.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
