// Differential checks of CaseNumber-pbo.js against Lean, generated by leanscript --check
import * as M from "./CaseNumber-pbo.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("test1(0)", () => M.test1(0), "catch", false);
check("test1(0.5)", () => M.test1(0.5), "catch", false);
check("test1(1)", () => M.test1(1), "1", false);
check("test1(2)", () => M.test1(2), "2", false);
check("test1(3)", () => M.test1(3), "3", false);
check("test1(2.25)", () => M.test1(2.25), "catch", false);
check("test1(30)", () => M.test1(30), "catch", false);
check("test1(-1.5)", () => M.test1(-1.5), "catch", false);
check("test2(0)", () => M.test2(0), "catch", false);
check("test2(0.5)", () => M.test2(0.5), "catch", false);
check("test2(1)", () => M.test2(1), "1", false);
check("test2(2)", () => M.test2(2), "2", false);
check("test2(3)", () => M.test2(3), "3", false);
check("test2(2.25)", () => M.test2(2.25), "catch", false);
check("test2(30)", () => M.test2(30), "catch", false);
check("test2(-1.5)", () => M.test2(-1.5), "catch", false);

console.log(`CaseNumber-pbo.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
