// JavaScript of Tests/SnapshotsPBOPure/CaseHeuristics.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `testP`
 * @param {int53(number)} a
 * @param {int53(number)} a1
 * @param {int53(number)} a2
 * @returns {int53(number)}
 */
export const testP = (a, a1, a2) => {
  if (a === 1) {
    if (a1 === 2) {
      if (a2 === 1) {
        return 1;
      }
      if (a2 === 2) {
        return 2;
      }
      if (a2 === 3) {
        return 3;
      }
      return a2 === 4 ? 4 : 5;
    }
    return a2 === 4 ? 4 : 5;
  }
  if (a1 === 2) {
    return a2 === 3 ? 3 : 5;
  }
  return 5;
};

/**
 * `testPB`
 * @param {({ tag: 0 } | { tag: 1, _1: int53(number) } | { tag: 2, _1: int53(number), _2: int53(number) })} a
 * @param {({ tag: 0 } | { tag: 1, _1: int53(number) } | { tag: 2, _1: int53(number), _2: int53(number) })} a1
 * @returns {int53(number)}
 */
export const testPB = (a, a1) => {
  if (a.tag === 0) {
    if (a1.tag === 0) {
      return 3;
    }
    return a1.tag === 1 ? 4 : 4;
  }
  if (a.tag === 1) {
    if (a._1 === 1) {
      if (a1.tag === 0) {
        return 3;
      }
      if (a1.tag === 1) {
        return a1._1 === 1 ? 1 : 4;
      }
      return 4;
    }
    if (a1.tag === 0) {
      return 3;
    }
    return a1.tag === 1 ? 4 : 4;
  }
  if (a._1 === 2 && a._2 === 3) {
    if (a1.tag === 0) {
      return 3;
    }
    if (a1.tag === 1) {
      return 4;
    }
    if (a1._1 === 2) {
      return a1._2 === 3 ? 2 : 4;
    }
    return 4;
  }
  if (a1.tag === 0) {
    return 3;
  }
  return a1.tag === 1 ? 4 : 4;
};

/**
 * `testPBA`
 * @param {({ tag: 0 } | { tag: 1, _1: int53(number) } | { tag: 2, _1: int53(number), _2: int53(number) })} a
 * @param {({ tag: 0 } | { tag: 1, _1: int53(number) } | { tag: 2, _1: int53(number), _2: int53(number) })} a1
 * @returns {int53(number)}
 */
export const testPBA = (a, a1) => {
  if (a.tag === 0) {
    return 4;
  }
  if (a.tag === 1) {
    const { _1: f$1 } = a;
    if (f$1 === 1) {
      if (a1.tag === 0) {
        return 4;
      }
      if (a1.tag === 1) {
        return a1._1 === 1 ? 1 : 4;
      }
      return 4;
    }
    if (f$1 === 2) {
      if (a1.tag === 0) {
        return 4;
      }
      if (a1.tag === 1) {
        return a1._1 === 2 ? 2 : 4;
      }
      return 4;
    }
    return 4;
  }
  if (a._1 === 1) {
    if (a1.tag === 0) {
      return 4;
    }
    return a1.tag === 1 ? 4 : 3;
  }
  return 4;
};

/**
 * `testPBAN`
 * @param {({ tag: 0 } | { tag: 1, _1: int53(number) } | { tag: 2, _1: int53(number), _2: int53(number) })} a
 * @param {({ tag: 0 } | { tag: 1, _1: int53(number) } | { tag: 2, _1: int53(number), _2: int53(number) })} a1
 * @returns {int53(number)}
 */
export const testPBAN = (a, a1) => {
  if (a.tag === 0) {
    return 4;
  }
  if (a.tag === 1) {
    const { _1: f$1 } = a;
    if (f$1 === 1) {
      if (a1.tag === 0) {
        return 4;
      }
      if (a1.tag === 1) {
        return a1._1 === 1 ? 1 : 4;
      }
      return 4;
    }
    if (f$1 === 2) {
      if (a1.tag === 0) {
        return 4;
      }
      if (a1.tag === 1) {
        return a1._1 === 2 ? 2 : 4;
      }
      return 4;
    }
    return 4;
  }
  if (a1.tag === 0) {
    return 4;
  }
  return a1.tag === 1 ? 4 : 3;
};
