// JavaScript of Tests/SnapshotsPBOPure/CaseArray.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic

import { uint53__lean_array_get } from "../../runtime.js";

/**
 * `test1`
 * @param {Array<uint53(number)>} a
 * @returns {string}
 */
export const test1 = (a) => {
  if (a.length === 0) {
    return "0";
  } else if (a.length === 1) {
    if (uint53__lean_array_get(0, a, 0) === 1) {
      return "1";
    } else {
      return "any1";
    }
  } else if (a.length === 2) {
    if (uint53__lean_array_get(0, a, 1) === 2) {
      return "2";
    } else {
      return "catch";
    }
  } else if (a.length === 3) {
    return "3";
  } else {
    return "catch";
  }
};
