// JavaScript of Tests/SnapshotsPBOPure/DefaultRulesSemigroup01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `test1`
 * @param {(int53(number)) => string} f
 * @param {(int53(number)) => string} g
 * @param {int53(number)} x
 * @returns {string}
 */
export const test1 = (f, g, x) => f(x) + g(x);

/**
 * `test2`
 * @param {(int53(number)) => string} f
 * @param {(int53(number)) => string} g
 * @param {int53(number)} x
 * @returns {string}
 */
export const test2 = (f, g, x) => {
  const fx = f(x);
  const gx = g(x);
  return fx + gx + fx + gx;
};
