// JavaScript of Tests/SnapshotsPBOPure/DefaultRulesSemigroup02.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic
// not translated:
//   instReprR.repr: LeanScript: the recursive type Std.Format is not declared in any signature; declare it with `leanscript_signature`
//   Inline.test3: LeanScript: the recursive type List String is not declared in any signature; declare it with `leanscript_signature`
//   Inline.test4: LeanScript: the recursive type List String is not declared in any signature; declare it with `leanscript_signature`
//   Noinline.test3: LeanScript: the recursive type List String is not declared in any signature; declare it with `leanscript_signature`
//   Noinline.test4: LeanScript: the recursive type List String is not declared in any signature; declare it with `leanscript_signature`
//   AlwaysInline.test3: LeanScript: the recursive type List String is not declared in any signature; declare it with `leanscript_signature`
//   AlwaysInline.test4: LeanScript: the recursive type List String is not declared in any signature; declare it with `leanscript_signature`
//   InlineIfReduceInline.test3: LeanScript: the recursive type List String is not declared in any signature; declare it with `leanscript_signature`
//   InlineIfReduceInline.test4: LeanScript: the recursive type List String is not declared in any signature; declare it with `leanscript_signature`

// ---- runtime helpers ----

function $arrayPush(a, x) {
  if (Array.isArray(a)) return [...a, x];
  const r = new a.constructor(a.length + 1);
  r.set(a);
  r[a.length] = x;
  return r;
}

function lean_array_push(a, b) {
  return $arrayPush(a, b);
}

// ---- exported functions ----

/**
 * `Inline.appendR`
 * @param {[string, Array<string>]} a
 * @param {[string, Array<string>]} b
 * @returns {[string, Array<string>]}
 */
export const Inline_appendR = (a, b) => {
  const [f$1, f$2] = a;
  const [f$3, f$4] = b;
  const [f$5, f$6] = b;
  const [f$7, f$8] = a;
  let acc$9 = f$8;
  for (const e$10 of f$6) {
    acc$9 = lean_array_push(acc$9, e$10);
  }
  return [f$1 + f$3, acc$9];
};

/**
 * `Inline.test1`
 * @param {[string, Array<string>]} a
 * @param {[string, Array<string>]} a1
 * @returns {[string, Array<string>]}
 */
export const Inline_test1 = (a, a1) => {
  const [f$1, f$2] = a;
  const [f$3, f$4] = a1;
  const [f$5, f$6] = a1;
  const [f$7, f$8] = a;
  let acc$9 = f$8;
  for (const e$10 of f$6) {
    acc$9 = lean_array_push(acc$9, e$10);
  }
  return [f$1 + f$3, acc$9];
};

/**
 * `Inline.test2`
 * @param {[string, Array<string>]} a
 * @param {[string, Array<string>]} b
 * @returns {[string, Array<string>]}
 */
export const Inline_test2 = (a, b) => {
  const k$1 = (x$2) => (x$4) => {
    const [f$5, f$6] = x$2;
    const [f$7, f$8] = x$4;
    const [f$9, f$10] = x$4;
    const [f$11, f$12] = x$2;
    let acc$13 = f$12;
    for (const e$14 of f$10) {
      acc$13 = lean_array_push(acc$13, e$14);
    }
    return [f$5 + f$7, acc$13];
  };
  const x$16 = k$1(a);
  return x$16(b);
};

/**
 * `Noinline.appendR`
 * @param {[string, Array<string>]} a
 * @param {[string, Array<string>]} b
 * @returns {[string, Array<string>]}
 */
export const Noinline_appendR = (a, b) => {
  const [f$1, f$2] = a;
  const [f$3, f$4] = b;
  const [f$5, f$6] = b;
  const [f$7, f$8] = a;
  let acc$9 = f$8;
  for (const e$10 of f$6) {
    acc$9 = lean_array_push(acc$9, e$10);
  }
  return [f$1 + f$3, acc$9];
};

/**
 * `Noinline.test1`
 * @param {[string, Array<string>]} a
 * @param {[string, Array<string>]} a1
 * @returns {[string, Array<string>]}
 */
export const Noinline_test1 = (a, a1) => {
  const [f$1, f$2] = a;
  const [f$3, f$4] = a1;
  const [f$5, f$6] = a1;
  const [f$7, f$8] = a;
  let acc$9 = f$8;
  for (const e$10 of f$6) {
    acc$9 = lean_array_push(acc$9, e$10);
  }
  return [f$1 + f$3, acc$9];
};

/**
 * `Noinline.test2`
 * @param {[string, Array<string>]} a
 * @param {[string, Array<string>]} b
 * @returns {[string, Array<string>]}
 */
export const Noinline_test2 = (a, b) => {
  const k$1 = (x$2) => (x$4) => {
    const [f$5, f$6] = x$2;
    const [f$7, f$8] = x$4;
    const [f$9, f$10] = x$4;
    const [f$11, f$12] = x$2;
    let acc$13 = f$12;
    for (const e$14 of f$10) {
      acc$13 = lean_array_push(acc$13, e$14);
    }
    return [f$5 + f$7, acc$13];
  };
  const x$16 = k$1(a);
  return x$16(b);
};

/**
 * `AlwaysInline.appendR`
 * @param {[string, Array<string>]} a
 * @param {[string, Array<string>]} b
 * @returns {[string, Array<string>]}
 */
export const AlwaysInline_appendR = (a, b) => {
  const [f$1, f$2] = a;
  const [f$3, f$4] = b;
  const [f$5, f$6] = b;
  const [f$7, f$8] = a;
  let acc$9 = f$8;
  for (const e$10 of f$6) {
    acc$9 = lean_array_push(acc$9, e$10);
  }
  return [f$1 + f$3, acc$9];
};

/**
 * `AlwaysInline.test1`
 * @param {[string, Array<string>]} a
 * @param {[string, Array<string>]} a1
 * @returns {[string, Array<string>]}
 */
export const AlwaysInline_test1 = (a, a1) => {
  const [f$1, f$2] = a;
  const [f$3, f$4] = a1;
  const [f$5, f$6] = a1;
  const [f$7, f$8] = a;
  let acc$9 = f$8;
  for (const e$10 of f$6) {
    acc$9 = lean_array_push(acc$9, e$10);
  }
  return [f$1 + f$3, acc$9];
};

/**
 * `AlwaysInline.test2`
 * @param {[string, Array<string>]} a
 * @param {[string, Array<string>]} b
 * @returns {[string, Array<string>]}
 */
export const AlwaysInline_test2 = (a, b) => {
  const k$1 = (x$2) => (x$4) => {
    const [f$5, f$6] = x$2;
    const [f$7, f$8] = x$4;
    const [f$9, f$10] = x$4;
    const [f$11, f$12] = x$2;
    let acc$13 = f$12;
    for (const e$14 of f$10) {
      acc$13 = lean_array_push(acc$13, e$14);
    }
    return [f$5 + f$7, acc$13];
  };
  const x$16 = k$1(a);
  return x$16(b);
};

/**
 * `InlineIfReduceInline.appendR`
 * @param {[string, Array<string>]} a
 * @param {[string, Array<string>]} b
 * @returns {[string, Array<string>]}
 */
export const InlineIfReduceInline_appendR = (a, b) => {
  const [f$1, f$2] = a;
  const [f$3, f$4] = b;
  const [f$5, f$6] = b;
  const [f$7, f$8] = a;
  let acc$9 = f$8;
  for (const e$10 of f$6) {
    acc$9 = lean_array_push(acc$9, e$10);
  }
  return [f$1 + f$3, acc$9];
};

/**
 * `InlineIfReduceInline.test1`
 * @param {[string, Array<string>]} a
 * @param {[string, Array<string>]} a1
 * @returns {[string, Array<string>]}
 */
export const InlineIfReduceInline_test1 = (a, a1) => {
  const [f$1, f$2] = a;
  const [f$3, f$4] = a1;
  const [f$5, f$6] = a1;
  const [f$7, f$8] = a;
  let acc$9 = f$8;
  for (const e$10 of f$6) {
    acc$9 = lean_array_push(acc$9, e$10);
  }
  return [f$1 + f$3, acc$9];
};

/**
 * `InlineIfReduceInline.test2`
 * @param {[string, Array<string>]} a
 * @param {[string, Array<string>]} b
 * @returns {[string, Array<string>]}
 */
export const InlineIfReduceInline_test2 = (a, b) => {
  const k$1 = (x$2) => (x$4) => {
    const [f$5, f$6] = x$2;
    const [f$7, f$8] = x$4;
    const [f$9, f$10] = x$4;
    const [f$11, f$12] = x$2;
    let acc$13 = f$12;
    for (const e$14 of f$10) {
      acc$13 = lean_array_push(acc$13, e$14);
    }
    return [f$5 + f$7, acc$13];
  };
  const x$16 = k$1(a);
  return x$16(b);
};
