// JavaScript of Tests/SnapshotsPBOPure/EsPrecedence02.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic

/**
 * `test1`
 * @param {float} a
 * @returns {float}
 */
export const test1 = (a) => a + (a + (a + a));

/**
 * `test2`
 * @param {float} a
 * @returns {float}
 */
export const test2 = (a) => a + a + a + a;

/**
 * `test3`
 * @param {float} a
 * @returns {float}
 */
export const test3 = (a) => a + (a + (a - a));

/**
 * `test4`
 * @param {float} a
 * @returns {float}
 */
export const test4 = (a) => a - a + a + a;

/**
 * `test5`
 * @param {float} a
 * @returns {float}
 */
export const test5 = (a) => a - a + (a + a);
