// JavaScript of Tests/SnapshotsPBOPure/EsSharedElse.lean, generated by leanscript
// configuration: nat=bigint int=bigint uint64=bigint int64=bigint bitvec=bigint array-fixed-int=typed array-float=typed array-uint64=typed array-int64=typed array-bitvec=round-up array-bool=generic array-char=generic


/**
 * `test1`
 * @param {boolean} a
 * @param {boolean} b
 * @param {boolean} c
 * @returns {int(bigint)}
 */
export function test1(a, b, c) {
  if (a) {
    if (b) {
      return 1n;
    } else if (c) {
      return 2n;
    } else {
      return 3n;
    }
  } else if (c) {
    return 2n;
  } else {
    return 3n;
  }
}
