// JavaScript of Tests/SnapshotsPBOPure/EtaReduceRegression01.lean, generated by leanscript
// configuration: nat=bigint int=bigint uint64=bigint int64=bigint bitvec=bigint array-fixed-int=typed array-float=typed array-uint64=typed array-int64=typed array-bitvec=round-up array-bool=generic array-char=generic
// not translated:
//   identity: LeanScript: `identity` is universe polymorphic
//   fold: LeanScript: `fold` is universe polymorphic


/**
 * `test`
 * @param {([0] | [1, string])} a
 * @returns {string}
 */
export function test(a) {
  if (a[0] === 0) {
    return "";
  } else {
    const [, f$1] = a;
    return f$1;
  }
}
