// JavaScript of Tests/SnapshotsPBOPure/FunctionCompose02.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `test1`
 * @param {(int53(number)) => int53(number)} f
 * @param {(int53(number)) => int53(number)} g
 * @param {int53(number)} p2
 * @returns {int53(number)}
 */
export const test1 = (f, g, p2) => f(g(p2));

/**
 * `test2`
 * @param {(int53(number)) => int53(number)} f
 * @param {(int53(number)) => int53(number)} g
 * @param {int53(number)} p2
 * @returns {int53(number)}
 */
export const test2 = (f, g, p2) => g(f(g(p2)));

/**
 * `test3`
 * @param {(int53(number)) => int53(number)} f
 * @param {(int53(number)) => int53(number)} g
 * @param {int53(number)} p2
 * @returns {int53(number)}
 */
export const test3 = (f, g, p2) => f(g(f(g(p2))));

/**
 * `test4`
 * @param {(int53(number)) => int53(number)} f
 * @param {(int53(number)) => int53(number)} g
 * @param {int53(number)} p2
 * @returns {int53(number)}
 */
export const test4 = (f, g, p2) => g(f(g(f(g(p2)))));
