// JavaScript of Tests/SnapshotsPBOPure/FunctionCompose01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic

/**
 * `f`
 * @param {string} x
 * @returns {string}
 */
export const f = (x) => "a";

/**
 * `g`
 * @param {string} x
 * @returns {string}
 */
export const g = (x) => "b";

/**
 * `test1`
 * @param {string} a
 * @returns {string}
 */
export const test1 = f;

/**
 * `test2`
 * @param {string} a
 * @returns {string}
 */
export const test2 = g;

/**
 * `test3`
 * @param {string} a
 * @returns {string}
 */
export const test3 = f;

/**
 * `test4`
 * @param {string} a
 * @returns {string}
 */
export const test4 = g;
