// JavaScript of Tests/SnapshotsPBOPure/Fusion01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   mapF: LeanScript: not a type former application Type
//   filterMapF: LeanScript: not a type former application Type
//   filterF: LeanScript: the parameter `α` of `filterMapF` is a type
//   fromArray: LeanScript: not a type former application Type
//   toArray: LeanScript: the polymorphic function fold.1 is applied to the type List Nat where the language reads it at the stand-in Nat
//   overArray: LeanScript: the parameter `α` of `toArray` is a type
//   dropPrefix1: LeanScript: `String.Pos.Raw` is a leaf of the language: its values are literals, not constructor applications
//   test: LeanScript: the parameter `α` of `overArray` is a type

