// JavaScript of Tests/SnapshotsPBOPure/Fusion02.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   toArrayLoop: defined by well-founded recursion: only non-recursive and structurally recursive definitions are translated (to `Term`)
//   filterMapStep: defined by well-founded recursion: only non-recursive and structurally recursive definitions are translated (to `Term`)
//   fromArray: LeanScript: the constructor `Unfold.mk` has a field whose value is a type (existential typing is not supported)
//   toArray: LeanScript: the constructor `Unfold.mk` has a field whose value is a type (existential typing is not supported)
//   mapU: LeanScript: the constructor `Unfold.mk` has a field whose value is a type (existential typing is not supported)
//   filterMapU: LeanScript: the constructor `Unfold.mk` has a field whose value is a type (existential typing is not supported)
//   filterU: LeanScript: the constructor `Unfold.mk` has a field whose value is a type (existential typing is not supported)
//   overArray: LeanScript: the constructor `Unfold.mk` has a field whose value is a type (existential typing is not supported)
//   dropPrefix1: LeanScript: `String.Pos.Raw` is a leaf of the language: its values are literals, not constructor applications
//   test: LeanScript: the parameter `α` of `overArray` is a type

