// JavaScript of Tests/SnapshotsPBOPure/Heterogeneous01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

import { int53__lean_int_add } from "../../runtime.js";

/**
 * `test1`
 * @type {{ _1: int53(number), _2: { _1: string, _2: float }, _3: boolean }}
 */
export const test1 = { _1: 13, _2: { _1: "bar", _2: 42 }, _3: false };

/**
 * `test2`
 * @param {{ _1: int53(number), _2: float, _3: boolean }} args
 * @returns {{ _1: int53(number), _2: { _1: string, _2: float }, _3: boolean }}
 */
export const test2 = (args) => ({
  _1: int53__lean_int_add(args._1, 1),
  _2: { _1: "bar", _2: args._2 },
  _3: !args._3,
});
