// JavaScript of Tests/SnapshotsPBOPure/InlineNever.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `foo`
 * @type {string}
 */
export const foo = "foo";

/**
 * `test`
 * @type {string}
 */
export const test = "foo";
