// JavaScript of Tests/SnapshotsPBOPure/InlineReferencePrimOpBoolean.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic
// not translated:
//   fn: LeanScript: the parameter `α` of `fn` is a type


/**
 * `test1`
 * @returns {int53(number)}
 */
export const test1 = () => 42;

/**
 * `test2`
 * @returns {int53(number)}
 */
export const test2 = () => 42;

/**
 * `test3`
 * @returns {int53(number)}
 */
export const test3 = () => 42;

/**
 * `extern1`
 * @returns {[boolean, int53(number), boolean, boolean]}
 */
export const extern1 = () => [true, 0, true, false];

/**
 * `test4`
 * @returns {int53(number)}
 */
export const test4 = () => 42;

/**
 * `test5`
 * @returns {int53(number)}
 */
export const test5 = () => 42;

/**
 * `test6`
 * @returns {int53(number)}
 */
export const test6 = () => 42;
