// JavaScript of Tests/SnapshotsPBOPure/InlineReferencePrimOpInt.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   fn: LeanScript: the parameter `α` of `fn` is a type

/**
 * `localTest`
 * @param {({ _1: int53(number), _2: int53(number), _3: int53(number) }) => int53(number)} f
 * @returns {int53(number)}
 */
export const localTest = (f) => {
  const x$1 = f({ _1: 99, _2: 0, _3: 11 });
  return x$1 === -2147483648 ? 0 : x$1;
};

/**
 * `test1`
 * @type {int53(number)}
 */
export const test1 = 110;

/**
 * `test2`
 * @type {int53(number)}
 */
export const test2 = 88;

/**
 * `test3`
 * @type {int53(number)}
 */
export const test3 = 1089;

/**
 * `test4`
 * @type {int53(number)}
 */
export const test4 = 9;

/**
 * `extern`
 * @type {{ _1: int53(number), _2: int53(number), _3: int53(number) }}
 */
export const extern = { _1: 99, _2: 0, _3: 11 };

/**
 * `externTest`
 * @param {({ _1: int53(number), _2: int53(number), _3: int53(number) }) => int53(number)} f
 * @returns {int53(number)}
 */
export const externTest = (f) => {
  const x$1 = f({ _1: 99, _2: 0, _3: 11 });
  return x$1 === -2147483648 ? -2147483648 : x$1;
};

/**
 * `test5`
 * @type {int53(number)}
 */
export const test5 = 110;

/**
 * `test6`
 * @type {int53(number)}
 */
export const test6 = 88;

/**
 * `test7`
 * @type {int53(number)}
 */
export const test7 = 1089;

/**
 * `test8`
 * @type {int53(number)}
 */
export const test8 = 9;
