// JavaScript of Tests/SnapshotsPBOPure/InlineReferenceOpArrayLength.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   test2: Application type mismatch: The argument rfl has type ?m.928 = ?m.928 but is expected to have type LeanScript.Lvl.meet ?m.848 (LeanScript.Lvl.meet ?m.909 (LeanScript.Lvl.meet none none)) = some ?m.830 in the application LeanScript.Neu.extern (LeanScript.LeanInitPureExtern.lean_array_get (LeanScript.Ty.prim LeanScript.LeanPrimTy.int).array) (LeanScript.Args.cons ?m.891 (LeanScript.Args.cons (LeanScript.PExpr.kvar LeanScript.KVar.head) (LeanScript.Args.cons (LeanScript.PExpr.lit LeanScript.LeanPrimTy.nat 0) LeanScript.Args.nil))) ⋯

/**
 * `test1`
 * @param {() => int53(number)} fn
 * @returns {Array<int53(number)>}
 */
export const test1 = (fn) => {
  const x$1 = fn();
  const k$2 = [1, 2, x$1];
  return k$2.length === 3 ? k$2 : [];
};

/**
 * `fn'`
 * @returns {int53(number)}
 */
export const fn_ = () => {
  const k$2 = () => 0;
  const f$1 = k$2;
  return f$1();
};

/**
 * `extern1`
 * @returns {Array<int53(number)>}
 */
export const extern1 = () => [1, 2, 0];

/**
 * `extern2`
 * @returns {Array<Array<int53(number)>>}
 */
export const extern2 = () => [[1, 2, 0], [3], [0]];

/**
 * `test3`
 * @returns {Array<int53(number)>}
 */
export const test3 = () => [1, 2, 0];

/**
 * `test4`
 * @returns {Array<Array<int53(number)>>}
 */
export const test4 = () => [[1, 2, 0], [3], [0]];
