// JavaScript of Tests/SnapshotsPBOPure/KnownConstructors05.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

const $k1 = { tag: 1, _1: 0 };
const $k2 = { tag: 1, _1: 1 };
const $k3 = { tag: 1, _1: 2 };
const $k4 = { tag: 1, _1: 3 };
const $tag0 = { tag: 0 };

/**
 * `fromString`
 * @param {string} a
 * @returns {({ tag: 0 } | { tag: 1, _1: enum4@0 })}
 */
export const fromString = (a) => {
  if (a === "foo") {
    return $k1;
  }
  if (a === "bar") {
    return $k2;
  }
  if (a === "baz") {
    return $k3;
  }
  return a === "qux" ? $k4 : $tag0;
};

/**
 * `test`
 * @param {string} a
 * @returns {int53(number)}
 */
export const test = (a) => {
  const x$1 = fromString(a);
  if (x$1.tag === 0) {
    return 0;
  }
  if (x$1._1 === 0) {
    return 1;
  }
  if (x$1._1 === 1) {
    return 2;
  }
  return x$1._1 === 2 ? 3 : 4;
};
