// JavaScript of Tests/SnapshotsPBOPure/KnownConstructors02.lean, generated by leanscript
// configuration: nat=bigint int=bigint uint64=bigint int64=bigint bitvec=bigint array-fixed-int=typed array-float=typed array-uint64=typed array-int64=typed array-bitvec=round-up array-bool=generic array-char=generic


/**
 * `test`
 * @param {([0, int(bigint)] | [1, int(bigint)])} a
 * @returns {int(bigint)}
 */
export function test(a) {
  if (a[0] === 0) {
    const [, f$1] = a;
    return f$1;
  } else {
    const [, f$2] = a;
    return f$2;
  }
}
