// JavaScript of Tests/SnapshotsPBOPure/KnownConstructors05.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `fromString`
 * @param {string} a
 * @returns {({ tag: 0 } | { tag: 1, _1: enum4@0 })}
 */
export const fromString = (a) => {
  if (a === "foo") {
    return { tag: 1, _1: 0 };
  }
  if (a === "bar") {
    return { tag: 1, _1: 1 };
  }
  if (a === "baz") {
    return { tag: 1, _1: 2 };
  }
  return a === "qux" ? { tag: 1, _1: 3 } : { tag: 0 };
};

/**
 * `test`
 * @param {string} a
 * @returns {int53(number)}
 */
export const test = (a) => {
  const k$2 = (x$1) => {
    if (x$1 === "foo") {
      return { tag: 1, _1: 0 };
    }
    if (x$1 === "bar") {
      return { tag: 1, _1: 1 };
    }
    if (x$1 === "baz") {
      return { tag: 1, _1: 2 };
    }
    return x$1 === "qux" ? { tag: 1, _1: 3 } : { tag: 0 };
  };
  const x$3 = k$2(a);
  if (x$3.tag === 0) {
    return 0;
  }
  if (x$3._1 === 0) {
    return 1;
  }
  if (x$3._1 === 1) {
    return 2;
  }
  return x$3._1 === 2 ? 3 : 4;
};
