// JavaScript of Tests/SnapshotsPBOPure/KnownConstructor07.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   instReprPairBox.repr: LeanScript: the recursive type Std.Format is not declared in any signature; declare it with `leanscript_signature`

import { int53__lean_int_add, int53__lean_int_sub } from "../../runtime.js";

/**
 * `test`
 * @param {(int53(number)) => int53(number)} f
 * @param {int53(number)} y
 * @returns {{ _1: int53(number), _2: int53(number) }}
 */
export const test = (f, y) => {
  const x$1 = f(y);
  return { _1: int53__lean_int_add(x$1, 1), _2: int53__lean_int_sub(x$1, 2) };
};
