// Differential checks of KnownConstructors-faithful.js against Lean, generated by leanscript --check
import * as M from "./KnownConstructors-faithful.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  return String(v);
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("known1()", () => M.known1(), "b", false);
check("test6(\"\")", () => M.test6(""), "0", false);
check("test6(\"a\")", () => M.test6("a"), "0", false);
check("test6(\"hello world\")", () => M.test6("hello world"), "0", false);
check("test6(\"héllo, wörld\")", () => M.test6("héllo, wörld"), "0", false);
check("test6(\"abcabc\")", () => M.test6("abcabc"), "0", false);

console.log(`KnownConstructors-faithful.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
