// JavaScript of Tests/SnapshotsPBOPure/KnownConstructors05.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic

const $k1 = { tag: 1, _1: 0 };
const $k2 = { tag: 1, _1: 1 };
const $k3 = { tag: 1, _1: 2 };
const $k4 = { tag: 1, _1: 3 };
const $tag0 = { tag: 0 };
const $k6 = (x$1) => {
  if (x$1 === "foo") {
    return $k1;
  } else if (x$1 === "bar") {
    return $k2;
  } else if (x$1 === "baz") {
    return $k3;
  } else if (x$1 === "qux") {
    return $k4;
  } else {
    return $tag0;
  }
};

/**
 * `fromString`
 * @param {string} a
 * @returns {({ tag: 0 } | { tag: 1, _1: enum4@0 })}
 */
export const fromString = (a) => {
  if (a === "foo") {
    return $k1;
  } else if (a === "bar") {
    return $k2;
  } else if (a === "baz") {
    return $k3;
  } else if (a === "qux") {
    return $k4;
  } else {
    return $tag0;
  }
};

/**
 * `test`
 * @param {string} a
 * @returns {int53(number)}
 */
export const test = (a) => {
  const k$1 = $k6;
  const x$2 = k$1(a);
  if (x$2.tag === 0) {
    return 0;
  } else {
    const { _1: f$3 } = x$2;
    if (f$3 === 0) {
      return 1;
    } else if (f$3 === 1) {
      return 2;
    } else if (f$3 === 2) {
      return 3;
    } else {
      return 4;
    }
  }
};
