// JavaScript of Tests/SnapshotsPBOPure/KnownConstructors03.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `test`
 * @param {int53(number)} x
 * @returns {string}
 */
export const test = (x) => {
  const s$1 = 42 < x ? { tag: 1, _1: "Hello" } : { tag: 0 };
  if (s$1.tag === 0) {
    return "";
  }
  return s$1._1 + ", World!";
};
