// JavaScript of Tests/SnapshotsPBOPure/Object01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `test1`
 * @param {Object<string, int53(number)>} a
 * @returns {int53(number)}
 */
export const test1 = (a) => a.foo ?? 0;

/**
 * `test2`
 * @param {Object<string, int53(number)>} a
 * @returns {int53(number)}
 */
export const test2 = (a) => a["foo.bar"] ?? 0;

/**
 * `test3`
 * @param {Object<string, int53(number)>} a
 * @param {string} b
 * @returns {int53(number)}
 */
export const test3 = (a, b) => (Object.hasOwn(a, b) ? a[b] : 0);

/**
 * `test4`
 * @param {Object<string, int53(number)>} a
 * @returns {Array<string>}
 */
export const test4 = (a) => Object.keys(a);

/**
 * `test5`
 * @param {Object<string, int53(number)>} a
 * @returns {boolean}
 */
export const test5 = (a) => Object.hasOwn(a, "wat");
