// JavaScript of Tests/SnapshotsPBOPure/PrimOpBitVec02Configurable.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

import {
  uint53__lean_uint64_land,
  uint53__lean_uint64_lor,
  uint53__lean_uint64_xor,
  uint53__lean_uint64_shift_left,
  uint53__lean_uint64_complement,
} from "../../runtime.js";

/**
 * `TestBitVec32.land`
 * @param {bitvec32(number)} a
 * @param {bitvec32(number)} b
 * @returns {bitvec32(number)}
 */
export const TestBitVec32$land = (a, b) => (a & b) >>> 0;

/**
 * `TestBitVec32.lor`
 * @param {bitvec32(number)} a
 * @param {bitvec32(number)} b
 * @returns {bitvec32(number)}
 */
export const TestBitVec32$lor = (a, b) => (a | b) >>> 0;

/**
 * `TestBitVec32.xor`
 * @param {bitvec32(number)} a
 * @param {bitvec32(number)} b
 * @returns {bitvec32(number)}
 */
export const TestBitVec32$xor = (a, b) => (a ^ b) >>> 0;

/**
 * `TestBitVec32.shiftLeft`
 * @param {bitvec32(number)} a
 * @param {bitvec32(number)} b
 * @returns {bitvec32(number)}
 */
export const TestBitVec32$shiftLeft = (a, b) => (b < 32 ? (a << b) >>> 0 : 0);

/**
 * `TestBitVec32.shiftRight`
 * @param {bitvec32(number)} a
 * @param {bitvec32(number)} b
 * @returns {bitvec32(number)}
 */
export const TestBitVec32$shiftRight = (a, b) => (b < 32 ? a >>> b : 0);

/**
 * `TestBitVec32.complement`
 * @param {bitvec32(number)} a
 * @returns {bitvec32(number)}
 */
export const TestBitVec32$complement = (a) => ~a >>> 0;

/**
 * `TestBitVec64.land`
 * @param {bitvec64(number)} a
 * @param {bitvec64(number)} b
 * @returns {bitvec64(number)}
 */
export const TestBitVec64$land = (a, b) => uint53__lean_uint64_land(a, b);

/**
 * `TestBitVec64.lor`
 * @param {bitvec64(number)} a
 * @param {bitvec64(number)} b
 * @returns {bitvec64(number)}
 */
export const TestBitVec64$lor = (a, b) => uint53__lean_uint64_lor(a, b);

/**
 * `TestBitVec64.xor`
 * @param {bitvec64(number)} a
 * @param {bitvec64(number)} b
 * @returns {bitvec64(number)}
 */
export const TestBitVec64$xor = (a, b) => uint53__lean_uint64_xor(a, b);

/**
 * `TestBitVec64.shiftLeft`
 * @param {bitvec64(number)} a
 * @param {bitvec64(number)} b
 * @returns {bitvec64(number)}
 */
export const TestBitVec64$shiftLeft = (a, b) =>
  b < 64 ? uint53__lean_uint64_shift_left(a, b) : 0;

/**
 * `TestBitVec64.shiftRight`
 * @param {bitvec64(number)} a
 * @param {bitvec64(number)} b
 * @returns {bitvec64(number)}
 */
export const TestBitVec64$shiftRight = (a, b) => Math.floor(a / 2 ** b);

/**
 * `TestBitVec64.complement`
 * @param {bitvec64(number)} a
 * @returns {bitvec64(number)}
 */
export const TestBitVec64$complement = (a) => uint53__lean_uint64_complement(a);
