// Differential checks of PrimOpBitVec02Configurable-faithful.js against Lean, generated by leanscript --check
import * as M from "./PrimOpBitVec02Configurable-faithful.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
// a recursive union: as `showUnion`, the fields marked in `rec[tag]` (the type itself) printed
// the same way, one level less deep (`…` at depth 0, as `showExpr` cuts it in Lean)
function showTree(v, rec, d) {
  if (d === 0) return "…";
  if (typeof v === "number") return v + "()";
  const r = rec[v.tag] || [];
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++)
    fs.push(r[i - 1] ? showTree(v["_" + i], rec, d - 1) : show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("TestBitVec32$land(0, 0)", () => M.TestBitVec32$land(0, 0), "0", false);
check("TestBitVec32$land(1, 0)", () => M.TestBitVec32$land(1, 0), "0", false);
check("TestBitVec32$land(0, 2)", () => M.TestBitVec32$land(0, 2), "0", false);
check("TestBitVec32$land(2, 0)", () => M.TestBitVec32$land(2, 0), "0", false);
check("TestBitVec32$land(1, 2)", () => M.TestBitVec32$land(1, 2), "0", false);
check("TestBitVec32$land(5, 0)", () => M.TestBitVec32$land(5, 0), "0", false);
check("TestBitVec32$land(0, 13)", () => M.TestBitVec32$land(0, 13), "0", false);
check("TestBitVec32$land(2, 2)", () => M.TestBitVec32$land(2, 2), "2", false);
check("TestBitVec32$land(13, 0)", () => M.TestBitVec32$land(13, 0), "0", false);
check("TestBitVec32$land(1, 13)", () => M.TestBitVec32$land(1, 13), "1", false);
check("TestBitVec32$land(5, 2)", () => M.TestBitVec32$land(5, 2), "0", false);
check("TestBitVec32$land(4294967295, 0)", () => M.TestBitVec32$land(4294967295, 0), "0", false);
check("TestBitVec32$land(2, 13)", () => M.TestBitVec32$land(2, 13), "0", false);
check("TestBitVec32$land(13, 2)", () => M.TestBitVec32$land(13, 2), "0", false);
check("TestBitVec32$land(5, 13)", () => M.TestBitVec32$land(5, 13), "5", false);
check("TestBitVec32$land(4294967295, 2)", () => M.TestBitVec32$land(4294967295, 2), "2", false);
check("TestBitVec32$land(13, 13)", () => M.TestBitVec32$land(13, 13), "13", false);
check("TestBitVec32$land(4294967295, 13)", () => M.TestBitVec32$land(4294967295, 13), "13", false);
check("TestBitVec32$lor(0, 0)", () => M.TestBitVec32$lor(0, 0), "0", false);
check("TestBitVec32$lor(1, 0)", () => M.TestBitVec32$lor(1, 0), "1", false);
check("TestBitVec32$lor(0, 2)", () => M.TestBitVec32$lor(0, 2), "2", false);
check("TestBitVec32$lor(2, 0)", () => M.TestBitVec32$lor(2, 0), "2", false);
check("TestBitVec32$lor(1, 2)", () => M.TestBitVec32$lor(1, 2), "3", false);
check("TestBitVec32$lor(5, 0)", () => M.TestBitVec32$lor(5, 0), "5", false);
check("TestBitVec32$lor(0, 13)", () => M.TestBitVec32$lor(0, 13), "13", false);
check("TestBitVec32$lor(2, 2)", () => M.TestBitVec32$lor(2, 2), "2", false);
check("TestBitVec32$lor(13, 0)", () => M.TestBitVec32$lor(13, 0), "13", false);
check("TestBitVec32$lor(1, 13)", () => M.TestBitVec32$lor(1, 13), "13", false);
check("TestBitVec32$lor(5, 2)", () => M.TestBitVec32$lor(5, 2), "7", false);
check("TestBitVec32$lor(4294967295, 0)", () => M.TestBitVec32$lor(4294967295, 0), "4294967295", false);
check("TestBitVec32$lor(2, 13)", () => M.TestBitVec32$lor(2, 13), "15", false);
check("TestBitVec32$lor(13, 2)", () => M.TestBitVec32$lor(13, 2), "15", false);
check("TestBitVec32$lor(5, 13)", () => M.TestBitVec32$lor(5, 13), "13", false);
check("TestBitVec32$lor(4294967295, 2)", () => M.TestBitVec32$lor(4294967295, 2), "4294967295", false);
check("TestBitVec32$lor(13, 13)", () => M.TestBitVec32$lor(13, 13), "13", false);
check("TestBitVec32$lor(4294967295, 13)", () => M.TestBitVec32$lor(4294967295, 13), "4294967295", false);
check("TestBitVec32$xor(0, 0)", () => M.TestBitVec32$xor(0, 0), "0", false);
check("TestBitVec32$xor(1, 0)", () => M.TestBitVec32$xor(1, 0), "1", false);
check("TestBitVec32$xor(0, 2)", () => M.TestBitVec32$xor(0, 2), "2", false);
check("TestBitVec32$xor(2, 0)", () => M.TestBitVec32$xor(2, 0), "2", false);
check("TestBitVec32$xor(1, 2)", () => M.TestBitVec32$xor(1, 2), "3", false);
check("TestBitVec32$xor(5, 0)", () => M.TestBitVec32$xor(5, 0), "5", false);
check("TestBitVec32$xor(0, 13)", () => M.TestBitVec32$xor(0, 13), "13", false);
check("TestBitVec32$xor(2, 2)", () => M.TestBitVec32$xor(2, 2), "0", false);
check("TestBitVec32$xor(13, 0)", () => M.TestBitVec32$xor(13, 0), "13", false);
check("TestBitVec32$xor(1, 13)", () => M.TestBitVec32$xor(1, 13), "12", false);
check("TestBitVec32$xor(5, 2)", () => M.TestBitVec32$xor(5, 2), "7", false);
check("TestBitVec32$xor(4294967295, 0)", () => M.TestBitVec32$xor(4294967295, 0), "4294967295", false);
check("TestBitVec32$xor(2, 13)", () => M.TestBitVec32$xor(2, 13), "15", false);
check("TestBitVec32$xor(13, 2)", () => M.TestBitVec32$xor(13, 2), "15", false);
check("TestBitVec32$xor(5, 13)", () => M.TestBitVec32$xor(5, 13), "8", false);
check("TestBitVec32$xor(4294967295, 2)", () => M.TestBitVec32$xor(4294967295, 2), "4294967293", false);
check("TestBitVec32$xor(13, 13)", () => M.TestBitVec32$xor(13, 13), "0", false);
check("TestBitVec32$xor(4294967295, 13)", () => M.TestBitVec32$xor(4294967295, 13), "4294967282", false);
check("TestBitVec32$complement(0)", () => M.TestBitVec32$complement(0), "4294967295", false);
check("TestBitVec32$complement(1)", () => M.TestBitVec32$complement(1), "4294967294", false);
check("TestBitVec32$complement(2)", () => M.TestBitVec32$complement(2), "4294967293", false);
check("TestBitVec32$complement(5)", () => M.TestBitVec32$complement(5), "4294967290", false);
check("TestBitVec32$complement(13)", () => M.TestBitVec32$complement(13), "4294967282", false);
check("TestBitVec32$complement(4294967295)", () => M.TestBitVec32$complement(4294967295), "0", false);
check("TestBitVec64$land(0n, 0n)", () => M.TestBitVec64$land(0n, 0n), "0", false);
check("TestBitVec64$land(1n, 0n)", () => M.TestBitVec64$land(1n, 0n), "0", false);
check("TestBitVec64$land(0n, 2n)", () => M.TestBitVec64$land(0n, 2n), "0", false);
check("TestBitVec64$land(2n, 0n)", () => M.TestBitVec64$land(2n, 0n), "0", false);
check("TestBitVec64$land(1n, 2n)", () => M.TestBitVec64$land(1n, 2n), "0", false);
check("TestBitVec64$land(5n, 0n)", () => M.TestBitVec64$land(5n, 0n), "0", false);
check("TestBitVec64$land(0n, 13n)", () => M.TestBitVec64$land(0n, 13n), "0", false);
check("TestBitVec64$land(2n, 2n)", () => M.TestBitVec64$land(2n, 2n), "2", false);
check("TestBitVec64$land(13n, 0n)", () => M.TestBitVec64$land(13n, 0n), "0", false);
check("TestBitVec64$land(1n, 13n)", () => M.TestBitVec64$land(1n, 13n), "1", false);
check("TestBitVec64$land(5n, 2n)", () => M.TestBitVec64$land(5n, 2n), "0", false);
check("TestBitVec64$land(18446744073709551615n, 0n)", () => M.TestBitVec64$land(18446744073709551615n, 0n), "0", false);
check("TestBitVec64$land(2n, 13n)", () => M.TestBitVec64$land(2n, 13n), "0", false);
check("TestBitVec64$land(13n, 2n)", () => M.TestBitVec64$land(13n, 2n), "0", false);
check("TestBitVec64$land(5n, 13n)", () => M.TestBitVec64$land(5n, 13n), "5", false);
check("TestBitVec64$land(18446744073709551615n, 2n)", () => M.TestBitVec64$land(18446744073709551615n, 2n), "2", false);
check("TestBitVec64$land(13n, 13n)", () => M.TestBitVec64$land(13n, 13n), "13", false);
check("TestBitVec64$land(18446744073709551615n, 13n)", () => M.TestBitVec64$land(18446744073709551615n, 13n), "13", false);
check("TestBitVec64$lor(0n, 0n)", () => M.TestBitVec64$lor(0n, 0n), "0", false);
check("TestBitVec64$lor(1n, 0n)", () => M.TestBitVec64$lor(1n, 0n), "1", false);
check("TestBitVec64$lor(0n, 2n)", () => M.TestBitVec64$lor(0n, 2n), "2", false);
check("TestBitVec64$lor(2n, 0n)", () => M.TestBitVec64$lor(2n, 0n), "2", false);
check("TestBitVec64$lor(1n, 2n)", () => M.TestBitVec64$lor(1n, 2n), "3", false);
check("TestBitVec64$lor(5n, 0n)", () => M.TestBitVec64$lor(5n, 0n), "5", false);
check("TestBitVec64$lor(0n, 13n)", () => M.TestBitVec64$lor(0n, 13n), "13", false);
check("TestBitVec64$lor(2n, 2n)", () => M.TestBitVec64$lor(2n, 2n), "2", false);
check("TestBitVec64$lor(13n, 0n)", () => M.TestBitVec64$lor(13n, 0n), "13", false);
check("TestBitVec64$lor(1n, 13n)", () => M.TestBitVec64$lor(1n, 13n), "13", false);
check("TestBitVec64$lor(5n, 2n)", () => M.TestBitVec64$lor(5n, 2n), "7", false);
check("TestBitVec64$lor(18446744073709551615n, 0n)", () => M.TestBitVec64$lor(18446744073709551615n, 0n), "18446744073709551615", false);
check("TestBitVec64$lor(2n, 13n)", () => M.TestBitVec64$lor(2n, 13n), "15", false);
check("TestBitVec64$lor(13n, 2n)", () => M.TestBitVec64$lor(13n, 2n), "15", false);
check("TestBitVec64$lor(5n, 13n)", () => M.TestBitVec64$lor(5n, 13n), "13", false);
check("TestBitVec64$lor(18446744073709551615n, 2n)", () => M.TestBitVec64$lor(18446744073709551615n, 2n), "18446744073709551615", false);
check("TestBitVec64$lor(13n, 13n)", () => M.TestBitVec64$lor(13n, 13n), "13", false);
check("TestBitVec64$lor(18446744073709551615n, 13n)", () => M.TestBitVec64$lor(18446744073709551615n, 13n), "18446744073709551615", false);
check("TestBitVec64$xor(0n, 0n)", () => M.TestBitVec64$xor(0n, 0n), "0", false);
check("TestBitVec64$xor(1n, 0n)", () => M.TestBitVec64$xor(1n, 0n), "1", false);
check("TestBitVec64$xor(0n, 2n)", () => M.TestBitVec64$xor(0n, 2n), "2", false);
check("TestBitVec64$xor(2n, 0n)", () => M.TestBitVec64$xor(2n, 0n), "2", false);
check("TestBitVec64$xor(1n, 2n)", () => M.TestBitVec64$xor(1n, 2n), "3", false);
check("TestBitVec64$xor(5n, 0n)", () => M.TestBitVec64$xor(5n, 0n), "5", false);
check("TestBitVec64$xor(0n, 13n)", () => M.TestBitVec64$xor(0n, 13n), "13", false);
check("TestBitVec64$xor(2n, 2n)", () => M.TestBitVec64$xor(2n, 2n), "0", false);
check("TestBitVec64$xor(13n, 0n)", () => M.TestBitVec64$xor(13n, 0n), "13", false);
check("TestBitVec64$xor(1n, 13n)", () => M.TestBitVec64$xor(1n, 13n), "12", false);
check("TestBitVec64$xor(5n, 2n)", () => M.TestBitVec64$xor(5n, 2n), "7", false);
check("TestBitVec64$xor(18446744073709551615n, 0n)", () => M.TestBitVec64$xor(18446744073709551615n, 0n), "18446744073709551615", false);
check("TestBitVec64$xor(2n, 13n)", () => M.TestBitVec64$xor(2n, 13n), "15", false);
check("TestBitVec64$xor(13n, 2n)", () => M.TestBitVec64$xor(13n, 2n), "15", false);
check("TestBitVec64$xor(5n, 13n)", () => M.TestBitVec64$xor(5n, 13n), "8", false);
check("TestBitVec64$xor(18446744073709551615n, 2n)", () => M.TestBitVec64$xor(18446744073709551615n, 2n), "18446744073709551613", false);
check("TestBitVec64$xor(13n, 13n)", () => M.TestBitVec64$xor(13n, 13n), "0", false);
check("TestBitVec64$xor(18446744073709551615n, 13n)", () => M.TestBitVec64$xor(18446744073709551615n, 13n), "18446744073709551602", false);
check("TestBitVec64$complement(0n)", () => M.TestBitVec64$complement(0n), "18446744073709551615", false);
check("TestBitVec64$complement(1n)", () => M.TestBitVec64$complement(1n), "18446744073709551614", false);
check("TestBitVec64$complement(2n)", () => M.TestBitVec64$complement(2n), "18446744073709551613", false);
check("TestBitVec64$complement(5n)", () => M.TestBitVec64$complement(5n), "18446744073709551610", false);
check("TestBitVec64$complement(13n)", () => M.TestBitVec64$complement(13n), "18446744073709551602", false);
check("TestBitVec64$complement(18446744073709551615n)", () => M.TestBitVec64$complement(18446744073709551615n), "0", false);

console.log(`PrimOpBitVec02Configurable-faithful.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
