// JavaScript of Tests/SnapshotsPBOPure/PrimOpString01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic

/**
 * `test1`
 * @param {string} a
 * @param {string} b
 * @returns {boolean}
 */
export const test1 = (a, b) => a === b;

/**
 * `test2`
 * @param {string} a
 * @param {string} b
 * @returns {boolean}
 */
export const test2 = (a, b) => {
  if (a === b) {
    return false;
  } else {
    return true;
  }
};

/**
 * `test3`
 * @param {string} a
 * @param {string} b
 * @returns {boolean}
 */
export const test3 = (a, b) => a < b;

/**
 * `test4`
 * @param {string} a
 * @param {string} b
 * @returns {boolean}
 */
export const test4 = (a, b) => b < a;

/**
 * `test5`
 * @param {string} a
 * @param {string} b
 * @returns {boolean}
 */
export const test5 = (a, b) => {
  if (b < a) {
    return false;
  } else {
    return true;
  }
};

/**
 * `test6`
 * @param {string} a
 * @param {string} b
 * @returns {boolean}
 */
export const test6 = (a, b) => {
  if (a < b) {
    return false;
  } else {
    return true;
  }
};

/**
 * `test7`
 * @param {string} a
 * @param {string} b
 * @returns {string}
 */
export const test7 = (a, b) => a + b;
