// Differential checks of PrimOpArray01-pbo.js against Lean, generated by leanscript --check
import * as M from "./PrimOpArray01-pbo.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
// a recursive union: as `showUnion`, the fields marked in `rec[tag]` (the type itself) printed
// the same way, one level less deep (`…` at depth 0, as `showExpr` cuts it in Lean)
function showTree(v, rec, d) {
  if (d === 0) return "…";
  if (typeof v === "number") return v + "()";
  const r = rec[v.tag] || [];
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++)
    fs.push(r[i - 1] ? showTree(v["_" + i], rec, d - 1) : show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("test1([])", () => M.test1([]), "0", false);
check("test1([]) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))([]), "0", false);
check("test1([0])", () => M.test1([0]), "1", false);
check("test1([0]) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))([0]), "1", false);
check("test1([0, 1, 2])", () => M.test1([0, 1, 2]), "3", false);
check("test1([0, 1, 2]) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))([0, 1, 2]), "3", false);
check("test1([13, 5, 2, 1])", () => M.test1([13, 5, 2, 1]), "4", false);
check("test1([13, 5, 2, 1]) twice", () => ((a0) => (M.test1(a0), M.test1(a0)))([13, 5, 2, 1]), "4", false);
check("test2(0, [])", () => M.test2(0, []), "0", false);
check("test2(0, []) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(0, []), "0", false);
check("test2(0, [0])", () => M.test2(0, [0]), "0", false);
check("test2(0, [0]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(0, [0]), "0", false);
check("test2(1, [])", () => M.test2(1, []), "1", false);
check("test2(1, []) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(1, []), "1", false);
check("test2(0, [0, 1, 2])", () => M.test2(0, [0, 1, 2]), "2", false);
check("test2(0, [0, 1, 2]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(0, [0, 1, 2]), "2", false);
check("test2(1, [0])", () => M.test2(1, [0]), "1", false);
check("test2(1, [0]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(1, [0]), "1", false);
check("test2(2, [])", () => M.test2(2, []), "2", false);
check("test2(2, []) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(2, []), "2", false);
check("test2(0, [13, 5, 2, 1])", () => M.test2(0, [13, 5, 2, 1]), "2", false);
check("test2(0, [13, 5, 2, 1]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(0, [13, 5, 2, 1]), "2", false);
check("test2(1, [0, 1, 2])", () => M.test2(1, [0, 1, 2]), "2", false);
check("test2(1, [0, 1, 2]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(1, [0, 1, 2]), "2", false);
check("test2(2, [0])", () => M.test2(2, [0]), "2", false);
check("test2(2, [0]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(2, [0]), "2", false);
check("test2(5, [])", () => M.test2(5, []), "5", false);
check("test2(5, []) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(5, []), "5", false);
check("test2(1, [13, 5, 2, 1])", () => M.test2(1, [13, 5, 2, 1]), "2", false);
check("test2(1, [13, 5, 2, 1]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(1, [13, 5, 2, 1]), "2", false);
check("test2(2, [0, 1, 2])", () => M.test2(2, [0, 1, 2]), "2", false);
check("test2(2, [0, 1, 2]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(2, [0, 1, 2]), "2", false);
check("test2(5, [0])", () => M.test2(5, [0]), "5", false);
check("test2(5, [0]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(5, [0]), "5", false);
check("test2(13, [])", () => M.test2(13, []), "13", false);
check("test2(13, []) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(13, []), "13", false);
check("test2(2, [13, 5, 2, 1])", () => M.test2(2, [13, 5, 2, 1]), "2", false);
check("test2(2, [13, 5, 2, 1]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(2, [13, 5, 2, 1]), "2", false);
check("test2(5, [0, 1, 2])", () => M.test2(5, [0, 1, 2]), "2", false);
check("test2(5, [0, 1, 2]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(5, [0, 1, 2]), "2", false);
check("test2(13, [0])", () => M.test2(13, [0]), "13", false);
check("test2(13, [0]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(13, [0]), "13", false);
check("test2(5, [13, 5, 2, 1])", () => M.test2(5, [13, 5, 2, 1]), "2", false);
check("test2(5, [13, 5, 2, 1]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(5, [13, 5, 2, 1]), "2", false);
check("test2(13, [0, 1, 2])", () => M.test2(13, [0, 1, 2]), "2", false);
check("test2(13, [0, 1, 2]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(13, [0, 1, 2]), "2", false);
check("test2(13, [13, 5, 2, 1])", () => M.test2(13, [13, 5, 2, 1]), "2", false);
check("test2(13, [13, 5, 2, 1]) twice", () => ((a0, a1) => (M.test2(a0, a1), M.test2(a0, a1)))(13, [13, 5, 2, 1]), "2", false);

console.log(`PrimOpArray01-pbo.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
