// JavaScript of Tests/SnapshotsPBOPure/PrimOpString03.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `test1`
 * @param {string} a
 * @returns {string}
 */
export const test1 = (a) => "ab" + a + "cd";

/**
 * `test2`
 * @param {string} a
 * @returns {string}
 */
export const test2 = (a) => "ab" + a + "cd";

/**
 * `test3`
 * @param {string} a
 * @returns {string}
 */
export const test3 = (a) => "ab" + a + "cd";
