// Differential checks of PrimOpIntBit01Configurable-faithful.js against Lean, generated by leanscript --check
import * as M from "./PrimOpIntBit01Configurable-faithful.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  return String(v);
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("TestNat$land(0n, 0n)", () => M.TestNat$land(0n, 0n), "0", false);
check("TestNat$land(0n, 2n)", () => M.TestNat$land(0n, 2n), "0", false);
check("TestNat$land(1n, 1n)", () => M.TestNat$land(1n, 1n), "1", false);
check("TestNat$land(2n, 0n)", () => M.TestNat$land(2n, 0n), "0", false);
check("TestNat$land(0n, 13n)", () => M.TestNat$land(0n, 13n), "0", false);
check("TestNat$land(1n, 5n)", () => M.TestNat$land(1n, 5n), "1", false);
check("TestNat$land(2n, 2n)", () => M.TestNat$land(2n, 2n), "2", false);
check("TestNat$land(5n, 1n)", () => M.TestNat$land(5n, 1n), "1", false);
check("TestNat$land(13n, 0n)", () => M.TestNat$land(13n, 0n), "0", false);
check("TestNat$land(2n, 13n)", () => M.TestNat$land(2n, 13n), "0", false);
check("TestNat$land(5n, 5n)", () => M.TestNat$land(5n, 5n), "5", false);
check("TestNat$land(13n, 2n)", () => M.TestNat$land(13n, 2n), "0", false);
check("TestNat$land(13n, 13n)", () => M.TestNat$land(13n, 13n), "13", false);
check("TestNat$lor(0n, 0n)", () => M.TestNat$lor(0n, 0n), "0", false);
check("TestNat$lor(0n, 2n)", () => M.TestNat$lor(0n, 2n), "2", false);
check("TestNat$lor(1n, 1n)", () => M.TestNat$lor(1n, 1n), "1", false);
check("TestNat$lor(2n, 0n)", () => M.TestNat$lor(2n, 0n), "2", false);
check("TestNat$lor(0n, 13n)", () => M.TestNat$lor(0n, 13n), "13", false);
check("TestNat$lor(1n, 5n)", () => M.TestNat$lor(1n, 5n), "5", false);
check("TestNat$lor(2n, 2n)", () => M.TestNat$lor(2n, 2n), "2", false);
check("TestNat$lor(5n, 1n)", () => M.TestNat$lor(5n, 1n), "5", false);
check("TestNat$lor(13n, 0n)", () => M.TestNat$lor(13n, 0n), "13", false);
check("TestNat$lor(2n, 13n)", () => M.TestNat$lor(2n, 13n), "15", false);
check("TestNat$lor(5n, 5n)", () => M.TestNat$lor(5n, 5n), "5", false);
check("TestNat$lor(13n, 2n)", () => M.TestNat$lor(13n, 2n), "15", false);
check("TestNat$lor(13n, 13n)", () => M.TestNat$lor(13n, 13n), "13", false);
check("TestNat$shiftLeft(0n, 0n)", () => M.TestNat$shiftLeft(0n, 0n), "0", false);
check("TestNat$shiftLeft(0n, 2n)", () => M.TestNat$shiftLeft(0n, 2n), "0", false);
check("TestNat$shiftLeft(1n, 1n)", () => M.TestNat$shiftLeft(1n, 1n), "2", false);
check("TestNat$shiftLeft(2n, 0n)", () => M.TestNat$shiftLeft(2n, 0n), "2", false);
check("TestNat$shiftLeft(0n, 13n)", () => M.TestNat$shiftLeft(0n, 13n), "0", false);
check("TestNat$shiftLeft(1n, 5n)", () => M.TestNat$shiftLeft(1n, 5n), "32", false);
check("TestNat$shiftLeft(2n, 2n)", () => M.TestNat$shiftLeft(2n, 2n), "8", false);
check("TestNat$shiftLeft(5n, 1n)", () => M.TestNat$shiftLeft(5n, 1n), "10", false);
check("TestNat$shiftLeft(13n, 0n)", () => M.TestNat$shiftLeft(13n, 0n), "13", false);
check("TestNat$shiftLeft(2n, 13n)", () => M.TestNat$shiftLeft(2n, 13n), "16384", false);
check("TestNat$shiftLeft(5n, 5n)", () => M.TestNat$shiftLeft(5n, 5n), "160", false);
check("TestNat$shiftLeft(13n, 2n)", () => M.TestNat$shiftLeft(13n, 2n), "52", false);
check("TestNat$shiftLeft(13n, 13n)", () => M.TestNat$shiftLeft(13n, 13n), "106496", false);
check("TestNat$shiftRight(0n, 0n)", () => M.TestNat$shiftRight(0n, 0n), "0", false);
check("TestNat$shiftRight(0n, 2n)", () => M.TestNat$shiftRight(0n, 2n), "0", false);
check("TestNat$shiftRight(1n, 1n)", () => M.TestNat$shiftRight(1n, 1n), "0", false);
check("TestNat$shiftRight(2n, 0n)", () => M.TestNat$shiftRight(2n, 0n), "2", false);
check("TestNat$shiftRight(0n, 13n)", () => M.TestNat$shiftRight(0n, 13n), "0", false);
check("TestNat$shiftRight(1n, 5n)", () => M.TestNat$shiftRight(1n, 5n), "0", false);
check("TestNat$shiftRight(2n, 2n)", () => M.TestNat$shiftRight(2n, 2n), "0", false);
check("TestNat$shiftRight(5n, 1n)", () => M.TestNat$shiftRight(5n, 1n), "2", false);
check("TestNat$shiftRight(13n, 0n)", () => M.TestNat$shiftRight(13n, 0n), "13", false);
check("TestNat$shiftRight(2n, 13n)", () => M.TestNat$shiftRight(2n, 13n), "0", false);
check("TestNat$shiftRight(5n, 5n)", () => M.TestNat$shiftRight(5n, 5n), "0", false);
check("TestNat$shiftRight(13n, 2n)", () => M.TestNat$shiftRight(13n, 2n), "3", false);
check("TestNat$shiftRight(13n, 13n)", () => M.TestNat$shiftRight(13n, 13n), "0", false);
check("TestNat$xor(0n, 0n)", () => M.TestNat$xor(0n, 0n), "0", false);
check("TestNat$xor(0n, 2n)", () => M.TestNat$xor(0n, 2n), "2", false);
check("TestNat$xor(1n, 1n)", () => M.TestNat$xor(1n, 1n), "0", false);
check("TestNat$xor(2n, 0n)", () => M.TestNat$xor(2n, 0n), "2", false);
check("TestNat$xor(0n, 13n)", () => M.TestNat$xor(0n, 13n), "13", false);
check("TestNat$xor(1n, 5n)", () => M.TestNat$xor(1n, 5n), "4", false);
check("TestNat$xor(2n, 2n)", () => M.TestNat$xor(2n, 2n), "0", false);
check("TestNat$xor(5n, 1n)", () => M.TestNat$xor(5n, 1n), "4", false);
check("TestNat$xor(13n, 0n)", () => M.TestNat$xor(13n, 0n), "13", false);
check("TestNat$xor(2n, 13n)", () => M.TestNat$xor(2n, 13n), "15", false);
check("TestNat$xor(5n, 5n)", () => M.TestNat$xor(5n, 5n), "0", false);
check("TestNat$xor(13n, 2n)", () => M.TestNat$xor(13n, 2n), "15", false);
check("TestNat$xor(13n, 13n)", () => M.TestNat$xor(13n, 13n), "0", false);

console.log(`PrimOpIntBit01Configurable-faithful.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
