// Differential checks of PrimOpBoolean01-pbo.js against Lean, generated by leanscript --check
import * as M from "./PrimOpBoolean01-pbo.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  return String(v);
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("test1(false, false)", () => M.test1(false, false), "false", false);
check("test1(false, true)", () => M.test1(false, true), "false", false);
check("test1(true, false)", () => M.test1(true, false), "false", false);
check("test1(true, true)", () => M.test1(true, true), "true", false);
check("test2(false, false)", () => M.test2(false, false), "false", false);
check("test2(false, true)", () => M.test2(false, true), "true", false);
check("test2(true, false)", () => M.test2(true, false), "true", false);
check("test2(true, true)", () => M.test2(true, true), "true", false);
check("test3(false, false)", () => M.test3(false, false), "true", false);
check("test3(false, true)", () => M.test3(false, true), "false", false);
check("test3(true, false)", () => M.test3(true, false), "false", false);
check("test3(true, true)", () => M.test3(true, true), "true", false);
check("test4(false, false)", () => M.test4(false, false), "false", false);
check("test4(false, true)", () => M.test4(false, true), "true", false);
check("test4(true, false)", () => M.test4(true, false), "true", false);
check("test4(true, true)", () => M.test4(true, true), "false", false);
check("test5(false, false)", () => M.test5(false, false), "false", false);
check("test5(false, true)", () => M.test5(false, true), "true", false);
check("test5(true, false)", () => M.test5(true, false), "false", false);
check("test5(true, true)", () => M.test5(true, true), "false", false);
check("test6(false, false)", () => M.test6(false, false), "false", false);
check("test6(false, true)", () => M.test6(false, true), "false", false);
check("test6(true, false)", () => M.test6(true, false), "true", false);
check("test6(true, true)", () => M.test6(true, true), "false", false);
check("test7(false, false)", () => M.test7(false, false), "true", false);
check("test7(false, true)", () => M.test7(false, true), "true", false);
check("test7(true, false)", () => M.test7(true, false), "false", false);
check("test7(true, true)", () => M.test7(true, true), "true", false);
check("test8(false, false)", () => M.test8(false, false), "true", false);
check("test8(false, true)", () => M.test8(false, true), "false", false);
check("test8(true, false)", () => M.test8(true, false), "true", false);
check("test8(true, true)", () => M.test8(true, true), "true", false);
check("test9(false)", () => M.test9(false), "true", false);
check("test9(true)", () => M.test9(true), "false", false);

console.log(`PrimOpBoolean01-pbo.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
