// JavaScript of Tests/SnapshotsPBOPure/PrimOpInt03NonConfigurable.lean, generated by leanscript
// configuration: nat=bigint int=bigint uint64=bigint int64=bigint bitvec=bigint array-fixed-int=typed array-float=typed array-uint64=typed array-int64=typed array-bitvec=round-up array-bool=generic array-char=generic

// ---- runtime helpers ----

function lean_uint8_add(a, b) {
  return ((a + b) & 255);
}

function lean_uint16_add(a, b) {
  return ((a + b) & 65535);
}

function lean_uint32_add(a, b) {
  return ((a + b) >>> 0);
}

function lean_int8_add(a, b) {
  return (((a + b) << 24) >> 24);
}

function lean_int16_add(a, b) {
  return (((a + b) << 16) >> 16);
}

function lean_int32_add(a, b) {
  return ((a + b) | 0);
}

// ---- exported functions ----

/**
 * `TestUInt8.test1`
 * @returns {uint8}
 */
export function TestUInt8_test1() {
  return 144;
}

/**
 * `TestUInt8.test2`
 * @returns {uint8}
 */
export function TestUInt8_test2() {
  return 106;
}

/**
 * `TestUInt8.test3`
 * @returns {uint8}
 */
export function TestUInt8_test3() {
  return 144;
}

/**
 * `TestUInt8.test4`
 * @param {uint8} a
 * @returns {uint8}
 */
export function TestUInt8_test4(a) {
  return lean_uint8_add(lean_uint8_add(200, a), 200);
}

/**
 * `TestUInt16.test1`
 * @returns {uint16}
 */
export function TestUInt16_test1() {
  return 34464;
}

/**
 * `TestUInt16.test2`
 * @returns {uint16}
 */
export function TestUInt16_test2() {
  return 25536;
}

/**
 * `TestUInt16.test3`
 * @returns {uint16}
 */
export function TestUInt16_test3() {
  return 16960;
}

/**
 * `TestUInt16.test4`
 * @param {uint16} a
 * @returns {uint16}
 */
export function TestUInt16_test4(a) {
  return lean_uint16_add(lean_uint16_add(50000, a), 50000);
}

/**
 * `TestUInt32.test1`
 * @returns {uint32}
 */
export function TestUInt32_test1() {
  return 1705032704;
}

/**
 * `TestUInt32.test2`
 * @returns {uint32}
 */
export function TestUInt32_test2() {
  return 2294967296;
}

/**
 * `TestUInt32.test3`
 * @returns {uint32}
 */
export function TestUInt32_test3() {
  return 2643460096;
}

/**
 * `TestUInt32.test4`
 * @param {uint32} a
 * @returns {uint32}
 */
export function TestUInt32_test4(a) {
  return lean_uint32_add(lean_uint32_add(3000000000, a), 3000000000);
}

/**
 * `TestInt8.test1`
 * @returns {int8}
 */
export function TestInt8_test1() {
  return -56;
}

/**
 * `TestInt8.test2`
 * @returns {int8}
 */
export function TestInt8_test2() {
  return 56;
}

/**
 * `TestInt8.test3`
 * @returns {int8}
 */
export function TestInt8_test3() {
  return -112;
}

/**
 * `TestInt8.test4`
 * @param {int8} a
 * @returns {int8}
 */
export function TestInt8_test4(a) {
  return lean_int8_add(lean_int8_add(100, a), 100);
}

/**
 * `TestInt16.test1`
 * @returns {int16}
 */
export function TestInt16_test1() {
  return -25536;
}

/**
 * `TestInt16.test2`
 * @returns {int16}
 */
export function TestInt16_test2() {
  return 25536;
}

/**
 * `TestInt16.test3`
 * @returns {int16}
 */
export function TestInt16_test3() {
  return 16960;
}

/**
 * `TestInt16.test4`
 * @param {int16} a
 * @returns {int16}
 */
export function TestInt16_test4(a) {
  return lean_int16_add(lean_int16_add(20000, a), 20000);
}

/**
 * `TestInt32.test1`
 * @returns {int32}
 */
export function TestInt32_test1() {
  return -294967296;
}

/**
 * `TestInt32.test2`
 * @returns {int32}
 */
export function TestInt32_test2() {
  return 294967296;
}

/**
 * `TestInt32.test3`
 * @returns {int32}
 */
export function TestInt32_test3() {
  return -1946474495;
}

/**
 * `TestInt32.test4`
 * @param {int32} a
 * @returns {int32}
 */
export function TestInt32_test4(a) {
  return lean_int32_add(lean_int32_add(2000000000, a), 2000000000);
}
