// JavaScript of Tests/SnapshotsPBOPure/PrimOpString03.lean, generated by leanscript
// configuration: nat=bigint int=bigint uint64=bigint int64=bigint bitvec=bigint array-fixed-int=typed array-float=typed array-uint64=typed array-int64=typed array-bitvec=round-up array-bool=generic array-char=generic


/**
 * `test1`
 * @param {string} a
 * @returns {string}
 */
export function test1(a) {
  return "ab" + a + "c" + "d";
}

/**
 * `test2`
 * @param {string} a
 * @returns {string}
 */
export function test2(a) {
  return "a" + ("b" + a + "c") + "d";
}

/**
 * `test3`
 * @param {string} a
 * @returns {string}
 */
export function test3(a) {
  return "a" + ("b" + (a + "c")) + "d";
}
