// JavaScript of Tests/SnapshotsPBOPure/PrimOpBitVec02Configurable.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic
// not translated:
//   TestBitVec32.land: LeanScript: `BitVec 32` is a leaf of the language: its values are literals, not constructor applications
//   TestBitVec32.lor: LeanScript: `BitVec 32` is a leaf of the language: its values are literals, not constructor applications
//   TestBitVec32.xor: LeanScript: `BitVec 32` is a leaf of the language: its values are literals, not constructor applications
//   TestBitVec32.shiftLeft: LeanScript: `BitVec 32` is a leaf of the language: its values are literals, not constructor applications
//   TestBitVec32.shiftRight: LeanScript: `BitVec 32` is a leaf of the language: its values are literals, not constructor applications
//   TestBitVec32.complement: LeanScript: `BitVec 32` is a leaf of the language: its values are literals, not constructor applications
//   TestBitVec64.land: LeanScript: `BitVec 64` is a leaf of the language: its values are literals, not constructor applications
//   TestBitVec64.lor: LeanScript: `BitVec 64` is a leaf of the language: its values are literals, not constructor applications
//   TestBitVec64.xor: LeanScript: `BitVec 64` is a leaf of the language: its values are literals, not constructor applications
//   TestBitVec64.shiftLeft: LeanScript: `BitVec 64` is a leaf of the language: its values are literals, not constructor applications
//   TestBitVec64.shiftRight: LeanScript: `BitVec 64` is a leaf of the language: its values are literals, not constructor applications
//   TestBitVec64.complement: LeanScript: `BitVec 64` is a leaf of the language: its values are literals, not constructor applications

