// JavaScript of Tests/SnapshotsPBOPure/PrimOpInt01Configurable.lean, generated by leanscript
// configuration: nat=bigint int=bigint uint64=bigint int64=bigint bitvec=bigint array-fixed-int=typed array-float=typed array-uint64=typed array-int64=typed array-bitvec=round-up array-bool=generic array-char=generic
// not translated:
//   TestUSize.add: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestUSize.sub: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestUSize.eq: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestUSize.ne: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestUSize.lt: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestUSize.gt: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestUSize.le: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestUSize.ge: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestUSize.mul: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestUSize.div: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestUSize.neg: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestISize.add: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestISize.sub: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestISize.eq: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestISize.ne: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestISize.lt: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestISize.gt: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestISize.le: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestISize.ge: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestISize.mul: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestISize.div: LeanScript: the width of BitVec System.Platform.numBits is not a numeral
//   TestISize.neg: LeanScript: the width of BitVec System.Platform.numBits is not a numeral

// ---- runtime helpers ----

function lean_uint64_add$bbb(a, b) {
  return BigInt.asUintN(64, a + b);
}

function lean_uint64_sub$bbb(a, b) {
  return BigInt.asUintN(64, a - b);
}

function lean_uint64_mul$bbb(a, b) {
  return BigInt.asUintN(64, a * b);
}

function lean_uint64_div$bbb(a, b) {
  return (b === 0n ? 0n : BigInt.asUintN(64, a / b));
}

function lean_uint64_neg$bb(a) {
  return BigInt.asUintN(64, -a);
}

function lean_nat_sub$bbb(a, b) {
  return (a > b ? a - b : 0n);
}

function lean_nat_div$bbb(a, b) {
  return (b === 0n ? 0n : a / b);
}

function lean_int64_add$bbb(a, b) {
  return BigInt.asIntN(64, a + b);
}

function lean_int64_sub$bbb(a, b) {
  return BigInt.asIntN(64, a - b);
}

function lean_int64_mul$bbb(a, b) {
  return BigInt.asIntN(64, a * b);
}

function lean_int64_div$bbb(a, b) {
  return (b === 0n ? 0n : BigInt.asIntN(64, a / b));
}

function lean_int64_neg$bb(a) {
  return BigInt.asIntN(64, -a);
}

function lean_int_ediv$bbb(a, b) {
  return (b === 0n ? 0n : (a % b < 0n ? (b > 0n ? a / b - 1n : a / b + 1n) : a / b));
}

function lean_int_neg$bb(a) {
  return -a;
}

// ---- exported functions ----

/**
 * `TestUInt64.add`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {nat(bigint)}
 */
export function TestUInt64_add(a, b) {
  return lean_uint64_add$bbb(a, b);
}

/**
 * `TestUInt64.sub`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {nat(bigint)}
 */
export function TestUInt64_sub(a, b) {
  return lean_uint64_sub$bbb(a, b);
}

/**
 * `TestUInt64.eq`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {boolean}
 */
export function TestUInt64_eq(a, b) {
  return a === b;
}

/**
 * `TestUInt64.ne`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {boolean}
 */
export function TestUInt64_ne(a, b) {
  if (a === b) {
    return false;
  } else {
    return true;
  }
}

/**
 * `TestUInt64.lt`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {boolean}
 */
export function TestUInt64_lt(a, b) {
  return a < b;
}

/**
 * `TestUInt64.gt`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {boolean}
 */
export function TestUInt64_gt(a, b) {
  return b < a;
}

/**
 * `TestUInt64.le`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {boolean}
 */
export function TestUInt64_le(a, b) {
  return a <= b;
}

/**
 * `TestUInt64.ge`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {boolean}
 */
export function TestUInt64_ge(a, b) {
  return b <= a;
}

/**
 * `TestUInt64.mul`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {nat(bigint)}
 */
export function TestUInt64_mul(a, b) {
  return lean_uint64_mul$bbb(a, b);
}

/**
 * `TestUInt64.div`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {nat(bigint)}
 */
export function TestUInt64_div(a, b) {
  return lean_uint64_div$bbb(a, b);
}

/**
 * `TestUInt64.neg`
 * @param {nat(bigint)} a
 * @returns {nat(bigint)}
 */
export function TestUInt64_neg(a) {
  return lean_uint64_neg$bb(a);
}

/**
 * `TestNat.add`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {nat(bigint)}
 */
export function TestNat_add(a, b) {
  return a + b;
}

/**
 * `TestNat.sub`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {nat(bigint)}
 */
export function TestNat_sub(a, b) {
  return lean_nat_sub$bbb(a, b);
}

/**
 * `TestNat.eq`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {boolean}
 */
export function TestNat_eq(a, b) {
  return a === b;
}

/**
 * `TestNat.ne`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {boolean}
 */
export function TestNat_ne(a, b) {
  if (a === b) {
    return false;
  } else {
    return true;
  }
}

/**
 * `TestNat.lt`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {boolean}
 */
export function TestNat_lt(a, b) {
  return a < b;
}

/**
 * `TestNat.gt`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {boolean}
 */
export function TestNat_gt(a, b) {
  return b < a;
}

/**
 * `TestNat.le`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {boolean}
 */
export function TestNat_le(a, b) {
  return a <= b;
}

/**
 * `TestNat.ge`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {boolean}
 */
export function TestNat_ge(a, b) {
  return b <= a;
}

/**
 * `TestNat.mul`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {nat(bigint)}
 */
export function TestNat_mul(a, b) {
  return a * b;
}

/**
 * `TestNat.div`
 * @param {nat(bigint)} a
 * @param {nat(bigint)} b
 * @returns {nat(bigint)}
 */
export function TestNat_div(a, b) {
  return lean_nat_div$bbb(a, b);
}

/**
 * `TestInt64.add`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {int(bigint)}
 */
export function TestInt64_add(a, b) {
  return lean_int64_add$bbb(a, b);
}

/**
 * `TestInt64.sub`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {int(bigint)}
 */
export function TestInt64_sub(a, b) {
  return lean_int64_sub$bbb(a, b);
}

/**
 * `TestInt64.eq`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {boolean}
 */
export function TestInt64_eq(a, b) {
  return a === b;
}

/**
 * `TestInt64.ne`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {boolean}
 */
export function TestInt64_ne(a, b) {
  if (a === b) {
    return false;
  } else {
    return true;
  }
}

/**
 * `TestInt64.lt`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {boolean}
 */
export function TestInt64_lt(a, b) {
  return a < b;
}

/**
 * `TestInt64.gt`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {boolean}
 */
export function TestInt64_gt(a, b) {
  return b < a;
}

/**
 * `TestInt64.le`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {boolean}
 */
export function TestInt64_le(a, b) {
  return a <= b;
}

/**
 * `TestInt64.ge`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {boolean}
 */
export function TestInt64_ge(a, b) {
  return b <= a;
}

/**
 * `TestInt64.mul`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {int(bigint)}
 */
export function TestInt64_mul(a, b) {
  return lean_int64_mul$bbb(a, b);
}

/**
 * `TestInt64.div`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {int(bigint)}
 */
export function TestInt64_div(a, b) {
  return lean_int64_div$bbb(a, b);
}

/**
 * `TestInt64.neg`
 * @param {int(bigint)} a
 * @returns {int(bigint)}
 */
export function TestInt64_neg(a) {
  return lean_int64_neg$bb(a);
}

/**
 * `TestInt.add`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {int(bigint)}
 */
export function TestInt_add(a, b) {
  return a + b;
}

/**
 * `TestInt.sub`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {int(bigint)}
 */
export function TestInt_sub(a, b) {
  return a - b;
}

/**
 * `TestInt.eq`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {boolean}
 */
export function TestInt_eq(a, b) {
  return a === b;
}

/**
 * `TestInt.ne`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {boolean}
 */
export function TestInt_ne(a, b) {
  if (a === b) {
    return false;
  } else {
    return true;
  }
}

/**
 * `TestInt.lt`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {boolean}
 */
export function TestInt_lt(a, b) {
  return a < b;
}

/**
 * `TestInt.gt`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {boolean}
 */
export function TestInt_gt(a, b) {
  return b < a;
}

/**
 * `TestInt.le`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {boolean}
 */
export function TestInt_le(a, b) {
  return a <= b;
}

/**
 * `TestInt.ge`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {boolean}
 */
export function TestInt_ge(a, b) {
  return b <= a;
}

/**
 * `TestInt.mul`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {int(bigint)}
 */
export function TestInt_mul(a, b) {
  return a * b;
}

/**
 * `TestInt.div`
 * @param {int(bigint)} a
 * @param {int(bigint)} b
 * @returns {int(bigint)}
 */
export function TestInt_div(a, b) {
  return lean_int_ediv$bbb(a, b);
}

/**
 * `TestInt.neg`
 * @param {int(bigint)} a
 * @returns {int(bigint)}
 */
export function TestInt_neg(a) {
  return lean_int_neg$bb(a);
}
