// JavaScript of Tests/SnapshotsPBOPure/PrimOpString02.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `stringValues`
 * @param {(string, string) => uint53(number)} op
 * @returns {Array<uint53(number)>}
 */
export const stringValues = (op) => {
  const x$1 = op("a", "a");
  return [x$1, op("a", "b"), op("b", "a")];
};

/**
 * `test1`
 * @type {Array<boolean>}
 */
export const test1 = [true, false, false];

/**
 * `test2`
 * @type {Array<boolean>}
 */
export const test2 = [false, true, true];

/**
 * `test3`
 * @type {Array<boolean>}
 */
export const test3 = [false, true, false];

/**
 * `test4`
 * @type {Array<boolean>}
 */
export const test4 = [false, false, true];

/**
 * `test5`
 * @type {Array<boolean>}
 */
export const test5 = [true, true, false];

/**
 * `test6`
 * @type {Array<boolean>}
 */
export const test6 = [true, false, true];

/**
 * `test7`
 * @type {Array<string>}
 */
export const test7 = ["aa", "ab", "ba"];
