// Differential checks of PrimOpInt02Configurable-pbo.js against Lean, generated by leanscript --check
import * as M from "./PrimOpInt02Configurable-pbo.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
// a recursive union: as `showUnion`, the fields marked in `rec[tag]` (the type itself) printed
// the same way, one level less deep (`…` at depth 0, as `showExpr` cuts it in Lean)
function showTree(v, rec, d) {
  if (d === 0) return "…";
  if (typeof v === "number") return v + "()";
  const r = rec[v.tag] || [];
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++)
    fs.push(r[i - 1] ? showTree(v["_" + i], rec, d - 1) : show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("TestUInt64$test3", () => M.TestUInt64$test3, "#[true, false, false, false, false, true]", false);
check("TestUInt64$test4", () => M.TestUInt64$test4, "#[false, true, true, true, true, false]", false);
check("TestUInt64$test5", () => M.TestUInt64$test5, "#[false, true, false, true, false, false]", false);
check("TestUInt64$test6", () => M.TestUInt64$test6, "#[false, false, true, false, true, false]", false);
check("TestUInt64$test7", () => M.TestUInt64$test7, "#[true, true, false, true, false, true]", false);
check("TestUInt64$test8", () => M.TestUInt64$test8, "#[true, false, true, false, true, true]", false);
check("TestNat$intValues((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y))", () => M.TestNat$intValues((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y)), "#[11, 12, 21, 10, 2, 0]", false);
check("TestNat$intValues((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x))", () => M.TestNat$intValues((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x)), "#[2, 5, 1, 0, 6, 0]", false);
check("TestNat$test1", () => M.TestNat$test1, "#[2, 3, 3, 1, 2, 0]", false);
check("TestNat$test2", () => M.TestNat$test2, "#[0, 0, 1, 1, 0, 0]", false);
check("TestNat$test3", () => M.TestNat$test3, "#[true, false, false, false, false, true]", false);
check("TestNat$test4", () => M.TestNat$test4, "#[false, true, true, true, true, false]", false);
check("TestNat$test5", () => M.TestNat$test5, "#[false, true, false, false, true, false]", false);
check("TestNat$test6", () => M.TestNat$test6, "#[false, false, true, true, false, false]", false);
check("TestNat$test7", () => M.TestNat$test7, "#[true, true, false, false, true, true]", false);
check("TestNat$test8", () => M.TestNat$test8, "#[true, false, true, true, false, true]", false);
check("TestNat$test9", () => M.TestNat$test9, "#[1, 2, 2, 0, 0, 0]", false);
check("TestNat$test10", () => M.TestNat$test10, "#[1, 0, 2, 0, 0, 0]", false);
check("TestInt64$test3", () => M.TestInt64$test3, "#[true, false, false, false, false, true]", false);
check("TestInt64$test4", () => M.TestInt64$test4, "#[false, true, true, true, true, false]", false);
check("TestInt64$test5", () => M.TestInt64$test5, "#[false, true, false, false, true, false]", false);
check("TestInt64$test6", () => M.TestInt64$test6, "#[false, false, true, true, false, false]", false);
check("TestInt64$test7", () => M.TestInt64$test7, "#[true, true, false, false, true, true]", false);
check("TestInt64$test8", () => M.TestInt64$test8, "#[true, false, true, true, false, true]", false);
check("TestInt$intValues((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y))", () => M.TestInt$intValues((x, y) => ((v) => (v > 0 ? v : 0))(x * 10 + y)), "#[11, 12, 21, 8, 0, 0]", false);
check("TestInt$intValues((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x))", () => M.TestInt$intValues((x, y) => ((v) => (v > 0 ? v : 0))(y * 3 - x)), "#[2, 5, 1, 0, 7, 0]", false);
check("TestInt$test1", () => M.TestInt$test1, "#[2, 3, 3, -1, 1, -2]", false);
check("TestInt$test2", () => M.TestInt$test2, "#[0, -1, 1, 3, -3, 0]", false);
check("TestInt$test3", () => M.TestInt$test3, "#[true, false, false, false, false, true]", false);
check("TestInt$test4", () => M.TestInt$test4, "#[false, true, true, true, true, false]", false);
check("TestInt$test5", () => M.TestInt$test5, "#[false, true, false, false, true, false]", false);
check("TestInt$test6", () => M.TestInt$test6, "#[false, false, true, true, false, false]", false);
check("TestInt$test7", () => M.TestInt$test7, "#[true, true, false, false, true, true]", false);
check("TestInt$test8", () => M.TestInt$test8, "#[true, false, true, true, false, true]", false);
check("TestInt$test9", () => M.TestInt$test9, "#[1, 2, 2, -2, -2, 1]", false);
check("TestInt$test10", () => M.TestInt$test10, "#[1, 0, 2, 0, -1, 1]", false);
check("TestInt$test11", () => M.TestInt$test11, "#[-1, 1]", false);

console.log(`PrimOpInt02Configurable-pbo.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
