// Differential checks of PrimOpInt02NonConfigurable-faithful.js against Lean, generated by leanscript --check
import * as M from "./PrimOpInt02NonConfigurable-faithful.js";

function show(v) {
  if (Array.isArray(v) || ArrayBuffer.isView(v)) return "#[" + [...v].map(show).join(", ") + "]";
  // a list of cons cells (`ListRepr.taggedUnion`) is shown as its elements
  if (v !== null && typeof v === "object" && (v.tag === 0 || v.tag === 1)) {
    const a = [];
    for (; v.tag === 1; v = v._2) a.push(v._1);
    return show(a);
  }
  // a record (a structure-like type) is shown as its fields: `{a, b}`
  if (v !== null && typeof v === "object" && !("tag" in v) && "_1" in v) {
    const fs = [];
    for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
    return "{" + fs.join(", ") + "}";
  }
  return String(v);
}
// a union `{ tag: i, _1: …, … }` of leaf fields is shown as `i(…, …)`
function showUnion(v) {
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++) fs.push(show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
// a recursive union: as `showUnion`, the fields marked in `rec[tag]` (the type itself) printed
// the same way, one level less deep (`…` at depth 0, as `showExpr` cuts it in Lean)
function showTree(v, rec, d) {
  if (d === 0) return "…";
  if (typeof v === "number") return v + "()";
  const r = rec[v.tag] || [];
  const fs = [];
  for (let i = 1; ("_" + i) in v; i++)
    fs.push(r[i - 1] ? showTree(v["_" + i], rec, d - 1) : show(v["_" + i]));
  return v.tag + "(" + fs.join(", ") + ")";
}
function floatBits(x) {
  return String(new BigUint64Array(new Float64Array([x]).buffer)[0]);
}
function isNaNBits(s) {
  const b = BigInt(s);
  return ((b >> 52n) & 0x7ffn) === 0x7ffn && (b & 0xfffffffffffffn) !== 0n;
}
let passed = 0, failed = 0;
function check(label, thunk, expected, isFloat) {
  let got;
  try {
    const v = thunk();
    got = isFloat ? floatBits(v) : show(v);
    // NaN payloads differ between platforms: any NaN matches any NaN
    if (isFloat && Number.isNaN(v) && isNaNBits(expected)) got = expected;
  } catch (e) {
    got = "threw: " + e.message;
  }
  if (got === expected) passed++;
  else {
    failed++;
    console.log(`FAIL ${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(got)}`);
  }
}

check("TestUInt8$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(x) * 10n + BigInt(y)))", () => M.TestUInt8$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(x) * 10n + BigInt(y))), "#[11, 12, 21, 264, 2552, 2805]", false);
check("TestUInt8$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(y) * 3n - BigInt(x)))", () => M.TestUInt8$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(y) * 3n - BigInt(x))), "#[2, 5, 1, 761, 0, 510]", false);
check("TestUInt8$test1", () => M.TestUInt8$test1, "#[2, 3, 3, 255, 1, 254]", false);
check("TestUInt8$test2", () => M.TestUInt8$test2, "#[0, 255, 1, 3, 253, 0]", false);
check("TestUInt8$test3", () => M.TestUInt8$test3, "#[true, false, false, false, false, true]", false);
check("TestUInt8$test4", () => M.TestUInt8$test4, "#[false, true, true, true, true, false]", false);
check("TestUInt8$test5", () => M.TestUInt8$test5, "#[false, true, false, true, false, false]", false);
check("TestUInt8$test6", () => M.TestUInt8$test6, "#[false, false, true, false, true, false]", false);
check("TestUInt8$test7", () => M.TestUInt8$test7, "#[true, true, false, true, false, true]", false);
check("TestUInt8$test8", () => M.TestUInt8$test8, "#[true, false, true, false, true, true]", false);
check("TestUInt8$test9", () => M.TestUInt8$test9, "#[1, 2, 2, 254, 254, 1]", false);
check("TestUInt8$test10", () => M.TestUInt8$test10, "#[1, 0, 2, 0, 127, 1]", false);
check("TestUInt8$test11", () => M.TestUInt8$test11, "#[255, 1]", false);
check("TestUInt16$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(x) * 10n + BigInt(y)))", () => M.TestUInt16$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(x) * 10n + BigInt(y))), "#[11, 12, 21, 65544, 655352, 720885]", false);
check("TestUInt16$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(y) * 3n - BigInt(x)))", () => M.TestUInt16$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(y) * 3n - BigInt(x))), "#[2, 5, 1, 196601, 0, 131070]", false);
check("TestUInt16$test1", () => M.TestUInt16$test1, "#[2, 3, 3, 65535, 1, 65534]", false);
check("TestUInt16$test2", () => M.TestUInt16$test2, "#[0, 65535, 1, 3, 65533, 0]", false);
check("TestUInt16$test3", () => M.TestUInt16$test3, "#[true, false, false, false, false, true]", false);
check("TestUInt16$test4", () => M.TestUInt16$test4, "#[false, true, true, true, true, false]", false);
check("TestUInt16$test5", () => M.TestUInt16$test5, "#[false, true, false, true, false, false]", false);
check("TestUInt16$test6", () => M.TestUInt16$test6, "#[false, false, true, false, true, false]", false);
check("TestUInt16$test7", () => M.TestUInt16$test7, "#[true, true, false, true, false, true]", false);
check("TestUInt16$test8", () => M.TestUInt16$test8, "#[true, false, true, false, true, true]", false);
check("TestUInt16$test9", () => M.TestUInt16$test9, "#[1, 2, 2, 65534, 65534, 1]", false);
check("TestUInt16$test10", () => M.TestUInt16$test10, "#[1, 0, 2, 0, 32767, 1]", false);
check("TestUInt16$test11", () => M.TestUInt16$test11, "#[65535, 1]", false);
check("TestUInt32$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(x) * 10n + BigInt(y)))", () => M.TestUInt32$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(x) * 10n + BigInt(y))), "#[11, 12, 21, 4294967304, 42949672952, 47244640245]", false);
check("TestUInt32$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(y) * 3n - BigInt(x)))", () => M.TestUInt32$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(y) * 3n - BigInt(x))), "#[2, 5, 1, 12884901881, 0, 8589934590]", false);
check("TestUInt32$test1", () => M.TestUInt32$test1, "#[2, 3, 3, 4294967295, 1, 4294967294]", false);
check("TestUInt32$test2", () => M.TestUInt32$test2, "#[0, 4294967295, 1, 3, 4294967293, 0]", false);
check("TestUInt32$test3", () => M.TestUInt32$test3, "#[true, false, false, false, false, true]", false);
check("TestUInt32$test4", () => M.TestUInt32$test4, "#[false, true, true, true, true, false]", false);
check("TestUInt32$test5", () => M.TestUInt32$test5, "#[false, true, false, true, false, false]", false);
check("TestUInt32$test6", () => M.TestUInt32$test6, "#[false, false, true, false, true, false]", false);
check("TestUInt32$test7", () => M.TestUInt32$test7, "#[true, true, false, true, false, true]", false);
check("TestUInt32$test8", () => M.TestUInt32$test8, "#[true, false, true, false, true, true]", false);
check("TestUInt32$test9", () => M.TestUInt32$test9, "#[1, 2, 2, 4294967294, 4294967294, 1]", false);
check("TestUInt32$test10", () => M.TestUInt32$test10, "#[1, 0, 2, 0, 2147483647, 1]", false);
check("TestUInt32$test11", () => M.TestUInt32$test11, "#[4294967295, 1]", false);
check("TestInt8$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(x) * 10n + BigInt(y)))", () => M.TestInt8$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(x) * 10n + BigInt(y))), "#[11, 12, 21, 8, 0, 0]", false);
check("TestInt8$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(y) * 3n - BigInt(x)))", () => M.TestInt8$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(y) * 3n - BigInt(x))), "#[2, 5, 1, 0, 7, 0]", false);
check("TestInt8$test1", () => M.TestInt8$test1, "#[2, 3, 3, -1, 1, -2]", false);
check("TestInt8$test2", () => M.TestInt8$test2, "#[0, -1, 1, 3, -3, 0]", false);
check("TestInt8$test3", () => M.TestInt8$test3, "#[true, false, false, false, false, true]", false);
check("TestInt8$test4", () => M.TestInt8$test4, "#[false, true, true, true, true, false]", false);
check("TestInt8$test5", () => M.TestInt8$test5, "#[false, true, false, false, true, false]", false);
check("TestInt8$test6", () => M.TestInt8$test6, "#[false, false, true, true, false, false]", false);
check("TestInt8$test7", () => M.TestInt8$test7, "#[true, true, false, false, true, true]", false);
check("TestInt8$test8", () => M.TestInt8$test8, "#[true, false, true, true, false, true]", false);
check("TestInt8$test9", () => M.TestInt8$test9, "#[1, 2, 2, -2, -2, 1]", false);
check("TestInt8$test10", () => M.TestInt8$test10, "#[1, 0, 2, 0, 0, 1]", false);
check("TestInt8$test11", () => M.TestInt8$test11, "#[-1, 1]", false);
check("TestInt16$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(x) * 10n + BigInt(y)))", () => M.TestInt16$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(x) * 10n + BigInt(y))), "#[11, 12, 21, 8, 0, 0]", false);
check("TestInt16$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(y) * 3n - BigInt(x)))", () => M.TestInt16$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(y) * 3n - BigInt(x))), "#[2, 5, 1, 0, 7, 0]", false);
check("TestInt16$test1", () => M.TestInt16$test1, "#[2, 3, 3, -1, 1, -2]", false);
check("TestInt16$test2", () => M.TestInt16$test2, "#[0, -1, 1, 3, -3, 0]", false);
check("TestInt16$test3", () => M.TestInt16$test3, "#[true, false, false, false, false, true]", false);
check("TestInt16$test4", () => M.TestInt16$test4, "#[false, true, true, true, true, false]", false);
check("TestInt16$test5", () => M.TestInt16$test5, "#[false, true, false, false, true, false]", false);
check("TestInt16$test6", () => M.TestInt16$test6, "#[false, false, true, true, false, false]", false);
check("TestInt16$test7", () => M.TestInt16$test7, "#[true, true, false, false, true, true]", false);
check("TestInt16$test8", () => M.TestInt16$test8, "#[true, false, true, true, false, true]", false);
check("TestInt16$test9", () => M.TestInt16$test9, "#[1, 2, 2, -2, -2, 1]", false);
check("TestInt16$test10", () => M.TestInt16$test10, "#[1, 0, 2, 0, 0, 1]", false);
check("TestInt16$test11", () => M.TestInt16$test11, "#[-1, 1]", false);
check("TestInt32$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(x) * 10n + BigInt(y)))", () => M.TestInt32$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(x) * 10n + BigInt(y))), "#[11, 12, 21, 8, 0, 0]", false);
check("TestInt32$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(y) * 3n - BigInt(x)))", () => M.TestInt32$intValues((x, y) => ((v) => (v > 0n ? v : 0n))(BigInt(y) * 3n - BigInt(x))), "#[2, 5, 1, 0, 7, 0]", false);
check("TestInt32$test1", () => M.TestInt32$test1, "#[2, 3, 3, -1, 1, -2]", false);
check("TestInt32$test2", () => M.TestInt32$test2, "#[0, -1, 1, 3, -3, 0]", false);
check("TestInt32$test3", () => M.TestInt32$test3, "#[true, false, false, false, false, true]", false);
check("TestInt32$test4", () => M.TestInt32$test4, "#[false, true, true, true, true, false]", false);
check("TestInt32$test5", () => M.TestInt32$test5, "#[false, true, false, false, true, false]", false);
check("TestInt32$test6", () => M.TestInt32$test6, "#[false, false, true, true, false, false]", false);
check("TestInt32$test7", () => M.TestInt32$test7, "#[true, true, false, false, true, true]", false);
check("TestInt32$test8", () => M.TestInt32$test8, "#[true, false, true, true, false, true]", false);
check("TestInt32$test9", () => M.TestInt32$test9, "#[1, 2, 2, -2, -2, 1]", false);
check("TestInt32$test10", () => M.TestInt32$test10, "#[1, 0, 2, 0, 0, 1]", false);
check("TestInt32$test11", () => M.TestInt32$test11, "#[-1, 1]", false);

console.log(`PrimOpInt02NonConfigurable-faithful.js: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
