// JavaScript of Tests/SnapshotsPBOPure/ProfunctorLenses02.lean, generated by leanscript
// configuration: nat=bigint int=bigint uint64=bigint int64=bigint bitvec=bigint array-fixed-int=typed array-float=typed array-uint64=typed array-int64=typed array-bitvec=round-up array-bool=generic array-char=generic
// not translated:
//   preview_left: LeanScript: the parameter `α` of `preview_left` is a type
//   preview_left_right: LeanScript: the parameter `α` of `preview_left_right` is a type
//   test3: LeanScript: the parameter `α` of `preview_left_right` is a type
//   test4: LeanScript: the parameter `α` of `preview_left_right` is a type


/**
 * `test1`
 * @param {([0, int(bigint)] | [1, int(bigint)])} a
 * @returns {([0] | [1, int(bigint)])}
 */
export function test1(a) {
  if (a[0] === 0) {
    const [, f$1] = a;
    return [1, f$1];
  } else {
    const [, f$2] = a;
    return [0];
  }
}

/**
 * `test2`
 * @param {([0, int(bigint)] | [1, int(bigint)])} a
 * @returns {([0] | [1, int(bigint)])}
 */
export function test2(a) {
  if (a[0] === 0) {
    const [, f$1] = a;
    return [1, f$1];
  } else {
    const [, f$2] = a;
    return [0];
  }
}
