// JavaScript of Tests/SnapshotsPBOPure/ProfunctorLenses01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   instReprRecBaz.repr: LeanScript: the recursive type Std.Format is not declared in any signature; declare it with `leanscript_signature`
//   instReprRecFooBaz.repr: LeanScript: the recursive type Std.Format is not declared in any signature; declare it with `leanscript_signature`
//   instReprRecFooBar.repr: LeanScript: the recursive type Std.Format is not declared in any signature; declare it with `leanscript_signature`

import { int53__lean_int_add } from "../../runtime.js";

/**
 * `test1`
 * @param {{ _1: int53(number), _2: int53(number) }} a
 * @returns {int53(number)}
 */
export const test1 = (a) => a._1;

/**
 * `test2`
 * @param {{ _1: int53(number), _2: int53(number) }} a
 * @returns {int53(number)}
 */
export const test2 = (a) => a._1;

/**
 * `test3`
 * @param {{ _1: int53(number), _2: int53(number) }} a
 * @returns {{ _1: int53(number), _2: int53(number) }}
 */
export const test3 = (a) => ({ _1: a._1, _2: int53__lean_int_add(a._2, 1) });

/**
 * `test4`
 * @param {{ _1: int53(number), _2: int53(number) }} a
 * @returns {{ _1: int53(number), _2: int53(number) }}
 */
export const test4 = (a) => ({ _1: a._1, _2: int53__lean_int_add(a._2, 1) });

/**
 * `test5`
 * @param {{ _1: int53(number), _2: int53(number) }} a
 * @returns {{ _1: int53(number), _2: int53(number) }}
 */
export const test5 = (a) => ({ _1: a._1, _2: int53__lean_int_add(a._2, 1) });

/**
 * `test6`
 * @param {{ _1: int53(number), _2: int53(number) }} a
 * @returns {{ _1: int53(number), _2: int53(number) }}
 */
export const test6 = (a) => ({ _1: a._1, _2: int53__lean_int_add(a._2, 1) });

/**
 * `test7`
 * @param {{ _1: int53(number), _2: int53(number) }} a
 * @returns {{ _1: int53(number), _2: int53(number) }}
 */
export const test7 = (a) => ({
  _1: int53__lean_int_add(a._1, 1),
  _2: int53__lean_int_add(a._2, 42),
});

/**
 * `test8`
 * @param {{ _1: int53(number), _2: int53(number) }} a
 * @returns {{ _1: int53(number), _2: int53(number) }}
 */
export const test8 = (a) => ({
  _1: int53__lean_int_add(a._1, 1),
  _2: int53__lean_int_add(a._2, 42),
});
