// JavaScript of Tests/SnapshotsPBOPure/STArray03.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   test1: LeanScript: the call Array.forIn'.loop as (fun a x => (fun a __s => have bs := __s; have bs := bs.push (f a); pure (ForInStep.yield bs)) a) as.size ⋯ #[] is not a call of an extern: `Array.forIn'.loop` is not the Lean function of an entry of the catalogue of externs (`LeanInitPureExtern`), and its definition cannot be unfolded
//   test2: LeanScript: the call Array.forIn'.loop as (fun a x => (fun a __s => have bs := __s; have as' := f a; do let __s ← forIn as' bs fun a' __s => have bs := __s; have bs := bs.push a'; pure (ForInStep.yield bs) have bs : Array Nat := __s pure (ForInStep.yield bs)) a) as.size ⋯ #[] is not a call of an extern: `Array.forIn'.loop` is not the Lean function of an entry of the catalogue of externs (`LeanInitPureExtern`), and its definition cannot be unfolded

