// JavaScript of Tests/SnapshotsPBOPure/STArray02.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic
// not translated:
//   test1: LeanScript: the recursive type List Int is not declared in any signature; declare it with `leanscript_signature`
//   test2: LeanScript: the recursive type List Int is not declared in any signature; declare it with `leanscript_signature`


