// JavaScript of Tests/SnapshotsPBOPure/STArrayUnsafeThawFreezeLengthRegression.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic

import { array__lean_array_push } from "../../runtime.js";

/**
 * `test`
 * @param {int53(number)} x
 * @returns {Array<int53(number)>}
 */
export const test = (x) => {
  const x$1 = array__lean_array_push([x], 12);
  const x$2 = x$1.length;
  return array__lean_array_push(x$1, x$2);
};
