// JavaScript of Tests/SnapshotsPBOPure/STArray05.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   test: the translation has unresolved parts (metavariables)

