// JavaScript of Tests/SnapshotsPBOPure/Tco03.lean, generated by leanscript
// configuration: nat=bigint int=bigint uint64=bigint int64=bigint bitvec=bigint array-fixed-int=typed array-float=typed array-uint64=typed array-int64=typed array-bitvec=round-up array-bool=generic array-char=generic

// ---- runtime helpers ----

function lean_nat_sub$bbb(a, b) {
  return (a > b ? a - b : 0n);
}

// ---- exported functions ----

/**
 * `go`
 * @param {nat(bigint)} n
 * @returns {nat(bigint)}
 */
export function go(n) {
  if (n === 0n) {
    return n;
  } else if (n <= 100n) {
    return go(lean_nat_sub$bbb(n, 1n));
  } else {
    return k(lean_nat_sub$bbb(n, 1n));
  }
}

/**
 * `k`
 * @param {nat(bigint)} m
 * @returns {nat(bigint)}
 */
export function k(m) {
  if (m === 100n) {
    return go(lean_nat_sub$bbb(m, 1n));
  } else if (m === 900n) {
    return 42n;
  } else {
    return k(lean_nat_sub$bbb(m, 1n));
  }
}
