// JavaScript of Tests/SnapshotsPBOPure/Tco01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `test`
 * @param {uint53(number)} n
 * @returns {uint53(number)}
 */
export const test = (n) => {
  let acc$1 = 0;
  for (let i$2 = 0; i$2 < n; i$2++) {
    const a$3 = acc$1;
    acc$1 = a$3;
  }
  return acc$1;
};
