// JavaScript of Tests/SnapshotsPBOPure/TopLevelHygiene02.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `wat`
 * @type {int53(number)}
 */
export const wat = 42;

/**
 * `test1`
 * @template A, B
 * @param {(A) => B} wat
 * @param {A} a
 * @returns {B}
 */
export const test1 = (wat, a) => wat(a);

/**
 * `test2`
 * @template A, B
 * @param {(A) => B} f
 * @param {A} a
 * @returns {B}
 */
export const test2 = (f, a) => f(a);
