// JavaScript of Tests/SnapshotsPBOPure/UnpackArray01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic

// ---- runtime helpers ----

function lean_array_get$__n_(a, b, c) {
  return c < b.length ? b[c] : a;
}

// ---- exported functions ----

/**
 * `test`
 * @param {(string => (string => string))} fn1
 * @param {(() => string)} fn2
 * @returns {string}
 */
export const test = (fn1, fn2) => {
  const x$1 = fn2();
  const k$2 = ["foo", "bar", "baz", x$1];
  const x$3 = fn1(lean_array_get$__n_("", k$2, 0));
  return x$3(lean_array_get$__n_("", k$2, 2));
};
