// JavaScript of Tests/SnapshotsPBOPure/VanLaarhovenTraversals01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   rewriteBottomUpM: defined by well-founded recursion: only non-recursive and structurally recursive definitions are translated (to `Term`)
//   instReprFun.repr: LeanScript: the recursive type Fun is not declared in the signature `LeanScriptAutoSig`; add it to `leanscript_signature LeanScriptAutoSig`
//   instDecidableEqFun.decEq: LeanScript: the recursive type Fun is not declared in the signature `LeanScriptAutoSig`; add it to `leanscript_signature LeanScriptAutoSig`
//   traverseFun1: LeanScript: the parameter `f` of `traverseFun1` has the polymorphic type Type → Type and is not always applied to the types of an instance
//   Fun.size: LeanScript: the recursive type Fun is not declared in the signature `LeanScriptAutoSig`; add it to `leanscript_signature LeanScriptAutoSig`
//   traverseFun1D: LeanScript: the parameter `f` of `traverseFun1D` has the polymorphic type Type → Type and is not always applied to the types of an instance
//   rewriteBottomUp: LeanScript: the recursive type Fun is not declared in the signature `LeanScriptAutoSig`; add it to `leanscript_signature LeanScriptAutoSig`

