// JavaScript of Tests/SnapshotsPBOPure/Variant01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array

/**
 * `test1`
 * @param {({ tag: 0, _1: int53(number) } | { tag: 1, _1: boolean } | { tag: 2, _1: string })} a
 * @returns {string}
 */
export const test1 = (a) => {
  if (a.tag === 0) {
    return String(a._1);
  }
  if (a.tag === 1) {
    return a._1 ? "true" : "false";
  }
  return a._1;
};
