// JavaScript of Tests/SnapshotsPBOPure/Variant01.lean (preset pbo), generated by leanscript
// configuration: nat=num int=num uint64=num int64=num bitvec=num array-fixed-int=generic array-float=generic array-uint64=generic array-int64=generic array-bitvec=generic list=array
// not translated:
//   test1: LeanScript: `Int` is a leaf of the language: its values are literals, not constructor applications

